### ISSUE TITLE
Set local env defaults so that app can be started locally with one command 

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#103]
On a fresh install of the app, when I run:

```
docker-compose up
```

I get: 

```
web_1  |     raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
web_1  | django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

I then have to set a SECRET_KEY variable manually before the app can start.

Let's adjust this so that the app can be started locally with a single command.

**Comment by LindsayYoung** [comment]
I think this is done here:
https://github.com/usdoj/crt-portal/blob/9bbbbd7dfb7153c86cb261c24f0b7c100dd15f48/crt_portal/crt_portal/local_settings.py#L16

 @alexsoble reopen something else in mind.
