### ISSUE TITLE
Set up log drain service

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#106]
This will set up a log drain service to feed our logs into DOJ's Splunk. This is one of the tasks necessary for ATO.

Here is the cloud foundry documentation on that: https://docs.cloudfoundry.org/devguide/services/log-management.html

General cloud.gov logging documentation:
https://cloud.gov/docs/apps/logs/

**Comment by LindsayYoung** [comment]
I guess it might not be a dependency since we have the logging mechanics to test, but wanted to link it to this issue https://app.zenhub.com/workspace/o/18f/crt-portal/issues/62

**Comment by LindsayYoung** [comment]
@lalitha-jonnalagadda @UchMok @blaughman 
FYI: It looks like we have some movement on this. We might meet with the Splunk team this week or next week. In the mean time I can reach out to cloud.gov to make sure I understand what the implementation looks like on our end. Hopefully, we can just use the [cloud foundry plugin](https://github.com/cloudfoundry/cf-drain-cli#installing-plugin).

**Comment by LindsayYoung** [comment]
Call with DOJ splunk team scheduled for 10/31 at 1:30

**Comment by LindsayYoung** [comment]
Had a good talk with the DOJ Splunk team today. They wanted to know how many logs we would produce, for the next month or two it sounds like they are on a tight quota. I sent them an estimate of how many logs we produce, I doubt it will be a problem. If they think they can accommodate, they will set up an endpoint for us and we can create the log drain service.

**Comment by LindsayYoung** [comment]
The Splunk team isn't on-boarding new projects until Jan 15.

**Comment by LindsayYoung** [comment]
Got a ticket from the Spunk team. Will update if we need next steps

**Comment by LindsayYoung** [comment]
Sean has a on-boarding doc for Splunk.

**Comment by LindsayYoung** [comment]
Log clarification

**Comment by LindsayYoung** [comment]
sent additional details about the logs today

**Comment by LindsayYoung** [comment]
Got the VIP, setting that up now

**Comment by LindsayYoung** [comment]
OK there is an error so I am following up with the cloud.gov team.

**Comment by LindsayYoung** [comment]
Looks like there might need to be a firewall update on the JMD side.

**Comment by LindsayYoung** [comment]
The code is done but they are working on implementation on the Splunk side

**Comment by lalitha-jonnalagadda** [comment]
Closing this card as its dev complete and tested.
