### ISSUE TITLE
Set up DNS

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#107]
https://cloud.gov/docs/ops/dns/

Approved URL: civilrights.justice.gov

- [ ] Lindsay to ping John on requesting a subdomain

**Comment by LindsayYoung** [comment]
We will need to know what the URL is going to be, then it can be requested from DOJ. Then, we can set it up in cloud.gov's custom domain support for the app https://cloud.gov/docs/services/custom-domains/

**Comment by LindsayYoung** [comment]
Creating the CDN route

**Comment by LindsayYoung** [comment]
got the txt record creation paperwork in

**Comment by LindsayYoung** [comment]
Submitted TXT record ticket to JMD.

**Comment by LindsayYoung** [comment]
TXT record set up!

**Comment by LindsayYoung** [comment]
Broker expired, need to delete broker, create new broker and request new TXT record.

**Comment by LindsayYoung** [comment]
Made new broker, submitted new request for TXT.

**Comment by LindsayYoung** [comment]
TXT record was created. The cloudfrount host was successfully created as well. Replied to the thread with the CNAME creation request 🤞

**Comment by LindsayYoung** [comment]
pinged the thread

**Comment by LindsayYoung** [comment]
We have requested a ticket be made.

**Comment by LindsayYoung** [comment]
✅ CNAME records are created 🎉
✅ Updated CORS config for the s3 bucket of static assets.

To do:
- [ ] Need to straighten out referer checking for the CSRF token

**Comment by LindsayYoung** [comment]
We figured out the CRF token issue, CloudFront is stripping out headers we need. I reached out to cloud.gov to see if there is anyway we can change the config without remaking the csn service and starting from scratch.

**Comment by LindsayYoung** [comment]
cf update-service for the win!!
