### ISSUE TITLE
Get Docker set up for local development

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#11]
## Narrative
As a developer or designer, I want easy project set up so that I can run the project locally. 

## Acceptance criteria
- [ ] the project is easily set up with docker
- [ ] the docker set up doesn't interfere with production

## Technical notes
Using the new lightning drupal distro that we deployed to the Acquia cloud

**Comment by UchMok** [comment]
@alexsoble if this is taking >3 days to do then parking lot and move on to 'webform' and 'maestro' plugins

**Comment by alexsoble** [comment]
Have made progress here with a super-minimal Dockerfile:

```
FROM drupal:8.7.3-apache

CMD echo "standard" | php core/scripts/drupal quick-start
```

Still stuck on one issue: connecting to the running Drupal app locally. Will add more about this sticking point below.

**Comment by alexsoble** [comment]
Docker may not be the right tool to use here. Acquia BLT may be the right tool:

https://docs.acquia.com/blt/

USDOJ's existing Acquia Drupal project uses BLT for build, testing, and deploy: 

https://github.com/usdoj/foia-api

**Comment by alexsoble** [comment]
@UchMok Based on the above, should I move this to "Closed" or somewhere else? In addition to Docker probably not being the right tool, I spent more than 3 days on this.

**Comment by alexsoble** [comment]
I'm going to Close this since I don't think Docker is the right solution for the Drupal / Acquia stack
