### ISSUE TITLE
Have configurations ready for production

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#12]
## Narrative
As a \<type of user\>, I want \<a goal\> so that \<benefit\>. 

## Background
:add business context to help us better understand the story:

## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Mockups / Wireframes
![image]()

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by UchMok** [comment]
@LindsayYoung @alexsoble if duplicate, please delete

**Comment by LindsayYoung** [comment]
I think we can flesh this out later as separate issues
