### ISSUE TITLE
Add automated pa11y check to CircleCI setup

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#125]
Use pa11y to run automated accessibility checks as part of our CircleCI setup: 

https://pa11y.org

**Comment by alexsoble** [comment]
An orb that could serve as a helpful reference: https://circleci.com/orbs/registry/orb/nebulab/pa11yci.

**Comment by Jacklynn** [comment]
Some conflicts with it's functions...compromise to choose what kind of machine it runs on. Testing machine and deploying machine. Slows testing down a little.
