### ISSUE TITLE
Confirm USDOJ GitHub and Circle settings

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#128]
Go through settings and document and confirm:
  - [x] GitHub org level settings
  - [x] GitHub repo level settings
  - [x] GitHub Personal settings
  - [x] CircleCI org settings
  - [x] CircleCI repo settings
  - [x] CircleCI personal settings

**Comment by LindsayYoung** [comment]
Key settings documented here: https://docs.google.com/document/d/1-NXmGpz-B0UrxulKN5bp8Zt48LC2AaZd0JKVERkLxoU/edit#heading=h.4l7p3bxvatro

**Comment by LindsayYoung** [comment]
Done
