### ISSUE TITLE
Users to view default error pages

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#134]
3) **"TAKE THIS AC OUT OF STORY"**
Given CRT intake portal connection is down
When I am viewing the 'View all complaint records' table
THen... 404 message <--- *Developers*

## Mocks

I modeled this off our basic card headings styles
![404 error.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/c19d021e-4de6-4566-9b71-7aa92046ce97)

**Comment by lalitha-jonnalagadda** [comment]
500 page - when the user is unable to save the complaint due to a server error. 
We want to start off with a generic template +status code+error message + design to add branding to the page

**Comment by Jacklynn** [comment]
Here's a [list of HTTP errors I found](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status), would you need us to write some copy for them? I'm not sure how common these are.

**Comment by LindsayYoung** [comment]
No need to make a list since we aren't' doing custom messages yet. That mock should be good for now. We can put that into the base template.

**Comment by lalitha-jonnalagadda** [comment]
Desk checked this card with this page and I see the error page - https://crt-portal-django-dev.app.cloud.gov/report/dash. Waiting for @blaughman @Jacklynn to take a look and move to UAT complete.

**Comment by blaughman** [comment]
There is a typo in the error message.  "Try _**retuning**_ to the previous page."

**Comment by Jacklynn** [comment]
+1 to Bill's comment about the text change.

It doesn't look how I expected, I learned that it's difficult to remove the heading, the spacing looks off and the page looks broken itself. Functionally works, but would be nice to do another round of design updates given the constraints. 

Current:
![Screen Shot 2020-04-14 at 9.12.15 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/e6d24bba-0ec2-4d7e-9c91-4731edd120b3)

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
