### ISSUE TITLE
Write up and share out a11y manual testing plan for Stories

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#139]
Link: https://docs.google.com/document/d/15ondXXQytfmSNAgboZP-CajXLVbQvFBRhPDnawEPiZU/edit

# Definition of Done 

+ [x] Loop in Terri Youngblood
+ [ ] Add a11y plan to GitHub repo and link it to the PR template
  + [ ] Make any changes as needed based on feedback
+ [ ] Share out to team (18F + CRT, especially CRT devs!)
+ [ ] Share out to sections

**Comment by UchMok** [comment]
@alexsoble to add link to draft

**Comment by alexsoble** [comment]
@UchMok Added above! https://docs.google.com/document/d/15ondXXQytfmSNAgboZP-CajXLVbQvFBRhPDnawEPiZU/edit
