### ISSUE TITLE
be authenticated as an active DOJ CRT user

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#14]
## Narrative
As a DOJ owner, I want a secure website to protect the security and privacy of website visitors. 

## Acceptance criteria
- [ ] the only way to get to the admin on prod is through the DOJ SSO

## Technical Notes
Need to coordinate with JMD

**Comment by UchMok** [comment]
@LindsayYoung I wouldn't want you to work on this outside of just playing the story for authentication. If it's derisking you want to do, maybe we just make this a Spike?

**Comment by LindsayYoung** [comment]
Started looking at options tried out some code in https://github.com/usdoj/crt-portal/pull/29 and sent an email for coordination with JMD on 8/23.

**Comment by LindsayYoung** [comment]
Working with John collecting needed data to advance this with JMD.

**Comment by LindsayYoung** [comment]
Meeting with John today, we realized we needed to send them some endpoint info.

**Comment by LindsayYoung** [comment]
Going to test the dev environment on the prod url on Friday.

**Comment by LindsayYoung** [comment]
We got the endpoint and metadata last week for the DOJ test environment. I have a good local test going and need to add the new libxmlsec1 dependency to our deploy.

- [x] Put the metadata in a private S3 bucket
- [x] Refactored the code to be set up for using two S3 buckets
- [x] Added libxmlsec1 dependency locally
- [] Configure buildpack set with libxmlsec1 dependency

**Comment by LindsayYoung** [comment]
John spent more time on debugging this, seems like we still need some configuration work on the DOJ side to get this going. 

Good news is that updating to prod should be easy once we have dev figured out.

**Comment by LindsayYoung** [comment]
Found the problem last week, thanks to pairing with Amos. Basically the SAML package we are using is getting confused because there are a lot of ways we can send the SAML request. It is tying to make a get request with a post message. That isn't a valid request. 

I can't tell if the problem arises in the way that the django_saml2_auth package is implementing the saml2 package or if there is an issue with the saml2 package. 

The options seem to be - find another package, try to fix the package or try to implement saml to work with djnago using the saml2 package directly.

**Comment by LindsayYoung** [comment]
Libraries I have tried so far

https://github.com/fangli/django-saml2-auth
   relatively simple set up but was sending malformed requests (post requests via git)

https://github.com/MindPointGroup/django-saml2-pro-auth
   needs it's won cert and looks like it is uses sha-1

other packages
https://github.com/IronCountySchoolDistrict/django-python3-saml

**Comment by lalitha-jonnalagadda** [comment]
From the release planning meeting: Once this story is developed, we should test the following:
 - System log out (after the designated number of hours - may be 12)
 - Manual log out

**Comment by LindsayYoung** [comment]
The cloud.gov integration is also running into issues, I proposed another debugging session. With Mike too.

**Comment by LindsayYoung** [comment]
Got our first login 1/28/2020 using production app with the DOJ test environment.

**Comment by lalitha-jonnalagadda** [comment]
Finally closing this card!🎉
