### ISSUE TITLE
Form progress bar [enhancement]

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#146]
I want to note this before I forget
- I'm worried about the tight fit of the words here especially since we're looking at adding more steps and 2) localization where the [text can easily increase up to 300%] (https://www.w3.org/International/articles/article-text-size)

It would be nice to explore a more flexible layout that can fit more text easily.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card. Design and implementation card #233 covers this one

**Comment by LindsayYoung** [comment]
no estimate since this was a duplicate ticket
