### ISSUE TITLE
[a11y] input fields read multiple labels

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#149]
Issue: With voiceover turn on, when I tab through fields on the contact page, it reads three labels for each field

Steps to recreate:
1. Open form in **Safari** 
2. Turn voiceover on using (shortcut: apple+ f5)
3. tab through fields
4. notice that field reads 3 times: "Email address, edit, Email address,  Email address group"

Expected result: when I get to the field, a screen reader will read one label for it. Example website where forms read as expected: https://webaim.org/techniques/forms/controls

I tried to find in the code where this is but I think it's formatted differently than the documentation because it's in python?

**Comment by lalitha-jonnalagadda** [comment]
@Jacklynn can you please test if the bug has been fixed and working as expected and move it to the ready for UAT column?

**Comment by Jacklynn** [comment]
Went through this with alex and we believe this is working as intended.
When you enter a group, it reads the field name, then the group name. The first time you enter a group, it also reads the group name again. We checked this against a11y documentation like https://webaim.org/techniques/forms/controls

closing!
