### ISSUE TITLE
Create Acquia prototype account

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#15]
## Narrative
As a \<type of user\>, I want \<a goal\> so that \<benefit\>. 

## Background
:add business context to help us better understand the story:

## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Mockups / Wireframes
![image]()

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by LindsayYoung** [comment]
@dwechsle did this, the next step is to get the paid account
