### ISSUE TITLE
Update the content from deep dive feedback so that it's clearer for Public users what they need to do 

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#151]
**Summary of feedback on text changes**
- For the subtitle text — mentioning the word “form” is confusing, simplify and shorten this text. 
- Simplify “Who should we contact about this issue?”. Make it simpler and make it less likely that someone will list the offender. Possibility: “How can we reach you?”
- Note that complaints can be submitted in other languages. 

TEAM APPROVED CHANGE
![All Contact-post section feedback Copy.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/fd800218-792e-43da-a7a2-9cd76d944b74)

**Comment by Jacklynn** [comment]
![Comparison Copy.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/07fc2b66-f5a2-4da6-ba18-0b54822d74eb)

Suggested changes for review. @AvivaOskow.

Not sure if we should indicate that you can enter a submission in other languages here on the page previous.

**Comment by Jacklynn** [comment]
Change the title back to the 'concern' language.
block the progress bar

**Comment by Jacklynn** [comment]
![All Contact-post section feedback Copy.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/dbcfd851-f611-4d7b-807c-96cba74f42a7)

**Comment by Jacklynn** [comment]
I'm the worst and fell into my own sketch file trap. The text we sent for deep dive follow up is the mock, so:

`Contact the Department of Justice about a civil rights concern
If you believe you or someone else has experienced a civil rights violation, please tell us what happened`
- Folks were concerned with the 'complaint' language.

**Comment by alexsoble** [comment]
Ah, darn. We shipped `Submit a civil rights concern to the Department of Justice` to development because of what we saw in the Form Text Master sheet and in the diff image. The differences between the mockup, the Form Text Master sheet, and the diff image were confusing. We can adjust this in a follow-on PR. Is there anything besides the title that needs adjusting?

**Comment by Jacklynn** [comment]
- I just looked at the dev build and the text looks good to me now!
- So sorry for the confusion and thanks for the feedback. The mocks were a reference for the content designer because sometimes it's hard to make sense of things otherwise, but I see now that's confusing.
- I tried to put indicate proposed changes in green as well.

**Comment by lalitha-jonnalagadda** [comment]
I checked the dev site and the changes look good to me and are ready to be passed for Bill's review. I checked the changes proposed in this card as well as the text master doc linked in the comments above.

**Comment by blaughman** [comment]
Looks good to me.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card as we finished review with the deep dive group.
