### ISSUE TITLE
Spike on i18n

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#152]
# Notes

+ Timeboxed spike. TODO: Determine how much time.
+ See what work needs to be done in order to internationalize the application.

**Comment by lalitha-jonnalagadda** [comment]
@alexsoble were you able to determine the timebox for this spike?

**Comment by alexsoble** [comment]
@lalitha-jonnalagadda I would suggest two days / 8 hours of dev time.

**Comment by alexsoble** [comment]
Django docs on localization: https://docs.djangoproject.com/en/2.2/topics/i18n/formatting/

**Comment by alexsoble** [comment]
Django translation docs: https://docs.djangoproject.com/en/2.2/topics/i18n/translation/

**Comment by alexsoble** [comment]
— Mark strings as translation strings
— Decide on `_()` vs `gettext()` 
— Figure out which text needs to be translated lazily (text stored as DB strings): https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#model-fields-and-relationships-verbose-name-and-help-text-option-values
— JavaScript: use TheJavaScriptCatalog view: https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#module-django.views.i18n
— Pseudolocalization: https://en.wikipedia.org/wiki/Pseudolocalization

**Comment by alexsoble** [comment]
— Checking for what will need translation: https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#message-files

**Comment by alexsoble** [comment]
Places that need marking of translation strings:

— JS
— PY (non database)
— Database code: looks like just protected classes
— HTML

**Comment by el-mapache** [comment]
Quick update from the front-end side:

* Added a route to `url.py` that exposes a browser-downloadable JS resource. This code injects the django i18n helper functions e.g. `gettext` into the browser and makes them callable from our JavaScript code.

* I had to add a second locale folder at the top level of the app, co-located with the `scripts` directory to get the translation files to compile

* The compilation process seems to generate a bunch of `filename.js.py` files. Each of these corresponds to a JS file. This seems a little clunky / adds noise to the app. I'm not sure if this is a setting I'm missing in the compilation step, but googling has yielded little thus far.

* The `makemessages` command will look for _every_ JS file, so we have to manually ignore anything we don't want translated. This, coupled with the `.js.py` files that get generated, makes me think we should have a single JS file where all of our translations live. We can put those strings into a `CRT` namespace on the `window` object and the files that need the strings can pull them from there

**Comment by LindsayYoung** [comment]
Just wanted to ring in that I reserved some time on Monday for this PR. I didn't have enough uninterrupted time to do the review it needed this week.

**Comment by alexsoble** [comment]
No problem!! Have a great weekend!!

**Comment by LindsayYoung** [comment]
Right now it looks like we have internationalization 1/2 implemented. I think it would take about 2 hours to finish it.  I think it would be worth the extra hours to get us in a great place for translation later.

Here are the subtasks:
 - [x] document how to add translations to the app
 - [x] get an example translation going locally
 - [ ] consistently format text in forms.py (started)
 - [ ] consistently format text in models.py (started)
 - [ ] pass text to javascript from Django

That would put us in a good position to add text consistently going forward. Then we would be able to generate files of text to be translated. 

We can add the language codes from the browser as we add translations for that language and we will eventually need a UI element.

**Comment by el-mapache** [comment]
@LindsayYoung @alexsoble How do ya'll feel about moving this ticket to `Dev Done` and opening a new one to capture these ACs?

**Comment by alexsoble** [comment]
I love that idea @el-mapache! That was the original intent of this ticket — a timeboxed spike, with follow-on work captured separately.

**Comment by LindsayYoung** [comment]
Sorry, just seeing this now, a separate ticket would have been fine.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card as work on this spike is complete.

**Comment by LindsayYoung** [comment]
wasn't showing up as closed, so I am closing it ;)
