### ISSUE TITLE
Style Changes -- Sprint 4

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#158]
## Definition of done

Update hover and focus states of textarea, input field, and button based on designer feedback. See thread here: https://gsa-tts.slack.com/archives/CGWRRBB0E/p1570571678035200.

### Notes on colors

Default button: `#1A4480`
Hover state (button): `#2378C3`
Focus state (all components): `#2491FF`

**Comment by Jacklynn** [comment]
looks updated when i check dev and reflects our slack convo, thanks!
