### ISSUE TITLE
Set up single CRT Portal Repo under USDOJ GitHub Org

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#16]
## Narrative
As a DOJ owner, I want DOJ to own the code so DOJ can have responsibility and control over the code and its integrations. 

## Acceptance criteria
- [x] Create repo https://github.com/usdoj/crt-portal
- [ ] Enable protected branches so that only certain people have access to merge into master
- [x] ~Create team on GitHub for this project and make sure this team has access to only the crt repo~ (Has a per-repo set up so that is how we are only given access to the crt repo.)

## Technical Notes
This is easy but Brock is the one with access to these settings.
https://help.github.com/en/articles/about-protected-branches

**Comment by LindsayYoung** [comment]
@dwechsle is working on this

**Comment by LindsayYoung** [comment]
Brock got a repo going! 

@dwechsle I don't have access to settings on that repo- which is fine, if you also don't have access to the settings, we can work with Brock to make the master branch protected and later, integrating Acquia pipelines and GitHub.

**Comment by alexsoble** [comment]
@UchMok I think we can tweak this task to make it clearer — the title says, "Create DOJ CRT github org", but the body refers to creating a GitHub repo, not a GitHub org. And the repo is already created. 

So we can likely break out the sub-tasks into their own tasks and move the overall "Create DOJ CRT repo" task to Done.

**Comment by alexsoble** [comment]
I'm picking this one up as of today! Have made progress locally :)

**Comment by LindsayYoung** [comment]
Lindsay
- [ ] switch around the repos 
    - contents of 18f/crt-django will go to usdoj/crt-portal
    - contents of usdoj/crt-portal will go to 18F/crt-portal, to perserve the work
   - 18f/crt-django will be archived 
- [ ] send out how to update remotes locally

Darren
-  [ ] update the settings

**Comment by LindsayYoung** [comment]
Done!

**Comment by alexsoble** [comment]
@LindsayYoung 🙌🙌
