### ISSUE TITLE
Gov banner text black on black in dev

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#161]
The paragraph css is over-riding the usa-media-block__body css, so the text is black:

![Screen Shot 2019-10-21 at 4.44.04 PM.png](https://images.zenhubusercontent.com/56f1892d6caf56c9d38e1ac3/24f2ce85-5aae-4a44-87c6-41991674d25b)

**Comment by alexsoble** [comment]
Pairing on this one with @ilodidoj!

**Comment by alexsoble** [comment]
Shipped to dev!
