### ISSUE TITLE
Highlight error field

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#163]
Error message should also highlight the field somehow so you know what field it's associated with.
Red border + increase border/stroke width.

Current build only shows error message without the field highlighted
![Screen Shot 2019-12-02 at 4.14.56 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/1ed89987-2fb2-4b2d-8c89-2a8ac1fbb043)

**Comment by Jacklynn** [comment]
Error message should also highlight the field somehow so you know what field it's associated with. 
Red border + increase border/stroke width. 

![Screen Shot 2019-12-02 at 4.14.56 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/1ed89987-2fb2-4b2d-8c89-2a8ac1fbb043)

**Comment by el-mapache** [comment]
@Jacklynn What do you envision the functionality would be like for checkboxes and radio groups? This is the style the `uswds` would offer if we add it to the app:

<img width="350" alt="Screen Shot 2020-02-18 at 2 40 08 PM" src="https://user-images.githubusercontent.com/1421848/74784318-83cde880-525c-11ea-8a34-ed9a7f2cc95a.png">

Or, do we just want to start with adding a large red stroke around the text fields for now?

**Comment by Jacklynn** [comment]
I like that, i especially like that it might already be built out!

What will happen on the primary issue page though? -- will it try to do something if implement the default behavior or is it a custom component anyway? @AvivaOskow fyi

**Comment by el-mapache** [comment]
Yeah for pages like that it will look a bit weird, since there will be a giant red bar floating down the length of the entire page. 

Unfortunately it isn't built out at all from our end, there will be some upfront work to get this behavior.

**Comment by Jacklynn** [comment]
Maybe start with the fields because I feel like that's more stable and predictable.

**Comment by Jacklynn** [comment]
So pretty, but when testing this today I noticed that it was highlighting the wrong one on the date field. If we're not able to tell, can we highlight all three? 
![Screen Shot 2020-02-24 at 9.59.07 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/a34d03e2-227f-4338-a531-693120d8290b)

**Comment by el-mapache** [comment]
@Jacklynn This is happening (in part) because we haven't added any additional error handling for the `day` field yet.

**Comment by Jacklynn** [comment]
I noticed it doesn't do this for in yellow for the Other field word limit reached but should that be another card? @lalitha-jonnalagadda
