### ISSUE TITLE
Deep Dive 10/31 feedback

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#169]
- [x] Contact page - Update to "Your name" https://github.com/usdoj-crt/crt-portal/pull/130
- [x] View all table - Violation summary to "Summary" https://github.com/usdoj-crt/crt-portal/pull/129

**Comment by lalitha-jonnalagadda** [comment]
Checked these changes in dev and they seem to be working fine. @blaughman adding you to the card for your sign off.

**Comment by blaughman** [comment]
The changes look as they should in IE 11.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card as we finished review with the deep dive group.
