### ISSUE TITLE
Push to prod (Acquia) from GitHub

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#17]
## Narrative
As a developer, I want ci/cd so that we can have a modern, efficient development environment

## Background
We are looking at using GitHub and the Acquia pipeline this ticket covers enabling GitHub as our code repo once we have a pain Acquia account. 

## Acceptance criteria
- [ ] the apps on Aquia cloud are connected to the GitHub repo

## Technical Notes
https://docs.acquia.com/tutorials/getting-started-acquia-cloud-cd/3-integrating-github/
related to #9

**Comment by UchMok** [comment]
We can push to prod from local if we don't secure a paid Acquia account and Github account in a timely manner

**Comment by alexsoble** [comment]
Closing this because we're not on Acquia anymore.
