### ISSUE TITLE
Italicize "other" protected class text in the View all table

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#170]
## Narrative
As an intake specialist I would like to quickly be able to tell if a protected class is user-submitted vs one of our categories

## Background
As part of #130 the designs had specified that the "Other" text someone has written in would be italicized to show it was user entered.

(@LindsayYoung hopefully I'm capturing this right:) The logic for this field is already complicated (treating two different pieces of dat as one) and italicizing adds to this complexity. It's still do-able but might want to treat as an enhancement.

**Comment by Jacklynn** [comment]
@blaughman @lalitha-jonnalagadda @UchMok FYI

**Comment by Jacklynn** [comment]
Copying image: ![image.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/41d78792-51e3-4b4a-b0c3-5473b450eb94)

**Comment by lalitha-jonnalagadda** [comment]
@Jacklynn can we close this card given that we no longer show protected class in the view all table?

**Comment by Jacklynn** [comment]
Yup!
