### ISSUE TITLE
Top vertical align table cell text

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#173]
Right now the elements of the table are center vertical aligned with makes the text kind of bounce up and down depending on how many lines there are. 
![Screen Shot 2019-11-13 at 10.28.29 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/8ae9a977-87b7-48b5-8caf-5beb253aa70e)

Expected, all text is top vertically aligned in a cell. This would improve the usability of the table. 
![topaligned.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/9d40dc6f-65f3-449c-b3cb-67d8ce219f1f)

**Comment by Jacklynn** [comment]
per discussion with @LindsayYoung during design-dev time!

**Comment by blaughman** [comment]
Looks great.

**Comment by lalitha-jonnalagadda** [comment]
@Jacklynn can you confirm UAT and move this card to done?

**Comment by Jacklynn** [comment]
They look top aligned, but now everything also looks like it's in all caps. known issue?

**Comment by Jacklynn** [comment]
But in terms of top alignment, good to go.

Filed a separate issue for the upper case and listed in the styles bug. https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/184

**Comment by lalitha-jonnalagadda** [comment]
Moving this card into 'ready for UAT' given that we have a new card for the upper case issue.
