### ISSUE TITLE
Spike: try django Preview option

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#175]
placeholder: Lindsay mentioned that Django has a built in preview plugin that we could use instead of the debugging page at the end we're using today. This would be more of a technical spike.

**Comment by lalitha-jonnalagadda** [comment]
From our slack conversation, this will be a 1/2 day spike to determine feasibility.

**Comment by LindsayYoung** [comment]
The module we are using comes with a preview and includes some templates you can use, unfortunately the ready-made tool only doesn't work out of the box with multi step forms. 

We can add some logic to the done function and add our own template if we want a form preview. I would estimate that at a 5

**Comment by lalitha-jonnalagadda** [comment]
Thanks @LindsayYoung - so from your notes, it seems like we might not have to create the review page from scratch, but we might still have quite a bit of work in terms of customizing the Django template. I connected this spike card with #23 - review page card for reference. We could close this card.
