### ISSUE TITLE
Make freeform required field

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#176]
## Background
Based on section feedback, it would would be very valuable for most section if the freeform was 'required' instead of 'optional'

## Acceptance Criteria
1) Given that I'm on the free form description page
when I try to click the 'Next' button without entering any text 
then I see an error message - 'Please provide description to continue' 

## Mock up
I don't have @AvivaOskow's design file but the alert should match this style:

![image.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/3f7c8c0b-ba31-4f0a-912d-25876e588138)

And I would expect the the freeform box to have the same red color border, like when the yellow 'word limit reached' warning appears. https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/56

red-60v #b51d09

## Sign off
Story Sign off
- [ ] PO
UAT Sign off
- [ ] PO

**Comment by Jacklynn** [comment]
Per Lindsay, easier to track this as a separate issue from the VOT card.

**Comment by LindsayYoung** [comment]
This would be a good pairing card for tomorrow with @ilodidoj @dwechsle

**Comment by blaughman** [comment]
@LindsayYoung @dwechsle @ilodidoj I assigned ownership to Darren and Imran.

**Comment by blaughman** [comment]
The error message populated in IE 11.   Moving to UAT.

**Comment by Jacklynn** [comment]
@blaughman @lalitha-jonnalagadda this is missing the field highlight in red (like the warning makes the text box have a yellow border. 

I mentioned this in the generic error ticket but let me know if this should be tracked elsewhere: https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/163

**Comment by lalitha-jonnalagadda** [comment]
Reviewed with the deep dive group on 12/12 and this card can now be closed.
