### ISSUE TITLE
Sprint 6 style changes

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#177]
## List
- [ ] 2/ Primary issue: Increase column width of selection boxes
- [x] 3/ PR to remove extra `)` https://github.com/usdoj-crt/crt-portal/pull/156
- [ ] 4/ Pagination: Expected record number & pagination to be on the same line
- [x] 5/ View all table: text all uppercase, bug -- https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/184

**Comment by AvivaOskow** [comment]
@Jacklynn I think the top and bottom should match visually and the change you are proposing makes it look like there is more space on the top than the bottom. If the need here is to save space for scrolling, then maybe they should both be .5, or somehow at least have the content centered in the box visually.

**Comment by Jacklynn** [comment]
@AvivaOskow Not to save space, I was only trying to change the spacing in the examples. It looks like the space between list items is bigger than the space between "example" and the first item, so it's not even and looks different from your mock ups.

Looking at the whole thing, I noticed it changed the padding on the boxes too :/-- not my intention

**Comment by Jacklynn** [comment]
Added a pagination change per Lindsay's request

**Comment by Jacklynn** [comment]
(Putting my suggestion as a comment so it doesn't look confirmed): 

Spacing between list items seems too big, I played around in the dev and I think .5 em might be closer to the mock. Making them closer together will help them read as a group better. 

![Group 5.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/5841685b-61f7-4c67-9eaf-8f0257e23876)

**Comment by lalitha-jonnalagadda** [comment]
Closing this card as the design is changing
