### ISSUE TITLE
[Feedback] Protected class list item changes

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#178]
- [ ] Order of disability in the list not at the top. But I also don't think it should be at the bottom because 1) to make it easier for intended users to find and selects and 2) it's one of the official federal protected classes

- Race/color
- National origin (including ancestry, and ethnicity) 
- Immigration/citizenship status (choosing this will not share your status)
- Religion
- Sex or gender identity (including gender stereotypes) or pregnancy
- Sexual orientation
- *Disability (including temporary or recovery)*
- *Language*
- Family, marriage, or parental status
- Military status
- Age
- Genetic information
- None of these apply to me
- Other reason

- [ ] Bringing out Language into it's own list item because folks who are reporting a language access issue might not recognize themselves in "national origin", ex: if their national origin is the US. Suggesting moving it after "Disability".

- [ ] Remove "language" as an example from "National Origin" item
- [ ] Add 'None of these apply to me' as a new item to the list.

**Comment by lalitha-jonnalagadda** [comment]
Ran a quick desk check in Chrome and it looks good. Changing this list display alphabetically will be a future card, but for this card, it looks good.

**Comment by blaughman** [comment]
Items have been updated on the list.  Moving to UAT.

**Comment by Jacklynn** [comment]
We also got feedback after this #220 to put these in alphabetical order 😅
