### ISSUE TITLE
Test Maestro plugin on drupal app

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#18]
## Narrative
As a team member, I want to create complex logic and workflows so that violation reports go to the right place, people can get assignments etc.

## Background
This ticket is for enabling the module not creating any of the scenarios, those will be separate tickets.

## Acceptance criteria
- [ ] Admin users can create workflows

## Technical Notes
https://www.drupal.org/project/maestro
All plugins will need drupal export of settings and check them into code

**Comment by LindsayYoung** [comment]
The example workflows are set up. The plan is to create new workflows in the design sandbox, export them when they are ready and put them through our development process as PRs to a develop branch.

![Screen Shot 2019-07-26 at 3.22.25 PM.png](https://images.zenhubusercontent.com/56f1892d6caf56c9d38e1ac3/b9c9e21e-baf2-4646-addf-f122c02ecc34)
