### ISSUE TITLE
Tell DOJ CRT additional information on where discrimination happened (Conditional logic - Voting)

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#182]
## Narrative
As a public user, I want to give DOJ CRT additional information about a potential civil rights violation so that DOJ CRT can investigate my complaint accordingly. 

## Business Context
VOT has jurisdiction with Federal elections only, though they happily receive correspondence about all elections (state and local). This story will allow VOT to better discern and prioritize the complaints they have jurisdiction to take action on vs everything else.

## Assumptions
- Additional voting question on this page is required

## Out of Scope
- Routing to sections
## Acceptance Criteria

1) Given that I'm on the primary issues page 
When I select - 'Right to vote impacted' and click next
Then I am taken to 'Location' page where I see a question - 'What kind of election was this related to?' 
AND 
I see an option to provide location details

2) Given that I'm on the 'Location' page
When I see  'What kind of election was this related to?' 
Then I see that I can make a selection on 3 options - Federal, State or Local and None

3) Given that I'm on the 'Location' Page
When I make a selection for the 'What kind of election was this related to?' 
Then I see that my selection is visually represented by the radio button being selected

4) Given that I'm on the 'Location' Page
When I DON'T make a selection 'What kind of election was this related to?' and click 'Next'
Then I see an alert - 'Please select the election type' 

5) Given that I'm on the 'Location' Page
When I make a selection 'What kind of election was this related to?' and click 'Next'
Then I'm taken to the 'Protected Classes' page

6) a11y requirements
This should be a generic check box interaction.
As a screen reader user, when I get to this question, I hear the question and options.
AND
I can tell when something is and isn't selected
AND
I can navigate & select using keyboard only
[documentation](https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/radio/radio.html)

## Mock ups
visual
https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/54
content
https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit#

### Sign Off
Story sign off
- [x] PO
- [x] VOT
UAT sign off
- [ ] PO

**Comment by blaughman** [comment]
Function works as intended in IE 11 and Chrome.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Demo'ed to the deep dive group on 1/9.
