### ISSUE TITLE
Sprint 6 - View all table is in all caps

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#184]
Noticed that with a change all the contents of the view all table are in caps and we're not that excited about individual records :). Just the status should be text-transformed to uppercase.

![Screen Shot 2019-11-22 at 9.08.41 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/5e4284ed-4e5f-43dd-9654-d47c8a6bb1d3)

**Comment by el-mapache** [comment]
@Jacklynn Just to further clarify, should the table headings remain UPPERCASED as well?

**Comment by Jacklynn** [comment]
@el-mapache yes please! I realized that in some of my mocks they drifted back to lowercase.

**Comment by LindsayYoung** [comment]
I had a fix for this in here - https://github.com/usdoj-crt/crt-portal/blob/57e164435fa72af2fe96b2184572f165045cb509/crt_portal/static/sass/custom/table.scss

That should be coming soon.

**Comment by LindsayYoung** [comment]
this is fixed :)
