### ISSUE TITLE
Update CRT view designs to accommodate larger screen size

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crt-portal#187]
We recently found out that the average DOJ monitor screen size it much wider than we were designing for, so the view all table and complaint details page should be updated to fit this ratio better.

@Jacklynn  started mocking up what these could look like, and @AvivaOskow is taking over the work to continue designing.

## Examples (works in progress)

![Viewall-screensize.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/9eb5f344-c273-4f5c-aa13-f3cc152f03fd)

**Comment by lalitha-jonnalagadda** [comment]
Work on this card is complete as we have new designs. Moving this to the completed column. CC @AvivaOskow
