### ISSUE TITLE
Filter by submission date - View all table

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#189]
## Narrative
As a \<type of user\>, I want \<a goal\> so that \<benefit\>. 

## Background
:add business context to help us better understand the story:

## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Mockups / Wireframes
![image]()

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by lalitha-jonnalagadda** [comment]
Date here infers to submission date.

**Comment by blaughman** [comment]
Closing this card.  Replaced with card #310.
