### ISSUE TITLE
Run Django app on local machines using Docker

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#19]
## Narrative
As a developer, I want to run code locally so that we can add packages, write code and customize the app. 

## Background
this is needed for any development work

## Acceptance criteria
- [ ] Runs locally for @dwechsle 
- [] Runs locally for @alexsoble 
- [x] Runs locally for @lindsayyoung
- [ ] Runs locally for @ilodidoj 

## Technical notes
install composer for managing packages https://getcomposer.org/doc/00-intro.md

**Comment by alexsoble** [comment]
Key instructions for running the acquia lightning generated Drupal app (`dojportal`) are in the following file:

```
/docroot/core/INSTALL.txt
```

**Comment by UchMok** [comment]
Need review and discussion (w/ Soble) from Darren before moving this to Done @dwechsle

**Comment by alexsoble** [comment]
I had success getting the Drupal installation running locally using Quick Start: 

https://www.drupal.org/docs/8/install/drupal-8-quick-start-command

**Comment by alexsoble** [comment]
Since we're going with BLT, we need to debug a lot of steps with the BLT local environment setup process. 

Documenting that here:

https://github.com/usdoj/crt-portal/pull/1

**Comment by alexsoble** [comment]
@LindsayYoung got a local environment working on her machine, so now we have two local envs going! Darren's the last one we need to get up and running

**Comment by UchMok** [comment]
Big blocker for CRT devs are the DOJ network rules

**Comment by alexsoble** [comment]
Reviewing and leaving review comments/questions/suggestions here: https://github.com/18F/crt-django/pull/5
