### ISSUE TITLE
Filter by City - View all table

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#191]
## Narrative
As a DOJ CRT intake specialist, I want to be able to filter records by incident city so that I can view a subset dataset of interest to look at. 

## Background
All sections at DOJ, receive about 93K complaints annually. With this kind of volume, it's difficult to locate and look up complaints. Filtering by name will allow the intake specialists to look up a list of all complaints by a complainant. 

## Out of scope
- Filter by other location data
- Expandable/collapsable field categories

## Acceptance criteria

1) Given that I'm on the view all table
When I'm at the Filter by location 
Then I see a free form text box to enter a city name
AND
I see a 'Filter Results' button

2)  Given that I'm on the view all table
When I don't select any filter option
Then I see all complaints as the default view

3) Given that I'm on the view all table
When I enter the full or a phrase of the city name in the  'City' filter and click the 'Filter Results' button
Then I see the view all table filters to display all records matching the city name 
AND
I see a tag/label with the filtered criteria 

4) Given that I filtered the results by a city name
When I click 'X' on the tag/label 
Then I see the view all table to display all complaints 

5) Given that I filtered data by city name AND there are no records for that section
Then I see a message warning me about why there are no records showing
AND 
back and forward pagination arrows are disabled

6) Given that I've applied a filter and have reach the end of all the pages for a given filter (ex: less than 15 or on the final page of pagination)
Then I see a message confirming that I've reached the end of records and to change filters to see more.

## Mockups / Wireframes
![image]()

## Sign off
Story and UAT
- [ ] PO

**Comment by Jacklynn** [comment]
12/10 meeting:
* Lindsay: we might want to break these up into different cards. Filter by state vs city

**Comment by el-mapache** [comment]
@Jacklynn Just a heads up that the design mockup image link for this card is broken!

**Comment by blaughman** [comment]
Worked as intended on IE 11 and Chrome.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Demo'ed to the deep dive group on 1/9.
