### ISSUE TITLE
Tell DOJ CRT additional information on where discrimination happened (Conditional logic - workplace)

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#195]
## Narrative
As a public user, I want to give DOJ CRT additional information about a potential civil rights violation so that DOJ CRT can investigate my complaint accordingly.

## Background
Workplace discrimination related complaints are handled by IER, EOS and sometimes even referred out to EEOC, based on the type of the complaint and on the section that has jurisdiction to enact on that case. These conditional logic questions allow us to capture this additional information to determine the jurisdiction. 
In this case, EOS and IER can only take action on the complaint when it is referred from a public employer. If the complaint is for a private employer, then it is generally referred out to EEOC. 

## Assumptions
- Workplace related conditional logic question is required

## Out of scope
- Routing to sections 

## Acceptance Criteria
1) Given that I'm on the primary issues page
When I select - 'Workplace discrimination or other employment-related problem' and click next
Then I am taken to 'Location' page where I see two questions - 'Was this a public or private employer?' and 'How large is this employer?' 
AND
I see an option to provide location details

2) Given that I'm on the 'Workplace discrimination or other employment-related problem' question
When I see 'Was this a public or private employer?'
Then I see I can make a selection between 3 options - Public, Private and I'm not sure
AND 
When I see 'How large is this employer?' 
Then I see that I can make a selection between 3 options - Less than 15 employees, 15 or more employees, I'm not sure

3) Given that I'm on the 'Location' Page
When I make a selection for 'Was this a public or private employer?' and 'How large is this employer?' 
Then I see my radio button selection is filled/selected

4) Given that I'm on the 'Location' Page
When I DON'T make a selection for 'Was this a public or private employer?' and click 'Next'
Then I see an error message - 'Please select an option for what type of employer this is'
AND 
When I DON'T make a selection for 'How large is this employer?'
Then I see an error - 'Please select an option for how large the employer is' 

5) Given that I'm on the 'Location' Page
When I make a selection 'What kind of election was this related to?' and click 'Next'
Then I'm taken to the 'Protected Classes' page

6) a11y requirements
This should be a generic check box interaction.
As a screen reader user, when I get to this question, I hear the question and options.
AND
I can tell when something is and isn't selected
AND
I can navigate & select using keyboard only
[documentation](https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/radio/radio.html)

## Mockups / Wireframes
https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/47
Content Source of Truth - https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit?ts=5de6f69e

## Sign off
Story sign off
- [x] PO
- [x] ELS
- [x] IER
UAT sign off
- [ ] PO

**Comment by blaughman** [comment]
This function works as intended in IE 11 and Chrome.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
@el-mapache The sub text under public and private employee is not showing up as subtext, but rather separated by hyphens with the selection itself. Its not a blocker, but in terms of styling, it seems a bit off!

[Screen Shot 2020-01-02 at 2.09.44 PM.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/516c3542-6609-43c6-80f5-cc2e4e0d15e3)

**Comment by el-mapache** [comment]
@lalitha-jonnalagadda Weird, I'll look into it!

**Comment by lalitha-jonnalagadda** [comment]
Demo'ed to the deep dive group on 1/9.
