### ISSUE TITLE
Tell DOJ CRT additional information on where discrimination happened (conditional logic - school)

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#197]
## Narrative
As a public user, I want to give DOJ CRT additional information about a potential civil rights violation so that DOJ CRT can investigate my complaint accordingly.

## Background
The Educational Opportunities Section works to ensure that officials in elementary and secondary schools and institutions of higher education do not discriminate against students on the basis of sex, national origin, language barrier, religion, or disability.

## Assumptions
- School related conditional logic question is required

## Out of scope
- Routing to sections 
- Any further branching questions

## Acceptance Criteria

1) Given that I'm on the primary issues page
When I select - 'Discrimination at a school, educational program, or related to receive education' and click next
Then I am taken to 'Location' page where I see two questions - 'Was this a public or a private school or education program' 
AND
I see an option to provide location details

2) Given that I'm on the 'Discrimination at a school, educational program, or related to receive education' question
When I see 'Was this a public or a private school or education program'
Then I see I can make a selection between 3 options 
 - Public school or education program
 - Private school or education program  
 - I'm not sure

3) Given that I'm on the 'Location' Page
When I make a selection for 'Was this a public or a private school or education program' 
Then I see my radio button selection is filled/selected

4) Given that I'm on the 'Location' Page
When I DON'T make a selection for 'Was this a public or a private school or education program' and click 'Next'
Then I see an error message - 'Please select the type of school or educational program'

5) Given that I'm on the 'Location' Page
When I make a selection 'Was this a public or a private school or education program' and click 'Next'
Then I'm taken to the 'Protected Classes' page

6) a11y requirements
This should be a generic check box interaction.
As a screen reader user, when I get to this question, I hear the question and options.
AND
I can tell when something is and isn't selected
AND
I can navigate & select using keyboard only
[documentation](https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/radio/radio.html)

## Mockups / Wireframes
![School.jpeg](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/36e1eed1-c5b6-4d51-85d2-329ebbf7a7b3)

Source of truth:
https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit?ts=5de6f69e

## Sign off
- [x] PO
- [x] EOS
UAT Sign off 
- [ ] PO

**Comment by lalitha-jonnalagadda** [comment]
@Jacklynn - can you please update the mock with a third radio button - 'I'm not sure'

**Comment by el-mapache** [comment]
@lalitha-jonnalagadda Does the `I'm not sure` choice have a description text box in this case?

**Comment by Jacklynn** [comment]
Nope, no help text under it.

**Comment by blaughman** [comment]
Function works as intended in IE11 and Chrome.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep-dive on 2/6.
