### ISSUE TITLE
Tell DOJ CRT additional information on where discrimination happened (conditional logic - mistreated by law) 

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#198]
## Narrative
As a public user, I want to give DOJ CRT additional information about a potential civil rights violation so that DOJ CRT can investigate my complaint accordingly.

## Background
Routing misconduct by law enforcement or correctional staff is dependent upon where the incident occurred.  Incidents that occur in a prison or correctional facility should go to SPL and outside of a prison or correctional facility should go to CRM.
 
## Assumptions
- conditional logic question is required

## Out of scope
- Routing to sections 
- Inmate number free form text
- Question on police or correctional officer details 

## Acceptance Criteria
1) Given that I'm on the primary issues page
When I select - 'Mistreated by police, law enforcement or correctional staff' and click next
Then I am taken to 'Location' page where I see a question - 'Where did this take place?' 
AND
I see an option to provide location details

2) Given that I'm on the 'Mistreated by police, law enforcement or correctional staff' question
When I see 'Where did this take place?'
Then I see I can make a selection between 2 options - 'Outside a prison or correctional facility' and 'In a prison or correctional  facility'

3) Given that I'm on the 'Location' Page
When I make a selection for 'Where did this take place?' 
Then I see my radio button selection is filled/selected

4) Given that I'm on the question 'Where did this take place?'
When I select 'In a prison or correctional facility'
Then I see a question - 'What type of prison or correctional facility' and I see 4 options to select - State/local, Federal, Private, I'm not sure

5) Given that I'm on the 'Location' Page
When I DON'T make a selection for 'Where did this take place?' and click 'Next'
Then I see an error message - 'Please select the type of location' 

6) Given that I'm on the 'Location' Page
When I make a selection 'Where did this take place?' and click 'Next'
Then I'm taken to the 'Protected Classes' page

7) a11y requirements
This should be a generic check box interaction.
As a screen reader user, when I get to this question, I hear the question and options.
AND
I can tell when something is and isn't selected
AND
I can navigate & select using keyboard only
[documentation](https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/radio/radio.html)

## Mockups / Wireframes
![location details-expanded copy (1).jpg](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/d6d03e34-840a-4ccc-b8b4-e078fd2744e4)

Source of truth:
https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit?ts=5de6f69e#bookmark=id.g81tvbtz5ejm

## Sign off
- [x] PO
- [ ] DRS
- [x] SPL
UAT Sign off 
- [ ] PO

**Comment by lalitha-jonnalagadda** [comment]
Mock up mural shared by @Jacklynn for review - https://app.mural.co/t/gsa6/m/gsa6/1576020700971/9b8f55c8521d2126a7c510bcfb7981d9dc202cc6

**Comment by lalitha-jonnalagadda** [comment]
@Jacklynn can you please add the mocks to this story?

**Comment by Jacklynn** [comment]
[Added link](https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/58) above

**Comment by Jacklynn** [comment]
Switch outside/inside order so that INSIDE is last

**Comment by blaughman** [comment]
@LindsayYoung @el-mapache @lalitha-jonnalagadda @UchMok When I selected, "mistreated by police..." then I selected "outside a prison..." the complaint was routed to ADM.  Is this because CRM's logic has yet to be installed?

**Comment by el-mapache** [comment]
@blaughman That's correct, the work to route the complaint to the correct section is out of scope for this ticket. This work just adds the user interface and the database model code!

**Comment by el-mapache** [comment]
I think we've currently only implemented `CRM` routing for the hate crimes & trafficking question.

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep-dive on 2/6.
