### ISSUE TITLE
Tell DOJ CRT additional information on where discrimination happened (conditional logic - other public/commercial)

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#199]
## Narrative
As a public user, I want to give DOJ CRT additional information about the location where my rights were allegedly violated so my concern can be routed to the appropriate section.

## Background
The location where a violation occurs is a very important piece of information for CRT intake specialists.  Many times the location will determine which section within CRT may have jurisdiction over the complaint. 

## Assumptions
- conditional logic question is required

## Out of scope
- Routing to sections 
- Branching 'Place of worship' question
 - 'Online' location check box under location details

## Acceptance Criteria
1) Given that I'm on the primary issues page
When I select - 'Discriminated against in any other commercial location or public place' and click next
Then I am taken to 'Location' page where I see two questions - 'Please choose the location that best describes your situation' 
AND
I see an option to provide location details

2) Given that I'm on the 'Discriminated against in any other commercial location or public place' question
When I see 'Please choose the location that best describes your situation'
Then I see I can make a selection between 6 options:
  - Place of worship, 
  - healthcare facility, 
  - commercial or retail,
  - financial institution, 
  - public outdoor space 
  -  other

3) Given that I'm on the 'Location' Page
When I make a selection for 'Please choose the location that best describes your situation' 
Then I see my radio button selection is filled/selected

4) Given that I'm on the 'Location' Page
When I DON'T make a selection for 'Please choose the location that best describes your situation' and click 'Next'
Then I see an error message - 'Please selected type location. If none of these apply to your situation, please select "Other reason" and explain'

5) Given that I'm on the 'Location' Page
When I make a selection 'Was this a public or a private school or education program' and click 'Next'
Then I'm taken to the 'Protected Classes' page

6) Given I'm on the 'location' page
When I select "Other reason"
Then I view a freeform text box (word limit of 10) where I can briefly explain the details of the location
AND a word counter below the text box that says, "10 words remaining" if I have written no words

When I enter 5 words in the 'other' text field
THen I should see '5 words remaining' on the word counter.

When I enter 10 or above words in the 'other' text field
Then I should see 'default message' when words are up.

7) a11y requirements
This should be a generic check box interaction.
As a screen reader user, when I get to this question, I hear the question and options.
AND
I can tell when something is and isn't selected
AND
I can navigate & select using keyboard only
[documentation](https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/radio/radio.html)

## Mockups / Wireframes

https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/55
Source of truth:
https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit?ts=5de6f69e

## Questions
- @Jacklynn and @AvivaOskow - is the expectation here that when the user selects other, we have a free form description box? Something similar to the one on the protected class page with a 10 word limit?

## Sign off
- [x] PO
- [ ] SPL
- [ ] DRS
- [ ] EOS
UAT Sign off 
- [ ] PO

**Comment by el-mapache** [comment]
@Jacklynn @lalitha-jonnalagadda The content source of truth also lists 'Online' as a valid public location for a complaint to be lodged, but the mocks and this issue do not reflect that. Should I be including it here? I'll update the AC if so!

Thanks!

**Comment by Jacklynn** [comment]
@el-mapache My vote is to treat the separately for now. 

Background:
The strongest use case we've heard is from the Disability section, so it might be nice if it was conditionally shown there. We also explored something like this: 
![Online](https://user-images.githubusercontent.com/2560618/72476463-24cf0c80-37a2-11ea-8a03-4ea62dce083b.jpg)

**Comment by el-mapache** [comment]
Got it! I like that checkbox option. I'll remove it from this work then. Thanks for the clarification 😄

**Comment by lalitha-jonnalagadda** [comment]
+1  to what y'all have said - Online check box is out of scope from this story. I updated the out of scope section for this story. For now, if a public user wants to provide information on an 'online' location, they can do so in the location name section and the intake specialists will see that as a part of the location details section of the complaint details page.

**Comment by Jacklynn** [comment]
As a note, this is a special bullet style with help text. I'm pulling this out of @AvivaOskow's patterns list:
<img width="184" alt="Screen Shot 2020-01-15 at 2 41 28 PM" src="https://user-images.githubusercontent.com/2560618/72477849-54cbdf00-37a5-11ea-9f54-b8159b3a6f48.png">

This also affects [Voting's Location details page](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/267) 😇

**Comment by el-mapache** [comment]
Cool, I'll make sure we are using the right classes here!

**Comment by LindsayYoung** [comment]
just noting that the AC language and the content doc have diverged I am assuming the content doc is correct:
- "Place of worship or about a place of worship"
- "Public space"

**Comment by Jacklynn** [comment]
@el-mapache @LindsayYoung when I opened the Location details for the public/commercial the "other" was opened by default. I don't think I've done anything special with my java script

![Screen Shot 2020-01-22 at 2.14.15 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/45f3700c-d042-4fd0-9610-ef15ca9ccd30)

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep-dive on 2/6.
