### ISSUE TITLE
Upgrade Acquia account

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#20]
## Narrative
As a developer, I want advanced features so that we can set up CI/CD. 

## Background
@dwechsle should be assigned this when he accepts membership on the GitHub team
  
## Acceptance criteria
- [ ] GitHub connectivity
- [ ] Pipelines
- [ ] An official production environment
- [ ] Anything to enable log reporting to the DOJ (we will want the same or similar set up to doj.com)

**Comment by UchMok** [comment]
@danielhyi there are 9 days left on our free trial of Acquia. We will need to upgrade to a paid account soon.

**Comment by UchMok** [comment]
@dwechsle to reach out to Acquia requesting a couple weeks extension on our current app
