### ISSUE TITLE
[Placeholder] Translate Landing Page, Form, Error Pages and Privacy Policy to Korean.

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#203]
## Narrative
As a public user, I want to access the complaint portal in Korean so that I can submit a complaint in my native language.

## Background
The Language Working Group (LWG) requested the portal be translated to Vietnamese to increase language access.

**Comment by blaughman** [comment]
Translation from Marta:

[https://app.zenhub.com/files/183258764/aaef3628-01c0-4510-9031-dd944005ded7/download](https://app.zenhub.com/files/183258764/aaef3628-01c0-4510-9031-dd944005ded7/download)

**Comment by blaughman** [comment]
@timoballard @timoballard @Jkrzy @randyabramson I caught this on the landing page during testing

![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/f86043be-109f-4b3e-b842-0ef3bb116440)

**Comment by timoballard** [comment]
Great find @blaughman -- this is due to a merge conflict, so we'll see the same thing in simplified Chinese and Vietnamese as well. I'll fix all 3 and open a single PR shortly!

cc: @Jkrzy @randyabramson

**Comment by blaughman** [comment]
@timoballard Looks like Traditional Chinese is good, but Simplified Chinese, Vietnamese and Korean all have the same issue.

**Comment by blaughman** [comment]
Aside from the aforementioned issue, everything else appears to be working as normal.  Test records created for all pathways.  Pages appeared as intended.

**Comment by randyabramson** [comment]
Good pick up @blaughman

**Comment by timoballard** [comment]
PR open: https://github.com/usdoj-crt/crt-portal/pull/869

**Comment by blaughman** [comment]
Pages are translated with no apparent bugs.  Moving to UAT.
