### ISSUE TITLE
[Placeholder] Translate Landing Page, Form, Error Pages and Privacy Policy to Simplified Chinese

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#207]
## Narrative
As a public user, I want to access the complaint portal in Simplified Chinese so that I can submit a complaint in my native language. 

## Background
The Language Working Group (LWG) requested the portal be translated to Simplified Chinese to increase language access.

**Comment by blaughman** [comment]
All pages appear to be properly translated.  Still need content assessment.  Moving to UAT.
