### ISSUE TITLE
[Feedback] Add "Language" as list item in protected class page

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#208]
[Place holder based on sprint 5 deep dive. @blaughman suggested making this a separate line instead of emphasizing it more on the current line]

Master text file: https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit#bookmark=id.8mspw1xx5w4

**Comment by lalitha-jonnalagadda** [comment]
Looks like we finished this card and we can close this.
