### ISSUE TITLE
Filter by Contact Name - View all table

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#210]
## Narrative
As a DOJ CRT user, I want to be able to filter complaints by complainant first name and last name so that I can only view a subset of the complaints I prefer so I can take relevant action on. 

## Background
All sections at DOJ, receive about 93K complaints annually. With this kind of volume, it's difficult to locate and look up complaints. Filtering by name will allow the intake specialists to look up a list of all complaints by a complainant. 
 
## Out of scope
- Filter by status, incident location, submitted date and other contact information (phone, email)
- Expandable and collapsable filter panel/modal(?)

## Acceptance Criteria

1) Given that I'm on the view all table
When I'm at the Filter by contact name 
Then I see free form text boxes to enter a first and last name
AND
I see a 'Filter Results' option

2)  Given that I'm on the view all table
When I don't select any filter option
Then I see all complaints as the default view

3) Given that I'm on the view all table
When I enter a name or any portion of the first or last name(phrase) in the  'Contact first name' and 'Contact last name' filters and click the 'Filter Results' button
Then I see the view all table filters to display all records matching the name 
AND
I see a tag/label with the filtered criteria by the filtered data

4) Given that I filtered the results by a contact name
When I click 'X' on the tag/label 
Then I see the view all table to display all complaints 

5) Given that I filtered data by contact name AND there are no records for that section
Then I see a message warning me about why there are no records showing
AND 
back and forward pagination arrows are disabled

6) Given that I've applied a filter and have reach the end of all the pages for a given filter (ex: less than 15 or on the final page of pagination)
Then I see a message confirming that I've reached the end of records and to change filters to see more. 

## Mockups
![Viewall-Contact Name.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/c889baa2-3edc-489e-9708-ed09046b62f1)

No records for a filter
![Filter-no records.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/dc577451-6e77-4cd6-97b6-d82799db4341)

Records with less than 15 filter
![Filter-less than 15.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/df3414e1-0e7b-4847-ae8b-304420903eef)

## Questions:
- What is the selection criteria between filters - AND/OR? I'm assuming that the criteria is AND

**Comment by Jacklynn** [comment]
jan 3:
- Ok to move forward with two separate fields for first and last name

**Comment by blaughman** [comment]
Function works as intended in IE 11 and Chrome.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Demo'ed to the deep dive group on 1/9.
