### ISSUE TITLE
Remove extra tab indexes

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#213]
Pulling this out of #211 because we've gotten a11y feedback on this from Terri.

- [ ] We should revert back the changes to the extra tab stops we added, only actionable content should have a tab stop. 

## Additional notes
* The screen reader would read the field with the "optional" label with this field already when (#211) gets implemented
* Then, as an enhancement, use aria-describedby for the help text (#214)

![Screen Shot 2019-12-05 at 10.55.52 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/677b42a9-590d-466d-beb6-674d85d22c1f)

**Comment by LindsayYoung** [comment]
@Jacklynn would you like to confirm this ticket? If you do, you can close it if you are satisfied.

**Comment by Jacklynn** [comment]
Tab stops work for me! I can check with voice over later too.

**Comment by Jacklynn** [comment]
Working well for the most part, but the hint text reads before the examples on the primary issues page. Could it read AFTER the examples for each radio button? If this is complicated, I think it's also ok if we don't use describedby here (this one is more straight forward vs the extra info on the contact page)

**Comment by el-mapache** [comment]
My understanding is that the `describedby` text is going to be read along with the label text, so I don't think this is possible. I think that if we want this text read after each of the examples, we would need to duplicate the `describedby` content in a new DOM element with the `usa-sr-only` class applied to it. That new element would live within each of the radio button's example sections.

**Comment by Jacklynn** [comment]
@el-mapache when we were testing before the whole square of a radio button read together (I think), are the examples getting treated differently now?

**Comment by el-mapache** [comment]
I didn't change anything with the examples, the only thing added was the `describedby` text. I wonder if that is superseding the content in the label? The examples aren't getting read for me at all :/

**Comment by Jacklynn** [comment]
Latest changes working for me now!
