### ISSUE TITLE
Remove header and footers from view all table (CRT side view)

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#216]
[placeholder, will make look more like a webapp]

**Comment by lalitha-jonnalagadda** [comment]
@el-mapache Is there a PR for this already?

**Comment by el-mapache** [comment]
@lalitha-jonnalagadda There sure is! It's already been merged. I didn't realize there was an issue 😄 .

[PR here](https://github.com/usdoj-crt/crt-portal/pull/212)

**Comment by lalitha-jonnalagadda** [comment]
Awesome!!!! Closing this issue :)
