### ISSUE TITLE
Order protected classes in alphabetical order

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#220]
Feedback from DRS 12/10/19 to present protected classes in alphabetical order. 

Team/stakeholders to weigh pros/cons.
- Very neutral but seems like it would be helpful to order them in terms of what's most common.

**Comment by LindsayYoung** [comment]
This is done.
@Jacklynn can this be closed or are we tracking feedback differently?

**Comment by Jacklynn** [comment]
Done! some of these might be old
