### ISSUE TITLE
Make forms.py more consistent

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#223]
There are some small formatting consistency in forms.py would be nice 
make the ` __init__` methods the same

fields attributes are sometimes together and sometimes on separate lines - let's make them like:

    self.fields['location_state'] = ChoiceField(
            choices=STATES_AND_TERRITORIES,
            widget=CrtDropdown,
            required=True,
            error_messages={
                'required': errors['location_state']
            },
            label='State'
        )

**Comment by lalitha-jonnalagadda** [comment]
Since we are using Linter, we don't need this anymore. Per release planning on 7/22
