### ISSUE TITLE
Complaint record viewer text overflow in 'Correspondent Details' section

### ISSUE THREAD

**Issue by el-mapache** [18F/crt-portal#229]
Very long names and emails overflow the 'Details' table.

Visit this (url)[https://crt-portal-django-dev.app.cloud.gov/form/33/?next=%3Fper_page%3D15%26sort%3D-create_date%26page%3D7] to see the bug in action.

## Screenshot

![Screen Shot 2019-12-12 at 10.29.36 AM.png](https://images.zenhubusercontent.com/576c0787bf93871ccd9d1492/fce32383-4517-4b8e-9b46-137ffa6fa4f2)

## AC:

- [ ] As a user, when I visit the Complaint Record view, and I view the correspondent details section, I should not see a table with overflowing content.

**Comment by lalitha-jonnalagadda** [comment]
Tested the record in question and created another one with long names and email and the issue seems to be fixed. Closing this card
