### ISSUE TITLE
Implementing design into development (CRT Intake side)

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#231]
- [x] Annotating the complaint details page - @AvivaOskow 
https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/66

- [ ] Dev implementation

## Questions:
- Do we need annotations for the view all table?
-

**Comment by AvivaOskow** [comment]
I uploaded the annotations for complaint details page [here](https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/66)

**Comment by LindsayYoung** [comment]
One outstanding task is to apply the new style to the section filter. Otherwise, we are in great shape!

**Comment by LindsayYoung** [comment]
It seems like this is covered in https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/426

Feel free to reopen if I missed anything
