### ISSUE TITLE
Implement designs into development (CRT Portal view)

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#232]
- [x] Annotating design for the portal view - @AvivaOskow 
- [ ] Dev work

**Comment by AvivaOskow** [comment]
# Updated Designs

## Contact page (or first page)
![UPDATED Contact - annotations.jpg](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/96d73918-15c5-4b1e-9d32-41395bcc2568)

### Columns
![Screen Shot 2020-01-09 at 2.40.54 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/00be4156-78aa-4349-b078-ca3db3b7a61a)

### Progress Bar
![Screen Shot 2020-01-09 at 3.15.58 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/7e0c19ec-d769-40fa-8665-a33441de9217)

![Screen Shot 2020-01-09 at 3.16.10 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/c9c00460-98c5-4422-b490-44e06c248387)

**Comment by blaughman** [comment]
Update applied.  Moving the card to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Moving this card to 'dev done' for @AvivaOskow to audit the design implementations

**Comment by lalitha-jonnalagadda** [comment]
Since we are going through a thorough design audit and identified a few improvements in other cards, this card can now be closed.
