### ISSUE TITLE
Develop the style guide

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#233]
# [Google folder](https://drive.google.com/file/d/1qEvvTo_YFGupkp6CL6lcLZFA7Yb_yuPv/view?usp=sharing)

[PDF direct download](https://app.zenhub.com/files/183258764/5a30b682-38a4-47fe-b4f3-64d10e85e13d/download)

**Comment by blaughman** [comment]
Moving to closed.
