### ISSUE TITLE
Section names in the filter should be abbreviated

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#234]
Section names are listed in full in the 'view sections'  filter instead of the abbreviations. The view sections filter should list them as follows:

 - All (default)
  - ADM 
  - IER 
  - VOT 
  - DRS 
  - CRM 
  - HCE 
  - EOS 
  - SPL 
  - ELS 
  - FCS 
  - APP

**Comment by blaughman** [comment]
This works as intended.  Would it be possible to have the sections in alphabetical order?

**Comment by lalitha-jonnalagadda** [comment]
Demo'ed to the deep dive group on 1/9.
