### ISSUE TITLE
View Incident Date  

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#236]
## Narrative
As a CRT user, I want to view the date an incident occurred for a complainant so that I can use that information as part of my analysis.
  
## Background
The last date of occurrence is a very important part of CRT's analysis of incoming complaints.  Some statutes enforced by CRT have time limitations and incidents that occur outside of that time frame may not be eligible for relief.  

## Assumptions
 - Incorporating incident date will mean we will be getting rid of the protected classes from the view all table

## Questions
- Where do we put the recurring vs 1x information? @Jacklynn 

## Out of scope
- Recurring incident metadata from #239

### View all table

1. Given a complainant has submitted a record
When I am viewing the 'view all records' page
Then I see
- [ ]  a new column called 'Incident Date'
AND 
- [ ] Incident Date column is to the right of the summary column
AND
- [ ] I no longer see the protected classes column

2) Given that I'm on the view all table
When I'm at the Incident date column
Then I see
- [ ] Date format is MM/DD/YYYY
AND 
 - [ ] For records where a user doesn't provide a date, the date format shown is MM/--/YYYY ( with dashes in the date field) 

3) Given that I'm on the view all table
When I try to sort the date in that column
Then I see that records are sorted chronologically ascending/descending - First by year, then month and then date

### Complaint Details Page

4) Given I am on the view all records page
When I click on that complaint to see the detail page
Then I view 
- [ ] a new label on the detail page called 'Date of Incident' in the complaint details section (refer to the [content source of truth document](https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit#bookmark=id.rjge5koo0jnh))
AND
- [ ] I view the incident date of that record as 'MM/DD/YYYY' with date field replaced by dashes when not provided

5) [a11y] _should be just text in the table_
* a user can navigate to this via keyboard (because the whole row is tappable/interactive)
* there is visible focus
* as a screen reader user, I can understand the date announced (including if a day is missing). If `01/ - /2020` I believe a screen reader will just announce "zero one slash dash slash two thousand twenty"

## Mockups / Wireframes
![D - no protected class Copy.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/2bd50d66-042d-4b58-a9f0-24c7e44f3f64)

## Questions
- How are we going to sort when complaints don't have a date?

## Sign off
- [x] PO
UAT Sign off
 - [ ] PO
 - [ ] UX and a11y
 - [ ] Product design

**Comment by Jacklynn** [comment]
I think it'll be hard to fit any more columns in the table as it now without making them narrower, which might not be easy. I have three options I was experimented with [here](https://docs.google.com/presentation/d/1FuuSg0bb9DDQx_EjRK-T_YZQ0gpcVgIz8-M6BQE-u4g/edit#slide=id.g7c057bbf09_1_0)
- As the columns are now
- With a "global" section view
- Without protected class column

**Comment by lalitha-jonnalagadda** [comment]
Show the date as in view all table.

**Comment by blaughman** [comment]
Incident date is now on the view all table.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep-dive on 2/6.
