### ISSUE TITLE
"Violation summary" to "summary"

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#237]
We got this feedback a while ago during deep dive to change the "violation summary" column heading to just "summary" (and I thought we updated it?) but the view all table still says "Violation summary" and Emily's brought this up a couple of times.

**Comment by blaughman** [comment]
Violation is removed as requested.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Demo'ed to the deep dive group on 1/9.
