### ISSUE TITLE
Record protected class as CRT on complaint record detail page

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#238]

**Comment by Jacklynn** [comment]
@blaughman @UchMok @LindsayYoung  @lalitha-jonnalagadda can you weigh in on text changes we talked about?:
https://docs.google.com/presentation/d/179C6ZvKyZTETbuc-w7OBYMDWZ2GlT8xcjidLf0Xvi1I/edit?folder=11BIYQ9lL3ww10tglqXivjjOHFfenuwTp#slide=id.g7bfc312abd_0_10

**Comment by Jacklynn** [comment]
Text updated, can reopen if this issue isn't solved but I can't remember what this was about?
