### ISSUE TITLE
Make hate crimes & human trafficking question more consistent

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#245]
Devs identified this question as being a unique style that we might want to  make more consistent with other forms that make the form easier to maintain (because less unique styles) and potentially a better user experience, especially for screen reader users. 

Current question on the Primary issues page:
![Screen Shot 2020-01-07 at 10.23.55 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/6cacf0e0-fcf9-4959-b725-66cbaba05982)

**Comment by Jacklynn** [comment]
Aviva is taking a first pass at this!

**Comment by AvivaOskow** [comment]
**Updated design with annotations here**
https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/72

**Comment by blaughman** [comment]
This question is now broken off into it's own page and selecting one or both of the options is routing the complaint to CRM, as expected.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card following our deep dive session on 3/5
