### ISSUE TITLE
Update Primary Issues headings to be more consistent with the rest of the form

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#247]
Right now the primary issues page is not consistent with patterns on the other pages. Prosed updating this to create better user experience and more dev consistency too.

Current: 
![Screen Shot 2020-01-07 at 10.16.26 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/d090f491-8a65-4355-8405-427d2322223d)

Proposed:
- [x] Change page title to "Primary issue" in black text (not "complaint")
- [x] Put the question, "What is your primary reason for contacting the Civil Rights Division?" in blue text under neath it.

Quick mural mock:
![Screen Shot 2020-01-07 at 10.20.36 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/caf8e2dd-9973-4085-807c-160a65f6fab1)

**Comment by blaughman** [comment]
The form now reflects this text change.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Showcased at deep dive on 3/19.
