### ISSUE TITLE
View (and change) complaint status on Complaint details page

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#248]
## Narrative
As a CRT intake specialist,
I want to view the status of a complaint
so that I can determine I need to process the complaint

## Background
DOJ CRT labels an incoming case as 'new' if the complaint has been submitted by the complainant, but has not been analyzed by DOJ CRT staff.  The label designation allows DOJ CRT staff to determine daily workloads and allocate resources. 

Details on [mural](https://app.mural.co/t/gsa6/m/gsa6/1562611057486)

With representation from ADM, DRS, EOS, FCS, IER, SPL, VOT, we gathered the following feedback:
**New** : Record has just been submitted to CRT from the online portal or manual entry, but has not yet been opened by a CRT user; assigned to section
**Open** : Record is being processed by the section, this could mean different things for each section. #50
**Closed** #53 : Complaint was responded to or recommended for review; attempts to contact complainants unsuccessful; section decides to close or open DJ number

## Assumptions
- From the details page, user can not navigate to other complaints (detailed pages of other complaints) using the 'Next' and 'Back' buttons

## Out of scope
- Styling changes on view all table when changing status
- (Re)Routing complaints
- Editing a complaint

## Acceptance criteria
1) Given I am viewing a complaint on the view all complaints table
When I click on a complaint (row)
Then I am directed to that complaint's record page

2) Given I've clicked on a complaint in the view all table
When I am viewing that complaint's record page
Then I view a new column to the left of correspondent information, details and full summary 
AND
I see a status drop down
AND
status on that record details page matches the information of that complaint line item the view all page (should be 'new' for now)

3) Given that I'm on the complaint details page
When I click on the drop down
Then I see 3 options - New, Open and Close

4) Given that I am on the complaint details page of a complaint with 'New' status
When I select 'Open' (or Close)in the status drop down and click the 'Save' button
Then I see that status of the complaint is now 'Open' (or Close)
AND
Then in the view all table, the status of the complaint is now 'Open' (or 'Close)

5) a11y requirements
A screen reader user should be able to hear that this is a drop down and what their current status is
AND
 if they interact with it, they should be able to hear the other options and select a different one.

IF they select another option, they should hear confirmation of that the the status changed.
(this hopefully happens with standard drop down components)

## Mockups
![status drop down.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/ad272310-3142-4bbf-8c36-dc07c64f9c68)

Aviva is using the pill design right now so I added a version with and without that. I mimicked the [default HTML](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_option) behavior where the options stay in the same order every time. 
![Screen Shot 2019-12-30 at 3.10.36 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/1e9b6196-8c2e-48bb-bb88-bb673ebb6348)

## Sign off
- [x] PO
UAT sign off
- [ ] PO
- [ ] UX
- [ ] Product Design

**Comment by Jacklynn** [comment]
@lalitha-jonnalagadda I think this should go back to design/analyzing for a bit. The interaction design should be driven by the ultimate behavior and it seems like there was a little disagreement still. 

Maybe a stop gap would just be showing the status in the same format as the other the other content?

**Comment by lalitha-jonnalagadda** [comment]
Moving this card back to analyzing to address some open questions and finalize design prior to implementation

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep-dive on 2/6.
