### ISSUE TITLE
View section on complaint details page

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#249]
## Narrative
As a CRT intake specialist,
I want to view the section a complaint was routed to
so that I can determine the section a complaint is assigned to

## Background
Complaints received via the CRT portal are routed to sections according to the routing logic. Section assignment if shown on the view all table for sections to glance and filter through. On the complaints detail page, intake specialists can view the section assignment and be able to re route them as needed. 
 
## Out of scope
- Changing sections
- (Re)Routing complaints

## Acceptance criteria
1) Given I am viewing a complaint on the view all complaints table
When I click on a complaint (row)
Then I am directed to that complaint's record page

2) Given I've clicked on a complaint in the view all table
When I am viewing that complaint's record page
Then I view a new column to the left of correspondent information, details and full summary 
AND
I see a section drop down
AND
section on that record details page matches that complaint line item the view all page 

3) Given that I'm on the complaint details page
When I click on the drop down
Then I see the following sections:
  - ADM 
  - IER 
  - VOT 
  - DRS 
  - CRM 
  - HCE 
  - EOS 
  - SPL 
  - ELS 
  - FCS 
  - APP 

4) a11y requirements
 
## Mockups
![section drop down.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/ec534a45-967e-4fed-b053-360c4d5c2bd5)

# Questions:
 - @AvivaOskow @Jacklynn - what is the expected behavior in the section dropdown - is the section a complaint routed to marked by a check box? Is it in bold? How can a user differentiate the section a complaint is assigned to when they click on the drop down?

## Sign off
- [ ] PO
UAT sign off
- [ ] PO

**Comment by lalitha-jonnalagadda** [comment]
Just show abbreviations and not the full section name.

**Comment by el-mapache** [comment]
@lalitha-jonnalagadda Given that the design view in this ticket is quite a bit different from what we currently have on develop, how much of the changes reflected in the mocks is in scope for this issue? 

Would it be sufficient to just add a new card to the left of the info section, with the single routing display? 

I also see that changing sections is out of scope, but the ticket calls for a drop down. Do you think that might have the potential to be confusing to our testers?

Thanks!

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep-dive on 2/6.
