### ISSUE TITLE
View conditional logic selection(mistreated by law) on complaint details page

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#250]
## Narrative
As a CRT intake specialist,
I want to view relevant details of a complaint
so that I can 
- see complainant responses to specific conditional logic questions 
- validate if the complaint was routed appropriately or reroute as needed. 
- take further action on the complaint

## Background
Allegations of mistreatment by police, law enforcement or correctional staff typically are assigned based upon where the incident occurs.  Incidents occurring in a correctional facility are assigned to SPL and incidents that happen in public are assigned to CRM.

## Out of scope

- (Re)Routing complaints
- Editing a complaint

## Acceptance criteria

1) Given that a complainant selected their primary issue as - 'Mistreated by police, law enforcement or correctional staff' 
When they make a selection to 'In a prison or correctional facility' question
Then as a CRT intake specialist, when I am at the complaint details page, I see the selection in the 'Relevant details' section

2) Given that a complainant selected 'Out of prison...' 
When a CRT intake specialist is at the 'Relevant details' section on the complaint details page
Then they see 
- Location: Outside of prison 

3) Given that a complainant selected 'In prison or correctional' 
AND 
Given they select an option from - 'State/local, Federal, Private, I'm not sure'   
When a CRT intake specialist is at the 'Relevant details' section on the complaint details page
Then they see 
- Location: State/local prison
- Location: Federal prison
- Location: Private prison
- Location: Prison (I'm not sure)

4) A user should be able to navigate through this page using a keyboard following a tab order that matches what's visually displayed 

## Mockups

[See MASTER TEXT for latest](https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit#bookmark=id.rjge5koo0jnh)
![Screen Shot 2020-01-13 at 2.59.41 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/833f164a-b008-47ca-880d-d5494d00556c)

## Sign off
- [ ] PO
UAT sign off
- [ ] PO

**Comment by Jacklynn** [comment]
Updated proposed text

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep-dive on 2/6.
