### ISSUE TITLE
View conditional logic selection(active duty service member) on complaint details page

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#251]
## Narrative
As a CRT intake specialist,
I want to view relevant details of a complaint
so that I can 
- see complainant responses to specific conditional logic questions 
- validate if the complaint was routed appropriately or reroute as needed. 
- take further action on the complaint

## Background
 -

## Out of scope

- (Re)Routing complaints
- Editing a complaint

## Acceptance criteria

1) Given that a complainant is on the contact page
When I scroll past the free form contact details
Then I see a new question ' Are you or have you been an active duty service member?'

2) Given that a complainant selected 'Yes' to the 'Active duty service member' question
When a CRT intake specialist is at the 'Relevant details' section on the complaint details page
Then they see 'Service member: Yes'

2) Given that a complainant selected 'No' to the 'Active duty service member' question
When a CRT intake specialist is at the 'Relevant details' section on the complaint details page
Then they see 'Service member: No'

4) A user should be able to navigate through this page using a keyboard following a tab order that matches what's visually displayed 

## Mockups
See latest proposed text in the [MASTER TEXT FILE](https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit#bookmark=id.rjge5koo0jnh)
![Screen Shot 2020-01-13 at 3.08.35 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/8414451f-4219-45f3-af2c-8a0d9f5ce8e1)

## Sign off
- [ ] PO
UAT sign off
- [ ] PO

**Comment by lalitha-jonnalagadda** [comment]
Do these need to be ordered in a particular fashion?

**Comment by Jacklynn** [comment]
Updated proposed text

**Comment by LindsayYoung** [comment]
This would be a good one for pairing for @ilodidoj and @dwechsle

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep-dive on 2/6.
