### ISSUE TITLE
View 'last updated' on complaint details page

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#252]
## Narrative
As a CRT intake specialist,
I want to see when the last update was made 
so that I can determine if there were changes from the last time I accessed the record

## Background
Changes to a complaint can be:
- Change status
- Change section (Re routing)
- Updating narrative
- Adding comments?
Since these changes can be made by several users, having a timestamp to indicate the latest change made will help CRT teams understand if there were changes made since the last time they referred to the complaint.

## Assumptions
- 

## Out of scope
- Specifying what the recent change was 

## Acceptance criteria

1) Given I've clicked on a complaint in the view all table
When I am viewing that complaint's record page
Then I view a new time stamp below 'Received' timestamp

2) Given that I'm on the complaint details page of a newly complaint for the first time
When I'm at the Received and Updated sections
Then I see the timestamps are matching

3) Given that I am on the complaint details page of a complaint with 'New' status
When I select 'Open' (or Close)in the status drop down
Then I see that status of the complaint is now 'Open' (or Close)
AND
Then the 'last Updated' time stamp reflect time and date when the change was made

5) [a11y] _It seems like this would just be text nothing interactive so..._ as a user I would like to read the text in sufficient contrast and, if I'm using a screen reader, be able to navigate to the text using the Arrow keys and hear the same text as is visually represented.
- I believe `text-transform` should be used to make any text all caps so that a screen reader doesn't think it's an abbreviation

I have a life preference for actually showing the date instead of numerically :) `Jan. 29, 2020 at 3:29 PM` because I believe it's the least cognitive load for all users, but I'm ok being consistent with what we're using and what sections are used to: `01/29/2020 at 3:29 PM`

## Questions

- Should the AC's reflect other changes that one can make on the details page too?

## Mockups
![Complaint Details.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/694786a3-588a-4e3b-b5a9-d39b9112568f)

## Sign off
- [x] PO
UAT sign off
- [x] PO
- [ ] UX and a11y 
- [ ] Product Design

**Comment by LindsayYoung** [comment]
(estimate based on the other history card being done)

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Created a new card #342 to change the time to EST. Closing this card.
