### ISSUE TITLE
View 'Status change' in the activity log

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#253]
## Narrative
As a CRT user
I want to see a the changes I or others made on the complaint
So I have a log for all past activity/changes

## Background

Changes to a complaint can be:
- Change status
- Change section (Re routing)
- Updating narrative
- Adding comments?
Since these changes can be made by several users, having a timestamp to indicate the latest change made will help CRT teams understand if there were changes made since the last time they referred to the complaint.

## Out of Scope
- Changing sections
- Commenting on the details page
- Displaying details of the user that made the change
- Customized styling to the activity

## Acceptance Criteria
1) Given that I am on the complaint details page
When I scroll below the 'Actions' Panel 
Then I now see a new  'Activity' Panel

2) Given that I am on the complaint details page
When I change the status of a complaint
Then I see this message in the 'Activity' panel - 'Status changed from X to Y'
AND 
I see a timestamp on when the change was made
AND
I see a user name (identifier)

3) a11y - _Initial thoughts is that this shouldn't be interruptive-ly announced since visually you might miss the change if you're at the top of the page._ 
- A screen reader user should be able to navigate to the activity area and read all of the text in the same visual order by using the arrow keys. 
- All the text should have the proper contrast for its size. 
- I don't think any of the activities need to use semantic heading levels, it would just a be a visual heading styles

## Mock ups
![Complaint detail activity.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/db6142c7-e05f-484e-ade8-aaf4167277ad)

#Questions

- Is the intention from the mock that system generated messages are displayed in italics and user generated ones in regular font? @AvivaOskow @Jacklynn 

## Sign off
 - [x] PO
UAT Sign off
 - [ ] PO
 - [ ] UX and a11y
 - [ ] Product Design

**Comment by Jacklynn** [comment]
@lalitha-jonnalagadda yes, I was thinking system generated statuses would be italic.

**Comment by LindsayYoung** [comment]
Possible packages to help track history:
 https://github.com/justquick/django-activity-stream
 https://github.com/pinax/pinax-notifications 
 https://github.com/etianen/django-reversion

**Comment by el-mapache** [comment]
I've reviewed these packages a bit and spoken with @LindsayYoung, and we both agreed the first package looks like the best fit to achieve the functionality needed for the thin slice.

The second package, `pinax-notifications` seems to primarily deal with email notifications when models update. This makes it a good candidate for future integration when that functionality is necessary, but we don't need it for this piece of work.

Similarly, the third package might prove useful if we need to work with data requiring that revisions to be saved e.g. if intake workers need to access older versions of that data.

I'll be opening a timeboxed spike PR to investigate the first package!

**Comment by lalitha-jonnalagadda** [comment]
Format of the activity change message to be: "Updated <thing that is updated> to <new value>"

**Comment by LindsayYoung** [comment]
@el-mapache did the lion's share of the work on this, I have updated the language in a pr.

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.  The checkbox will not allow input beside PO.

**Comment by lalitha-jonnalagadda** [comment]
Created #350 for additional copy changes. Closing this card
