### ISSUE TITLE
View conditional logic selection(public/commercial) on complaint details page

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#254]
## Narrative
As a CRT intake specialist,
I want to view relevant details of a complaint
so that I can 
- see complainant responses to specific conditional logic questions 
- validate if the complaint was routed appropriately or reroute as needed. 
- take further action on the complaint

## Out of scope
- (Re)Routing complaints
- Editing a complaint

## Acceptance criteria

1) Given that a complainant selected their primary issue as - 'Discriminated against in any other commercial location or public place' and click next
When they make a selection for 'Location that best describes your situation' question
Then as a CRT intake specialist, when I am at the complaint details page, I see the selection in the 'Relevant details' section

2) Given that a complainant selected 'Location that best describes your situation' 
When a CRT intake specialist is at the 'Relevant details' section on the complaint details page
Then they see the complainant select
- Location: Place of worship
- Location: Healthcare facility
-- Reproductive care clinic: Yes
-- Reproductive care clinic: No
- Location: Commercial
- Location: Financial institution
- Location: Public outdoor space

3) Given that a complainant selected 'Other' and entered information in the freeform text box
When a CRT intake specialist is at the 'Relevant details' section on the complaint details page
Then they see 
- Location: Other, _my apartment leasing office_

4) A user should be able to navigate through this page using a keyboard following a tab order that matches what's visually displayed 

## Mockups
Most up-to-date copy in [MASTER TEXT FILE](https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit#bookmark=id.rjge5koo0jnh)

## Sign off
- [ ] PO
UAT sign off
- [ ] PO

**Comment by aviva** [comment]
I am not Aviva Oskow. I am not sure how my email is associates with this.


Aviva Lazar
cfprogrammer.ca 
{ Sent from my data pad 🖖🏻}

**Comment by lalitha-jonnalagadda** [comment]
Incorrect tagging :( my apologies!

**Comment by aviva** [comment]
No problem.

Aviva Lazar
cfprogrammer.ca 
{ Sent from my data pad 🖖🏻}

**Comment by Jacklynn** [comment]
Updated copy with my proposed content

**Comment by aviva** [comment]
Wrong Aviva

Aviva Lazar
cfprogrammer.ca 
{ Sent from my data pad 🖖🏻}

**Comment by Jacklynn** [comment]
Closing this issue and made #266 to track this issue because I think it's going to keep pinging the other Aviva otherwise.
