### ISSUE TITLE
[Task] Routing permutations 

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#260]
Per our tech sync conversation, pulling through all the permutations and combinations between primary issues, protected classes and conditional logic cards that lead to the ultimate routing. 

Make a one off testing and maintenance script
- [x] make a script to make a spread sheet of the permutations
- [x] upload to Drive with fun color coating

**Comment by LindsayYoung** [comment]
Once enhancement we can do as a follow up is to adapt the script to run the logic and compare expected outcome to the test.

**Comment by LindsayYoung** [comment]
@lalitha-jonnalagadda I think we can close this, unless you want anything else. We might want a new ticket when we finish routing and we can make this into an automated test

**Comment by LindsayYoung** [comment]
Here are the results: https://docs.google.com/spreadsheets/d/1Ba0617v1wqwf89vYkCQmpNGmi3yI-bfPgXSF8JPqkeQ/edit#gid=80818894 

I have been updating them as tickets close.

**Comment by lalitha-jonnalagadda** [comment]
Created #291 for automated scripts. Moving this card to Done!
