### ISSUE TITLE
Unique Complaint ID

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#263]
## Narrative
As a user of the complaint portal, I want the system to generate a unique ID number for each complaint submitted into the system.  

## Background
A unique ID number will allow public users to provide a reference number when checking on the status of a previously submitted complaint.  CRT users can easily locate the record using the ID number as well.

## Assumptions
 - This should be a system generated unique ID. We discussed in the past that this could be a unique ID + an alpha numeric appended to the ID. 

## Acceptance Criteria
1) Given that I am a public user and I have filled out the complaint form and am on the 'Review Your Concern' page
  When I select 'Submit Concern'
  Then I am taken to the confirmation page where I see information on what I can expect now that I have submitted my concern as well as a unique complaint ID assigned by the intake system.

2) Given that I am a public user and I have submitted my concern to CRT and my concern has been assigned a unique ID number
  When I want to check on the status of my concern
  Then I can use my unique ID number when contacting CRT staff for a status update

3)  Given that I am a CRT user and on the 'View All Table'
  When I click to select an individual record to view the complaint details page
  Then I see a unique ID number assigned by the system as well as other information submitted by the public user

## Questions:
  - Should this be just on the Complaint details page or both the details and the view all page? (Not at this time as we don't have the real estate on the current view all page)
  - Could we append the year to the unique ID? Eg: 2020-123456 (No, this is going to be a tally number with a 3 letter word appended to the ID)
  - Can we make it a 6 digit number? Ex: 2020-000001 (Format: X-YYY) 
  - Can we reset it each cal year? (No)
  - Will CRT be able to locate complaint ID numbers with a filter function? (Yes, with a future card)

## Sign off
- [x] PO
UAT Sign Off
- [ ] PO
- [ ] Product Design

**Comment by lalitha-jonnalagadda** [comment]
We should use the Django generated ID. For the public facing ID, we want to append a random 'salt' to the unique ID

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Showcased at deep dive on 3/19.
