### ISSUE TITLE
Complaint Narrative - Summary of the complaint

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#264]
## Narrative
As a CRT User, I want to summarize a complainant's submission into a concise format to highlight the issues presented.   

## Background

Extracting key details of a public user's submission will allow CRT users to quickly determine the merit of a concern.

## Assumptions

- The summary should not approach the words allotted to the public users in the freeform of the intake form.
- CRT users will list the relevant data to allow for informed decisions on how to proceed with a submission.
- This summary section should be editable
- Soft character limit - 7000 characters

## Out of Scope
- Editing a summary

## Acceptance Criteria
1)  Given I am on the view all table
     When I I click to select a particular submission from the public
     Then I am taken to the complaint detail page

2)  Given I am on the complaint detail page
     When I see the information for the 'Reported Complaint'
     Then I see a title of "Summary" and a text box to add a summary. 
AND 
The "Save" button is disabled because I have not typed anything and can't submit

3)  Given I'm on the summary section of the 'Reported Complaint' section
     When I see a text box
     Then I can add my analysis of the complainant's concerns
AND 
I can click 'Save' to record my summary, which became active after I started typing/made changes
OR I can click 'Cancel' to leave the text box and not save any changes I've made

4) Given that I completed adding a narrative
When I click the 'Save' button
Then I see that my information is saved
AND
In the activity log a new entry that includes:
 - The user that added the comment
 - Description that 'a new complaint summary was added'
 - Description as entered in the narrative

5)  a11y requirements
- [ ] Field should have a label that reads out to a screen reader (whatever the visual field label is)
- [ ] Field should have visible focus when active
- [ ] you should be able to get to this text area a keyboard only (ex: tabbing)
- [ ] feedback on action
- [ ] buttons have labels that read out to a screen reader
- [ ] there is sufficient contrast for the all elements, including on hover and click states

## Questions

- Functionality to allow the intake specialists to write up a summary narrative of the complaint in their own words
- Edit?  Should changes be reflected in the activity log?

### [UX details](https://docs.google.com/presentation/d/1FuuSg0bb9DDQx_EjRK-T_YZQ0gpcVgIz8-M6BQE-u4g/edit#slide=id.g8144cd0cd1_0_17)

![4 - submitted@2x](https://user-images.githubusercontent.com/2560618/76787243-d4f6cc80-6775-11ea-9f76-c4c627c3a1d0.png)

## Sign Off
- [x] PO
UAT Sign Off
- [ ] Design Staff

**Comment by UchMok** [comment]
@Jacklynn please add your 'like to have' in-line edit version to this story

**Comment by Jacklynn** [comment]
Added & updated links

**Comment by lalitha-jonnalagadda** [comment]
Add an AC for activity log

**Comment by blaughman** [comment]
Function works as intended in Dev.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
