### ISSUE TITLE
Explore removing "military" from protected class list

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#265]
We're asking if a someone is a service member as an explicit, required question already. It seems duplicative of asking if 'military' seemed like the basis of discrimination. We don't want to ask users unnecessary or duplicative information and CRT might get mixed data (ex: self report one but not the other).

- [ ] Ask ELS, HCE, VOT if there is any value for keeping the class there if we're asking as a required question elsewhere in the form. Weigh against user cost.
- [ ] Determine if we should remove the question or not—if removing, implement.

**Comment by Jacklynn** [comment]
From standup, @blaughman agreed to email ELS, HCE, and VOT.

**Comment by LindsayYoung** [comment]
Done
