### ISSUE TITLE
Tell us what happened: style regression for blue text

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#268]
The "Tell us what happened" isn't using a heading style.

Current "tell us what happened text":
![Screen Shot 2020-01-14 at 3.31.21 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/59ab4b47-ae31-459f-9dc6-b541b6dbe9c4)

Expected/previous:
(this is a screenshot of a previous build)
![Screen Shot 2020-01-14 at 3.35.12 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/389f8030-2480-4604-a24a-5a5efa09c167)

**Comment by lalitha-jonnalagadda** [comment]
Works well in dev. @Jacklynn @AvivaOskow - please move this to ready for UAT if design approves

**Comment by Jacklynn** [comment]
Approved. It's just like how I remembered _tear_
