### ISSUE TITLE
View total # of complaints when I view all or some complaints

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#27]
View total # of complaints when I view all or some complaintsI know the volume of complaints I have to deal with or report on

**Comment by LindsayYoung** [comment]
We have this done as part of: https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/28

**Comment by lalitha-jonnalagadda** [comment]
As part of pagination card, we are now showing the total number of complaints on the view all table along with the number of records being viewed at that point in time. @UchMok I'm ready to close this card. If you want this to be open for any other reason, please let me know. ![Screen Shot 2019-12-06 at 10.32.18 AM.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/eda133e1-bdb1-4813-a2c9-3e607fc3bd0d)
