### ISSUE TITLE
Update protected class text in the CRT view

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#270]
- [ ] Update table column heading to..."reported class"
- [ ] Update details page heading to... "reported class"

Today they say "class" and "protected class" but protected class is a legal term which we want to move away from and we want to make them consistent

**Comment by Jacklynn** [comment]
@AvivaOskow to sign off

**Comment by lalitha-jonnalagadda** [comment]
Closing this card. We moved away from 'Protected classes' copy altogether
