### ISSUE TITLE
Upgrades

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#272]
We need to update some packages:

- new Python version
Support on the build pack for 3.7 is being phased out, we need to upgrade to 3.8

- new Django version 2.2.8 to 2.2.9
There is a CVE out, but it doesn't affect us because we are not enabling the affected feature

- some node updates
pa11y, autoprefixer, node sass

This would be good for pairing

**Comment by lalitha-jonnalagadda** [comment]
Done!
