### ISSUE TITLE
Conditional logic selection(School) in relevant details  

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#273]
## Narrative
As a CRT intake specialist,
I want to view relevant details of a complaint
so that I can 
- see complainant responses to specific conditional logic questions 
- validate if the complaint was routed appropriately or reroute as needed. 
- take further action on the complaint

## Out of scope

- (Re)Routing complaints
- Editing a complaint

## Acceptance criteria

1) Given that a complainant selected their primary issue as - 'Discrimination at school..' 
When they make a selection to 'Was this a public/private school' question
Then as a CRT intake specialist, when I am at the complaint details page, I see the selection in the 'Relevant details' section

2) Given that a complainant selected 'Discrimination at school...' 
When a CRT intake specialist is at the 'Relevant details' section on the complaint details page
Then they see 
- School: Public OR Private OR I'm not sure 

3) A user should be able to navigate through this page using a keyboard following a tab order that matches what's visually displayed 

## Mockups

[See MASTER TEXT for latest](https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit#bookmark=id.rjge5koo0jnh)

## Sign off
- [x] PO
UAT sign off
- [ ] PO

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep-dive on 2/6.
