### ISSUE TITLE
In radio lists with an 'other' field, clicking on another option does not toggle the 'other' text box

### ISSUE THREAD

**Issue by el-mapache** [18F/crt-portal#274]
The previous implementation relied on the list of options being checkboxes, and thus multiple select. Because the user can only select a single radio button at a time, continuing to display the `other` text box doesn't make sense if the user selects another option.

**AC**

1. GIVEN I am on a page with a list of radio options
AND list of options has an `other` option
2. WHEN I select `other`
3. THEN I select any other choice
  * [ ] The `other` text box is hidden

**Comment by blaughman** [comment]
Function works as intended.

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep-dive on 2/6.
