### ISSUE TITLE
[CRT View] City & State boxes are running into each other

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#276]
CURRENT:
![Screen Shot 2020-01-22 at 6.08.12 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/e7008f6e-a0b2-4d4c-8bb5-e0b65729bb34)

Need to spec solution

**Comment by el-mapache** [comment]
@Jacklynn On which page are you seeing this?

**Comment by Jacklynn** [comment]
Ack sorry, this is on the desktop view for the View All table. But I think some more things need to be ironed out so I don't think we need to tackle this just yet. Just tracking so I remember.

**Comment by Jacklynn** [comment]
This looks ok now
