### ISSUE TITLE
View X complaints at a time (pagination)

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#28]
## Narrative
As a CRT user
I want to *View 15 complaints at a time* on the view all table
So that I can easily navigate large volumes of complaints

## Business Context
CRT gets around 100,000 complaints a year. Assuming 30,000 of those complaints are phone calls, we can assume they can potentially get on avg ~1000 complaints a week collectively (no sections filtered). 

SPL receives around 21000 complaints a year of which ~13000 are email and snail mail. In the new system, they can potentially receive up to 200 SPL-related complaints a week.

[Volume of complaints data](https://docs.google.com/spreadsheets/d/1AgXdYklkNoKOO3qAj3IZ-NccVcrb0iI9ZiIDr8cbcMs/edit#gid=1701452409)

## Assumptions
- fixed pagination is in scope for this story
- X(15 for now) can be changed once feedback received from UAT

## Out of scope
- Customization on the number of records ( dropdown to select 15, 25, 50..etc)
 
## Dependency
- Sorting and filtering can get played after this story has been developed

## Acceptance Criteria

1) Given that I am on the View all table page, 
 when there are 15 complaints
then I see the total number of records is 15
AND
the back and forward arrows are disabled (indicated by gray color) because there is only one page

2) Given that I am on the view all table page
when I have (more than 15) >=16 records
then
- [ ]  I see that there are more than 15 records 
AND 
- [ ]  I see that I'm viewing 15 of the total number of records
AND 
- [ ] I see an option to go to the next page
AND 
- [ ] If I'm on the first page, the back arrow is disabled (indicated by gray color)

3) Given that I have Z (3X complaints), 
when I am on the view all table
then 
- [ ] I see that there are Z complaints 
AND 
- [ ]  there are 3 pages of records
AND
 - [ ] I can move between pages by clicking on the page number or the next button
AND
- [ ] `total-visible` numbers shown will be six [(documentation)](https://vuetifyjs.com/en/components/paginations) 

AND
- [ ] when i get to the last page, the Next arrow is disabled (gray color)

4) Given that I am on the view all table page, 
when I'm on a pages
then I see that the page number I'm on is highlighted

5) Accessibility -- as a user....
I should be able to navigate by keyboard.
I should be able to know that there is a pagination navigation when scanning the page with a screen reader.
Each navigation item should be read as "Goto Page 1".
I need to know which element is currently active.
I need to navigate with Next and Previous links.
-- found this documentation on pagination: https://www.a11ymatters.com/pattern/pagination/
## Questions
- @Jacklynn - when a user clicks on the ellipsis, what is the behavior? Will we show the next 5 pages to select from or something else? 
--- I like the interaction here where the `...` isn't clickable but let's you move around the pagination. https://vuetifyjs.com/en/components/paginations (long example). Updated the mock too.

## Mocks 
![[LATEST] CRT view all no stripes Copy 2.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/b2bef877-bbe3-444b-9ddf-40e463b76568)
One page
![[LATEST] CRT view all no stripes Pagination Copy 2.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/15087ef4-9c25-4d1c-9eb7-b9d2ad393d49)

**Interaction**

![Group 7.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/9daa0c3a-7fbf-46b1-a3b9-6a581fd496b1)

**box**
toch target size: 40w x 44h
`border-radius: 5px;`
Selected number bg: primary blue (#1A4480)
selected text color: white #ffffff
unselected text color: (primary blue)

**elipses**
Normal text color (#2E2E2A, bg-gray-warm-80)

**onhover**
(same as primary issue interaction)
`background: #E1E7F1;` (same background as primary issue, bg-blue-warm-5)

**onclick**
`background: #E1E7F1;` (bg-blue-warm-10)

**disabled arrow**
`#ADADAD`
**Active arrow**
_Primary blue (#1A4480)_

**arrow SVG--> download** ![ic-backarrow.svg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/1f8f537d-7ff6-4fef-8ac8-f131841d5103)

**Comment by lalitha-jonnalagadda** [comment]
@alexsoble and @LindsayYoung to direct the team on the pagination tool that they are thinking of and if we need to flush this story further. 

@AvivaOskow and @Jacklynn to mock up pagination on the intake view all table screen

- USWDS pagination can be used for reference.

**Comment by Jacklynn** [comment]
To answer the question above, I mimicked this design from the SAMSHA team: https://findtreatmentbeta.18f.gov/results (type in a zip code and see the pagination at the bottom)
--- But actually I like the interaction here where you the `...` isn't clickable but let's you move around the pagination. https://vuetifyjs.com/en/components/paginations (long example)

**Comment by Jacklynn** [comment]
Updated the mock

**Comment by lalitha-jonnalagadda** [comment]
Notes from the review:

- @lalitha-jonnalagadda to update the AC's and expected behavior

**Comment by lalitha-jonnalagadda** [comment]
Updated the AC's. This story is ready for story kick-off before moving it to 'Ready for UAT'

**Comment by LindsayYoung** [comment]
docs for reference
https://docs.djangoproject.com/en/2.2/topics/pagination/

found a great post on pagination https://simpleisbetterthancomplex.com/tutorial/2016/08/03/how-to-paginate-with-django.html

**Comment by Jacklynn** [comment]
@lalitha-jonnalagadda @LindsayYoung Lalitha was right, the example I showed uses total visible 7 (i guess ellipses counts), but I know you're using something different.

**Comment by LindsayYoung** [comment]
First round of functionality is deployed to dev, handing off to @alexsoble for styling

![Screen Shot 2019-11-14 at 6.04.10 PM.png](https://images.zenhubusercontent.com/56f1892d6caf56c9d38e1ac3/5e92526f-d62f-4fe6-ab42-05c5a98952ad)

**Comment by blaughman** [comment]
Pagination works as expected in IE 11.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Completed independent UAT review.
