### ISSUE TITLE
[a11y] Details page isn't announcing 'words remaining' when typed

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#286]
This appears to be a regression, because it was working previously.

As you type, 'words remaining' should announce politely (after a pause), until you get towards the end (I can't remember the exact number but it's probably in the original ticket) and it'll announce more assertively (after a shorter pause). Terri noticed it wasn't announcing when she typed, only when she pasted text. I was able to recreate this too.

I wonder if something happened to this page because the styles are off too. The heading style and the 'words remaining' text itself drifted down.

**Comment by Jacklynn** [comment]
@el-mapache I'm not able to get this to work without pasting text and i've tried hard refreshing. 

This is a regression because it was working before, I wonder if you could see what changed from previous version of this component?

**Comment by el-mapache** [comment]
Did you try on safari with VO? I think unless you are using one of the windows tools we arent going to get consistent results with chrome 😢 🐼

**Comment by Jacklynn** [comment]
Yeah I did try in safari + VO!  😅 are you able to get it to work in Safari/VO?

**Comment by Jacklynn** [comment]
That seems to be working when you type a single letter it will announce, if you get beyond the first letter it shuts up, maybe that's what we were noticing?

**Comment by lalitha-jonnalagadda** [comment]
@Jacklynn are we good to close this card?

**Comment by Jacklynn** [comment]
Yup, this was working when we tested with Terri yesterday
