### ISSUE TITLE
view a summary page before submitting my complaint

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#29]
view a summary page before submitting my complaintI know all the information that I entered is as I intended it to be.read-only

**Comment by lalitha-jonnalagadda** [comment]
Based on Lindsay's comments from her spike, the done functionality in Django needs some customizing. Adding an estimate to this card based on the notes from the spike.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card as we finished work on this as a part of the thin slice already
