### ISSUE TITLE
Review Page

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#294]
## Narrative
As a public user
I want to be able to review my complaint before submission
So that I can finish my complaint and submit it

## Out of Scope
 - Editing complaint from the review page

## Acceptance Criteria

1. Given that I'm on the 'Tell us what happened' 
When I click 'Next'
Then I'm on the 'Review your submission' page

2. Given that I'm on the 'Review your submission' page
Then I see
 - The navigation bar is highlighted to the review and submit step
 - I see two buttons - 'Go back to review your submission' and 'Submit complaint' 
 - my complaint details/selections

3. Given that i'm on the 'Review your submission' page
When I click on the submit button
Then I'm taken to the confirmation page

4. Given that I'm using a screen reader, I can navigate to interactive elements using keyboard only (I think just buttons on this page), understand what they are (buttons are labeled) and interactive with them (press the buttons!). 
-- I would also expect there to be fewer semantic headings than might be visually shown, but I'm not sure how Aviva is designing it right now!

## Mock ups
📖[Bookmarked content here](https://docs.google.com/document/d/1-HLdb21JA6_EuMHZTOi7KXFWWV4mT2Af54Tzzijl2E8/edit#bookmark=id.f0z1rn36bnty)

Mocks (visuals only!)
![UPDATED Review & Submit.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/a5e32642-90ec-4c60-a533-c6b2646df740)

## Sign off 
- [x] PO
UAT Sign off
- [x] PO
- [ ] UX and a11y
- [ ] Product Design

**Comment by Jacklynn** [comment]
Added a11y ACs

**Comment by Jacklynn** [comment]
I added @AvivaOskow latest mocks and a link to the master content

**Comment by LindsayYoung** [comment]
noticing the steps are off, and that is causing the review bubble not to light up

![Screen Shot 2020-03-03 at 2.02.15 PM.png](https://images.zenhubusercontent.com/56f1892d6caf56c9d38e1ac3/6409cd76-a472-41eb-aa6f-c920b929619e)

**Comment by Jacklynn** [comment]
This is amazing!!

For accessibility, I propose remove headings 3 & 4 as _semantic_ headings so they don't get picked up on screen reader outlines of a page. 

Today they're showing up as heading levels: 
![Screen Shot 2020-03-04 at 5.30.39 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/3caad378-c1e0-42a4-9c48-6998a1925b61)

Expected that they don't show ups as semantic headings, like on the other parts of the form:
![Screen Shot 2020-03-04 at 5.32.13 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/4726e2b9-9512-43c3-9e30-8654e57e3708)

**Documentation**
* [Here's a helpful explainer](https://www.nomensa.com/blog/2017/how-structure-headings-web-accessibility)

**Comment by Jacklynn** [comment]
- [ ] for headings, Terri said we could just remove the H4s
- [ ] Links should have unique labels. On the review page, it looks like we need to use `aria-label` instead of just `label` to the buttons since Lindsay already added unique labels (yay!)

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card as we UAT'ed this feature during the past deep dive
