### ISSUE TITLE
Add Filter by status

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#299]
## Narrative
As a DOJ CRT intake specialist, I want to be able to filter records by status so that I can view a subset dataset of interest to look at. 

## Background
All sections at DOJ, receive about 93K complaints annually. With this kind of volume, it's difficult to locate and look up complaints. Filtering by name will allow the intake specialists to look up a list of all complaints by a complainant. 

## Out of scope
-Dynamic filtering

## Acceptance criteria

1) Given that I'm on the view all table
When I'm at the Filter by status section
Then I see a drop down to select the status
AND
I see a 'Filter Results' button
AND
I see 3 statuses to choose from - New, Open and Close

2)  Given that I'm on the view all table
When I don't select any filter option
Then I see all complaints as the default view

3) Given that I'm on the view all table
When I select a status from the drop down and click the 'Filter Results' button
Then I see the view all table filters to display all records matching the status
AND
I see a tag/label with the filtered criteria 

4) Given that I filtered the results by a status
When I click 'X' on the tag/label 
Then I see the view all table to display all complaints 

5) Given that I filtered data by status AND there are no records for that section
Then I see a message warning me about why there are no records showing
AND 
back and forward pagination arrows are disabled

6) Given that I've applied a filter and have reach the end of all the pages for a given filter (ex: less than 15 or on the final page of pagination)
Then I see a message confirming that I've reached the end of records and to change filters to see more.

## Sign off
Story and UAT
- [x] PO
- [ ] Product Design
- [ ] a11y

**Comment by Jkrzy** [comment]
Pulling this one back to integrate w/ @el-mapache's awesome design implementation

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card following our deep dive session on 3/5
