### ISSUE TITLE
Update "day" page error messages"

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#304]
Entered: 00/ /000 and got the error message **"invalid date format 0/1/0."** which is also not a valid date format.

- [ ] Generic, fall-back message: `Please enter a valid date format. Use format MM/DD/YYYY.` for the **generic error message**

Entered 01/33/2000 got generic error message. 
- [ ] Day error message: `Please enter a valid day of the month. Day must be between 1 and the last day of the month.`

Source of truth: https://docs.google.com/document/d/1-HLdb21JA6_EuMHZTOi7KXFWWV4mT2Af54Tzzijl2E8/edit#

**Comment by Mtcarp** [comment]
@Jacklynn @lalitha-jonnalagadda First, I want to verify that the valid date format is MM/DD/YYYY because in the source of truth doc it says use format MM/DD/YY. Just want to verify. In terms of error message (and I have updated this in the "Content Review" source of truth doc: https://docs.google.com/document/d/1-HLdb21JA6_EuMHZTOi7KXFWWV4mT2Af54Tzzijl2E8/edit#), I recommend:

[Error message for day]: "Please enter a valid day. Day cannot be greater than 31."
[Error message for not valid date]: "Please enter a valid date format. Use format MM/DD/YYYY."

**Comment by Jacklynn** [comment]
@mtcarp The component might have additional validation, so can we make the day one more generic? Like, it could know that Feb doesn’t have more than 29 days ever.

Yes it's a four digit year, good catch!

**Comment by Mtcarp** [comment]
@Jacklynn I'd have to think through the "day" error a bit more. I figured "Day cannot be greater than 31" would account for entering any number that is 31 or less. Let me look into some UX writing guidance regarding something more generic.

**Comment by Mtcarp** [comment]
@Jacklynn I made an update to the "day" error and updated it in the content review source of truth too: "Please enter a valid day of the month. Day must be between 1 and the last day of the month."

**Comment by Jacklynn** [comment]
Thank you! updated the description too!

**Comment by Jacklynn** [comment]
I'm still seeing a the same old generic message, which I don't think should show up at all for this scenario since the other message covers it?

![Screen Shot 2020-03-04 at 4.48.27 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/ba7d3424-1479-4de6-a3ee-cdb4b57bd066)

**Comment by Jkrzy** [comment]
Hey @Jacklynn, I'm picking up this card now...

It's a bit tricky to capture _all_ of the possible error states given that we have 3 inputd, each of which can have errors, and the combination of 2 or more of those inputs can generate different errors.

e.g. 2/29/2020 is valid
       2/29/2019 fails as `Invalid date format 2/29/2019.` at the moment.

I'll take a first pass at tweaking this a bit but will timebox and check back in as I don't want to go too far down the rabbit hole.

**Comment by Jacklynn** [comment]
@Jkrzy I _think_ we're on the same page in that we don't know all of the error states, but we just wanted to update the language of the 'catch all' error message to "Please enter a valid date format. Use format MM/DD/YYYY."  Previously shown above as "Invalid date format [content entered]"

**Comment by Jkrzy** [comment]
Ah ok, thanks for the clarification!

**Comment by Jkrzy** [comment]
Like this @Jacklynn? 

The logic still seems funky to me, with both error messages appearing. I see some potentially small changes we can make to tweak this a bit but I don't want to reinvent the wheel if you all have already settled on an approach here.


![Screen Shot 2020-03-13 at 10.02.11 AM.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/b29bb4e6-7e0f-4307-9a85-545f11490de0)

**Comment by Jacklynn** [comment]
Agree the logic is funky. What triggers the second one to show up? Or did we manually add the day one so there's a conflict? 

Maybe it would help if it was just "Please enter a valid date. Use the format MM/DD/YYY" -- No "format" because what's off is an invalid date, not a the format as a generic problem that could catch other things.

**Comment by Jacklynn** [comment]
i really like error messages to tell users exactly how to fix the problem, but if this is causing conflicts and messiness we can improve our generic message and roll back the other message?

**Comment by LindsayYoung** [comment]
Ok, think I can do this when I update the error messages.

**Comment by Jkrzy** [comment]
Tackled by @LindsayYoung  in https://github.com/usdoj-crt/crt-portal/pull/355

**Comment by blaughman** [comment]
Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
