### ISSUE TITLE
Upgrade Prod DB

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#307]
unbind and delete current shared postgres database to prepare for higher loads.
created redundant medium sized postgres database for better performance. 3.75 GB storage

**Comment by LindsayYoung** [comment]
Updates have taken place just need to confirm that everything is working. Ran out of time during paring

 - [ ] can create sample record
 - [ ] can view sample record (DOJ login only)

**Comment by lalitha-jonnalagadda** [comment]
Completed
