### ISSUE TITLE
As a CRT user, I'd like to filter by the unique ID

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#312]
[placeholder: As a CRT user, if I want to pull up a specific record quickly and have the unique idea (maybe public complainant called asking about it and has their information), I would like to filter by the unique ID I have]

**Comment by LindsayYoung** [comment]
backend work is done for this, needs front end implementation

**Comment by lalitha-jonnalagadda** [comment]
Duplicate to #198. Closing this card
