### ISSUE TITLE
Link to privacy policy on the public facing form

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#314]
## Narrative

As a public user
I would like to have DOJ's privacy policy available on the form
So that I can refer to and understand privacy limitations accordingly

## Mock up
Content for privacy policy
https://docs.google.com/document/d/1CPEz6mtvYxonbILPZZFfujajV7SRcJ9K6apq6Zomvyg/edit

@AvivaOskow can you please provide a mock up for this

**Comment by AvivaOskow** [comment]
# Link in the footer:
![Screen Shot 2020-04-27 at 2.37.53 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/3fae9218-f36c-44df-bc5a-e92935c773e2)

# Privacy policy page (first draft! Content needs work)

![Privacy.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/504eebce-ea2a-499e-8a70-fcca7d882d69)

**Comment by Jacklynn** [comment]
@AvivaOskow My 2cents for simplifying the page would be to soften the section divides. If the color change is important, maybe making it not reverse the text (changing from black to white), but like different soft colors (that might look really bad).

**Comment by Jkrzy** [comment]
Grabbing this one and building off @cantsin 's work in [#32](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/32)

@AvivaOskow, @Jacklynn, it looks like the final content only has three sections:
* Privacy Act Statement
* You should also know that:
* We are authorized to collect this information pursuant to the following statutes:

From the most recent mock-up I see this as the first two with a pale background, and statutes with the dark blue. yes, no, maybe?

**Comment by Jacklynn** [comment]
@Jkrzy I think @AvivaOskow was making a truly noble attempt to make the privacy policy more plain language. 

My two cents is that we should put the content as is all on the tan background as a first pass since we don't expect this to be the website's most popular page.

**Comment by blaughman** [comment]
Privacy policy is properly accessed through the link.
