### ISSUE TITLE
Changes to the protected classes page

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#316]
- [x] Remove Military status as a protected class
- [x] Arrange protected classes alphabetically 
  - [x] Exception: Other and None of these apply to me will always stay at the bottom of the list

**Comment by Jacklynn** [comment]
@LindsayYoung The "Other" option should read `Other reason` --- it's missing the word "reason"

**Comment by blaughman** [comment]
Edits made to requested items.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card following our deep dive session on 3/5
