### ISSUE TITLE
Copy edits - Step names

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#317]
- Make copy changes proposed by the team on the questionnaire 

Latest content source of truth: 

 https://docs.google.com/document/d/1-HLdb21JA6_EuMHZTOi7KXFWWV4mT2Af54Tzzijl2E8/edit?ts=5e41ce91

**Comment by Jacklynn** [comment]
1-6 look good to me!

**Comment by Mtcarp** [comment]
After testing, step names are fine as-is. One thing is to double-check the order of the steps. I noticed that order on dev differs from the order listed in the "content review" document.
@lalitha-jonnalagadda -- since I am a read-only user, I can't move this card. FYI.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card following our deep dive session on 3/5
