### ISSUE TITLE
Copy edits - Change 'Protected classes' to 'Personal Characteristics'

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#320]
Update the language on the protected class page.

Latest content source of truth:

https://docs.google.com/document/d/1-HLdb21JA6_EuMHZTOi7KXFWWV4mT2Af54Tzzijl2E8/edit?ts=5e41ce91#heading=h.8yoll6pcyuf8

 Remove Military status as a protected class
 Arrange protected classes alphabetically
 Exception: Other and None of these apply to me will always stay at the bottom of the list

**Comment by blaughman** [comment]
Form reflects the change.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card following our deep dive session on 3/5
