### ISSUE TITLE
Copy Edits - Hate Crimes and human trafficking

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#321]
Update the language on the hate crimes and human trafficking page.

Latest content source of truth:

https://docs.google.com/document/d/1-HLdb21JA6_EuMHZTOi7KXFWWV4mT2Af54Tzzijl2E8/edit?ts=5e41ce91

**Comment by Jacklynn** [comment]
Should use "and" instead of "&" in the title.

**Comment by Mtcarp** [comment]
Language is updated for hate crime and human trafficking based on user research feedback. Changed all instances of "&" to "and" for all form content. 

All changes are tracked changes in doc so team can see what has changed.

**Comment by Mtcarp** [comment]
@lalitha-jonnalagadda - I only have read-only access do I can't move this card but it is ready for UAT

**Comment by blaughman** [comment]
Content has been updated.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card following our deep dive session on 3/5
