### ISSUE TITLE
Copy edits - Primary Issues

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#322]
Latest content source of truth:

https://docs.google.com/document/d/1-HLdb21JA6_EuMHZTOi7KXFWWV4mT2Af54Tzzijl2E8/edit?ts=5e41ce91

**Comment by Jacklynn** [comment]
These looked good to me. I removed the period from the content source of truth that Lindsay commented on in one of the examples (since none of the others had a period

**Comment by Mtcarp** [comment]
Updated Voting rights section only based on user testing. This is read for UAT. @lalitha-jonnalagadda - since i'm read only I can't move this card.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card following our deep dive session on 3/5
