### ISSUE TITLE
Complaint Detail Page - Incident Date view bug

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#323]
When a user enters a date in the day field, the complaint detail page is not placing a forward slash between the day and the year.  

![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/d75bbe27-bb3d-48fb-bf8e-7a704e12e22b)

**Comment by blaughman** [comment]
Bug has been fixed.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card following our deep dive session on 3/5
