### ISSUE TITLE
Off-board Adam and Alex

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#327]
## Description
Remove @el-mapache and @alexsoble from project accounts. 
**Don't start this until March 2nd. Since Adam is still working.** 

## Definition of done
- Remove accounts
   - [x] 18F CRT GitHub team (circle and zenhub access are connected to GitHub)
   - [x] CRT GitHub @dwechsle
   - [x] cloud.gov
   - CRT site accounts
      - [x] dev
      - [x] stage
      - [x] prod
- [x] Update [accounts tracker](https://docs.google.com/spreadsheets/d/1VM5hSsxUgqFM6t51Ejm_EjxnbxLI-pTXF_CVxZJSekQ/edit#gid=0)

**Comment by LindsayYoung** [comment]
@dwechsle when you remove Adam and confirm Alex is removed can you update the [accounts tracker](https://docs.google.com/spreadsheets/d/1VM5hSsxUgqFM6t51Ejm_EjxnbxLI-pTXF_CVxZJSekQ/edit#gid=0) and mark it as done on this card?

Thanks!

**Comment by dwechsle** [comment]
removed adam from github permissions and confirmed alex removed. also updated [accounts tracker](https://docs.google.com/spreadsheets/d/1VM5hSsxUgqFM6t51Ejm_EjxnbxLI-pTXF_CVxZJSekQ/edit#gid=0)
