### ISSUE TITLE
Copy edits

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#328]
Scope of this card:

- [ ] Remainder of the copy edits proposed by Malaika that weren't achieved in the 4 copy edit cards in the past

- [ ] Copy edits following the usability studies

Done:
- #320 Personal charastics
- #321 Human Traffing / hate crimes
- #317 Step names 
- #322 Primary concern

To do:
- #368 Title
- #369 Contact Page edits
- #370 Hate crimes again
- #371 Location
- #372 Date
- #373 Personal description

**Comment by LindsayYoung** [comment]
Closing this issue in favor of tracking the issues separately. Feel free to add anything I missed
