### ISSUE TITLE
Extra space above service members card

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#329]
![Screen Shot 2020-02-26 at 8.23.48 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/732f5641-eb1f-4c27-b096-2240e6faca25)

It looks like there's more than the 56px boarder above this card.

**Comment by lalitha-jonnalagadda** [comment]
Showcased at deep dive on 3/19.
