### ISSUE TITLE
Drop down radio button runs into text

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#331]
![Screen Shot 2020-02-26 at 11.04.44 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/fb346671-43f4-4595-8d55-1171d9101787)

Tested today on dev on Chrome and tried hard refreshing

**Comment by LindsayYoung** [comment]
@ilodidoj do you want to try this ticket?

**Comment by LindsayYoung** [comment]
I ended up doing this one

**Comment by LindsayYoung** [comment]
@Jacklynn this is how it is now, does this spacing look right to you?

![Screen Shot 2020-04-01 at 5.43.12 PM.png](https://images.zenhubusercontent.com/56f1892d6caf56c9d38e1ac3/92d336e9-4bbc-45cd-8256-1ce748d357b7)
![Screen Shot 2020-04-01 at 5.42.50 PM.png](https://images.zenhubusercontent.com/56f1892d6caf56c9d38e1ac3/24597696-8fc1-40db-9aee-63f4a2642ce6)

**Comment by blaughman** [comment]
Issue has been fixed.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
