### ISSUE TITLE
Intake pro form

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#332]
## Narrative
As an intake specialist, I want to be able to add complaints into the portal that I receive complaints by phone, fax, email and snail mail so that all complaints that CRT receives are in the complaints portal

## Background
Sections receive complaints via phone, email, snail mail and fax. Some sections like SPL get complaints exclusively via not digital mediums. While there are 4 sections that receive complaints via an online portal. For sections that receive complaints offline, they would need a form similar to the complainant portal which will allow them to capture complaints in the portal

## Out of scope
- Adding attachments
- Progress bar
- Clickable links
- Editing complaints

## Assumptions
- All conditional logic questions will be listed. No progressive disclosure of conditional logic questions based on the primary issue selection
- Only primary issue is a required field

## Acceptance Criteria

1) Given that I'm on the view all records page
When I click on the 'Add new record' button
Then I see a form to create a new complaint

2) Given that I'm on the 'new complaint' form
When I scroll through the form
Then I see the following sections:
- [ ] Contact
- [ ] Primary issue
- [ ] Personal Characteristics
- [ ] Date
- [ ] Intake summary 

3) Given that I'm on the 'new complaint' form
When I click the drop down to select the intake format
Then I see the 4 options to choose from - Phone, Fax, Mail and Email 

4)  Given that I'm on the 'new complaint' form
When I add the data needed for the concern and click the 'Submit' button
Then I'm taken to the view all records page 

5) Given that I'm on the 'new complaint' form
When I do not select an answer to the 'primary issue' question and click the submit button
Then I see an error message - 'Please select a primary issue to continue' 

6) A11y requirements

## Mock ups
https://gsa.invisionapp.com/share/KTW4MTWE9BP#/screens/406482413_Single_Page

## Sign off 
Story sign off 
- [x] PO
UAT sign off 
- [x] PO
- [ ] Product Design
- [ ] a11y

**Comment by blaughman** [comment]
Function works as intended.   Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Showcased at deep dive on 3/19.
