### ISSUE TITLE
View all table is overflowing

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#333]
The table is overflowing on the right if I have my screen a little bit smaller on my laptop.

![Screen Shot 2020-03-02 at 10.06.33 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/268ec302-7539-4b19-a2be-dac61d62e5f8)

Now that we can see things in dev, we can might want to adjust the columns more so they fit a smaller screen, or at least match/lock the table heading & table data so that doesn't look like an overflow bug.

**Comment by LindsayYoung** [comment]
I also think we will need to add a scroll bar at the bottom for accessibility when low-vision users use zoomed in views

**Comment by blaughman** [comment]
View All Table fits on one screen now, moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
