### ISSUE TITLE
Progress bar & content overlap with zoom

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#337]
Progress bar & card overlap on zoom, screenshot here is 200%.

![Screen Shot 2020-03-04 at 5.11.14 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/c40e69a1-cf89-44b5-9fb4-95a18289bc25)

A user should be able to zoom to at least 200% without any obscured text. Newer guidance goes up to 400%, which should match mobile. 

**Documentation**
* [Resize text info from WCAG](https://www.w3.org/WAI/WCAG21/Understanding/resize-text)
* [WCAG 2.1 guidance](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html) expect reflow at 400% zoom, which is equivalent to mobile

**Comment by blaughman** [comment]
Issue resolved.  Moving to UAT.

**Comment by Jacklynn** [comment]
200% zoom, no overlapping text! Although the little line extends out, but I can file a new issue for that. 

![image.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/87bfcb41-604b-4327-9df4-15186a00912f)

**Comment by Jacklynn** [comment]
Filed https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/428 for progress bar extending as an enhancement

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
