### ISSUE TITLE
If not contact information, alert user to their decision 

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#338]
If a user choses not to fill out any contact information the DOJ would never be able to get back to them or reach out for follow up information, it would be nice of the form provided another safety net to for users who might have missed this opportunity. 

For example, after not filling out the contact (email, phone, address) they could see a "are you sure?" type message. Or something more subtle on the Review page like an in-line alert for the contact section with something like "We would not able to reach out to you if we needed to because you didn't provide contact information"

**Comment by lalitha-jonnalagadda** [comment]
Per Bill, there aren't many reports without contact information after all. Closing it for now.
