### ISSUE TITLE
Renaming "full summary" 

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#339]
## Background

We got a question (which is like feedback) asking what "summary" was supposed to mean. Considering we're adding the ability to for CRT to also summarize what's happening I think we could use clearer language. I think part of the confusion is that 'summary' implies that someone summarized a source text

## Proposed

- Change '**Full Summary**"(description of the complaint by a complainant)  to " **Personal Description**"

**Comment by blaughman** [comment]
Change is reflected on details page.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
