### ISSUE TITLE
Tell DOJ CRT what type of discrimination I experienced (primary reason)

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#34]
## Narrative
As a Public user, 
I want to Tell DOJ CRT what type of discrimination I experienced 
so that The appropriate DOJ CRT section can handle my complaint _appropriately_

## Background
DOJ CRT sections enforce different statutes based upon subject matter. The questions asked in this section of the form gather 'statute-like' information that can help the system and CRT sections/ADM determine/confirm whether the record is in the correct jurisdiction.

## Assumptions
- public user picks answer(s) specific to the violation they're reporting
- public user needs to answer all questions on this page 
- A complainant can only choose one category/type of description on this page.

## Out of scope
- routing logic
- question on physical harm 
- dynamic branching based on selection

### Given (this pre context)..., When (action happens)..., Then (result)...
1. 
Given I am on the online portal and have entered (or not entered) my Contact information on step 1
When I click Next
Then I am on a new step called 'Primary Issue'  and the step 'Protected Class' is after
AND
View a page titled * What is your primary reason for contacting the Civil Rights Division?* with a section that allows me to choose from the following options in the following order:

- Workplace discrimination or other employment-related problem
- Housing discrimination or harassment
- Discrimination at a school, educational program, or related to receiving education
- Right to vote impacted
- Mistreated by police, law enforcement or correctional staff _(including while in prison)_
- Discriminated against or experienced an issue in any other commercial location or public place
- Something else

AND I see a button called 'Next' and 'Back'

2) 
Given I'm on the 'Primary Issue' step
When I *have to* to select what type of disc. I believed I (or someone else) experienced
Then  I can only choose one category option

3)Given I *have to* to select what type of discrimination I believed I (or someone else) experienced
When  I have chosen one category option by clicking anywhere on the card to make a selection
Then my selection is highlighted AND the radio button is filled to visually identify my selection (Refer to mockup for selected).

6)Given I'm on the 'Primary Issue' step
When I don't choose a category option
AND 
I click 'Next'
Then I view the following error message 
"Please select a primary reason to continue."

7)Given I'm on the 'Primary Issue' step
When I select *one* category option
AND 
I click 'Next'
Then I am brought the next step/page of the form 'Protected Class'

Accessibility:
- error messages working well
- tabbing works well
- treat this page as a list of selections 
- full text read for each selection via a screen reader

Style:
- Check to see if the style looks decent on mobile

## Content
https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit#

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by Jacklynn** [comment]
@UchMok I took a first pass at documenting the expected UX here. Is this the kind of thing what you are expecting? https://docs.google.com/presentation/d/1R69HZFZN6f1o7WUO2IjMg6b_sxOdJy-Mbsp7K6_2E7Q/edit#slide=id.g5d1e3039b8_0_6

**Comment by UchMok** [comment]
@Jacklynn the draft looks great! Feel free to make it leaner moving forward and do just enough to get your point across. Hope this didn't take long to do!

**Comment by lalitha-jonnalagadda** [comment]
Hi @AvivaOskow @Jacklynn - I was taking a stab at this story and had a few questions that I added inline in italics and in the questions section. If y'all can add some more color, we can refine this story further. Thank you! cc: @UchMok

**Comment by lalitha-jonnalagadda** [comment]
Notes from the sprint planning meeting:
- @AvivaOskow To work on the content and error messages 
- @lalitha-jonnalagadda add AC on highlighting the chosen option

**Comment by lalitha-jonnalagadda** [comment]
Added AC 5 as discussed during the sprint planning meeting to describe - highlighting a cotegory when selected.

**Comment by alexsoble** [comment]
Opened a PR with core functionality and most of the required styles, ready for review!

Much more detail here: https://github.com/usdoj-crt/crt-portal/pull/128#issue-335634418.

**Comment by Jacklynn** [comment]
Notes from standup
- amazing work
- radio button same blue as text
- change grid (longer work)

Aviva - to give mobile example

**Comment by Jacklynn** [comment]
Let me know if you want me to file a bug or if this is because it's still in progress:
In safari none of the styles are rendering for me: [Uploading... Screen Shot 2019-11-08 at 4.16.34 PM.png ]

**Comment by alexsoble** [comment]
@Jacklynn Could you try double-checking in Safari in incognito mode, or with a hard-refresh? This looks like a caching issue to me. I saw the same in Chrome/Safari before the CSS cache was refreshed.

**Comment by alexsoble** [comment]
PR for server-side alert styles opened and in review: https://github.com/usdoj-crt/crt-portal/pull/134

**Comment by alexsoble** [comment]
PR for server-side alert styles shipped, next up is PR on a11y/punctuation: https://github.com/usdoj-crt/crt-portal/pull/139

**Comment by blaughman** [comment]
The page works as expected in IE 11.

**Comment by Jacklynn** [comment]
Some of the design elements like the column width and spacing still looks off. I created a new ticket but let me know if this should be moved back instead: https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/177
