### ISSUE TITLE
Location name/city/state error is reading entire group

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#343]
On a screen reader, if you get an error on the Location page for the required fields (name, city, state) it will read all of the group text before reading the field with the error. Ex: if you forget a city, it will read the title, help text, name, mailing address 1 and 2, and then the city field and error.

Expected: 
Screen reader only announces the errors found when the page refreshes. When you get to the field with the error, the error is announced again.

**Comment by Jkrzy** [comment]
Hi @Jacklynn, would you have a few minutes today to :meet: and walk me through the issue here? I _think_ I'm able to replicate it and understand the problem but would love to see it from your expert view!

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
