### ISSUE TITLE
"optional" label not reading on contact page

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#344]
From testing with terri today: 
The optional labels were added later, they might have not been added to the AIRA label

**Comment by Jacklynn** [comment]
We also might want to switch indicating "required" over optional or add it to the instructions.

**Comment by LindsayYoung** [comment]
Can we put this card back to analyzing if we don't know if we want to implement a required pattern or stay with optional?

**Comment by Jacklynn** [comment]
Closing because we're moving to showing/announcing required only
