### ISSUE TITLE
Remove voting conditional logic question

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#345]
## Current workflow

1. Given that I'm on the primary issue page
When I select 'Right to vote impacted' and click next (past the hate crime and human trafficking question)
Then I'm taken to the locations page 
AND 
The first question on the page is 'What kind of election or voting activity was this related to?' followed by
'Where did this happen?'

## Proposed workflow

1. Given that I'm on the primary issue page
When I select 'Right to vote impacted' and click next (past the hate crime and human trafficking question)
Then I'm taken to the locations page 
AND 
The only question on that page is 'Where did this happen?'

**Comment by cantsin** [comment]
I think this is a duplicate of https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/503 ?

**Comment by lalitha-jonnalagadda** [comment]
Duplicate to 508. Closing this card
