### ISSUE TITLE
Last updated and recieved times in EST

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#349]
## Current

![Screen Shot 2020-03-31 at 2.24.53 PM.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/272186f5-3a81-472a-a39a-886468b17f67)

## Future

These timestamps should be reflected in EST

**Comment by blaughman** [comment]
Times are now showing as EST.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
