### ISSUE TITLE
Tell DOJ CRT my contact information [Email + Phone] when I'm reporting on behalf of myself

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#35]
## Narrative
As a Public user, 
I want DOJ CRT my contact information [Email + Phone] when I'm reporting on behalf of myself
so that DOJ CRT can get back to me about details of my complaint AND resolution about the discriminatory event

## Background
Public users can choose to give their contact information to CRT if they are submitting a complaint for themselves or someone else. They can also opt to report anonymously. Complainant contact information allows CRT sections to follow up with that individual to gather more information about their complaint. It does *not* prevent them from taking action on a case. If a complainant reports anonymously, CRT will not be able to contact them.

Currently, CRT sends case outcome correspondence to complainants via physical address. This may need to be a required field in this section.

## Out of scope
- reporting on behalf of someone else #117
- reporting anonymously #118
- Physical Address (need to talk about address validation and use case)
- Adding multiple people's contact information

##### Given (this pre context)..., When (action happens)..., Then (result)...
1)
Given I want to report a violation, 
When I enter or click on the following [hyperlink](https://crt-portal-django-prod.app.cloud.gov/report/), 
Then I should view an intake form titled 'Contact the Department of Justice about a civil rights concern' with the following subsection:
  - 'Who should we contact about this issue?'
AND I see a wizard at the top of the page
with the first bubble *'1/Contact'* filled in (indicating I'm on that page)
_View *Mockup section* for full content/design expectations of Title, sections, sub sections and page_

2)
Given I am viewing the section "Who should we contact for this issue"
When I want to enter my contact information
Then I am able to enter the best contact information into the following fields:

##### Name (optional)

First name
- string only

Last name
- string only

##### Contact information
Email address
- accepts valid email address only
- optional

Phone number
- Phone Number Field
- numeric plus the following characters allowed: "+", "(", ")", "-", " ", "."
- 7-15 numeric digits
- optional

AND

I am able to submit my validated information

## Mockups / Wireframes

![All Contact 1 Copy-annotations Copy.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/d261dd3a-f4a4-426d-90a1-df96f1e30927)

![All Contact 1 Copy-annotations.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/776bd002-6b14-46a1-9389-21bb8a077b63)

[Sketch file] (https://drive.google.com/open?id=1VL-nK87FRKb6tdZ28RiH0OWgGOXnyaHe)

**Comment by UchMok** [comment]
@Jacklynn 

From what I recall, @blaughman said the value he and sections get from 'Contact Info' is being able to:
- send contacter information/outcome about their complaint
- following up with contacter to request additional information

I think regardless of whether you're reporting for yourself on behalf of someone else, the contact information entered should be for this reason. So if I were filing on behalf of someone who can't type/write, I can enter their information if, I as the submitter, think they can receive correspondence. If I were filing on behalf of a minor, as a parent, then I would have to enter my information maybe because DOJ may not be able to contact that minor w/out parental consent anyway.

W/ all that being said.. I think we need 1 contact. I also think we need to be very clear to the submitter (myself or on behalf of someone else) as to what we need the contact information for, so they can enter the right person's information.

cc: @blaughman

**Comment by blaughman** [comment]
@UchMok - That makes sense.  I do think there should be some type of disclaimer indicating we will only be communicating w/ the individual listed in the contact field.  They can provide other names, info, etc. in the free form area.

**Comment by UchMok** [comment]
@AvivaOskow since we're working with international phone numbers, I think the field needs to look different.

**Comment by Jacklynn** [comment]
Added all the mocks (again) not sure what happened before!

**Comment by AvivaOskow** [comment]
@LindsayYoung @alexsoble one detail to note about this page that should relate to the upcoming pages as well: we changed the design for the *Next* and *Back* buttons from previous versions you've seen. Here the big blue button is *Next* and *Back* becomes a smaller link below.

**Comment by LindsayYoung** [comment]
OK got this going for review here: https://crt-portal-django-prod.app.cloud.gov/report/

A few notes:
- The spacing is not perfect and I don't have some of the color changes
- There is one accessibility issue with the phone field label that we need to fix
- There is no back button on the first page, So we can make that change in the next story
- getting clarity on the return to top link

**Comment by Jacklynn** [comment]
Feedback from team for dev:
- Match error messages, suggested use client side for both email and phone number validation
- The vertical spacing looks off, needs updating
- the [line length](https://baymard.com/blog/line-length-readability) of content is longer than expected, @AvivaOskow to review. 


Other notes (no dev action):
- The message about privacy might not be true, I would remove
- Create a new story for feature enhancement about automatically adding hyphens for the phone number (low priority)

**Comment by LindsayYoung** [comment]
Tracking the IE issues here because they span more than one story https://github.com/18F/crt-portal/issues/138

**Comment by UchMok** [comment]
@alexsoble @LindsayYoung I moved this back to 'Dev Done', because @blaughman and I haven't signed off this story yet.

**Comment by Jacklynn** [comment]
Feedback notes: 
- Match format -- no format required, update error text message
- Phone number doesn't accept +, parentheses, hyphens

**Comment by Jacklynn** [comment]
@blaughman
