### ISSUE TITLE
Copy: Activity log messages

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#350]
- In the activity log, the messages should be formatted as follows:
  - 'Updated _entity_ to Y'

**Comment by LindsayYoung** [comment]
@lalitha-jonnalagadda I updated this requirement to what we had before 'Updated _entity_ to Y' 
If we wanted to make it 'Updated _entity_ from X to Y' we have to rewrite the activity stream log to get the previous data. We can to that, but it's a bigger task so I wanted to clarify.

**Comment by lalitha-jonnalagadda** [comment]
@LindsayYoung I'm fine to leave the copy as you have it now - 'Updated entity to Y'. If we want to change it in the future based on further user feedback, we can make a new card for it.

**Comment by blaughman** [comment]
Status updates as directed.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Showcased at deep dive on 3/19.
