### ISSUE TITLE
[CRT view] Status missing label

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#353]
After the redesign the label for status disappeared, tracking bug to re-add

![Screen Shot 2020-03-10 at 10.48.58 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/c626103b-c99b-4eaa-82ef-78aed1d0afdc)

**Comment by blaughman** [comment]
Issue resolved.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
