### ISSUE TITLE
[CRT view] Make Section selection a simple drop down on record page

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#354]
On the single record page there is a dropdown within a drop down is a confusing interaction. I think this is because it's perfectly re-using the filter page drop down (also confusing)

**CURRENT:**
![Screen Shot 2020-03-11 at 3.32.26 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/11dcb93b-32af-4e8c-8ad4-4457705f8784)

**EXPECTED:** 
![Complaint details Copy 2.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/99fd12c8-b679-4d0b-a8fe-bf3090fa117b)

Regular dropdown because you can only choose one section.  V1 could just be showing the second drop down instead. I think Adam was trying to match the visual style of the button.

**Comment by lalitha-jonnalagadda** [comment]
I see the simple drop down implemented on dev. @Jacklynn please take a quick look and close this card if it fits your desk check as well.

**Comment by blaughman** [comment]
Drop down appears as it should.  Moving to UAT.

**Comment by Jacklynn** [comment]
The drop down is looking great! I think the stroke just needs to be changed to `1px solid #162E51` (reduce the stroke and change to the primary dark blue). cc/ @hbillings 

It's a little tight right now in the box, but there is a separate card for changing the padding 🤞

Here's a screenshot with the change via devtools:
![Screen Shot 2020-04-01 at 8.40.11 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/65aee721-a28e-4752-bf9a-31cb5b1299e8)

**Comment by hbillings** [comment]
@Jacklynn Easy enough! (This is one of the reasons I was mentioning that having access to the sketch files would be helpful, because then I could just check the color values and widths myself and take that off your plate mostly!)

**Comment by Jacklynn** [comment]
Desk check: The line styles aren't updated for me, but still functionally works

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
