### ISSUE TITLE
Footer Issue (IE 11)

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#356]
The footer does not stretch across the bottom of the screen on the public intake for on IE 11.

![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/c24d2af4-1218-4904-94fb-bd886a9b54c2)

**Comment by lalitha-jonnalagadda** [comment]
@blaughman Please close if this issue is resolved

**Comment by blaughman** [comment]
Issue resolved.
