### ISSUE TITLE
IE - View All Table filter appearance

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#357]
The view all table appearance is off in IE 11

![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/8f3710ed-585f-4a8b-9ef1-c2f4dee03017)

**Comment by LindsayYoung** [comment]
@ilodidoj  I deployed Heather's fix on dev. On Monday, can you look at this page in IE and confirm that the filters are not stuck open?

**Comment by blaughman** [comment]
Filters on table look as they should.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
