### ISSUE TITLE
Complaint Detail Page View Bug

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#358]
IE 11 issue 

![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/a7da35f2-2cf8-44b5-b1e7-7569802649f6)

**Comment by LindsayYoung** [comment]
This should be fixed with the last round of IE fixes

**Comment by lalitha-jonnalagadda** [comment]
@blaughman Please close this card if this is resolved

**Comment by blaughman** [comment]
Function works in Edge.  Closing card.
