### ISSUE TITLE
Email responses to complainants (form letter) 

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#362]
## Narrative

As an intake specialist, I would like to respond to a complainant with a 'no jurisdiction' response letter when the complaint is not meritable so that the complainant is aware of the decision from CRT. 

## Background

The last step of complaint processing involves sending a response to the complainant based on the resolution that the CRT teams lands on. These response letters or form letters as they are frequently called can be section specific or generic to CRT. Complaints usually fit into the scenario where CRT doesn't have jurisdiction over the complaint and aren't able to help the complainant.  This story addresses that use case. 

## Assumptions

- Form letters can only be sent from the app only when an email address is provided
- O365 integration is in place
- Will populate the metadata on the complaint into the response letter:
  - Name
  - Complaint ID
- In terms of the meta data that will be incorporated with the form letter response as salutation, data to be included:
  - First name and Last name 
  - If First name or Last name if provided and not both, either of those will be included in the letter
  - If neither First name or Last name are available, then a general salutation - **Dear friend** will be included
- Content of the email body cannot be edited
-  Until we have the O365 integration with the app, intake specialists should be able to copy and paste the body of the letter into an email 
- Until O365 integration is in place, the intake specialist can paste the response email  in comments section for record keeping 

## Out of scope

- O365 integration
- Printing a form letter
- Saving the body of the email sent as response in the activity log
- Section specific form letters
- Editing the body of the form letter

## Acceptance Criteria

1. Given that I'm on the complaint details page
When I'm at the action's panel 
Then I see a new button 'Contact Complainant'

2. Given that I'm on the activity panel
When I click on the 'contact complainant' button
Then I'm taken to a pop-out 'Contact complainant' page with the following information
- 'Response template' dropdown to select the type of letter ( for now, it will only have 'CRT - No jurisdiction (generic)' option. See next AC)
- Body of the letter (blank initially until a letter type is selected)
-  'Cancel' option 

3. Given I'm on the 'Contact complainant' screen
When I select 'CRT - No jurisdiction (generic)' option from the drop down
Then I see the body of the letter section populated with  the form content as in the source of truth attached to this card

4. Given that I'm on the 'Contact complainant' screen
When I click the 'Cancel' link
Then I'm taken back to the complaint details page

## Mocks

https://docs.google.com/presentation/d/15UngPbSU4CVjIdWSsZh75SuSrUbRQk0e7hunBuqlGyM/edit#slide=id.g76e5e33bc5_0_0

## Sign off
- [x] PO
UAT
- [ ] PO
- [ ] Product design
- [ ] a11y

## Tech notes

- Need to be able to save the letter with an ID
- need permissions for a small set of users to create new templates

## Tech Questions Notes:

1. Do we include any metadata with the response letter? _Yes - First and Last Name, Complaint ID_
2. Can I edit the content of the letter? _Not with this card, but in a future card_
3. Outgoing date: Date that the letter is originally being generated must be available on the letter. If there is a need to recreate a letter for FOIA or other public requests, the letter should add the newer date.  _Yes, outgoing date is included in the body of the letter_
4. When there is **not** contact information such as email address, physical address or name, then the letter will be addressed to 'open' such as Dear sir/madam

**Comment by cantsin** [comment]
> Need to be able to save the letter with an ID

Not sure what this refers to.

> need permissions for a small set of users to create new templates

Surely this is out of scope, given we can't create new templates anyway (except through the django admin interface)?

3. The templates provided in the "content source of truth for form letters" above does not have an outgoing date. Where should I insert this outgoing date?

4. I'm a bit confused about the `addressee`. Can we clarify when we have "sir/madam"? I think #4 should read "when we do _not_ have contact information..." is that right?

**Comment by Jacklynn** [comment]
- I tagged you in the content doc for "the Letter with an ID" question -- it's that the letter has the complaint ID in it.
- Permissions - not sure
- I updated to say "not".... let me do some research on a non-gendered salutation

**Comment by Jacklynn** [comment]
For the date...
@lalitha-jonnalagadda this is only for emails right? I would expect physical printed letters to have DOJ letter head. Dan expected the metadata in sending an email be sufficient.

**Comment by lalitha-jonnalagadda** [comment]
Regarding the question on permissions, please see #560 . The idea here is that a limited number of users will be able to create custom templates for special scenarios. 

Regarding letter head - @blaughman can you clarify Jacklynn's question?

**Comment by blaughman** [comment]
From Slack - IMO, we still have to account for hard copy responses to inquiries.  SPL has always maintained that a majority of their complaints are from prisoners without access to email.  I'm curious how hard it would be to implement the attached with form letter responses?  A standard letterhead will work for all sections, but I don't think this would be something we could copy and paste until we get email integration.  Results from the beta launch indicate most are providing an email address when submitting a complaint.[https://app.zenhub.com/files/183258764/bf495d92-f53d-4398-b7e0-687746557842/download]

**Comment by blaughman** [comment]
Function works great.  Moving to UAT.

**Comment by Jacklynn** [comment]
It didn't look like the gender neutral salutation got into this :(. I can create a new ticket

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/16
