### ISSUE TITLE
Editing a complaint narrative

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#366]
## Narrative
As a CRT User, I want to summarize a complainant's submission into a concise format to highlight the issues presented.   

## Background

Extracting key details of a public user's submission will allow CRT users to quickly determine the merit of a concern.

## Assumptions

- The summary should not approach the words allotted to the public users in the freeform of the intake form.
- CRT users will list the relevant data to allow for informed decisions on how to proceed with a submission.
- This summary section should be editable

## Out of Scope
- Maintaining versions of the complaint summary

## Acceptance Criteria
1)  Given I am on 'Reported Complaint' section on the complaints detail page
AND there is an existing summary for the complaint
When I click on the edit link/button/icon
Then I am taken to an editable text box with the existing summary

2) Given that i'm on the summary section of the reported complaint section
When I try to try to save an empty text box with no text
Then I see that the 'Save' button is greyed out
AND 
When I enter text into the complaints section 
Then I see the 'Save' button is now active(in blue color) and is clickable

3) Given I am in an editable version of the summary
When I review the summary and edit the summary as needed and click 'Save' 
Then my information saved with the latest edits

4) a11y requirements

## Questions

- Should changes be reflected in the activity log? -- Yes. We will store the comments post edits in the activity log

### [UX details](https://docs.google.com/presentation/d/1FuuSg0bb9DDQx_EjRK-T_YZQ0gpcVgIz8-M6BQE-u4g/edit#slide=id.g8144cd0cd1_0_17)

![4 - submitted@2x](https://user-images.githubusercontent.com/2560618/76787243-d4f6cc80-6775-11ea-9f76-c4c627c3a1d0.png)

## Sign Off
- [x] PO
UAT Sign Off
- [ ] Design Staff

**Comment by lalitha-jonnalagadda** [comment]
- Add AC's around active and inactive states of the save button
-

**Comment by blaughman** [comment]
Function works as intended in Dev.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
