### ISSUE TITLE
Copy edits: Update form title

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#368]
Title of form should be:
    Contact the Department of Justice to report a civil rights concern

See source of truth:
https://docs.google.com/document/d/1-HLdb21JA6_EuMHZTOi7KXFWWV4mT2Af54Tzzijl2E8/edit#heading=h.37ho6q4y2830

**Comment by blaughman** [comment]
Form reflects the change.

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep dive on 3/19. Closing this card
