### ISSUE TITLE
Copy edits: Update contact page

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#369]
Update the text on the contact page according to the doc:

Source of truth:
https://docs.google.com/document/d/1-HLdb21JA6_EuMHZTOi7KXFWWV4mT2Af54Tzzijl2E8/edit#heading=h.1q591albj4nl

**Comment by LindsayYoung** [comment]
I didn't add the link for the privacy page because we don't have it yet.

**Comment by blaughman** [comment]
Page now matches the source of truth.

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep dive on 3/19. Closing this card
