### ISSUE TITLE
Filter by 'section' - View all table

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#37]
## Narrative
As a DOJ CRT user, I want to be able to filter complaints by section so that I can only view a subset of the complaints I prefer so I can take relevant action on. 

## Out of scope
- Filter by status, incident location, submitted date and contact

## Acceptance Criteria

1) Given that I'm on the view all table
When I click on the 'view section' drop down
Then I see the following sections to select:
  - All (default)
  - ADM 
  - IER 
  - VOT 
  - DRS 
  - CRM 
  - HCE 
  - EOS 
  - SPL 
  - ELS 
  - FCS 
  - APP 

AND
I should be able to make/remove a selection using keyboard only.

2)  Given that I'm on the view all table
When I don't select any filter option
Then I see complaints for all sections is the default view

3) Given that I'm on the view all table
When I select a section from the 'view section' filter
Then I see that I am able to select more than one section at a time
AND
the view all table filters dynamically to display records for that selected section(s) 
AND
My section selection is visually displayed in the drop down and the tag above the view all table
AND
I am able to focus and remove a filter using keyboard only

4) Given that I selected a section in the filter drop down
When I click on the 'All section' option
OR
When I click 'X' on the tag 
Then I see the view all table to display all complaints 

5) Given that I'm using a screen reader
When I click on a section name/choice I get feedback that my option was selected
AND
When I on the filter tag list when I'm focused on a tag I understand that it's a button to remove that filter item. Ex "Remove [Washington/filter name] from the list, <button>" 
[Documentation example I found which you can try voiceover with](https://a11y-guidelines.orange.com/web_EN/exemples/tag-exemples/Exemple_filtre.html)

6) Given that I select a section AND there are no records for that section
Then I see a message warning me about why there are no records showing
AND 
back and forward pagination arrows are disabled

7) Given that I've applied a filter and have reach the end of all the pages for a given filter (ex: less than 15 or on the final page of pagination)
Then I see a message confirming that I've reached the end of records and to change filters to see more. 

## Mockups
![Viewall-without names.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/759bd3da-ab75-4458-b38c-43342fa93433)

No records for a filter
![Filter-no records.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/dc577451-6e77-4cd6-97b6-d82799db4341)

Records with less than 15 filter
![Filter-less than 15.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/df3414e1-0e7b-4847-ae8b-304420903eef)

## Questions:
- At this time, is the filter drop down going to have just VOT and ADM or all sections? @LindsayYoung 
- Pagination and number of records is updated when the filter is adjusted? Is that dynamic already? @LindsayYoung 
-  @blaughman @lalitha-jonnalagadda Is this the card where 'no records found' and 'less than 15 records' needs to be worked out too? I remember added those to a ticket but I couldn't find them. I added some mocks for those as well - Jacklynn
- Would AC 7 "no more records" message be helpful to see at the end of results regardless?

**Comment by Jacklynn** [comment]
Yes, I think the drop down should indicate which one(s) are already selected. 
* If "All" is selected and you choose an item below, it should also 'reset' to only show that selection.

"Clear all" is a good suggestion too, maybe adding it as the last item on the filters.

**Comment by Jacklynn** [comment]
@lalitha-jonnalagadda while I was writing the a11y criteria I thought it would be helpful to label the filter tags (plus, you asked what they were too). What do you think about think about adding "Filter" before the list? 

I also stretched the design to see how it would look there were many filters applied so giving filters more space in general:
![Screen Shot 2019-12-04 at 8.56.33 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/9343d12a-db74-498d-a916-cd262ca688ae)

**Comment by el-mapache** [comment]
@Jacklynn do you mind linking the icons for the two messages here? The filters icon and the little coffee cup? Thanks!

**Comment by LindsayYoung** [comment]
I am also wondering for AC 7 "Given that I've applied a filter and have reach the end of all the pages for a given filter (ex: less than 15 or on the final page of pagination) Then I see a message confirming that I've reached the end of records and to change filters to see more." It would be easer to simplify the behavior so that that message always appears after the last record on the last page. Otherwise we are going to have to add each filter to that check as we build them out and I think that might be error prone. I think the logic might get messy to maintain.  @el-mapache does that sound like a good idea? Maybe you have a better idea of how to implement this. @Jacklynn would that be okay?

**Comment by el-mapache** [comment]
@LindsayYoung Yes, I changed the code to use the `page_format.has_next` helper method, with some additional logic to make sure we don't see the 'end of results' message in concert with the 'no results found'.

**Comment by el-mapache** [comment]
@Jacklynn We are currently using the native `datalist` HTML element in our forms to provide dropdown typeahead functionality. Unfortunately, this element only allows for multiselect functionality when the applied to inputs of type `email` or `file`.

This means we will at least need a JavaScript typeahead solution for the `assigned section` filters if we want user's to be able to choose more than one.

What are your thoughts on shipping first with a single selectable section filter and adding the new typeahead behavior in a followup PR? And do we want to use the same code for the public facing forms?

I think my personal opinion is to use the JS typeahead multiselect only on the complaint form viewer; although the forms won't have consistent interfaces, I think that's ok, since the forms are directed at two different audiences. Plus, we don't need multiselect behavior on the public form yet 😄  

Thanks!

**Comment by Jacklynn** [comment]
@LindsayYoung @el-mapache yes always showing the message at the end of the results works for me!
@el-mapache When you say that it wouldn't have a consistent interface, you mean it would visibly look different for the public, right? Could it be design to look like it's in the same family?

**SVG icons:**
![coffee.svg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/39f5727d-6d28-4bcc-8387-65ae23d6aead)
![sliders.svg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/c33a26c2-f5ce-4683-82c8-5d1d6a23211f)

(these are both [feather icons](https://feathericons.com/))

**Comment by el-mapache** [comment]
@Jacklynn exactly, the styles won't match 100%. @LindsayYoung also brought up the fact that we could potentially just use a native multiselect `select` element with no typeahead for the filters dropdown. That would give us the ability to select multiple `section` filters right now, and we can decide later if we want to add a JS solution.

Thanks for the icons!

**Comment by el-mapache** [comment]
Spoke with the design team yesterday, and we are going to move forward with the browser's native multiselect UI element. A future PR will introduce in a better-looking / more feature rich alternative.

**Comment by blaughman** [comment]
As we discussed in bug bashing, clicking the "x" by the filtered section did not remove the filter.

**Comment by lalitha-jonnalagadda** [comment]
Notes from my desk check: 

- Per Slack conversations, for now, the filters will have a - 'Filter Results' button vs the view all list adjusting dynamically based on a user selection.(AC 3)

- (AC 1): The sections are listed with their full section names vs abbreviations. I can create a new card for this.

**Comment by blaughman** [comment]
Bug has been fixed.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Demo'ed to the deep dive group on 1/9.

**Comment by lalitha-jonnalagadda** [comment]
Demo'ed to the deep dive group on 1/9.
