### ISSUE TITLE
Copy edits: Hate Crimes

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#370]
Update Hate Crimes text

Content source of truth:
https://docs.google.com/document/d/1-HLdb21JA6_EuMHZTOi7KXFWWV4mT2Af54Tzzijl2E8/edit#bookmark=id.mff2ea7j4l62

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
