### ISSUE TITLE
Copy Edits: Location

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#371]
Update text on location page

Content source of truth:
https://docs.google.com/document/d/1-HLdb21JA6_EuMHZTOi7KXFWWV4mT2Af54Tzzijl2E8/edit#heading=h.z6b0d6xm8emw

**Comment by blaughman** [comment]
Form reflects the updates.

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep dive on 3/19. Closing this card
