### ISSUE TITLE
Copy Edits: Update Date page

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#372]
Update text on date page 

Source of truth:
https://docs.google.com/document/d/1-HLdb21JA6_EuMHZTOi7KXFWWV4mT2Af54Tzzijl2E8/edit#bookmark=id.9vci9jyf3ct2

**Comment by blaughman** [comment]
Form reflects the changes.

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep dive on 3/19. Closing this card
