### ISSUE TITLE
Copy edits and formatting for the Description page

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#373]
Update the description page text 
Add bulleted list 

source of truth:
https://docs.google.com/document/d/1-HLdb21JA6_EuMHZTOi7KXFWWV4mT2Af54Tzzijl2E8/edit#bookmark=id.ft6oojppigl6

**Comment by blaughman** [comment]
Form represents the changes

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep dive on 3/19. Closing this card
