### ISSUE TITLE
New law enforcement question

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#374]
changes "Inside" "outside to a yes / no

The back end display of the data remains the same (inside of prision/ outside of prision)

see new question in source of truth:
https://docs.google.com/document/d/1-HLdb21JA6_EuMHZTOi7KXFWWV4mT2Af54Tzzijl2E8/edit#heading=h.1bh1wiudc7x

**Comment by blaughman** [comment]
Form reflects the change.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep dive on 3/19. Closing this card
