### ISSUE TITLE
Design audit: Mobile progress bar fixes

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crt-portal#376]
## **Issues:** 

- Text becomes too crowded on mobile
- Not enough space between progress bar and element below
- Fixes from #375 should carry over

## **Changes:** 

- [ ] Remove page names from progress bar on mobile, except current page
**OR**

- [ ] Remove page names from progress bar on mobile always, since the page header is large right below it
---

- [ ] Add space between bar and element below, preferred 40 px for mobile (56 px on desktop— @LindsayYoung are we able to set them differently?)

### **Current**
![Screen Shot 2020-03-19 at 2.21.23 AM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/55c1916d-5540-4f5e-8806-e5c8f1c259db)
--- 

### **1. Circles + Current page name only**
![Screen Shot 2020-03-19 at 2.17.31 AM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/81d02767-0401-4697-8fc4-5d36a0674caa)

### **2. Circles + Current page name only + yellow line for visual cue**
![Screen Shot 2020-03-19 at 2.18.53 AM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/0dac5290-852e-4742-87ff-941261b1af02)

### **3. Circles, no text**
![Screen Shot 2020-03-19 at 2.20.03 AM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/d6f87aef-80be-4dfd-967e-fbc2c5e87fd9)

**Comment by AvivaOskow** [comment]
**My preference is # 3 —circles with no page name,** because the page name is very large right below it in the card, so it feels redundant.

@LindsayYoung we discussed being able to keep the pattern the same on desktop + mobile, but I am in favor of having the expanded progress bar for desktop/tablet, complete with page names, so it gives users an overview of the sections. However, I tried out a couple desktop versions of the mobile options I put above, but I don't think they work great on the larger screen.

@Jacklynn thoughts?

![Screen Shot 2020-03-19 at 2.26.48 AM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/e20ab665-4795-4564-9cd2-68ef5998287c)

![Screen Shot 2020-03-19 at 2.15.17 AM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/1d5c4b86-3991-4f4a-9c8a-0355588052b7)

**Comment by Jkrzy** [comment]
Hey @AvivaOskow, is this one ready for dev? It's on the priorities mural but wanted to confirm this one was ready for implementation

**Comment by Jkrzy** [comment]
Major work complete here, but another opporuntity for improvement noted by @LindsayYoung 
https://github.com/usdoj-crt/crt-portal/pull/496#issuecomment-634269215

**Comment by cantsin** [comment]
Thanks for the reminder! I looked at that bug -- not too easy to solve, unfortunately, especially because I'm still a bit confused about how the progress bar was originally set up. Is there a misc or catch-all design ticket we can add the above to?

**Comment by Jacklynn** [comment]
It's better!
