### ISSUE TITLE
Design audit: Contact form field lengths

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crt-portal#378]
## **Issue:** 
Currently, each field for the contact form is the same length, making it hard to scan and not look like a common address/contact format. From a UX perspective, adding more variety to the fields makes it easier to interact with and use quickly.
_Maybe this is how the USWDS code pulls, but I used the USWDS sketch file to design it, and it looked different_

## **Change:** 

- [ ] Suggested edit: Email address and Mailing 1 + 2 can be same length, Phone number a bit shorter, City and State should fit next to each other equalling the length of the longer fields, ZIP can be on it's own line below

## **Current**
![Screen Shot 2020-03-17 at 5.34.52 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/0a521355-2316-4bb5-a2e0-e98a016b385e)

## **Should be**
![Screen Shot 2020-03-19 at 11.15.35 AM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/4fb5bf76-d278-44f4-96fa-383ca3eb4a5b)

**Comment by AvivaOskow** [comment]
## **For reference, this is what the USWDS sketch file looks like out of the box**
---

![Screen Shot 2020-03-17 at 5.33.57 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/03bbc76e-2efc-461e-8d24-38ee7d5e3d79)

**Comment by Jacklynn** [comment]
@AvivaOskow USWDS component has [component code](https://designsystem.digital.gov/components/form-templates/) for it that matches the sketch file too.

**Comment by AvivaOskow** [comment]
This was resolved with Heather's design/dev work!
