### ISSUE TITLE
Design audit: Primary Concern cards—should be able to select anywhere within card

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crt-portal#380]
## **Issue:** 

- Currently, to select the card, you can either click directly on the radio button circle, or anywhere directly above/below it within the card. However, if you try to click on the margins on the card to the right or left of the content area, it doesn't select. This might make it confusing for a user if they think they can click the whole thing like a button but it doesn't select, especially since the whole things highlights on hover and shows a clickable cursor.

## **Changes:** 

- [ ] Make whole card clickable instead of just text/content area

**Comment by blaughman** [comment]
Whole card is now clickable.  Closing this card.
