### ISSUE TITLE
Design audit: error state updates

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crt-portal#384]
## **Issues:** 

- When there is more than one error message on a page, the list at the top becomes hard to read. It also directly quotes the error message, which takes up more space. Could it just say the name of the field or question instead?
- Location Details page: error message cuts into the State box with red outline
- Date page: error message for inputting a date over 31 has an extra message, "invalid date format, x/xx/xxxx" which makes it seem like the _format_ is wrong, instead of the number put in.
- Using two different reds for the error message up top and the message itself. The darker red in both should be # b51d09 - 'red-60v' (for text at top, red outline around fields, and icon) (Mostly done- remaining red bar on alert in it's [own issue](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/462) )

## **Changes:** 

- [ ] For error messages at top of card, simplest fix would be to have each on their own line, so they are easier to scan. _If there is a way to hide these but have the screen reader read them, then this might be ideal, because right now it's a bit redundant as is. Or have it just say how many errors but not right them out._

- [ ] Location details page: fix outline so it doesn't cut off box (low priority)

- [ ] Date: maybe just remove the word "format" from messaging, so it reads, "Invalid date, 6/33/2019" for example

#### **Multiple top errors**
![Screen Shot 2020-03-16 at 4.19.22 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/9647a1c9-b908-4f3a-9785-596039b85448)

#### **Location details . - State cut off**
![Screen Shot 2020-03-16 at 4.17.39 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/7384946a-1ec8-407a-8824-665b1f40b6ee)

#### **Date: "Invalid date format"**
![Screen Shot 2020-03-16 at 4.25.49 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/9568bb11-d7af-47f1-8a39-ba1d55902ec4)

--- 

#### OPTION 1: Top alert showing exact error messaging
![Screen Shot 2020-03-20 at 12.09.35 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/d9368437-efc6-41f5-ab64-264f4ba116f4)

#### OPTION 2: Top alert showing name of field/question
![Screen Shot 2020-03-20 at 12.09.48 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/3f89dffc-8d22-466d-bbd7-9a74eea46395)

#### OPTION 3: Top alert showing number of errors
![Screen Shot 2020-03-20 at 12.19.31 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/ea85530c-e016-4328-9a0c-44c968c9ac57)

#### Spacing (24 px between error and header)
![Screen Shot 2020-03-20 at 12.20.41 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/e0ebc67d-ea15-4942-8246-cf201b604c8c)

#### Colors
'red-60v' # b51d09
'red-warm-10' # F4E3DB

![Screen Shot 2020-03-20 at 12.29.45 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/55c1e4c5-90f1-41b6-849e-4251d03c7424)

**Comment by LindsayYoung** [comment]
Quick gut check @AvivaOskow and @Jacklynn. I just added focus to the first error on the page. Do we want to remove the errors on the top of the page? IIRC that started as a work around for not having focus.

**Comment by AvivaOskow** [comment]
@LindsayYoung sure, let's just remove them then! Can we leave the "2 errors" or say "2 errors found"? But just remove the repeat titles and keep the focus state like you said?

**Comment by LindsayYoung** [comment]
Yes, we can do the simpler "x errors found" I can get that going now.

**Comment by Jacklynn** [comment]
I'm not sure why this would be, but in safari it's showing the old darker red for the field outline and no icon. I did a hard refresh and cleared my cache

Safari screenshots:
![Screen Shot 2020-04-28 at 2.08.08 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/613f67c7-9eed-497e-9ea1-1d26fa8aa82a)![Screen Shot 2020-04-28 at 2.07.57 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/f5764395-8833-479e-a03e-c28e5c36fc24)

**Comment by LindsayYoung** [comment]
The red is it's own issue. It is supposed to be the darker red - https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/462

The icon is pointing to the wrong file location and not loading it will be updated here: https://github.com/usdoj-crt/crt-portal/pull/429
