### ISSUE TITLE
Design audit: Personal Description page text stylings

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crt-portal#385]
## **Issues:** 

- There is a "Continued" breadcrumb that shouldn't be there
- Help text bullet points are too spaced out from each other.

## **Changes:** 

- [ ] Remove "continued"

- [ ] Either make spacing between bullets smaller, or turn into a sentence (preferred, "Please share details like: time, names of people involved including witnesses if there are any, and any supporting materials we should know about (please list and describe them). _I realize this is probably pulling the style from the Examples bullet points from Primary Concern, but most of those are two lines, so the spacing feels right)_

### **Current**
![Screen Shot 2020-03-20 at 5.01.08 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/3e9fdab6-75cf-4752-accd-e133ee745a54)

--- 

#### With bullet points
![Screen Shot 2020-03-20 at 5.16.20 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/0c9484c8-e1c9-451f-b251-8bfa6bd73625)

#### As a sentence
![Screen Shot 2020-03-20 at 5.17.12 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/9a0ae5a2-0cf3-4650-9351-ad813678994f)

**Comment by Jacklynn** [comment]
My preference is with bullets, I would encourage CRT to provide important examples here, these were mainly generated by us

**Comment by AvivaOskow** [comment]
Result: we went with bullets, but now there is the other issue of the weird line break, captured in a different issue.
