### ISSUE TITLE
Design audit: Review Page spacing & content

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crt-portal#386]
## **Issues:** 

- Primary Concern is missing an edit button [high priority]
- Edit buttons feel too large  [reach]
- No hover state for edit button [reach]
- spacing between lines of text is too even, making it hard to scan [high priority]
- There seems to be too much padding at top/bottom of cards [Did Heather maybe already fixed?]
- Can address be normally displayed instead of by header? [high priority]

## **Changes:** 

- [ ] Update with annotations below

- [ ] @AvivaOskow define hover state for buttons

#### Spacing too even, making it hard to scan
![Screen Shot 2020-03-16 at 5.48.27 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/597fdd80-c583-4056-bd53-237101b3f39f)

#### Too much spacing at top of cards, large buttons (and primary concern missing edit button)
![Screen Shot 2020-03-23 at 2.42.57 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/bcdf4279-3d75-4926-be35-51cd047d012b)

--- 

#### Design board [issue](https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/74)

![UPDATED Review & Submit.jpg](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/d64936a6-31e3-48cd-8d0b-b1fecfe3df44)

#### Annotations
![Screen Shot 2020-03-23 at 3.01.46 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/e5999b33-c647-42bb-b472-5ec3e585291a)

**Comment by AvivaOskow** [comment]
Some notes on this one: 
- I know I'm asking for a new button style, but maybe we can discuss where else this can be used
- I say in this annotation there should be 40 px at the bottom of each review card, instead of the 48 I marked in the usual card for other pages— let's discuss.

**Comment by AvivaOskow** [comment]
I was also trying to decide between having a thin line between each element, or to just have them under the main questions... thoughts @Jacklynn ?

#### **Just under main question**
![Screen Shot 2020-03-23 at 2.13.59 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/e17aa103-8c51-43af-b40b-ef515318e778)

####  **Between each element**
![Screen Shot 2020-03-23 at 3.13.56 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/1299e2bc-2796-49e3-acd0-adfe0eacc70c)

**Comment by cantsin** [comment]
Just did a first pass.

Some notes: 

- Padding at top/bottom of cards seems fixed -- currently it is 24px as per the annotation.
- Edit button position has been fixed (this was bothering me too :sweat_smile:)

Some questions:

- I'm not too sure I should change `Email address` -> `Email`, `Phone number` -> `Phone` as that impacts all the other forms (and translations). Is this something we wanted to do?

- It's also a bit sticky to have `Address` because currently we depend on question text constants. The only way I can see is to hard-code this in the form, e.g., instead of `<h4>{{ question.contact.contact_address_line_1 }}</h4>` it would be `<h4>{% trans "Address" %}</h4>`. Would that be acceptable?

**Comment by cantsin** [comment]
Unfortunately, I believe there was a reason we didn't originally allow the editing of primary concern -- looks like the form becomes buggy if I edit primary concern and then go back to the review page and try to hit submit (the form seems to reset to where it was before, which may be unexpected behavior).

**Comment by AvivaOskow** [comment]
Thanks @cantsin ! **I reviewed this so far, and here are the edits I still noticed:**

### Edits
- [ ] Edit buttons (outline and text) are using the wrong blue I think, should be the darker blue-warm-80v

- [ ] Can there be 24 px before each blue question? Right now it’s even between all (Should be 16 before answers, but 24 between blue questions. You can see the annotations again [here](https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/74)

#### **Intro card text styles** 
- needs more space before main header "Review your concern" and blue question "Before you submit your report, please check your responses" _(this is the same issue happening on the Personal characteristics page)_
- Looks like the help text is using the wrong line height. Should match the other pages: 16px, 26 px line height (1.625). I know we fixed this with @hbillings on other parts of the form, so I'm not sure why the style is the same here...

##### Current
![Screen Shot 2020-05-15 at 12.28.18 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/a85d9c43-4c91-4816-a474-25747ec315ff)

##### Should be
![Screen Shot 2020-05-15 at 12.46.56 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/0dfe8f8c-eb82-488d-be13-3bf7fc58e894)

**Comment by blaughman** [comment]
PO approves.  @Jacklynn I assume this will need to pass product design as well.

**Comment by Jacklynn** [comment]
The address doesn't hav lines anymore, which is good but i think a lot of the visual changes are still remaining. One of the big ones is reducing the space between the <h4> and the value (ex: `Email` and `example@email.com`).

If it's helpful, we don't need to classify them semantically as H4s and would just style them to look that way. Screen reader users could use the H3s to outline the page. Terri said it was up to us.
