### ISSUE TITLE
Design audit: Confirmation Page edits

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crt-portal#387]
# Placeholder

## **Issues:** 

- Updated spacing and text annotations below
- Suggest changing copy at top to say:
"Please save your record number for tracking."
"If you want a copy of this report for your personal records, save or print a copy of this page."
"Your record number is: xxxxxx"
- Link style should be bg-blue-warm-80v instead of bright blue
- Same [updates to Review page](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/386) should apply to the copy of complaint at bottom of page

## **Changes:** 

- [ ] Update spacing between elements

- [ ] Update text styles

- [ ] Update copy to clarify messaging for saving record numbers

- [ ] update copy of report to match edits from Review page

## **Annotations - NOTE: _I only annotated things that needed fixing, not every detail, as much of the page is in good shape already_**
![Confirmation Annotations.jpg](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/dd5fb152-1ec1-4fbe-9489-b2c5e1f7c195)

**Comment by AvivaOskow** [comment]
@hbillings thanks for the changes so far!

### Edits
#### Here are some things I noticed, let me know what you think is feasible 

#### **Success box:** 

- [ ] _“If you want a copy of this report for your personal records, save or print a copy of this page.”_ goes too far to right, should cut off at same place as headers above

- [ ]  “Your record number” should be Public Sans Light 22 (same as the intro paragraph on the first page of the form)

![Screen Shot 2020-05-15 at 4.04.45 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/613310ce-708a-4ff3-9367-c4cf0c5f67b3)

#### **Text style changes**

- [ ] Leading is too tight, should be the 1.625 we changed it to in the form (26 px) 
![Screen Shot 2020-05-15 at 4.26.53 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/72787947-2b50-4b2a-a1ce-ee5f15e17d47)

- [ ] Second line of bullet points aren’t aligned
![Screen Shot 2020-05-15 at 4.07.20 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/df824d1e-eed7-4c81-98f7-e061fa4e872a)

-----

- [ ] 3 in circle looks too low
![Screen Shot 2020-05-15 at 4.24.20 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/919e09ac-031d-4fb2-8866-6f15694d4e4e)

-----

#### **Spacing** 
- [ ] Should be more padding between sections/before headers (looks like 40, should be 56 px)
![Screen Shot 2020-05-15 at 4.13.08 PM.png]
(https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/96e8fc8a-4b40-4e5a-9df8-960298bb697e)

----- 


- [ ] Can the paragraphs be shorter? They feel too long in comparison to the headers (but I see maybe it matches the edge of the box for the report)


**Current**
![Screen Shot 2020-05-15 at 4.22.03 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/3d3ccd70-835c-4144-b518-e794c6ea70f6)


**Mock**
![Screen Shot 2020-05-15 at 4.21.52 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/58530ee8-cf07-4c14-8dd1-36b1b85f7a1e)


-----


- [ ] Contact local legal header - 1 circle should align with the top line, right now it’s centered between the two lines and looks off
![Screen Shot 2020-05-15 at 4.12.29 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/042abecb-5e87-4a78-9454-1b5985409e3e)

**Comment by Jacklynn** [comment]
I reviewed this just now and I don't think a lot of @AvivaOskow comments have been updated. 

I created a [PR](https://github.com/usdoj-crt/crt-portal/pull/480) for the extra quote mark on the sentence` Legal aid offices or members of lawyer associations in your state may be able to help you with your issue."`
