### ISSUE TITLE
[View all] Bring filter buttons closer together

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#392]
### Problem
Filter buttons look more spread out than annotated. It looks like there's 32px padding after each button when I was expected 16px/ 1 rem. The 1 rem spacing fits the page's current patterns better.

### current
![Screen Shot 2020-03-23 at 4.52.30 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/ed6be4ea-ef79-4512-9bd1-90c0f6ed96b6)

### Expected
![Screen Shot 2020-03-23 at 4.52.22 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/b5e146ca-47c2-45b0-bbf1-916b8c0afa79)

### fix
Via inspector: 
```
.intake-content .intake-filters .crt-dropdown {
    margin-right: 1rem;
}
```
![Screen Shot 2020-03-23 at 4.55.34 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/5f1c8187-003d-44bb-9b9a-3d98afa626b3)

**Comment by blaughman** [comment]
Closing this card.  Filters 2.0 soon being deployed.
