### ISSUE TITLE
Create temporary "do not enter PII, test site" banner

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#399]
## Background/Problem

- Given that we now have three systems running various versions of the portal that CRT intake folks interact frequently and find it confusing as they switch between Dev/Stage/Prod. 

## Proposed Solution
- In order to help differentiate systems, we want to include a banner on 'dev' and 'stage' sites. This banner will read - 'This is a test site. Do not enter PII'

**Comment by Jacklynn** [comment]
(I'm excited for this)

**Comment by blaughman** [comment]
Banner appears as intended.
