### ISSUE TITLE
Set up Drupal instance on Acquia Cloud

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#4]
## Narrative
As a user, I want a website 

## Background
This will give us a foundational distribution of Drupal that we can extend to make our website

## Acceptance criteria
- [x] create functioning Drupal app in the Acquia cloud

**Comment by LindsayYoung** [comment]
@dwechsle and I got this going here: http://dojportalyjydgvyeno.devcloud.acquia-sites.com/
