### ISSUE TITLE
[proform] If not submitted incident date format -/-/-

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#404]
## Problem
If a CRT user creates a record using the proform and it doesn't have an incident date, then it shows up on the Complaint details page and view all table as "none/-/none". 

![Screen Shot 2020-03-24 at 5.09.49 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/b49ff9bf-6d86-4032-bd7e-0d90638e684f)

### Suggestion
Per conversation with Lindsay, update to dashes, so it appears as "-/-/-"

**Comment by LindsayYoung** [comment]
This is fixed
![Screen Shot 2020-05-20 at 4.20.30 PM.png](https://images.zenhubusercontent.com/56f1892d6caf56c9d38e1ac3/61a2587a-2199-4de2-b0ae-b3dd2e6354d7)

**Comment by cantsin** [comment]
Yes. The original fix is in, (by adding the template filter `|default:"-"`) but I believe this bug is occurring in _another_ location. So we fixed one instance but not all instances of this bug.

**Comment by Jkrzy** [comment]
Following up to catch the occurrence we're seeing on the reporting list view.

https://github.com/usdoj-crt/crt-portal/pull/539

**Comment by blaughman** [comment]
Fixed.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/16
