### ISSUE TITLE
Django hardening

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#405]
Scope of this card is to work and document the steps to prep Django prior to the soft launch. 
cc @LindsayYoung

**Comment by Jkrzy** [comment]
Let's run through https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/ !

**Comment by Jkrzy** [comment]
Output from `manage.py check --deploy` with `ENVIRONMENT=Production`

```log
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W006) Your SECURE_CONTENT_TYPE_NOSNIFF setting is not set to True, so your pages will not be served with an 'X-Content-Type-Options: nosniff' header. You should consider enabling this header to prevent the browser from identifying content types incorrectly.
?: (security.W007) Your SECURE_BROWSER_XSS_FILTER setting is not set to True, so your pages will not be served with an 'X-XSS-Protection: 1; mode=block' header. You should consider enabling this header to activate the browser's XSS filtering and help prevent XSS attacks.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W019) You have 'django.middleware.clickjacking.XFrameOptionsMiddleware' in your MIDDLEWARE, but X_FRAME_OPTIONS is not set to 'DENY'. The default is 'SAMEORIGIN', but unless there is a good reason for your site to serve other parts of itself in a frame, you should change it to 'DENY'.
```

**Comment by Jkrzy** [comment]
There's an opportunity to provide customized error pages for the site, right now we're serving the Django defaults. e.g. 

https://crt-portal-django-dev.app.cloud.gov/report/nothinghere

---

<img width="409" alt="Screen Shot 2020-03-25 at 1 00 38 PM" src="https://user-images.githubusercontent.com/3485564/77564160-a5904000-6e98-11ea-9518-81647ab6ad32.png">

**Comment by lalitha-jonnalagadda** [comment]
@Jkrzy There is also a card for the error page if it is helpful - #134

**Comment by Jkrzy** [comment]
Looks awesome @lalitha-jonnalagadda and @LindsayYoung! 

Only one item I think we should definitely change  -- set `X_FRAME_OPTIONS = 'DENY' `
We may also want to consider customized error templates, at least styled similarily to the existing site.

More details in the comments above.
