### ISSUE TITLE
[proform] change "next" button text to "submit"

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#408]
## Problem
The button on the proform says "next". it's not clear that this is the only step and clicking this button will submit the form. 

### Proposed
Label button "Submit" (should read the same on a screen reader)

**Comment by blaughman** [comment]
Button label has been updated.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
