### ISSUE TITLE
[proform] Update heading for the proform

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#409]
## Problem
Heading ("contact the DOJ...") not necessary for the pro form, for a difference audience, and takes up a lot of space. The heading should be consistent with the rest of the internal side. 

### Current
![Screen Shot 2020-03-25 at 4.42.48 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/e1b85282-0990-4390-8122-39cb95ad0fde)

### Expected
![Single page Copy@1x.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/14fafd8d-bbea-427a-b735-d1e9c8a60452)
_Showing future state without "follow up" question section"_

**Labels**
1. Intake
2. Contact
3. Service member
4. Primary concern
[] Follow up
5. Incident location
6. Personal chracteristics
7. Date
8. Intake description -- @lalitha-jonnalagadda thoughts?

### Spacing
![Single page Copy@1x.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/f93f3ef5-ac36-452d-b3ad-877df6c60ad6)

### Interaction
🎨 [Progress bar source of truth](https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/51)

**Active/Rollover:**
![Single page Copy@1x.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/39b1134f-98bc-46d8-8824-3fac747c301c)
[ic_check.svg](https://drive.google.com/drive/u/0/folders/1ipk2hf037rLMxZvMZm_NI0pSXL3BWM1X): width: 1 rem

**Hover**
background is active field color: `#2491FF`
Text: bold

**Progress bar header is sticky**
To allow CRT users to jump around the form during intake, especially helpful if they're taking a call and information is given out of order.
![Single page Copy 2@2x.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/fc5c1077-222f-4517-884c-92cdf67c7732)

**Comment by Jacklynn** [comment]
@lalitha-jonnalagadda I added more detail around the heading it's a bit more complex with the sticky interaction. Does there need to be a story around it?

**Comment by lalitha-jonnalagadda** [comment]
Checked with @LindsayYoung and @hbillings - We are good to move this card to ready for dev. If @hbillings isn't able to remove the header that would be OK so long as she is able to make it sticky instead.

**Comment by LindsayYoung** [comment]
@blaughman this should now be working on Dev!

**Comment by blaughman** [comment]
This function is now working on all browsers.  Great work.  Moving to UAT.
