### ISSUE TITLE
[proform] Only show follow up question once related primary issue is selected [in IE]

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#412]
## Current workflow: 

As an intake specialist, when I'm on the pro form and select a primary issue, I see all the conditional logic questions on the form which is confusing 

## Proposed workflow:

As an intake specialist, when I'm on the pro form and I select a primary issue, I *only* see conditional logic questions corresponding to that primary issue. The remaining conditional logic questions (that do not belong to the primary issue aren't shown.

**Comment by blaughman** [comment]
This function works on Chrome and Edge, but not IE 11.
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/fa726e02-0075-4bc4-8f44-b0c8abbf7bb8)

**Comment by Jacklynn** [comment]
working for me!
