### ISSUE TITLE
Filter by summary - View all table

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#413]
## Narrative
As a DOJ CRT user, I want to be able to filter complaints by keywords from the complaint summary so that I can only view a subset of the complaints I prefer to take relevant action on. 

## Background
All sections at DOJ, receive about 93K complaints annually. With this kind of volume, it's difficult to locate and look up complaints. Filtering by name will allow the intake specialists to look up a list of all complaints by a complainant. 
 
## Acceptance Criteria

1) Given that I'm on the view all table
When I'm at the Filter by summary 
Then I see free form text boxes to enter a word or a phrase
AND
I see a 'Filter Results' option

2)  Given that I'm on the view all table
When I don't select any filter option
Then I see all complaints as the default view

3) Given that I'm on the view all table
When I enter a word ( or phrase) in the 'Complaint summary' filter and click the 'Filter Results' button
Then I see the view all table filters to display all records matching the word/phrase
AND
I see a tag/label with the filtered criteria by the filtered data

4) Given that I filtered the results by a keyword in complaint summary
When I click 'X' on the tag/label 
Then I see the view all table to display all complaints 

5) Given that I filtered data by a keyword from the complaint summary AND there are no records for that section
Then I see a message warning me about why there are no records showing
AND 
back and forward pagination arrows are disabled

6) Given that I've applied a filter and have reach the end of all the pages for a given filter (ex: less than 15 or on the final page of pagination)
Then I see a message confirming that I've reached the end of records and to change filters to see more. 

## Mockups
![Viewall-Contact Name.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/c889baa2-3edc-489e-9708-ed09046b62f1)

No records for a filter
![Filter-no records.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/dc577451-6e77-4cd6-97b6-d82799db4341)

Records with less than 15 filter
![Filter-less than 15.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/df3414e1-0e7b-4847-ae8b-304420903eef)

## Sign off
- [ ] PO 
### UAT sign off
- [x] PO
- [ ] Product design
- [ ] a11y

**Comment by Jacklynn** [comment]
@lalitha-jonnalagadda maybe linking to the [design flow for the table would be easier](https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/65)

**Comment by LindsayYoung** [comment]
I think we can use some of the postgres features for this in particular search query and search rank https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/search/

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
