### ISSUE TITLE
As a CRT user, I'd like to filter by intake type (mail, phone, portal, etc)

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#415]
## Narrative
As a CRT intake specialist, I would like to filter complaints by intake type so that I can 
- differentiate complaints that were received via the web or via the pro form
- report on the total number of complaints from the portal vs non digital formats
- narrow down the list of complaints to process

## Background

Complaints are input into the portal via the proform where the intake specialist creates a complaint or when a complainant enters via the portal. In both these cases, complaints are then visible on the view all page. Intake specialists need to know if the complaint was created internally or via the portal so they have the information needed to process the complaint effectively.  

## Assumptions
Intake formats:
- Phone
- Email
- Web
- Fax
- Letter

## Acceptance Criteria

1) Given that I'm on the view all table
When I'm at the Filter by Intake format
Then I see a drop down to select from the intake formats - Phone, Email, Web, Fax, Letter
AND
I see a 'Filter Results' option

2) Given that I'm on the view all table
When I select an intake type and click the 'Filter Results' button
Then I see the view all table filters to display all records matching the selection
AND
I see a tag/label with the filtered criteria by the filtered data

## Mock ups
[Source of truth](https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/65)

## Sign off
- [ ] PO
- [ ] Product Design
- [ ] a11y

**Comment by LindsayYoung** [comment]
Made this filter specifically, display is handled in: https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/433

**Comment by Jacklynn** [comment]
DRS mentioned this request today

**Comment by blaughman** [comment]
Closing this card.  Merging this filter into card #623.
