### ISSUE TITLE
[Technical debt] path issue on the add zips migration for new cloud.gov databases

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#424]
It is odd because the only thing that works is if I move the zip_codes_by_district.csv into the migrations folder and refer to the path as: 
`csv_path = os.path.join(BASE_DIR, 'zip_codes_by_district.csv')`

But I though I should have been able to keep it where it is and use the path: 
`csv_path = os.path.join(BASE_DIR, '..' 'data/zip_codes_by_district.csv')`
 
That gives the error:
`[Errno 2] No such file or directory: '/home/vcap/app/crt_portal/cts_forms/../data/zip_codes_by_district.csv'`
But that path looks right to me.

**Comment by Jkrzy** [comment]
Since data lives at the root of the project, I _think_  the path we'd expect on cloud.gov is:
```'/home/vcap/app/data/zip_codes_by_district.csv'```

Initial thought is that BASE_DIR is resolving to ```/home/vcap/app/crt_portal/cts_forms/``` on cloud.gov while we would expect it to be ```/home/vcap/app/crt_portal/``` which is what we see in docker.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card as its dev complete.
