### ISSUE TITLE
[complaint details] Finish implementing updated designs (mostly right side of the page)

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#426]
## Problem
We weren't able to finish styling all of the complaint details page before Adam left. 

Current:
![image.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/6ba131c7-cef3-410b-8560-44403b54b694)

Expected:
- [x] Titles match left hand style with icons
- [x] Field label ("Name") matches left (black/darkgray)
- [x] Primary issue data not bold
- [x] Spacing between cards increased (40px/2.5rem between stacked cards, there should be 1 gutter between cards side by side)

Issues with this page accounted for in other tickets (for reference only, not part of working on this ticket.)
- Reduce size of comment box [#403](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/403)
- Line break in the middle of activity log [#401](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/401)
- Spacing inside of cards reduced/padding [#400](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/400)
- "other" misaligned [#425](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/425)

## Annotations
[Source of truth](https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/66)

**Comment by cantsin** [comment]
Update: we want to do 24px/1.5em between both public/CRT -- 2.5rem is too big. Gutter is supposed to be 32px as well. CCing @Jacklynn

**Comment by Jacklynn** [comment]
The checkbox items are complete. It made me realize I forgot to add that I expected the "personal description" to be part of the card above but I'll make a new card for that.
