### ISSUE TITLE
[text] "Mistreated by police, law enforcement, or correctional staff" text change

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#429]
Current Primary issue text redundant: "Mistreated by police, law enforcement, or correctional staff (including while in prison)"

Requested to remove "law enforcement" because means the same thing as police. 

Updated: "Mistreated by police or correctional staff (including while in prison)"

- [ ] Public side 
- [ ] proform

**Comment by blaughman** [comment]
Both forms reflect this change.  Moving to UAT.
