### ISSUE TITLE
Intake type on the complaint details page

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#433]
## Narrative

As a CRT intake specialist, I would like to see the intake format on the complaint details page so that I know the origin of the complaint (if it was from the online portal vs pro form)

## Background

Complaints are input into the portal via the proform where the intake specialist creates a complaint or when a complainant enters via the portal. In both these cases, complaints are then visible on the view all page. Intake specialists need to know if the complaint was created internally or via the portal so they have the information needed to process the complaint effectively.  

## Assumptions
Intake formats:
- Phone
- Email
- Web
- Fax
- Letter

## Out of scope
- Editing intake format type

## Acceptance Criteria

1. Given that I'm on the proform 
When I select an intake type and submit a complaint
AND
When I go to the complaint details page for that complaint
Then I see that the intake type is displayed on the detail page below the complaint ID

## Mock ups
![image.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/c22ee61c-ce47-4374-883e-ce1731f6adb6)

## Sign off
- [x] PO
- [ ] Design
- [ ] A11y

**Comment by LindsayYoung** [comment]
I updated the card with letter as a type, since that was one of the data types asked for on the pro form: https://github.com/18F/crt-portal/issues/332

**Comment by Jacklynn** [comment]
Added icons to the [drive](https://drive.google.com/drive/u/0/folders/1lUnkuS-A_7jD5Ey9alOOtGF-24h1aEHW) and sent them to Lindsay. The phone is the same as the one already used

**Comment by blaughman** [comment]
@LindsayYoung @Jkrzy @ilodidoj @lalitha-jonnalagadda  No matter what intake type is selected, the details page is showing this image. ![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/d0e010df-5c23-481f-816d-c9c012860598)

**Comment by LindsayYoung** [comment]
The fix for this is in PR review https://github.com/usdoj-crt/crt-portal/pull/392

**Comment by Jacklynn** [comment]
@LindsayYoung I wasn't able to arrow to this content with voice over. Is this something you'd like to me create a new a11y ticket for?

It would also be nice to have hint text for all users, if you hover over the icon it might read "from [web/phone/fax/email/letter]

**Comment by LindsayYoung** [comment]
That would be great as a new issue

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
