### ISSUE TITLE
Replace "summary" column in the view all page

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#434]
## Current

- The 'summary' column in the view all table is currently displaying the information from the 'personal description field' (complainant's full description) 

## Proposed

- The 'summary' column in the view all table is should display the information from the 'summary field' (intake specialist's description of the complaint)on the complaint details page

**Comment by blaughman** [comment]
View All Table reflects this change.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 4/21. Can be closed.
