### ISSUE TITLE
[public] Date: "day" missing optional help text

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#435]
![Screen Shot 2020-04-06 at 5.26.41 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/beaa4d14-c5b9-456c-9c9c-9c07d7df5289)

Day used to have "optional" under neath it. maybe want to hold until we revisit marking everything as 'required'

**Comment by LindsayYoung** [comment]
This changes was part of the content redesign, do you mind if I close this?
