### ISSUE TITLE
Assign newly, submitted complaint to Voting

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#44]
## Narrative
As a DOJ CRT user, I want voting-related complaints to route to Voting so that the Voting section can readily address and assess the violation. 

## Background
All complaint submissions, pending the answers to the questions, will be automatically routed to ADM section. This story focuses on implementing the routing logic for submissions that would default them to the Voting section.

## Assumptions
- _What is your primary reason for contacting the Civil Rights Division?"_  is **required**

## Out of scope
- Changing section allocation from VOT to other sections or vice versa
- Sorting and filtering by sections

## Acceptance criteria
~~ 1) Given a complainant is submitting a complaint 
When they select  **'Ability to vote was impacted'** on the 'Primary issue' page and completed all the required fields of the form and submitted the complaint
Then in the view all table, I see that the record is assigned to the voting section and marked with VOT in the 'Routed' column ~~

2) Given a complainant is submitting a complaint 
When they select  **'Ability to vote was impacted'** on the 'Primary issue' page 
AND
selected any option on the protected class page other than **Disability** and submitted the complaint
Then in the view all table, I see that the record is assigned to the voting section and marked with VOT in the 'Routed' column

3) given that I'm using a screen reader, when I get to a cell in this column it should announce "V-O-T, Routed" ([cell content, column name]).

I expect this to work as intended already based on the other tables. Preference for keeping it consistent with what sighted people would see vs having it read the section name

## Mockups / Wireframes 
**A**
Design source of truth: https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/43

Content source of truth: https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit#

![image.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/85b425f7-631e-469d-b13d-f04efdca2530)

![[LATEST] CRT view all - routed Copy.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/2cebc455-a0ae-4586-967a-34ed3d00ae4c)

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by lalitha-jonnalagadda** [comment]
@Jacklynn @AvivaOskow - can you please update the mocks for this story?

**Comment by Jacklynn** [comment]
Added "VOT" example mock

**Comment by LindsayYoung** [comment]
Noting this will assign new forms to voting, but not reassign old forms. This is intentional because we want to be able to re-assign the sections later. The initial assignment only happens when the form submits.

**Comment by lalitha-jonnalagadda** [comment]
@blaughman I added AC2 to support the DRS scenario.

**Comment by alexsoble** [comment]
Merged to dev, ready for review by Product.

**Comment by lalitha-jonnalagadda** [comment]
Completed independent UAT review.

**Comment by lalitha-jonnalagadda** [comment]
As per #77, noting an exception to the VOT routing:

- As a public user:
Given that I select primary issue as 'Right to vote impacted'
When I select either option for 'Hate crime and human trafficking'
Then my complaint is routed to CRM
