### ISSUE TITLE
[a11y] disable back button when no result on CRT viewall

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#440]
The back button on the pagination looks like it is disabled when you can't page back, but it is not currently disabled properly for screen readers and will read out the icon name.
 
If there are no results on the view all table, the back button for pagination should be disabled. It is currently Reading “ic icon graphic” when back pagination is disabled. The front arrow is acting as expected so copy the style and state from that button to fix this.

**Comment by Jacklynn** [comment]
Working for me!
