### ISSUE TITLE
[a11y] Labels not reading on complaint detail page

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#441]
On the detail page, make sure labels are associated and read for all form elements on the page:
- [x] section
- [x] status
- [x] judicial district
- [x] new comment 
- [x] summary

- [x] Get an A11y test going for that page (It was half finished for a while so we didn't set it up yet)

**Comment by Jacklynn** [comment]
![amazing.gif](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/d9fda290-5c02-4723-82c7-040c9b318d3e)
