### ISSUE TITLE
[a11y] Add an alert when the details page is updated

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#442]
There needs to be an announcement for addition or change for all form elements:
- [ ] comment 
- [ ] summary 
- [ ] section
- [ ] status 
- [ ] primary statute
- [ ] judicial district

My guess is the easiest way to implement that is to read the announcement of the change when a user clicks a submit button.

**Comment by Jacklynn** [comment]
I can see this, but it's not reading in Safari + VO. Any advice?

**Comment by LindsayYoung** [comment]
It becomes part of the page title and the page title is always read. 

Here it is being read on VO
![Screen Shot 2020-05-18 at 10.59.06 AM.png](https://images.zenhubusercontent.com/56f1892d6caf56c9d38e1ac3/c1933472-fb2e-4faa-9d66-c8c79935073a)

**Comment by Jacklynn** [comment]
They didn't announce for me but I saw the title, i think VO is not very reliable at this.
