### ISSUE TITLE
[a11y] error pages have unlabeled graphics

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#444]
Add label to graphic in error message template.

**Comment by Jacklynn** [comment]
@Jkrzy  I'm seeing no icon in the error messages now 🤔
![Screen Shot 2020-04-28 at 11.51.36 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/5e87ef5f-94f3-48ce-89a6-f9ea902ce001)

**Comment by LindsayYoung** [comment]
that icon isn't being loaded it's getting a 403
