### ISSUE TITLE
[a11y] 500 words remaining reads for all text boxes on the proform

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#445]
On the form/new page we are re-using the same js word counter script as the front end. We need to scope down the function so that it only reads the word count if people are on a particular textarea element rather than all elements. The result if this bug makes the pro-form so annoying that it is unusable.

**Comment by Jacklynn** [comment]
It wasn't reading anymore on the other fields which was this issue, but it also doesn't have warning on the actual free form box. As a user, I wouldn't have a way to know why additional words aren't being typed.

**Comment by LindsayYoung** [comment]
It's not loading the script it needs, should be an easy fix.
