### ISSUE TITLE
[A11y] Hate crimes and human trafficking not reading label

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#446]
When the options for hatecrimes and trafficking are navigated to, They are not reading the question. This was noticed on the pro form but looks like a main form problem as well.

**Comment by Jkrzy** [comment]
Working towards a fix for this one in https://github.com/usdoj-crt/crt-portal/pull/402 but not sure I'm replicating the original issue correctly. Would love to pair with someone who's more familiar with this issue and learn how to best observe it in the wild.

**Comment by LindsayYoung** [comment]
We want to confirm expected behavior with Terri

**Comment by Jacklynn** [comment]
This looks like it's working correctly on the proform to me @Jkrzy

**Comment by LindsayYoung** [comment]
we are re-doing this anyway
