### ISSUE TITLE
As a CRT user, I'd like to filter by statute

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#460]
## Narrative
As a DOJ CRT user, I want to be able to filter complaints by statute so that I can look up complaints by a statue category to respond/process these complaints

## Background
HCE feedback during soft launch wanting so sort on specific statutes. Used the example "SCRA" but we could also sort on the statute since that information is also in the statute. 
 
## Acceptance Criteria

1) Given that I'm on the view all table
When I'm at the Filter by statue drop 
Then I see typeahead dropdown with statute codes
AND
I see a 'Filter Results' option

2) Given that I'm on the view all table
When I enter a statute number or any portion of the number in the statute filters and click the 'Filter Results' button
Then I see the view all table filters to display all records matching the number 
AND
I see a tag/label with the filtered criteria by the filtered data

## Sign off
- [x] PO
### UAT sign off 
- [x] PO
- [ ] Product design
- [x] a11y

**Comment by blaughman** [comment]
Function works as intended.  Ready for deploy.

**Comment by Jacklynn** [comment]
**Product design:**
- this isn't this ticket specific but it looks like there's extra space after the X 
- and the X is black instead of the dark blue we've using for the text and outline.

![Screen Shot 2020-04-28 at 11.31.38 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/17fd16bc-fb7d-44e4-91bb-e2e0be24e25f)

**Comment by Jacklynn** [comment]
Filed https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/469 for the design things
