### ISSUE TITLE
add red box for select error state

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#461]
the new select box has the error class on it but the red box doesn't render anymore.

This was originally part of [Design audit: error state updates #384](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/384) but I couldn't seem to with the fight with the css

**Comment by Jacklynn** [comment]
Not sure if this was on a specific page, but seeing error boxes on all the public side pages
