### ISSUE TITLE
Onboard James

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#464]
## Description

James T joins team as a new full time engineer on 4/27

## Definition of done
- [x] @lalitha-jonnalagadda  Invite James to:
  - [x] core meetings
  - [x] documents/drive  
  - [x] PA shareback doc (describing the thin slice) 
  - [x] Charter
  - [x] Team Calendar

- [x] Walkthrough vision, roadmap and thin slice @lalitha-jonnalagadda  
- [ ] Schedule meeting with design around end-to-end mockups @Jacklynn  
- [ ] Schedule meeting w/ design around User research, personas, etc @Jacklynn 
- [ ] Schedule meeting w/ engineers around technical vision, history @LindsayYoung   
- [x] create accounts @LindsayYoung 
   - [x] 18F CRT GitHub team (circle and zenhub access are connected to GitHub)
   - [x] CRT GitHub @dwechsle 
   - [x] cloud.gov

**Comment by cantsin** [comment]
I think we're good here -- at this point I feel fairly caught up with tech and design! Please feel to re-open if there's anything we missed here.
