### ISSUE TITLE
Capture 'To' and 'From' states in the activity log

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#466]
## Current workflow

In the activity panel, we are capturing the the 'updated' state of an action. For example, when an intake specialist changes the status of a complaint from 'new' to 'open', the activity log shows an entry - Status updated to 'Open' 

## Proposed workflow

In the activity panel, we will capture both the previous and the updated activity. So the activity log will read - **Updated Activity from (blank) to (blank)**

**Comment by blaughman** [comment]
Function works as intended in Chrome, Edge and IE 11.  Moving to UAT.
