### ISSUE TITLE
SPL primary issue copy request

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#468]
Background: 
Request to add something to capture RILUPA more accurately . 
“Mistreated by Police, or while in a correctional facility, juvenile facility, health care facility (disabilities) or seeking safe access to reproductive healthcare clinics **or seeking the ability to practice my religion while in an institution**.”  

Final:
Talked to Glynis to just update the title to "Mistreated by police, correctional staff, or inmates (including while in prison)"

There was some confusion between the pro form and the public form

**Comment by blaughman** [comment]
Glynis feels the following copy edit would be more helpful for the public facing form (Mistreated by police, or correctional staff (including while in prison **or a juvenile justice facility**).

**Comment by Jacklynn** [comment]
Glynis: Limited the words to read **Mistreated by police, or correctional  staff or inmates (including while incarcerated)**.  The client will read that it is not limited to just prisons.  That should work for the section.  We can work on the other language at a later date.  Much appreciation for your office.

**Comment by lalitha-jonnalagadda** [comment]
@Jacklynn @blaughman - Can either of you please clarify what the final copy changes expected are?

**Comment by Jacklynn** [comment]
I sent an email to Glynis asking if this was her final request:

![Group 4.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/87618bdf-abfd-40ec-9415-df22d1c97955)

She had mentioned more but proposed this as a quick fix.

**Comment by Jacklynn** [comment]
Glynis signed off on the above copy change.

The change to blue title are...
- We removed "law enforcement" because it was redundant
- We added "inmates" to the list

Final text: `Mistreated by police, correctional staff, or inmates` `(including while in prison)`

**Comment by LindsayYoung** [comment]
Noting that we don't have the translation on this

**Comment by Jkrzy** [comment]
I'm a bit confused on the scope of these changes for this question.

Summarizing across the comments above, both the question text and examples should be changed.

1. Question text to be:

> Mistreated by police, correctional staff, or inmates (including while in prison)

2. Example text to be:
>* Police brutality or use of excessive force, including patterns of police misconduct
>* Searched or arrested under false pretenses, including racial or other discriminatory profiling
>* Denied rights, language access barriers, subjected to harmful living conditions or lack of accessible facilities

**Yes, No, Maaaaaybe??**

Current state for comparison:
![Screen Shot 2020-05-27 at 11.43.33 AM.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/05ba2ff8-565e-44fe-838e-206aa92e849c)

**Comment by Jacklynn** [comment]
Sorry for the confusion, we're only changing the blue title. `Mistreated by police, correctional staff, or inmates (including while in prison)`

I must have used an outdated mock and I should have updated the main body of this zenhub! We talked her down for making more text changes and Marta should have only translated the title.

**Comment by lalitha-jonnalagadda** [comment]
Translation for 'or Inmates': **“o reclusos”**

**Comment by Jacklynn** [comment]
saw the title change, thanks!
