### ISSUE TITLE
Adding form letter responses to the 'activity log'

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#477]
## Narrative

As an intake specialist, I would like to view the action taken regarding a form letter response on a particular complaint so that I can take the necessary action as needed

## Acceptance Criteria

1. Given that I'm on the complaint details page
When I take an action(Copy or Print for now) after clicking the 'Contact Complainant' button 
Then I see the corresponding action in the activity log 
AND
Then I see the action reflected in this format - Contacted complainant: _**Action** (Copied/Printed) **'Form letter template name'** (Eg: CRT generic - No jurisdiction)_

**Comment by blaughman** [comment]
@lalitha-jonnalagadda This looks good.

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/16
