### ISSUE TITLE
Copy edits to replace 'concern' with 'report'

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#483]
## Background

Based on feedback from the policy counsel groups, 'concern' doesn't outline 'what' is being collected via the form. In the past, we decided that 'complaint' isnt the right terminology either, given that not all incoming needs end up to be "complaints" depending on the sections and their processes/policy. In order to capture the essense of all incoming messages, we want to change the copy from "concern' to "report' to maintain uniformity from the landing page to the confirmation page.

|Page|Current|Proposed|
|--------|:-----------|:-------------|
|Contact page| Title - Contact the Department of Justice to report a civil rights concern| Contact the Department of Justice to report a civil rights **violation**|
| Hate Crimes page|Subheading - Please select if any apply to your concern (Optional)| Please select if any apply to your **report** (Optional)|
|Location Details| Italicized subtext - Please tell us the city, state, and name of the location where this incident took place. This ensures your concern is reviewed by the right people within the Civil Rights Division| Please tell us the city, state, and name of the location where this incident took place. This ensures your **report** is reviewed by the right people within the Civil Rights Division.|
|Review page| Two Buttons - Submit concern| Submit **report**|
|Review page|Heading - Review your concern| Review your **report**|
|Confirmation page| "Thank you for submitting a concern to the civil rights division| Thank you for submitting a **report** to the civil rights division", "Our specialists in the Civil Rights Division carefully read every report to identify civil rights violations, spot trends, and determine if we have authority to help with your **report**." "Collect more information before we can look into your **report**." "Recommend another government agency that can properly look into your **report**. If so, we’ll let you know." "In some cases, we may determine that we don’t have legal authority to handle your **report** and will recommend that you seek help from a private lawyer or local legal aid organization."|
|Confirmation page|If we are able to respond, we will contact you within 4 weeks using the contact information you provided in this report.|If we are able to respond, we will contact you using the contact information you provided in this report. Depending on the type of report, response times can vary. If you need to reach us about your report, please refer to your report number when contacting us. This is how we keep track of your submission.

## Won't change

- Primary **concern** will remain as is
- Italicized subtext on the primary concern page
- 'What to expect" section - Step 2: 'Concern'
- Hate crimes page, describe your concern

**Comment by LindsayYoung** [comment]
One more piece of text that is not on the change or don't change list:

Hate crimes page:

Please let us know if you would describe your **concern** as either a hate crime or human trafficking. This information can help us take action against these types of violations. We will contact you about the next steps. We also encourage you to contact law enforcement if you or someone else is in immediate danger.

**Comment by lalitha-jonnalagadda** [comment]
@LindsayYoung 
As discussed during the Sprint planning meeting today, we will leave the examples in the voting primary issue as is for now. We will however change the title on the voting issue from 'Voting rights or ability to vote blocked or affected' to **'Voting rights or ability to vote affected'**

**Comment by blaughman** [comment]
"Report" is now throughout the form as requested.
