### ISSUE TITLE
Spacing issues on Location pages

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#485]
Workpalce Missing space between questions
![page3-location-workplace.png](https://images.zenhubusercontent.com/56f1892d6caf56c9d38e1ac3/db38a79b-09a0-4ae2-b363-85dbd56ec396)

Education- missing space after helptext 
![page3-location-education.png](https://images.zenhubusercontent.com/56f1892d6caf56c9d38e1ac3/a7c2abac-46d1-4b3c-8a59-1bdeee6f218d)

Sorry, should have caught this in PR review

**Comment by blaughman** [comment]
Spacing looks good now.
