### ISSUE TITLE
Change response time copy on confirmation page

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#486]
## Current

On the confirmation page, in the 'what to expect' section, under bullet 3, we currently have description about response time that reads:

**_If we are able to respond, we will contact you within 4 weeks using the contact information you provided in this report._** 

## Proposed

The above language should be updated to:

_**If we are able to respond, we will contact you using the contact information you provided in this report. Depending on the type of report, response times can vary. If you need to reach us about your report, please refer to your report number when contacting us. This is how we keep track of your submission.**_

**Comment by LindsayYoung** [comment]
moved to #483
