### ISSUE TITLE
Embed Google Analytics/DAP into Complaints portal

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#487]
## Background

With the beta launch, we want to start collecting analytics information that will allow for team to monitor and track user activity as they make their way across the form. In order for us to collect data, we would like to embed GA tags on all our pages

## Proposed solution

@dwechsle will pass the GA tags they embedded on justice.gov/crt that @lindsay can include on civilrights.justice.gov prior to the beta site. At the very least, we would like to track click's to the opt in call to action link on justice.gov to understand traffic patters around users initiating the action vs completion in terms of successful submissions

**Comment by LindsayYoung** [comment]
I have the code thanks @dwechsle for getting that to us so quickly!
