### ISSUE TITLE
IE11 question header exceeds bounds, umatched tags, and word_count.js parse error

### ISSUE THREAD

**Issue by cantsin** [18F/crt-portal#490]
- IE11 line text exceeds bounds (see below)

[image.png](https://images.zenhubusercontent.com/5eb05c8e896abe15ccf6dfa3/d8b2ea95-a9b8-4d13-8b26-1359a6c69d5f)

Noting some IE11 bugs as I went along (note: probably not a comprehensive list)

- `Unmatched end tag` errors on most pages
- `Syntax error` when trying to parse `word_count.js`

**Comment by blaughman** [comment]
Issue resolved in IE 11 and Edge.  Moving to UAT.
