### ISSUE TITLE
Privacy policy in the footer of the form

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#493]
## Narrative

As a public user filing a report for civil rights violation, I would like to look at the CRT privacy policy on the form so I can review it as I need to

## Background
Privacy office at DOJ requested the privacy policy be available in the footer of the page vs on a different page. While the details of the implementation are to be hashed out, we will be including a short version of the privacy policy in the footer of the form.

## Assumptions
- Privacy policy link in the footer stays as is for now

## Acceptance criteria
1. Given that I'm on the form to report a violation
When I scroll to the bottom of the page
Then I see the privacy policy content

## Mock up
![Screen Shot 2020-05-13 at 5.11.47 PM.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/a0d431e5-7fe3-454f-b062-dcd2f2aee166)

**Comment by lalitha-jonnalagadda** [comment]
@cantsin - Copy for the footer is here - https://drive.google.com/open?id=1yIEKLghYy0bsC4VcmGmzRn8WsevIvXC7166BFsPTI6Q

**Comment by blaughman** [comment]
Abbreviated privacy policy is in the footer.
