### ISSUE TITLE
Required asterisk for month and year fields 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#494]
On the front facing form we want a required asterisk for month and year fields 

We do not want the astick the crt view forms: `form/new` and `form/id `

Current screen shot missing the asterisk
![Screen Shot 2020-05-13 at 2.35.44 PM.png](https://images.zenhubusercontent.com/56f1892d6caf56c9d38e1ac3/2e1f2bcb-a272-4be1-bb38-8d990fffb94c)

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.
