### ISSUE TITLE
Refine Hate crime and human trafficking question

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#495]
## Narrative
As a public user, I would like to better understand and answer if my report related to a hate crime issue (or if I was at the right place to report human trafficking issue) so that I can include that information with my report

## Background
[Latest research🔐](https://docs.google.com/presentation/d/1DQznfMdkUJrlkiAFG9IkNyjzDGgq0CqyUHvVknaMJwI/edit#slide=id.g8018312b4e_0_193)

These items can overlap with other primary issues.
The language is hard for users to understand or can be intimidating
Feels broken when they see the screen and it doesn't apply to their scenario
there isn't an explicit way to by pass this page

## Assumptions
- 

## Out of Scope
- Gracefully redirecting a user to the hotline page via a pop up describing that they are being redirected 
- No backward compatibility to fix prod records where we collected reports with the older version (two check box options for hate crime and human trafficking)
- Checking protected classes when a user selects hate crimes

## Acceptance Criteria

1. Given that I'm on the primary issues page
When I click 'next'
Then I'm taken to a page title ' Primary issues' _continued_
AND 
It has a two part question:
 - Does your situation involve physical harm or threats of violence? ((Yes/No)
 - Were you forced to work against your will?

2. Given that I'm on the hate crimes page
When I click on the 'Get help for human trafficking hotline' button
Then I'm redirected to https://humantraffickinghotline.org/
- should have an external link icon: ![ic_external-link.svg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/74bb053d-705b-416f-8e05-cd92fd1760e6)
 - [a11y] button is associated with the question group "Were you forced to work against your will?"

3. Given that I'm on the hate crimes question
When I select yes/no
Then I'm able to 'click' next to the location page
- [a11y] yes/no options are labeled with the question group "Does your situation involved physical harm or threats of violence?"
-- User should be able to click on the button using keyboard only. 

##### Complaint details page

4. Given that I'm on the hate crimes question
When I don't select yes/no 
Then (as an intake specialist) when I check the complaint details page I see 'Hate crime' - yes/no depending on the option chosen
AND
I don't see details on the 'Hate Crime' selection

#### Routing

5. Given that I'm on the hate crime question
When I select 'yes' to the hate crime question
Then my complaint is routed to CRM

#### Pro form

6. Given that (as an intake specialist) I'm on the pro form
When I'm at the Hate crimes/ Human trafficking question
Then I see that only hate crimes question is listed with the option to select Yes/No

**Comment by Jacklynn** [comment]
Per Jim: "human trafficking includes being forced or coerced to do work, or forced or coerced to engage in sex acts for something of value"

Mock discussed last week:
![Future state.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/efe9dd4b-72cc-4b5c-b4f2-4ebd800662d3)

**Comment by LindsayYoung** [comment]
I am going to start working on the data and testing elements for this card while it is getting finalized to make sure we can get it into the release.

**Comment by Jacklynn** [comment]
**Adding external link icon:** ![ic_external-link.svg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/74bb053d-705b-416f-8e05-cd92fd1760e6)

**Comment by Jacklynn** [comment]
Added some a11y criteria

**Comment by LindsayYoung** [comment]
Can I get a confirmation this is still not a required question?

**Comment by Jacklynn** [comment]
@LindsayYoung still optional! I know this was seven hours ago and was also answered on slack though...

**Comment by LindsayYoung** [comment]
Just clarifying "Were you forced to work against your will?" isn't going to be part of a question group because it isn't a form question, it is a link we are styling as a button.

To get the same effect, I am adding an aria-label to the link that reads "Were you forced to work against your will? Get help from the National Human Trafficking Hotline"

**Comment by Jacklynn** [comment]
Sounds good, thanks!

**Comment by blaughman** [comment]
Page works as intended.  Need @Jacklynn to confirm a11y functionality before moving.

**Comment by blaughman** [comment]
Page looks and works as intended.

**Comment by Jacklynn** [comment]
I tested with VO and was working correctly. There are no errors for this page which makes it easier too.
