### ISSUE TITLE
[a11y] Hint text reading for each option on personal characterstics page

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#499]
Problem:
[On the personal characteristics page] Screenreader reads the label, the intro "help text", and the sentence in the legend for each checkbox.

Expected:
Screenreader reads only the label and the legend for each checkbox in the fieldset

Proposed:
Removing the aria-describedby on the checkbox inputs. 
 Terri provided [this example](url)![image.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/3610d16f-c1bf-49fa-9659-0849aa922c9d) of what she expected. The group label only reads on the first option. 

[Via Julie](https://docs.google.com/spreadsheets/d/1ztC_mrj-r7My3TL_ihImKe_mHneyv_8zzk8A4MNk9X4/edit?folder=1Bhs8Khid52Oi96sSOw2ggojj_r0SQvKo&pli=1#gid=1849575968)

**Comment by Jacklynn** [comment]
Fixed! thank you. I noticed it's reading each option twice Any reason why it might be doing that? Sometime things are double labeled @Jkrzy

**Comment by Jkrzy** [comment]
I was getting the same thing @Jacklynn, it may be an issue with Safari+VO. Were you getting those results w/ another environment? 

Noted in https://github.com/usdoj-crt/crt-portal/pull/483#issue-420271981.

I've dug in a bit deeper but haven't found anything worthwhile yet in terms of a workaround/fix.

**Comment by Jacklynn** [comment]
Thank you!
