### ISSUE TITLE
Move case record to 'Open' from 'New'

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#50]
## Narrative
As a CRT User, I want to change the status of a record from 'New' to 'Open' so that I can acknowledge ownership of a complaint and process the complaint accordingly.

## Background
DOJ CRT labels an incoming case as 'new' if the complaint has been submitted by the complainant, but has not been analyzed by DOJ CRT staff.  The label designation allows DOJ CRT staff to determine daily workloads and allocate resources. 

Details on [mural](https://app.mural.co/t/gsa6/m/gsa6/1562611057486)

With representation from ADM, DRS, EOS, FCS, IER, SPL, VOT, we gathered the following feedback:
**New** : Record has just been submitted to CRT from the online portal or manual entry, but has not yet been opened by a CRT user; assigned to section
**Open** : Record is being processed by the section, this could mean different things for each section. #50
**Closed** #53 : Complaint was responded to or recommended for review; attempts to contact complainants unsuccessful; section decides to close or open DJ number

## Assumptions
- Case is in 'new' status

## Acceptance criteria
- [ ] viewing the detail page of a 'new' case record and then you see an option to 'change the case status' to 'In Process' (or under review)
- [ ] Once you select 'in process' then you should see the 'status' field change from 'new' to 'in process'
- [ ] a11y - a screen reader user should be able to hear that this is a drop down and what their current status is
AND if they interact with it, they should be able to hear the other options and select a different one. 
IF they select another option, they should hear confirmation of that the the status changed. 
(this hopefully happens with standard drop down components

## Mockups / Wireframes
1. Aviva is using the pill design right now so I added a version with and without that. I mimicked the [default HTML](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_option) behavior where the options stay in the same order every time. 
![Screen Shot 2019-12-30 at 3.10.36 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/1e9b6196-8c2e-48bb-bb88-bb673ebb6348)

2. I would also expect the status change to show up in the activity:
![Activity.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/fd603bf7-c82a-41e9-8f97-2ed6a56ce2ba)

Notes: I am assuming status changes are changeable, including "Closed", so I don't think a confirmation ("are you sure?" dialog) is necessary.

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by Jacklynn** [comment]
@UchMok @blaughman I added mocks for review

**Comment by Jacklynn** [comment]
Bill said it looked good to him, moving to Analyzing and unassigning

**Comment by Jacklynn** [comment]
New > Open should unbold the row on the View all table too!

**Comment by lalitha-jonnalagadda** [comment]
Closing this card as we have an updated card for this story - #248
