### ISSUE TITLE
[a11y] Error for primary issue state might be difficult to find

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#500]
Problem:
Step 2 (Primary Issue) specific error msg shows at bottom of long page. (Usability issue; esp burdensome for people using screenreader)

Expected: 
Understand error before scrolling/listening to all radio options

Notes:
* wondering if we can revisit some fo the design options on the [previous error ticket](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/384) which which lists out the errors one line each. 
* Also maybe we could move the error message to after the first instruction card and before the radio buttons

**Comment by Jacklynn** [comment]
Pulling out option 2 from the previous portal:
![image.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/3ef64d4b-d495-45e5-b76d-d08dd9853385)

**Comment by Jacklynn** [comment]
Future: maybe two exceptions for above are Primary issue and Personal characteristics having the red box between the question and options

**Comment by Jkrzy** [comment]
Thanks @Jacklynn, I'll implement the mock-up above for Primary Issue and Personal Characteristics page.

**Comment by Jkrzy** [comment]
![Screen Shot 2020-05-18 at 7.03.53 PM.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/cd5d406f-bf80-4e2f-a114-fe56603eb560)

Example of this for Primary Concern page, note that `1 error found` text doesn't match the mock but is consistent with the casing, punctuation we're using across all other questions.

**Comment by Jkrzy** [comment]
And personal characteristics page: ![Screen Shot 2020-05-18 at 7.19.30 PM.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/9b7b2e83-08a7-45f8-9064-707dade1b7cf)

How do these stack up to what you envisioned @Jacklynn?

**Comment by Jacklynn** [comment]
AMAZING YOU DID BOTH THE THINGS!!!
