### ISSUE TITLE
Copy/Design edits on the footer

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#509]
## Copy edits

- Remove 'Office of Assistant Attorney'
- Edit phone number - 202 514 3847

## Design edits
- [ ] The font size for contact and the site links should be 14 px, 1.5 leading (I had it as 1.7 but I think we use 1.5 for 14 px elsewhere so making it match would be good)

- [ ] **Privacy policy:**
- Last bullet point, "You can find our complete Privacy Policy here." shouldn't be a bullet point, should be aligned with the first paragraph
- Can we make the paragraph length shorter? It's easier to read if it doesn't run all the way across the page. I suggest 9 columns instead of the full 12

A couple others (for later) are commented in [318](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/318)

**Comment by blaughman** [comment]
@cantsin @LindsayYoung  The phone number still needs to be updated to 202-514-3847 from 202-514-4609.  Thanks.

**Comment by LindsayYoung** [comment]
Updated on stage: https://crt-portal-django-stage.app.cloud.gov/report/

**Comment by blaughman** [comment]
Fixed.
