### ISSUE TITLE
Missed translations from 5/15 release

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#514]
- [ ] Translate 'concern' on the form
- [ ] Translate the omitted blurb on confirmation page - **If we are able to respond, we will contact you using the contact information you provided in this report. Depending on the type of report, response times can vary. If you need to reach us about your report, please refer to your report number when contacting us. This is how we keep track of your submission.**
- [ ] Bring back the above blurb on the Spanish confirmation page

**Comment by LindsayYoung** [comment]
Qualifying that the missing "concern" is one instance in the title- we got the other concern edits in the release. 

The missing title translation- we are showing the previous translation. 
```
#: templates/forms/report_base.html:22
msgid "Contact the Department of Justice to report a civil rights violation"
```

The time follow up copy edit
```
#: templates/forms/confirmation.html:112
msgid ""
"<strong>If we are able to respond, we will contact you using the contact "
"information you provided in this report. Depending on the type of report, "
"response times can vary. If you need to reach us about your report, please "
"refer to your report number when contacting us. This is how we keep track of "
"your submission.</strong>"
msgstr ""
```

**Comment by LindsayYoung** [comment]
I started the email to get the translations.

**Comment by LindsayYoung** [comment]
Adding the blocked tag since we are waiting on transwlation text

**Comment by LindsayYoung** [comment]
## Edit to an existing translation:
Contact the Department of Justice to report a civil rights violation
Para reportar una violación de derechos civiles comuníquese con el Departamento de Justicia

## Missed translation:
If we are able to respond, we will contact you using the contact information you provided in this report. Depending on the type of report, response times can vary. If you need to reach us about your report, please refer to your report number when contacting us. This is how we keep track of your submission.
De poder responderle, nos pondremos en contacto con usted utilizando la información de contacto que proporcionó en este reporte. Dependiendo del tipo de reporte, el tiempo para responder puede variar. Si necesita comunicarse con nosotros acerca de su reporte, haga referencia a su número de informe al comunicarse con nosotros. Así es como podemos dar seguimiento a su envío.
