### ISSUE TITLE
Filters 2.0 

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#515]
## Narrative

As an intake specialist, I would like to be able to select more than one option in the filters so that I can see records that match my filter options to take action on

## Acceptance Criteria

1. Given that I'm at the view all table
When I'm selecting filter options for - status, state, section, assignee and classification 
Then I'm able to select more than one option from these drop downs
AND 
Then after multi selecting from the drop down options, the view all table reflect the corresponding data that I selected

**Comment by Jacklynn** [comment]
#390 seems related to this

**Comment by blaughman** [comment]
@lalitha-jonnalagadda I think we should add 'Assignee' to the filter options.

**Comment by Jacklynn** [comment]
I messaged Bill in slack, but so this doesn't get buried...

I mocked up [this prototype](https://gsa.invisionapp.com/share/53XK51LUWT4#/screens/420265438_1-View_All_Updated) on how we could optimize the filters for staff more based on what they're using.

- You can click the fields and the Date, Incident Location, and IER drop downs. _You have click outside of the drop downs to close them, but normally you’d just click the title again_
- You can click “More” to see more hidden filters.

Bill mentioned the filters he's using most often are..
1. Section
2. Status
3. Contact
4. Summary
5. Complaint ID#

**Comment by Jacklynn** [comment]
@lalitha-jonnalagadda added notes on all the changes: https://docs.google.com/document/d/1mKaZgthkNnSSDIyx-ZWbwqBH0PVdxrWTurwJZjkGUgk/edit
