### ISSUE TITLE
Test SSO upgrade on staging

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#517]
- JMD plans on upgrading SSO to a new ADSF version on 6/2 (web services)
- IP addresses the app is using to double check validity

On **June 1**, deploy single sign on to staging
Full Instructions for SSO: https://github.com/usdoj-crt/crt-portal/blob/develop/docs/maintenance_or_infrequent_tasks.md#single-sign-on 

Note that:
  - the variables are already set
  - the ca bundle file is already in place in the s3 bucket
  - you will need to **update the code** - https://github.com/usdoj-crt/crt-portal/blob/develop/docs/maintenance_or_infrequent_tasks.md#code-changes
- you can make a one-off deploy by naming the branch release/single-sign-on

Once CRT folks confirm it is working, we can deploy the last staging release by rerunning it in circle.

Only CRT users will be able to see the crt views and admin while that is being tested.

**Comment by Jkrzy** [comment]
@ilodidoj, do we still need this card?

 I think it can be replaced by https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/835 unless there's a specific upgrade coming from JMD that you're aware of and we need to test for.

**Comment by ilodidoj** [comment]
@Jkrzy agreed.  This can be closed and replaced by the #835.
