### ISSUE TITLE
Deployment path to Acquia Cloud from local

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#52]
## Narrative
As a developer, I want to push code to Acquia Cloud so that we can see, use, demo, and test our application easily.

## Notes

This deployment path can involve manual deploys; continuous integration can come later. 

## Definition of done 

+ [x] Site deployed! With modules enabled via command line 
+ [x] Code used for deploy merged to master: https://github.com/usdoj/crt-portal/pull/9

**Comment by alexsoble** [comment]
While we are able to trigger deploys of code to our Acquia Cloud site now — see https://github.com/usdoj/crt-portal/blob/ars/update-readme-getting-started/README.md#deploy — to deploy modules to our Acquia Cloud site, we need to be able to import configuration after deploying code. 

This "import configuration" step is the step we are stuck on. We are currently getting an obscure error related to Acquia Lightning when we attempt to import configuration. Have reached out to Rob and Marvin from Acquia about this issue to see if they have seen it before and might be able to help.

**Comment by alexsoble** [comment]
Filed a ticket with Acquia Support about the issue we ran into with the Acquia Lightning error message: 

Ticket #838405:

https://insight.acquia.com/support/tickets/838405

**Comment by alexsoble** [comment]
Filed a ticket with Acquia Support about env variable interpolation into drush sites.yml:

Ticket #838498:

https://insight.acquia.com/support/tickets/838498

**Comment by alexsoble** [comment]
We got a deploy with modules working yesterday!! 

In terms of what was blocking us before ... still not 100% sure, but my working hypothesis is that it had to do with moving Acquia Cloud apps. 

The "old" app had some messy state and pages that were erroring out; it threw errors when we tried to deploy. The newer app was in a "fresh" state and accepted the deploy.

**Comment by LindsayYoung** [comment]
Making a new issue for the follow up
