### ISSUE TITLE
Add connection line for the steps in spanish

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#520]
The connection line isn't being shown in the spanish version because the alignment is way off.

- Fix the alignment of the progress bar line in spanish

Things to check:
- Don't break the line on english desktop view
- Don't break the line on english mobile view
- Don't break the line on form/new Proform

https://github.com/usdoj-crt/crt-portal/blob/develop/crt_portal/cts_forms/templates/forms/portal/progress-bar.html#L36-#L38

**Comment by blaughman** [comment]
Line is in proper place in all browsers.
