### ISSUE TITLE
Copy edits before 6/2 

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#523]
## Public portal

- [x] A random quotation mark made its' way into Step 1 of "What Can You Do Next."  
![Screen Shot 2020-05-18 at 5.51.12 PM.png]
(https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/7014d34e-105f-4baf-957c-5372413ec5df)

- [x] _'Continued' on the personal description page_

![Screen Shot 2020-05-18 at 5.49.59 PM.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/b2607137-8ec5-4a5e-878e-3cfb4ed9d2de)

## Intake portal
- [x] Relabel 'Send' button to 'Save' for the comments section
- [x] Relabel 'Statue' to 'Classification' 

## Translation Edits

- [ ] Concise privacy policy in footer
- [ ] Hate crimes page translations

**Comment by cantsin** [comment]
Not sure what to do with translation edits here. 

1. We're removing the concise policy footer soon
2. hate crimes page translations -- where are these?

**Comment by cantsin** [comment]
Also, regarding `Relabel 'Statue' to 'Classification`:

Do we also want to change the name of the `Statute` dropdown in filters? Also I'm assuming that every instance of `Primary statute` should now read `Primary classification`?

**Comment by blaughman** [comment]
@cantsin You are correct with relabeling both of those instances to 'Classification' and 'Primary Classification'.  Keep up the amazing work.

**Comment by blaughman** [comment]
Add edits have been addressed.
