### ISSUE TITLE
Consolidate and componetize styles

### ISSUE THREAD

**Issue by hbillings** [18F/crt-portal#525]
Now that the app is at a point of maturity, we should wrap the styles up into a more productionalized format.

A few things we'll need to do to make the styles more reusable:
- [x] create a USWDS child theme and apply it
- [x] use USWDS tokens and theming consistently (i.e., instead of using `$blue-vivid-80` everywhere, assign a new variable such as `$primary-blue` to have the value `$blue-vivid-80`, then use `$primary-blue` everywhere).
- [ ] code for various components should be broken out according to type of item instead of by page, i.e., `forms.scss`, `buttons.scss`, `typography.scss`.
- [ ] when code only makes sense in a certain component's context (for instance, when an entire module needs to be styled together), that component should be its own Sass file, for instance, `footer.scss`.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/16.
