### ISSUE TITLE
Close a case record as a DOJ CRT user

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#53]
## Narrative
As a \<type of user\>, I want \<a goal\> so that \<benefit\>. 

## Background
![Screen Shot 2019-07-12 at 10.07.02 AM.png](https://images.zenhubusercontent.com/5d0270ab1c131e09cdccbd7c/36452807-1084-46f5-95a8-fc830d06ac82)

Details on [mural](https://app.mural.co/t/gsa6/m/gsa6/1562611057486)

With representation from ADM, DRS, EOS, FCS, IER, SPL, VOT, we gathered the following feedback:
New: Record has just been submitted to CRT from the online portal or manual entry, but has not yet been opened by a CRT user; assigned to section
Under review / in process: Record is being processed by the section, this could mean different things for each section. 
Pending: A case is within jurisdiction, but not being worked on because of some issue; case might be waiting further action or intake specialist is unsure of next steps
Closed: Complaint was responded to or recommended for review; attempts to contact complainants unsuccessful; section decides to close or open DJ number

## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Mockups / Wireframes
![image]()

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by lalitha-jonnalagadda** [comment]
Closing this card as we have an updated card for this story - #248
