### ISSUE TITLE
Canonical URL for SEO 

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#531]
- [ ] Create a canonical URL by 6/2 deploy for SEO's to rank the right URL - civilrights.justice.gov

## Technical Notes

Remove:
  https://github.com/usdoj-crt/crt-portal/blob/7ccf721a74cc43b41a3530483dc956ad8a7a77b1/crt_portal/cts_forms/templates/base.html#L11
Add:
`<link rel="canonical" href="https://civilrights.justice.gov{{ request.path }}">`

romove:
https://github.com/usdoj-crt/crt-portal/blob/7ccf721a74cc43b41a3530483dc956ad8a7a77b1/crt_portal/cts_forms/templates/robots.txt#L2

**Comment by LindsayYoung** [comment]
The steps above will enable search engines to index but we probably also want to:
- Add a meta description for the site
   - As a first pass we would want something we already have, so we can have a translation 
   - We want something that has content that will have relevant keywords in it, like discrimination, voting, disability etc. 
- Add an image for social media 
   - (the seal would be fine, we can update this later)
