### ISSUE TITLE
Step number in page title and progress bar not matching

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#534]
Example: 
![image.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/95024aed-5917-47ea-a1be-edf7785b7dd5)

The hate crimes & human trafficking page throws off the pages after. 

Detail of mismatches
- [ ] Hate crimes & human trafficking page --> Page title should stay "Step 2:"
- [ ] Location details page --> Page title should be "Step 3:"
- [ ] Personal characteristics --> Page title should be "Step 4:"
- [ ] Date page --> page title should be "Step 5:"
- [ ] Personal description --> Page title should be "Step 6:"
- [ ] Review page --> Page title should be "Step 7"

This can be confusing because the screen reader will read out the step number for the page and if a user reads out the progress bar it won't match.

**Comment by blaughman** [comment]
@Jacklynn I think I'm still seeing the same error you mentioned.  
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/0ecaff31-f9dc-411c-bf08-475a9219c7d2)

**Comment by Jacklynn** [comment]
This is working/updated in Lindsay's redeploy 🎉

**Comment by blaughman** [comment]
Problem solved.
