### ISSUE TITLE
[complaint details] Right hand boxes should be higher

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#540]
The complainant information is lower than expected, making more of the information below the fold for users. 

Current: 
![Screen Shot 2020-05-22 at 4.08.53 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/f0f0a9a3-67c0-4790-81c5-f40f36d160ea)

Expected:
![Screen Shot 2020-05-22 at 4.10.41 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/f7fb291a-83d4-4b0a-bbea-80926769d3e4)

**Comment by LindsayYoung** [comment]
What happens when there is a status message?

**Comment by Jacklynn** [comment]
Are some of them very long? I would expect it to fit. Here is a more designed version I haven't made a ticket for.
![B - button Copy 2@2x.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/a4a45c0b-970a-40e4-8aba-940047f4ad28)

**Comment by blaughman** [comment]
Closing this card.  The navigation buttons that were added to the complaint detail page do not allow for the validation message to move up.  This also prevents the cards on the right side of the detail page from moving up as well.
