### ISSUE TITLE
Translation-  Privacy footer + Hate Crime

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#542]
- [ ] From the doc sent May 19

[https://app.zenhub.com/files/183258764/e1b13958-53fa-4514-bbb1-dee89cf48357/download](https://app.zenhub.com/files/183258764/e1b13958-53fa-4514-bbb1-dee89cf48357/download)

- [ ] Translation for 'or inmates' to be added with the SPL primary issue

**Comment by lalitha-jonnalagadda** [comment]
Translations for footer privacy policy and hate crimes
[https://app.zenhub.com/files/183258764/7b331dc3-c695-4c4b-8e98-b898868ade1c/download](https://app.zenhub.com/files/183258764/7b331dc3-c695-4c4b-8e98-b898868ade1c/download)
