### ISSUE TITLE
Make sure certain word/number combinations aren't used in the random ID generator 

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#543]
Background:
We recently had a unique idea that included "SEX" as the random 3-letters. We should make sure certain words or numbers don't get generated accidentally (like how some combinations are banned on license plates)

**Comment by Jacklynn** [comment]
Omitting vowels from the randomizer would help

**Comment by Jkrzy** [comment]
https://github.com/usdoj-crt/crt-portal/pull/515

**Comment by Jacklynn** [comment]
Not totally sure how to test this, but i submitted 3 reports in a row and didn't get any vowels

**Comment by blaughman** [comment]
Function works as intended.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/16
