### ISSUE TITLE
Image attributions

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#548]
Photo attributions: 
Unsplash: Jacob Le, Paul Stickman, Andre Hunter, Sobhan Joodi , Library of Congress
Pexels: Akela Photography, Nicholas Swatz, Asad Photo, Cottonbro
Flickr: Kelly Johnson Revolutionary Photography, The U.S. National Archives
Wikimedia Commons Public Domain
Cover art by Aviva Oskow

**Comment by AvivaOskow** [comment]
@lalitha-jonnalagadda here are the attributions! Also I feel kind of funny about including my name since we all worked on the site technically and no one else's name is on there so...maybe we should remove it haha

**Comment by lalitha-jonnalagadda** [comment]
@AvivaOskow - which page do these attributions need to be on? in the footer of the landing page or someplace else?

**Comment by AvivaOskow** [comment]
@lalitha-jonnalagadda None of the photos _require_ attribution, it's just an extra precaution/courtesy, so I think we can put it whever is convenient for us. I had previously suggested on the Privacy page? Or we could put it in small type on the bottom of the landing. If you don't think we should put it on the Privacy page I can mock up what it should look like on the landing.

**Comment by lalitha-jonnalagadda** [comment]
Small text on landing sounds good to me, but adding @blaughman for his thoughts

**Comment by cantsin** [comment]
![2020-06-17_10-00.png](https://images.zenhubusercontent.com/5eb05c8e896abe15ccf6dfa3/e63d44b9-d278-4602-840d-817e573a6659)

**Comment by blaughman** [comment]
@cantsin This looks great.

**Comment by AvivaOskow** [comment]
@cantsin Can you also change the header to "Image attributions" instead of "Photo"? 

## Mockup
![Screen Shot 2020-06-19 at 12.55.00 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/38328120-98f1-424d-baaf-fb5844f7896c)

## Annotations
**Background color:**  'gray-warm-90' # 171716

![Screen Shot 2020-06-19 at 1.58.36 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/776e0b7a-51a3-4a22-81c9-48c427965620)

**Comment by blaughman** [comment]
Attributions appear as directed.

**Comment by AvivaOskow** [comment]
Looks good @cantsin !

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/30.
