### ISSUE TITLE
Landing page edits

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#549]
# From Lalitha
- [x] Submitted in 'Already Submitted' should be in lower case
- [x] Under protected classes - **Sex, gender identity, and sexual orientation _including gender stereotypes_**  
   - Remove _including gender stereotypes_
   - Remove _Incluye estereotipos de género_ on the Spanish version
- [x] Primary issue drop down and the examples dropdown should be the same size 

![Screen Shot 2020-05-28 at 12.29.39 PM.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/71f80841-9f37-4285-a980-f15e52015074)

# From Aviva

- [x] **Hero image**: The image looks pinned to the left and gets cut off on the right when the screen resizes, can we change it so the image scales at full width instead? (Until the breakpoint for tablet, then switch to that image instead)

- [x] **contact 911 banner:** The text is stretching too far across the page (if it can stay within the 8 middle columns that would be good)

**Current**
![Screen Shot 2020-05-28 at 12.41.33 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/4c1a6f19-a9aa-4700-b841-c2e4fe418d2b)

**Should be** 
![Screen Shot 2020-05-28 at 12.47.46 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/aa51b353-32f6-4b77-bde6-ffd4195bba3c)

---

- [x] **"Understanding your rights"** headline should should be 45px not 32

- [x] **Examples Dropdown:**
    - Fix box size for drop down (Same as Lalitha's above)
    - Can the text within the examples box left align with the text in the dropdown above? Right now it's farther left

**Current**
![Screen Shot 2020-05-28 at 12.51.09 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/2448b5d2-51ab-44b2-9f26-a6211634d426)

**Should be** 
_I tried editing for 40px and I think it looks better_
![Screen Shot 2020-05-28 at 12.59.56 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/a20778fa-fc27-4efa-8214-4b6c6a1a54b4)

 **Protected classes column:** 

- [x] Can icon hang with first line instead of in middle of the header? (like how the circle numbers are doing in _How to file_ section below)

- [x] The font sizes are off, I included the annotations here below

**Current:**
![Screen Shot 2020-05-28 at 1.02.46 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/7a12f510-4771-4c74-a28e-c42fdf883eb5)

**Should be** 
![Screen Shot 2020-05-28 at 1.03.24 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/f1a4523f-6a01-4a52-8ff6-fdee2590b4b1)

**Font annotations**
![Screen Shot 2020-05-28 at 1.10.46 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/5a295ef3-62d0-4a93-9d8c-07d893e6ee39)

---

- [x] Need urgent help box needs more spacing at top

**Current**
![Screen Shot 2020-05-28 at 1.11.38 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/e737f958-526f-452e-a3fa-e05f5140ab45)

**Should be**
![Screen Shot 2020-05-28 at 1.14.46 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/06d1a637-8f48-4139-af23-098e3d78aeec)

_I also tried just doing it in the code, doing 24px on top and 32px on the side and it looks like this_
![Screen Shot 2020-05-28 at 1.16.25 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/26fc4a55-e7e8-45b0-8cbc-6f9970dbc190)

# From Jacklynn
- [x] Both legal aid links and the FBI link at the top are reading the icon name as part of the label and should not. Can we change to "external website" or, if that's hard just remove the icon part of the label (it's unlabeled on the USWDS site so following that pattern)
![Screen Shot 2020-05-28 at 2.35.22 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/24ebec56-b27e-4aed-8cfc-ecbd7058c755)
![Screen Shot 2020-05-28 at 2.35.34 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/1a7229b9-bdfd-42a3-a326-48ac6909032c)
![Screen Shot 2020-05-28 at 2.38.39 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/0287a39e-1803-44f1-8cd7-b738174df0e2)

**Comment by Jacklynn** [comment]
I added "Start report button is supposed scroll down to the "How to file a report" section, https://crt-portal-django-dev.app.cloud.gov/#report-a-violation"

**Comment by Jacklynn** [comment]
I noticed that the legal aid links were reading the icon in a screen reader, added above too,
