### ISSUE TITLE
Remove Assignee Name after closing record.

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#551]
## Narrative
As a member of the CRT team, I would not like to see complaints that are 'closed' assigned to me so that my backlog of complaints stays clear of records that need my attention

## Background
Assignee name should be cleared once the status moves to closed.  Otherwise, a large amount of data could be displayed if a user needs to work on open matters assigned specifically to them.

## Assumptions
- Closing a complaint will release ownership no matter who closes the record.

## Acceptance Criteria

1. Given that I'm on the complaint details page
When I change the status of a complaint to 'Close'
Then I see that the assignee field is now empty and is not assigned to a member of CRT

2. Given that I'm on the complaint details page
When I change the status of a complaint to 'Close'
Then the 'Closed date' is logged in the activity log 

3. Given that I'm on the view all table
When I filter complaints assigned to me
Then I only see complaints that are - 'Open' and 'New' status (becuase closed issues have automatically been un assigned)

## Technical notes
**Add closed_date to the Report model,** populate that when a record is closed
This will also help CRT track throughput for complaints

**Comment by blaughman** [comment]
@lalitha-jonnalagadda I just wanted to make sure it will release ownership no matter who closes the record.

**Comment by lalitha-jonnalagadda** [comment]
@blaughman - Yes anyone can close the complaint and its no longer assigned to anyone. Note: This change seems to apply on a going forward basis and doesn't fix the complaints in the history. @Jkrzy would it be possible to make this change backward compatible especially since we cannot remove an assignee manually? I can create a new card for that.

**Comment by Jkrzy** [comment]
Yes, we can update existing records in a data migration.

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/30.
