### ISSUE TITLE
Accessibility and styling tweaks for touchpoints

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#552]
## Narrative
As a user, I need text and links providing access to and information about the Touchpoints form to be readable and accessible.

## Background
We implemented Touchpoints in [#488](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/488) and identified two areas requiring styling and accessibility improvements. 

https://github.com/usdoj-crt/crt-portal/pull/500#issuecomment-634261585

## Acceptance Criteria
Touchpoints form footer text is legible and accessible
Link to open Touchpoints modal has adequate contrast

**Comment by Jacklynn** [comment]
is there a screenshot of the contrast updates?
