### ISSUE TITLE
Confirmation page: extra dash after address when only state filled

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#554]
I only entered a state and i noticed on the confirmation page there is an extra dash after it.
![Screen Shot 2020-05-28 at 3.00.30 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/9240112f-d188-46dd-a8e9-861783d8ce82)

**Comment by LindsayYoung** [comment]
The dash appears on the contact information because there is no zip code. 

Just to be clear, @Jacklynn you are asking, all missing data on the page should be represented by a dash, except for zipcode, which should be an empty string?

**Comment by Jacklynn** [comment]
ohhhh, I totally forgot about zip codes. 😅 It looked a little broke, but it also is a little (content) broken, I'll close!
