### ISSUE TITLE
The space between the title and "continue" text is too large

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#556]
On primary concern page:
![Screen Shot 2020-05-28 at 3.34.19 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/f3a293f7-8a0b-4831-b239-4eeecfa6b724)

**Expected spacing is 8px**
![Screen Shot 2020-05-28 at 3.35.16 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/305b3cfe-74a7-442c-b943-c5edef92967e)

**Comment by AvivaOskow** [comment]
This looks fixed
