### ISSUE TITLE
Hover state of landing page incident examples button low contrast

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#558]
Hover state on the button of the dropdown control results in low-contrast background color for smaller screen sizes.

Stemming from from `navigation.scss`, specifically  `.usa-nav__primary button, .usa-nav__primary button:hover`

### We'll know we're done when
Te hover state doesn't change modify background color for medium/small screen sizes.

### Current State
![Screen Shot 2020-05-29 at 8.24.36 AM.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/a184cf2b-4674-497a-ac65-fe8177b90736)

### Desired state
![Screen Shot 2020-05-29 at 8.25.47 AM.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/d2177b0c-fd99-450b-9ee5-a68ea18188bc)

**Comment by LindsayYoung** [comment]
It looks like this is fixed in staging and dev

**Comment by Jacklynn** [comment]
Low contrast problem fixed. 

I would expect it to have the same hover as the other dark blue buttons (like "submit a report"), but I think that can be fixed elsewhere.

The hover color on the other buttons is #1a4480
