### ISSUE TITLE
Mobile Design Fixes

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crt-portal#559]
### These are fixes that should be done before our next release on June 16th. 
_These are from an iphone X but I didn't check on every size_

# Landing page

## Header
- [x]  Logo is running into mobile menu button, can make the text for Civil Rights Division smaller (and Dept. of Justice a little smaller to keep the ratio the same?)

![Screen Shot 2020-06-01 at 12.59.26 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/8b31789e-c891-433b-8d48-5d05a529df87)

## 911 section
- [x] Is there a way to make 9-1-1 be on one line? Either making the paragraph length smaller so it breaks earlier or ...something else?

![Screen Shot 2020-06-01 at 1.00.28 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/049adba8-1310-48ca-9636-ff2c680c67c4)

## Protected classes section
- [x] Can the line on the left either be removed or be moved to above the "Protected" section like in the mockup? It also needs more space between the sections

**Current**
![Screen Shot 2020-06-01 at 1.05.31 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/6f15e681-2511-4099-b41d-b83943d2084f)

**Mockup**
![Screen Shot 2020-06-01 at 1.06.18 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/1ff7bc84-afbe-4044-831c-7c7f8f507c07)

## Urgent help box
- [x] Can the clock icon position be fixed so it aligns with the first line of the header?
![Screen Shot 2020-06-01 at 1.07.40 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/07d71f02-9fab-4933-9a87-4bb1c1dd7c9c)

# Form

## Progress bar
- [x] Line goes too far to the right
![Screen Shot 2020-06-01 at 1.30.27 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/9313c9e5-40e9-4bc2-baa9-dcddb0aeebca)

## Padding inside boxes
- [x] padding is too much, squishes everything in the middle. The "Need urgent help" box on the landing page shows a better version
![Screen Shot 2020-06-01 at 1.30.34 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/51baa132-4378-42b1-953c-a74acbc90155)

## Spacing on hate crime page

- [x] spacing issues
- [ ] **Radio button** is a square (not on other pages like location details)
![Screen Shot 2020-06-01 at 1.30.44 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/31752f5c-ba0b-48c2-acaa-08324e3f1276)

![Screen Shot 2020-06-01 at 1.33.28 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/5c5036f7-ca85-45fe-8a83-39ea972e1c6d)

## Location details
- [ ] Second line of radio buttons are off
- [x] State is too close to city/state

![Screen Shot 2020-06-01 at 1.31.16 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/5c605f40-be1c-4d50-afce-f7505d1cac61)

![Screen Shot 2020-06-01 at 1.31.42 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/7536f70f-4bba-4227-8047-b0400dda7b5c)

## Review page

- [x] Edit button is too close to the header, it should go at the bottom of the card instead
![Screen Shot 2020-06-01 at 1.32.03 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/4cde3054-82a7-4833-aab2-2f9b0b2bbadc)

## Confirmation page

- [x] Checkmark icon is too far to right
- [x] Record number should be on one line (this should be fixed by the padding issue
- [x] Second line of bullet points isn't aligned (this should be fixed from the desktop version
- [x] Numbers in circles for headers should be aligned with the first line, instead of the middle (should be fixed from the desktop version also)

![Screen Shot 2020-06-01 at 1.32.12 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/bbd8db97-efa0-4b31-89fe-8e43837b62e7)

![Screen Shot 2020-06-01 at 1.32.20 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/7a369e2b-3062-45ce-a96f-0ba44a612f79)

**Comment by AvivaOskow** [comment]
# Here are the annotations for mobile form, using the [contact](https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/84) and [primary concern](https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/85) pages as examples

@hbillings

**Comment by AvivaOskow** [comment]
@hbillings @cantsin can we also use the same "logo" from the landing page on the form now? I think it's a weird inconsistency to have them different (sorry to not point this out earlier)

### Landing logo (let's use this one)
![Screen Shot 2020-06-08 at 6.36.59 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/d239fad0-f1ef-4ab7-8bd8-708fce16f622)

### Form
![Screen Shot 2020-06-08 at 6.37.08 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/1d28d271-3b0e-4a60-973f-25a411c53b7b)

**Comment by blaughman** [comment]
@hbillings @Jkrzy @cantsin @lalitha-jonnalagadda 

![Mobile Issue 1.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/31a3d437-dc92-4963-bf9b-871fd9e6997b)

**Comment by blaughman** [comment]
@hbillings @Jkrzy @cantsin @lalitha-jonnalagadda 

![Mobile Issue 2.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/6c866015-1d7d-4f8e-bbea-a3c95f58047d)

**Comment by blaughman** [comment]
@hbillings @Jkrzy @cantsin @lalitha-jonnalagadda 

![Mobile Issue 3.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/796dd207-c28d-48a6-b27e-2a5ad862fe9e)

**Comment by Jacklynn** [comment]
- [ ] Mobile header is out of place, low contrast for text. I think this was from some of the hero images changes we made too.
![image](https://user-images.githubusercontent.com/2560618/84685617-6ef22080-aeef-11ea-8c7f-a9e8bbcf3c9b.png)

**Comment by cantsin** [comment]
The mobile-header-being-out-of-place issue exists in production too :(

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/16
