### ISSUE TITLE
Ability to create custom email response templates 

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#560]
## Narrative

As an intake specialist, I would like to create custom email response templates in case of 'hot button issues' arising that need a quick and custom response so that the complainant's can be responded with these custom responses asap

## Assumptions

- Only 'super admins' (may be Imran and Bill for now) are able to create these custom templates 
## Acceptance Criteria

1. Given that I'm in the Django admin interface
When I select creating a new form letter template
Then I'm able to provide a name for the template
AND 
I'm able to enter a body for the response template

2. Given that I'm on the contact correspondent pop up screen
When I click on the template type drop down
Then I see the new custom template that was created 
AND
I'm able to select and view the content of the template
AND
I'm able to Copy/Print (and with future functionality, be able to Send) the content of the template
AND
I'm able to view the action taken reflected on the activity log

**Comment by blaughman** [comment]
@lalitha-jonnalagadda This looks good.

**Comment by blaughman** [comment]
Deployed 7/14/20 closing card.
