### ISSUE TITLE
IE link to redirect to edge for CRT. 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#561]
John did this one. It will help sections have a better experience on the backend because they won't run into IE issues. 

Someone on the CRT network can confirm this is done by going to https://crt-portal-django-prod.app.cloud.gov/ in IE, it should open it in edge.

**Comment by blaughman** [comment]
Function works as intended.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/16
