### ISSUE TITLE
Spanish translations by 6/12

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#563]
## Proposed changes

- [x] Latest version of Spanish translations are in this doc - https://docs.google.com/spreadsheets/d/1ZX-IKH6_uJQLEq20G33Yva3RwC8PZccKR1fkS9r8BJw/edit#gid=1416703596
  - Worksheet 6-12 tab has all the edits highlighted in green/yellow. 
  - Please see column F for all collective edits. 

#### Version History

Previous edits for future reference if needed:

- [ ] Include Spanish translation edits provided by Marta (edits in column F)- 
(this doc has the english edits clearly marked)
https://docs.google.com/spreadsheets/d/1V2NRBTdG5IRt3nP3L_cxPSKGQ5qbg_YmVxyIPMeV8sI/edit#gid=1727821174

- [ ] Round 2 of Spanish edits will be made available by 6/12 that need to be incorporated before the next prod deploy. 
(this doc is the latest spanish edits)
https://docs.google.com/spreadsheets/d/16WGJxyH2du82iqF6cLCm1dFupjkE4YjF_czKKhnuHXQ/edit#gid=2072764893

**Comment by LindsayYoung** [comment]
I am going to work on Mara's first round of edits.

**Comment by Jkrzy** [comment]
Implemented a handful of these in https://github.com/usdoj-crt/crt-portal/pull/537.

There I noticed this cell was previously empty and needs a translation update: https://docs.google.com/spreadsheets/d/1ZX-IKH6_uJQLEq20G33Yva3RwC8PZccKR1fkS9r8BJw/edit#gid=1416703596&range=B366

**Comment by lalitha-jonnalagadda** [comment]
@Jkrzy just want to make sure if you got the edits from the worksheet labelled 6-12? That sheet has the latest and greatest edits in column F. Can you please confirm?

**Comment by lalitha-jonnalagadda** [comment]
@Jkrzy - Updated line 366 with the Spanish translation in column F in your document - https://docs.google.com/spreadsheets/d/1ZX-IKH6_uJQLEq20G33Yva3RwC8PZccKR1fkS9r8BJw/edit#gid=1416703596

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/16
