### ISSUE TITLE
Landing page: Add Hate crime & humantrafficking examples to the drop down

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#564]
Want to add the last two primary issues from the "Primary issues continued" page to the landing page interaction:

### [Text here (starting line 336)](https://docs.google.com/spreadsheets/d/1ZX-IKH6_uJQLEq20G33Yva3RwC8PZccKR1fkS9r8BJw/edit#gid=1416703596)

# Updated examples drop down

### Added the last two, "Victim of a hate crime" and "Victim of human trafficking"

![Screen Shot 2020-06-10 at 5.45.18 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/16f6b4e5-9a03-4536-aae8-41c3aa863664)

![Screen Shot 2020-06-10 at 5.51.05 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/6503f403-eca3-4eef-b2f7-a345e2518931)

### Type + spacing annotations in [this ticket](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/564) (but using the old copy)
![Screen Shot 2020-06-08 at 1.31.32 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/2d3483c8-8ea4-4468-aef6-cbc949a58462)

## Old
![Screen Shot 2020-06-08 at 1.28.22 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/6b9826b0-0046-45fa-817b-e0fd17e9495d)

**Comment by Jacklynn** [comment]
@lalitha-jonnalagadda @blaughman Dan got more CRM approval today and he's updated the doc to reflect the changes they've requested.

**Comment by blaughman** [comment]
Content looks good.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/16
