### ISSUE TITLE
Update civilrights.justice.gov page title

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#566]
Currently the page title is: 
`Civil rights Division - Department of Justice`

This implies that this is the main page. I think it should show that this is just about filing a report. Maybe something like:
`Contact the Civil Rights Division | Department of Justice`

To match the pattern on the form following: _Step 1: Contact | Contact the Civil Rights Division | Department of Justice_

(for what it's worth, the DOJ is using `|` instead of `-` like we have today 

![Screen Shot 2020-06-03 at 11.56.18 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/4ebc8c5d-ed44-48f5-9411-27f440d00c24)

**Comment by cantsin** [comment]
After looking at this, I _think_ we don't need spanish updates, but we might have to update the Django messages file nonetheless (I'm guessing it will do a fuzzy match).

**Comment by harikrishnagit** [comment]
@cantsin beat me to it.

**Comment by harikrishnagit** [comment]
I think we'll need spanish conversion to "Contact the Civil Rights Division"

**Comment by blaughman** [comment]
Moving to UAT.

**Comment by blaughman** [comment]
Function is correctly displaying on Prod.  Closing card.
