### ISSUE TITLE
Add toll free number in the footer

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#567]
@blaughman - can you please add the number to this card

**Comment by blaughman** [comment]
1-855-856-1247

**Comment by cantsin** [comment]
Do we want this to _replace_ the current phone number -- (202) 514-3847 -- or add this below the current phone number, along with a `(toll-free number)` tag?

**Comment by blaughman** [comment]
@cantsin @Jkrzy We want this below the current phone number with a toll-free number tag.  Thanks.

**Comment by blaughman** [comment]
Updated and correct.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/16
