### ISSUE TITLE
Update Social Media Images

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crt-portal#569]
### When we updated the Hero text for the landing page on 6/16, we need to decide if we want to update the messaging for social as well.

- [ ] **Due:** in time for 6/16 release

- [ ] Team needs to decide on the messaging direction

- [ ] @AvivaOskow needs to update the final images to share

## Current social text:
_(Matches first release)_

**Have you or someone you know experienced unlawful discrimination?** 
The Civil Rights Division may be able to help. Visit civilrights.justice.gov to learn more.

![CRT_Twitter.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/d89082fc-b4f6-4be9-94b0-70dca93044f3)

## Option 1
**We uphold the civil rights of all people in the United States.**
I**f you believe your civil rights, or someone else’s, have been violated, submit a report using our online form.** 
Visit civilrights.justice.gov to learn more.

![CRT_Twitter Copy.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/e6a2e110-3806-44ae-9126-e4b530ef1aed)

## Option 2

**Do you believe your civil rights have been violated?**
The Civil Rights Division may be able to help.  We uphold the civil rights of all people in the United States. 
Visit civilrights.justice.gov to learn more.

![CRT_Twitter Copy 2.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/2b4e3f1b-6b73-42ef-9ff4-88ee32e10d71)

# Considerations
If we want to have the social match the new hero text exactly, then the new Option 1 is best, but we could also keep the original or use Option 2—both of these are more advertisement feeling - asking a question that pulls the reader in. If the point is to get people to check out the site, one of those might be better. 

# Reference
This is what the image looks like when shared on Twitter for example
![Screen Shot 2020-06-04 at 3.05.41 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/e839d6e0-e3ae-497b-ade9-ac99082a1497)

**Comment by Jacklynn** [comment]
I kind of like optional 1 better for a consistent message, but I don't have strong feelings. 

I actually always thought that the thumbnail was exactly the same landing page, so I learned something new. I thought when the title from the post and page were different they forgot to update one or the other ¯\_(ツ)_/¯.

worth pointing out that the text paired with would ask a question too (as your screenshot includes)
_Have you or someone you know experienced unlawful discrimination? The Civil Rights Division may be able to help. Civil rights laws can protect you from unlawful discrimination, harassment, or abuse in a variety of settings like housing, the workplace, school, voting, businesses, healthcare, public spaces, and more._

**Comment by danielhyi** [comment]
* Option 1 i feel like might get co-opted in problematic ways when circulated on social.
* Option 2 is good as far as text, but the civil - rights spillover from first to second line isn't ideal

**Comment by danielhyi** [comment]
Also, FYI, anything that is planned for social we'll have to ultimately clear with OPA (who is generally risk averse on this front, though Ashley has gotten them to open up a bit more)

**Comment by Jkrzy** [comment]
We're ready to implement this, @blaughman, @jacklynn can you confirm which of the images above should be used?

**Comment by Jacklynn** [comment]
Dan votes for option 2!

**Comment by Jkrzy** [comment]
Thanks! Waiting on updated source images from @AvivaOskow.

**Comment by AvivaOskow** [comment]
@Jkrzy I don't think any action is needed on this actually. We already updated the image back when we had to switch out one of the photos, and @danielhyi said he felt good about keeping the original messaging, so I don't think we need to update again.

**Comment by lalitha-jonnalagadda** [comment]
No changes anticipated with this card. Closing!
