### ISSUE TITLE
Know that DOJ CRT can't help me

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#57]
## Narrative
As a \<type of user\>, I want \<a goal\> so that \<benefit\>. 

## Background
:add business context to help us better understand the story:

## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Mockups / Wireframes
![image]()

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by lalitha-jonnalagadda** [comment]
Closing this card as we are handling this use case with the submission page, landing page and hopefully with rerouting
