### ISSUE TITLE
Trend tracing prototype

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#571]
This creates a view at /form/trends

It displays data to show the top 10 words for: this week, last week, the past four weeks and year to date.

- The table lists the words, document count, word count.
- The words link to the matching records.
- There is an explanation of the methodology and why search results and document counts might not be the same.

### Methodology 
Document count is the number of complaints that the word appears in. Word count is the total number of times that word appears.

The data is based on creation dates. Time periods start on Sunday, except for year. The cutoff is midnight GMT.

There my be variations in the document count and search results. For the search, results will be shown for variations on a word, so "pet" and "pets" will show up on the view all table if you search for "pet" or "pets" in the description. The counts on this page are using exact word matches, so "pet" and "pets" will be counted separately. Capitalization is not a factor when searching or counting so searching "Pet" will not be different than "pet". The counts for this page are also optimized for English characters.

**Comment by blaughman** [comment]
Function appears to be working.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/16
