### ISSUE TITLE
Update color behind hero image on desktop/tablet

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crt-portal#572]
#### Because the hero image is using a slightly different blue background (due to the gradient in the image), the blue-warm-5 behind the image is visible when resizing the browser (see screenshot)

It's a small detail, but if we can change the background color, we don't need to re-upload the image (I could do a slight gradient at the top of the image so it fades into the light blue)

@cantsin @hbillings Let me know which is better, changing the background (just in this one spot) in dev to #E9EEF5 (not a USWDS color) or for me to add the gradient in photoshop we re-deploy the image?

**Screenshots**
![Screen Shot 2020-06-04 at 12.15.14 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/256f603b-b5ce-43e1-86cf-36c5233f8854)

![Screen Shot 2020-06-04 at 5.40.39 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/196368f6-26b3-4288-a93d-cb23505a8e4c)

**Comment by cantsin** [comment]
@hbillings did this work -- moving to dev done

**Comment by blaughman** [comment]
I resized by browser window and issue appears to be fixed.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/16
