### ISSUE TITLE
Offboard Lindsay

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#573]
## Definition of done
- Remove accounts
   - [x] 18F CRT GitHub team (circle and zenhub access are connected to GitHub)
   - [x] CRT GitHub @dwechsle
   - [x] cloud.gov
   - CRT site accounts
      - [x] dev
      - [x] stage
- [x] Update [accounts tracker](https://docs.google.com/spreadsheets/d/1VM5hSsxUgqFM6t51Ejm_EjxnbxLI-pTXF_CVxZJSekQ/edit#gid=0)

**Comment by Jkrzy** [comment]
18F off-boarding complete.

@dwechsle please remove from https://github.com/orgs/usdoj-crt/teams when you're able. Thanks!

**Comment by dwechsle** [comment]
offboarded from github
