### ISSUE TITLE
Filter by service members [URL only] 

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#577]
## Narrative

As an intake specialist, I would like to filter the complaints on the view all table by selection made to the service member selection so I can view only complaints where the answer is Yes (or No)

## Assumption

- for this card, no front end work is expected. We want to be have a quick fix where we have the ability to filter based on a custom URL that will show filtered data
- There need to be changes to the backed to collect and track data for servicemember = Yes(or No)

## Acceptance Criteria

1. Given that I'm in the intake portal
When I submit a custom URL (TBD) 
Then I'm able to see only complaints where service member selection is Yes(or No)

**Comment by Jkrzy** [comment]
@blaughman 

Enables filtering by `Report.servicemember` by providing a servicemember URLparameter directly in the address bar. 

Example:
https://crt-portal-django-dev.app.cloud.gov/form/view/?servicemember=yes

**Comment by blaughman** [comment]
URL works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/16
