### ISSUE TITLE
Bug in Edge with assignee filters

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#580]

**Comment by Jkrzy** [comment]
I've been unable to replicate this locally with Edge 44.17763.1.0.

Autocomplete is working as expected for me. @cantsin, can we pair and take a look on your VM? I think you mentioned previously that you were able to replicate it.

**Comment by cantsin** [comment]
I can replicate. Happy to pair with you (or maybe someone from Trillion). Last I looked, the library (https://github.com/alphagov/accessible-autocomplete) was at fault here -- the first click does not "register" (does not set the `selected` attribute). A workaround: once the user is selected, clicking outside of the dropdown, and trying again _does_ work. 

Maybe we should disable this library when using Edge.
