### ISSUE TITLE
When you return to the "personal characteristics" page from the review page, the other reason is collapsed

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#584]
If I filled out an other reason, and want to change it, when i return to the page the "other reason" box isn't expanded. I have to uncheck and re-check to open it again (with content) which some users might not figure out. 

Steps to repo:
1. On the personal characteristics page, check other reason and fill something out, ex: "chameleons are cute"
2. Continue filling out form until you get to the Review page
3. Click "Edit this page" button next the Personal Characteristics card. this will take you to the Personal characteristics page
4. Observe that the "Other" field is collapsed. (Chrome, in dev)

![Screen Shot 2020-06-10 at 2.06.34 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/2ed6f01d-22c8-4fe4-8d24-d9883ae15d7c)

**Comment by blaughman** [comment]
Bug has been fixed.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/30.
