### ISSUE TITLE
[mobile] back & next buttons on the form are overlapping

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#586]
On dev with chrome.

This starts on step two since there isn't a back button on the contact page and persists throughout the form. I can accidentally tap "back" if i touch the center of the button

![image.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/3dda253f-31b7-44ce-9956-b9a3bf677b43)

**Comment by blaughman** [comment]
Form (buttons included) looks fine in Safari.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/16
