### ISSUE TITLE
Investigate creating pagebreaks (or similar) in Drupal webforms

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#59]
## Narrative
As a public user, I want to fill out a user friendly form that breaks up content so that it's not overwhelming while I'm trying to report my issue.

## Background
There should be a better way to create breaks in the questions that don't show up in the progress bar at the top (which are created by creating Pages in Drupal webforms), but I can't seem to find it. 

## Assumptions
Ex: We want to break up "What happened" and the "protected classes" question because they're both relatively long lists. 

## Acceptance criteria
- [ ] Time boxed investigation of why it might not be working in our current drupal instance (benevolent-bunny-3).  (Would love for public user testing!)
- [ ]
- [ ]

## Mockups / Wireframes
![image]()

## Technical Notes
- [ ] I found example documentation here: https://www.drupal.org/node/324779
- [ ]
- [ ]

**Comment by lalitha-jonnalagadda** [comment]
Closing this card as we aren't using Drupal for the implementation anymore.
