### ISSUE TITLE
Review/Confirmation page - card padding gone the complaint summary cards

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#590]
Noticed a regression where the card padding on the review/confirmation page got smaller. 

Seeing smaller padding around the card content:
![Screen Shot 2020-06-11 at 3.03.36 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/ed0959c9-fd68-4b00-9997-2d513b569a42)

Expect normal card spacing:
![Screen Shot 2020-06-11 at 3.22.25 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/69d9328e-a41e-48a3-9d0c-b4a02f8d44fe)

Full screenshot:
![image.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/f4b9a470-b9b4-4a8e-a2a2-0c8198255304)

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/16
