### ISSUE TITLE
[form letter] If no name (or not first name) use gender neutral salutation

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#593]
We wanted to move away from "Dear sir/madam" for the DOJ correspondence but it didn't make it into the first version.

Logic expected: 
Provided first and last name: `Dear John Doe`
Provided first name: `Dear John`
If no first name: `Thank you for your report`
If no first or last name: `Thank you for your report`

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/30.
