### ISSUE TITLE
[URL] Filter by hate crime 

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#594]
## Narrative

As an intake specialist, I would like to filter the complaints on the view all table by selection made to the hate crimes question so I can view only complaints where the answer is Yes (or No)

## Assumption

- for this card, no front end work is expected. We want to be have a quick fix where we have the ability to filter based on a custom URL that will show filtered data
- There need to be changes to the backed to collect and track data for hatecrime = Yes(or No)

## Acceptance Criteria

1. Given that I'm in the intake portal
When I submit a custom URL (TBD) 
Then I'm able to see only complaints where hatecrime selection is Yes(or No)

**Comment by Jkrzy** [comment]
There were some economies of scale here, small added lift so I went ahead and included `modified_date` and `closed_date` as filterable fields.

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/30.
