### ISSUE TITLE
Include a blurb into footer privacy policy

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#599]
- [ ] include the following blurb into the footer privacy policy on the form

**The full list of routine uses for this correspondence can be found in the System of Records Notice titled, JUSTICE/CRT – 001, "Central Civil Rights Division Index File and Associated Records", 68 Fed. Reg. 47610, 611 (8-11-2003); 70 Fed. Reg. 43904 (7-29-2005); 72 Fed. Reg. 3410 (1-25-2007) (rescinded by 82 FR 24147); 82 Fed. Reg. 24147 (5-25-2017).**

- [ ] Include a Spanish version of this blurb into the footer on the Espanol page. Translations:

La lista de usos rutinarios para esta correspondencia se encuentra en la Notificación del Sistema de Registros bajo el título JUSTICE/CRT – 001, "Central Civil Rights Division Index File and Associated Records", 68 Reg. Fed. 47610, 611 (11-8-2003); 70 Reg. Fed. 43904 (29-7-2005); 72 Reg. Fed. 3410 (25-1-2007) (rescindido por 82 FR 24147); 82 Reg. Fed. 24147 (25-5-2017).

**Comment by blaughman** [comment]
Blurb is now there.

**Comment by blaughman** [comment]
Deployed 7/14/20 closing card.
