### ISSUE TITLE
Submitting an empty `Comment` form produces a server error

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#601]
When a user submits an empty Comment form, the server returns a 500 error. 
Any changes made to other forms on the page are lost.

Steps to reproduce:
1. Navigate to a report details page
2. Click the `submit` button below the `New comment` form without entering any characters into the input field.

I suggest we rename the `submit` button to more clearly indicate the functionality. Maybe `Submit comment`

We should also disable the button unless there is text entered into the associated form.

**Comment by blaughman** [comment]
Trying to save without a comment now produces an error on the complaint details page and does not let the user save a blank comment.  Moving to UAT.
