### ISSUE TITLE
Trends dashboard taking too long to load

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#603]
- the new trends page throws an error when we try to access it on prod.
  - The current hypothesis is that its due to the performance issues on data load

**Comment by Jkrzy** [comment]
I believe this is failing when we hit the default timeout for gunicorn (30 seconds). The most immediate intervention would be increasing the timeout to 45 or 60 seconds.

**Comment by cantsin** [comment]
Do we have any logs that indicate we are hitting the gunicorn timeout? I agree that we can bump up to 60s safely for the short term.

Maybe we can leverage locust here and do some load testing on the trends page.

**Comment by Jkrzy** [comment]
Yea, it's showing a bit in the logs -- cloud.gov router returns 502 after ~30 seconds

e.g. `502 GET /form/trends/ (31564.585 ms)`

https://logs.fr.cloud.gov/goto/9754b7c9f1467761b44d00bc1f6836bd

**Comment by Jkrzy** [comment]
@lalitha-jonnalagadda, @cantsin, this isn't in  the release branch for today's release. It's only on development at the moment. 

https://github.com/usdoj-crt/crt-portal/commit/8dab0eea6fe06a5002b815fdee475247f3704d5f

We _can_ pull it in there but want to confirm that is desired since its outside our normal flow.

**Comment by cantsin** [comment]
This is not part of today's release, no.

**Comment by cantsin** [comment]
Not part of the release today, unless I missed something. We may want to hotfix this feature if we want this in sooner rather than later.

**Comment by blaughman** [comment]
Function is working and now in prod.  Closing the card.
