### ISSUE TITLE
Address 1 and Address 2 fields being cleared when editing reported complaint section

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#605]
## Current Behavior

-  Given that a complaint has incident address 1 and address 2 populated 
When an intake specialist tries to edit this complaint (Ex:to update the summary field)
AND 
Saves the edits
Then in the activity log, we are seeing that the Address 1 and Address 2 fields are being updated to 'None' aka, the incident address data is being cleared/removed

## Expected Behavior

-  Given that a complaint has incident address 1 and address 2 populated 
When an intake specialist tries to edit this complaint (Ex:to update the summary field)
AND 
Saves the edits
Then in the activity log, we are seeing that the Address 1 and Address 2 fields are preserved
AND
All the edits are saved

## Notes

- Address 1 and Address 2 fields should only be edited when the user explicitly edits these fields

**Comment by blaughman** [comment]
Bug has been fixed.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/30.
