### ISSUE TITLE
Adding section specific form letter responses 

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#609]
## Narrative

As a section intake staff, I would like to choose section specific form letter response so that I can reply to the user with an appropriate and catered response from my section

## Assumptions

- This card requires adding 4 new form letters:
- [ ] CRT - Comments & Opinions
- [ ] CRT- Request for Agency review
- [ ] HCE - Referral for Housing/Lending/Public Accommodation
- [ ] SPL - Referral for PREA issues

- Tables in these form letters should be rendered while copying the response
- Subject lines for these response templates should follow similar to #570

## Acceptance Criteria

1. Given that I'm on the complaint details page
When I click on 'Contact Complainant' 
Then in the response template drop down, I now see section specific templates
AND
Templates are named in the drop down as: Section Abbreviation - Template name (ex: HCE - No Jurisdiction)

### Accessibility 👻🧐🌟
- Should be able to access all fields from keyboard
- Fields should read out for visual 
- Select field by enter/space
- Focus, the field is highlight
- visit inputs in a logical tab order
- Can zoom 200% without the page breaking?
- Reflow content at 400%/mobile

**Comment by blaughman** [comment]
Function works as intended in Chrome and Edge.  Moving to UAT.

**Comment by blaughman** [comment]
Deployed 7/14/20 closing card.

**Comment by lalitha-jonnalagadda** [comment]
Reopened as this doesn't seem to be on prod. Scheduled for the deploy on 7/28

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 7/20 cc @blaughman
