### ISSUE TITLE
Set up monitoring (eg New Relic)

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#61]
@ilodidoj is researching this. We are waiting on permission but we want implementation to be ready 

## Technical Notes
- New Relic for Python overview https://docs.newrelic.com/docs/agents/python-agent/getting-started/introduction-new-relic-python
- Install instructions: https://docs.newrelic.com/docs/agents/python-agent/installation/standard-python-agent-install

**Comment by Jacklynn** [comment]
12/10
- Lindsay: not 100% required for ATO. something that is best practice for finding issues proactively. Waiting for DOJ, won't be able to review until Januar

**Comment by LindsayYoung** [comment]
@imran has made progress on this but we can't implement till the waiver is in

**Comment by Jkrzy** [comment]
@ilodidoj and I are going to move forward with a pilot implementation on dev.

**Comment by Jkrzy** [comment]
New relic is up and running on staging and development.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/30.
