### ISSUE TITLE
Pin uswds-gulp version

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#611]

**Comment by harikrishnagit** [comment]
https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/611

**Comment by cantsin** [comment]
Nothing to be done here for UAT (internal dependency change only)

**Comment by blaughman** [comment]
Deployed 7/14/20 closing card.
