### ISSUE TITLE
Removing assignee from existing records which are closed

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#613]
This is a follow up card from #551. #551 tackles removing an assignee from a report when its closed. 

This card is to clear assignee from all past 'closed' records prior to 6/30 on production

**Comment by Jacklynn** [comment]
@lalitha-jonnalagadda @blaughman did you still want to implement this given the feedback from deep dive about tracking?

**Comment by Jkrzy** [comment]
If the answer to Jacklynn's question above is Yes -- Let's do this with a data migration to iterate through all `closed` reports and set their assignee value to None, making sure to update the activity log for each.

**Comment by harikrishnagit** [comment]
@Jkrzy I'll need some help if you think our team should take this up.

**Comment by harikrishnagit** [comment]
@cantsin @ilodidoj , Found a way to test this fix. I'll be happy to setup a demo call. Pls let me know what works. BTW, I spoke to James, this is FYI Imran.

**Comment by blaughman** [comment]
@cantsin @ilodidoj @randyabramson I tested this in both dev and staging.  Record 268 in dev and Record 385 in staging still have assignee's even though they are closed.  In prod, record 23 still has an assignee.  If this hasn't been deployed in any environment, I can't really test the function to move it to UAT.  Please advise.  Thanks.

**Comment by ilodidoj** [comment]
@blaughman @randyabramson @harikrishnagit @cantsin , this should be in Dev for this to go on staging release.  Please note it only effects those records that have **report.closed_date is not None and report.closed_date < july1.**  You will see changes in staging once deployed.

**Comment by cantsin** [comment]
@harikrishnagit can you please take over reviewing this feature in dev (and staging, when we release later today) and confirm the migration works as intended? Maybe as part of the post-release-to-staging process? dev:268/staging:385 seem like good candidates to check.

**Comment by harikrishnagit** [comment]
@cantsin will do.

**Comment by blaughman** [comment]
Deployed to Prod on 8/18/20.
