### ISSUE TITLE
Set focus when opening modal

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#614]
When opening the modal for `contacting complainant`, or any other modal, we should set the focus inside of the modal. 

When navigating via keyboard a user should be able to immediately interact with the modal after opening without having to tab through the remainder of the page.

### Implementation notes
I think we could do this right in modals.js's `openModal` function.

**Comment by blaughman** [comment]
Function works as intended.

**Comment by blaughman** [comment]
Deployed 7/14/20 closing card.
