### ISSUE TITLE
Design Audit: Some headings on mobile not using correct headings

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crt-portal#617]
#### **Current**
![Screen Shot 2020-07-02 at 1.30.07 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/977fd8e6-c84b-4a67-bdd3-8c0844595412)

#### **Should be**
![Screen Shot 2020-07-02 at 1.33.49 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/e2705736-be44-47f5-b2cc-ca0fb436b630)

#### **Current**
![Screen Shot 2020-07-02 at 3.57.07 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/51613224-0b91-4664-b0e4-88f2fb77d5b8)

## Should be
![Screen Shot 2020-07-02 at 3.58.35 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/238a5e84-ac0e-4950-ab2a-957841eaefc5)
----

# For reference, here are the desktop to mobile Display and H conversions:
![Screen Shot 2020-07-02 at 1.57.35 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/7d4181d1-e627-4a35-9032-0b34c634abef)

### Annotation Key
![Screen Shot 2020-07-02 at 4.01.41 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/8406453b-8aa1-4f24-80f7-99c2c95feab3)

### Full annotations
![Artboard.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/1d2e54b7-d38e-4b77-a1c7-85a4b23b950e)

**Comment by hbillings** [comment]
@AvivaOskow Hrm, I'm perplexed by examples 1 & 2. I tied the display levels with their respective mobile heading levels via classname, so that `h1__display` has a mobile value of `32px` and a desktop value of `45px`. The Firefox inspector is telling me that those headings are picking up the `32px` size, which seems correct? Maybe when we correct the other items, they'll look better? Or could this perhaps be a spacing issue, and the heading in the hero isn't taking up enough vertical space because it's too wide?

**Comment by AvivaOskow** [comment]
@hbillings could be a line length issue for some...can you check what the Mobile H2 is? Like the paragraph under "How to report a civil rights violation" looks small to me (should be 24px). If that one is correct, it's probably the spacing/width, not the actual font sizes. Thanks!

**Comment by AvivaOskow** [comment]
@hbillings so it looks like the Display ones are correct but that some of the Hs are pulling the wrong class. Do you want me to grow through and figure out which exact ones or do you think you have enough info to go off of? Let me know what's helpful!

**Comment by hbillings** [comment]
@AvivaOskow thanks so much for this! So I suspect what's going on is that the things that are showing up as _looking_ like Mobile H1s are actually... not. haha. Question for you: when those same pieces of text are at full-screen, should they inherit regular H1 styling?

I don't think you need to go through and point them all out precisely, but I did want to make sure I wasn't losing my mind with the Display H1s!

**Comment by randyabramson** [comment]
@hakhalid11 I'm using the Android emulator and the text looks the same as it does in the 'current' grabs above and not the 'should be'. Example grab attached for the 'we uphold the civil rights...' text.![we-uplhold-civil.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/fcdf9693-80f1-4740-a1ac-223021df90f5)

**Comment by hakhalid11** [comment]
@randyabramson as Heather and Aviva brought up above some headers already have the correctly applied font-size and line-height so they won't appear to be changed. However, to give you an example of what this card changes you can compare dev and staging screenshots below. 

**DEV**
![image](https://user-images.githubusercontent.com/66343959/91864309-10ab2300-ec3e-11ea-9501-02fbd652cffd.png)

**STAGING**
![image](https://user-images.githubusercontent.com/66343959/91864463-346e6900-ec3e-11ea-8553-db92ccb42f43.png)

As you can see the paragraphs below the header have different fonts and line-heights. As heather and Aviva brought up the main issue with mobile fonts seemed to be subheading and other headers that needed to be changed.

**Comment by randyabramson** [comment]
Ah, @hakhalid11 thanks...it's very subtle for sure! I will put these side by side and hopefully move this to UAT complete.

Randy
