### ISSUE TITLE
Design Audit: Update spacing on Mobile Landing page

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crt-portal#618]
### All of the spacing was not previously defined before, so here are some more specifics to improve the readability of the landing page on mobile, and here are the [full spacing annotations](https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/81) for reference. 

_I'm not pointing out every change in this card, just trying to point out some standards that should apply across the board, to see full page annotations, click the link above)_

_Additionally, it seems like the mobile isn't pulling the correct heading sizes for mobile. [Here](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/617) is a separate issue with the correct mobile sizes._

#### Some standards

- On desktop, we use 72px padding for top/bottom of each section, **on mobile we can do 48px for main sections, and 32px top, 48px bottom for sub-sections** _(ex: sections that follow the down arrow caret—"Choose from this list to see example civil rights violations" and "Think you or someone you know has experienced a civil rights violation?" sections)_

- Space **between section paragraphs should be 40px** _(Ex: About the division and How to report sections)_

- **Padding within cards should be 24px on all sides** _(Ex: Violation examples dropdown and "Need urgent legal help" cards)_

#### Currently the paragraphs run too close together and make it harder to scan
![Screen Shot 2020-07-02 at 12.42.48 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/7c8a383a-002d-4005-bdf6-d22bd046602b)

#### Change to:
![Screen Shot 2020-07-02 at 12.41.47 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/4c64d808-6946-4d3b-b6c5-b0f6c1d72344)

## How to report section
![Screen Shot 2020-07-02 at 1.44.09 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/ccb67fd4-95d0-468b-bbbc-818a03e65241)

## Example sub section spacing (ones that follow the caret)
![Screen Shot 2020-07-02 at 1.45.29 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/519da091-7fa9-47cf-8188-c7438f47747f)

## Example card spacing
![Screen Shot 2020-07-02 at 1.46.53 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/c7df094c-0912-4d6b-9556-d0e0c1a60d5a)

![Screen Shot 2020-07-02 at 1.47.50 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/89cdb707-4d4e-47e8-b44c-8a691120d6fa)

**Comment by randyabramson** [comment]
Tested this on Android emulator and iOS. Good to go.
