### ISSUE TITLE
[view all table] Incident location stays bold when status is not new

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#624]
**Expected:**
A record row is bold when the status is new. For any other status, the text of the row is not blue.

**Issue:**
The "incident location" remains bold when the status changes
Example: 
![Screen Shot 2020-07-09 at 11.26.32 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/cc3fe605-c454-406e-8b97-1005baf08be9)

**Comment by Jacklynn** [comment]
This was fixed in dev for me, thanks!

**Comment by blaughman** [comment]
Incident location is no longer bold on Prod.  Closing card.
