### ISSUE TITLE
Form letter functionality tweaks

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#625]
1. Change the template names as follows:
 - [x] Non Actionable to **CRT -Non Actionable**
 - [x] No Capacity to **CRT - No Capacity**

![Screen Shot 2020-07-09 at 11.40.13 PM.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/33b84b76-8b37-4aef-96b8-2a81cc18cdb8)![Screen Shot 2020-07-09 at 11.41.14 PM.png]

2. Tweak subject line format:

###### Current
- _Response: Your Civil Rights Division Report - [123-ABC] from [Section name]_

###### Proposed
- _Response: Your Civil Rights Division Report - [123-ABC] from [Section name] **Section**_

![Screen Shot 2020-07-09 at 11.41.14 PM.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/c7c63488-7259-454f-aa8d-2bb738623f46)

3. Change 'Record number' to 'Report number'

![Screen Shot 2020-07-10 at 12.00.33 AM.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/f98501e5-0ee9-49d1-bf94-1111bab7f4d0)

**Comment by blaughman** [comment]
Updates are correct.  Moving to UAT.

**Comment by blaughman** [comment]
Function is working in Prod.  Closing card.
