### ISSUE TITLE
Add CRM section form letter response - referral to FBI.

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#628]
## Narrative

As a CRT CRM Section user, I want to use a CRM specific form letter to respond to complainants.

## Background

The last step of complaint processing involves sending a response to the complainant based on the resolution that the CRT - CRM section team lands on. This response letter or form letter is section specific to CRT-CRM and deals with situations that may involve violations of federal criminal civil rights statutes. Complaints of this nature should be directed to the FBI for an initial investigation.  This story addresses this particular use case. 

## Acceptance Criteria

1. Given that I'm on the complaint details page
When I'm at the action's panel 
Then I see a button 'Contact Complainant'

2. Given that I'm on the activity panel
When I click on the 'contact complainant' button
Then I'm taken to a pop-out 'Contact complainant' page with the following information
- 'Response template' dropdown to select the type of letter. See next AC)
- Body of the letter (blank initially until a letter type is selected)
-  'Cancel' option 

3. Given I'm on the 'Contact complainant' screen
When I select 'CRM - Referral to FBI' option from the drop down
Then I see the body of the letter section populated with the form content as in the source of truth attached to this card

4. Given that I'm on the 'Contact complainant' screen
When I click the 'Cancel' link
Then I'm taken back to the complaint details page

**Comment by danielhyi** [comment]
Form letter approved copy is here: https://docs.google.com/document/d/1F3AswAZ2e-TMMxlTgqF7w9CuMD8NJ5Iv/edit

**Comment by blaughman** [comment]
Should this function close card #112?

**Comment by cantsin** [comment]
Apologies if I missed something, but I don't see the subject line in either the doc or this issue (unless it's "Form Referral for Criminal Issues"). Please advise.

**Comment by blaughman** [comment]
@cantsin For the subject line, we should continue in the same manner as before -
Response: Your Civil Rights Division Report - [123-ABC] from [Section name]

As for the form letter selection modal, this should appear as:
CRM - Referral to FBI

Please let me know if there are any other questions.  Thanks.

**Comment by blaughman** [comment]
Function is as intended on Chrome and Edge in Staging.
