### ISSUE TITLE
Printing records as they were originally submitted.

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#629]
## Narrative

As a CRT user, I want to print a record in its' original format so I can forward it to an external agency.

##  Problem

CRT users express concern that there is too much extraneous and confusing information on printed records that are referred to other agencies.  

## Acceptance Criteria

1) Given that I am on the complaint detail page
when I look in the 'Actions' field
then I see a 'Print' button to the right of the 'Contact Complainant' button.

2) Given that I am on the complaint details page
when I click on the 'Print' button
then a modal opens with the following seven checkboxes and a 'Print' button at the bottom: 
-   [x] Correspondent Information
  - [x] Reported Issue
  - [x] Personal Description
  - [ ] Activity
  - [ ] Summary 
  - [ ] Actions

3) Given that I am viewing the print modal 
when I see the six checkboxes
then I see [x] Correspondent Information [x] Reported Issue [x] Personal Description are checked by default

4)  Given that I have made my selections in the print modal
when I click the 'Print' button
then I am taken to the print screen to select my printing output options

5) Given that I have printed the record
when I check the activity log
then I see an entry that I printed the record
AND
I see the selections I made to print.

## Assumptions
- The user wants the ability to select the data that can be printed. 
- The Correspondent Information, Reported Issue, and Personal Description boxes are checked by default since this will satisfy the most common use case.
- Primary printing output will be in PDF format.

## Tech Questions
- Separating comments from actions - does that need additional tech work?

**Comment by blaughman** [comment]
Good example from the web:
https://www.seriouseats.com/recipes/2020/08/print/mango-yogurt-popsicles.html

**Comment by blaughman** [comment]
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/5c3073c0-7cbe-425c-bbc7-e3315c59686a)

**Comment by blaughman** [comment]
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/89424204-e22b-40c8-aefb-39b4b7d71112)

**Comment by cantsin** [comment]
So it turns out that Safari doesn't really do print dialogs consistently relative to other browsers. Specifically, 

> In most browsers, this method will block while the print dialog is open. However in more recent versions of Safari, it may return immediately.

(from https://developer.mozilla.org/en-US/docs/Web/API/Window/print)

I know that we aren't focusing on Safari for internal functionality but wanted to note this for the record. IE/Edge from my testing works fine so far, but will do more testing once I finish up the remaining bits and pieces.

**Comment by blaughman** [comment]
@cantsin This is great.  I'm not sure what's possible, but would it be possible to bump the  "Personal Description" header to page two?  If not, no worries, overall the CRT users will be thrilled with the end product.

**Comment by cantsin** [comment]
@blaughman Hmm. We can attempt to do a "page break" for the Personal Description section which will force that section to start on its own page. Do we want this to apply to all sections (meaning, each section would start on the top of a new page)?

**Comment by blaughman** [comment]
@cantsin Can we add a page break for the  personal description section?  Once that is done, this card is good to go.  It looks great.

**Comment by blaughman** [comment]
@cantsin Don't worry about the page break.  The Edge version looks different so I don't want to solve for one browser and then have issues with another browser's appearance.  I'm moving this to UAT.

**Comment by blaughman** [comment]
Function is as intended on Chrome and Edge in Staging.

**Comment by blaughman** [comment]
Released to Production on 9/8/20.
