### ISSUE TITLE
Perform security scans

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#63]
## Narrative
As a person, I want the system not to get poned so that everyone's data is safe. 

## Background
Automated security checks can alert maintainers if there has been a regression or new vulnerability of the system. 

[OWASP ZAP](https://owasp.org/www-project-zap/) is a good tool for scanning and pen-testing that can be automated to make the system safer.

## Assumptions
Proposal so far for OWASP ZAP scans:
- passive scan on dev for each staging release
- passive scan on stage and prod for each production release
- active scan in circle for each staging and production release

What I am seeing: 
Passive scans on CI have a lot of false positives.
We will need selenium for the active scan, so that it can get to a meaningful part of the form. 
Active scans are going to take longer so we might not need/want to run them on every PR

## Acceptance criteria
- [x] verify this is a good plan with @el-mapache and CRT devs
- [ ] check in with Sean

We can flesh out the implementation steps below once we are on the same page:
- [ ]

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by lalitha-jonnalagadda** [comment]
Closing this card as the task is complete. @LindsayYoung shared documentation on performing these scans in the future with Sean
