### ISSUE TITLE
Make Servicemember and Hate Crime filters persistent

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#630]
## Narrative

As a CRT user, I want the Servicemember and/or Hate Crime filter to persist as I process incoming complaints.

## Problem

The lack of a persistent filter is causing frustrating delays for intake specialists processing complaints utilizing these two specific filters.

**Comment by lalitha-jonnalagadda** [comment]
This is a duplicate to #633 and good to be closed. cc @blaughman
