### ISSUE TITLE
Servicemember filter not persistant

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#633]
## Issue

When using the URL search for servicemember= yes, (https://crt-portal-django-dev.app.cloud.gov/form/view/?servicemember=yes) and from the results page, when the user is trying to navigate through adding other searches, then the filters are lost. 

## Proposed solution

From James - Fix is in this PR -  https://github.com/usdoj-crt/crt-portal/pull/586

**Comment by cantsin** [comment]
This applies to both the `servicemember` and `hate_crime` query params.

**Comment by Jacklynn** [comment]
This is working for me in dev. I tested adding more filters and editing the details page and the filter persisted

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed to prod on 7/20 cc @blaughman
