### ISSUE TITLE
Data mismatch on prod

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#636]
We are noticing data being mismatched when user is filing for a complaint via the form on civilrights.justice.gov. We learnt of the issue being related to the form setting a cookie and its interaction with CloudFront caching.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 7/17

**Comment by cantsin** [comment]
Fixed in https://github.com/usdoj-crt/crt-portal/pull/590

**Comment by blaughman** [comment]
Closing card.  Fix deployed on 7/17/20.
