### ISSUE TITLE
admin: CSV export is missing some fields

### ISSUE THREAD

**Issue by cantsin** [18F/crt-portal#639]
# issue

When doing a CSV export, we are missing (at least) the "protected class" field in the actual CSV export, despite it showing up on the report itself.

**Comment by Jkrzy** [comment]
This is a result of Protected Classes being a M2M relationship, can add shortly. 

The only other Report related data missing from the exports is the contents of the activity log associated with each.

**Comment by ilodidoj** [comment]
I do not see the protected_class field in the .csv file in staging and get Error #500 on dev.
