### ISSUE TITLE
Load Testing Production

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#64]
We will test concurrent record creation to identify the threshold that degrades performance or causes failures

For the test we will simulate user behavior:
- submissions via /report
- submissions via /report/new
- data queries on /form/view
- views of the detail page at /form/view/id
- posting of comments

Steps:
- [x] create load testing script
- [x] take down SSO for tests
- [x] run tests
- [x] adjust resources as needed
- [x] clean up data
- [x] re-deploy prod with sso

**Comment by LindsayYoung** [comment]
Closing this for now, the load testing was successful for the soft launch, the portal can take as much traffic as I could generate. We can do another round of testing once we have DNS and cloudfront in place.
