### ISSUE TITLE
Redirecting to human trafficking hotline - pop up message revisions

### ISSUE THREAD

**Issue by cantsin** [18F/crt-portal#640]
After some design feedback, we want to revise the pop up message:

- 20 second autodirect time instead of 5
- adding "continue" button if users are ready before hand
- a11y: make sure title/heading reads out when the modal opens.
- double check spanish translations are in place
- 50% desktop size breakpoint

**Comment by cantsin** [comment]
@blaughman this is ready for review now, save for one thing: we need the spanish translation string for `"You will automatically be redirected to:"`. What's the process for asking Marta for translation updates?

**Comment by blaughman** [comment]
@cantsin I sent an email to Marta regarding the translation.  I'll let you know as soon as I hear back from her.

**Comment by blaughman** [comment]
@cantsin From Marta:

You will automatically be redirected to:
Será redirigido automáticamente a:

**Comment by blaughman** [comment]
Deployed to Prod on 8/18/20.
