### ISSUE TITLE
[accessibility] "How can we improve this site" text contrast issue for visited link

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#641]
After submitting a report, you see the Insight request for feedback. The text color does not have sufficient contrast (screenshot below)

Heather believes this is a 'visited link' color issue because I've opened it before. If that's the case, I would suggest keeping the visited link color as "white" (or removing it, i defer to engineering)

![Screen Shot 2020-07-17 at 11.07.25 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/179400de-c482-4c82-9fd2-2b85b200e026)

**Comment by Jacklynn** [comment]
I want to note that this a regression of some kind

**Comment by hbillings** [comment]
@Jacklynn I _think_ what's happening is that the link being used doesn't have a `hover` or a `visited` color defined, which means it's picking up the normal link `hover` and `visited` state. This should get fixed by adding those states to the `.fixed-tab-button`.

Oh, and it's showing up like this for you now because you've clicked the link previously! It has probably been like this for a while. (Remind to me rant sometime about how much I hate `visited` link colors.)

**Comment by Jacklynn** [comment]
Oh yayyyy! Thank goodness it's not everyone! I'm actually not sure we have defined visited links. Plus, since you can only get to this link after submitting a new form I might suggest not having a 'visited' link color/keeping it white. I'll update the ACs above, thank you!

**Comment by harikrishnagit** [comment]
@Jacklynn, @hbillings , `.fixed-tab-button` class is defined by touchpoint (https://touchpoints.app.cloud.gov/touchpoints/a24aeb5e/js). The `.visited` is defined in touchpoint javascripts. I don't know how to address this other than changing the `a:visited ` color from color($theme-link-hover-color); to whatever you guys tell.

**Comment by hbillings** [comment]
@harikrishnagit there's nothing preventing us from using the `fixed-tab-button` class in our own CSS, though! We can super easily write a `.fixed-tab-button:visited` rule that sets the color to white. (We should also write one for hover, because it's unreadable on hover currently.)

**Comment by harikrishnagit** [comment]
thanks @hbillings , added color white text

**Comment by blaughman** [comment]
Contrast appears to be fixed.  Moving to UAT.

**Comment by blaughman** [comment]
Contrast also works in Staging.
