### ISSUE TITLE
Landing page buttons using the wrong roll over color

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#643]
**Issue:**
The roll over color on the landing page is not consistent with the rest of the form (ex: `Next` buttons)

the roll over color for the `blue-50` `#2378C3` for...
- [ ] Start a report
- [ ] Submit a report

That way it will make it consistent with buttons later in the form.

**Comment by blaughman** [comment]
Color appears consistent with the rest of the form.  Moving to UAT.

**Comment by blaughman** [comment]
Function works as intended in Staging.
