### ISSUE TITLE
Audit ZAP implementation 

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#645]
Based on the post-mortem on 7/21:

- [x] Double check ZAP to make sure such issues are being flagged (in production) and if ZAP monitors cookie

**Comment by cantsin** [comment]
Still doing some research/activity on ZAP -- specifically for localhost proxying, so keeping this open a bit longer

**Comment by Jkrzy** [comment]
Implemented 3 of the recommendations resulting from this audit.
