### ISSUE TITLE
Optimize hero image on HomePage of https://civilrights.justice.gov/

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#656]
The landing-page-hero-tablet.png is the heaviest image on the civilrights.justice.gov/ homepage.

The .PNG is is 685KB and can be optimized down to less than 60KB if converted to a Progressive JPG or WebP format.  Note that the container is also 1280x1458, but the image is 1536x1750, which is also adding weight to the image.

Once the image is resized/optimized, we will need to view the image on staging and publish to production.

![homepage-hero-optimization.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/c257874f-582e-4b63-aa73-36b865ee6039)

**Comment by randyabramson** [comment]
Optimized image is attached. Please replace the current live image at civilrights.justice.gov/landing-page-hero-tablet.png with the attached - landing-page-hero-tablet.jpg (note this is now a jpg and not a png file).

![landing-page-hero-tablet.jpg](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/a5839295-00ba-4b46-bb8f-0765fab37605)

**Comment by randyabramson** [comment]
@Jkrzy  OK...really good point. In my research, the hero image was the biggest offender and causing a hit on download performance, but you are correct....we should look at them all! I will put in a card for myself to do that assessment.

**Comment by randyabramson** [comment]
Tested new image on tablet on staging. This is good to go. Thank you @AvivaOskow

**Comment by cantsin** [comment]
Should we make a new issue to add the new smaller images above (only tablet is currently in dev/staging) or re-use this issue?

**Comment by randyabramson** [comment]
@cantsin - I added 678 on Friday. Hope this works for you: https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/678

**Comment by cantsin** [comment]
Perfect, many thanks!
