### ISSUE TITLE
Select multiple states when using the 'Incident Location' filter

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#662]
## Problem

As a CRT intake specialist, I need to see complaints from certain geographical areas so I can spot trends and know what complaints are assigned to me.

## Solution

Provide CRT intake specialists the option to select multiple states when filtering by incident location.

## Acceptance Criteria

1)  Given that I am on the view all table
when I see the drop down filter for 'Incident Location'
then I see three fields - 'Incident Location Name' 'Incident Location city' and 'Location State'

2) Given that I select the 'Location State' dropdown
when I see the list of states and territories to choose from
then I see checkboxes positioned on the left of each state and territory.

3) Given that I select multiple states and territories to filter
when I click the 'Apply Filters' button
then I see the filtered results on the view all table
AND
I see the selected states/territories as labels above the view all table

##  Assumptions
- This feature does not apply to:  location name, location city
- There is no cap on the number of selections.
- Research with CRT users indicates a preference for checkboxes for states/territories.

**Comment by cantsin** [comment]
Is this ready to be worked on? CC @randyabramson -- I see this is still part of Sprint 25

**Comment by blaughman** [comment]
@cantsin @randyabramson I did some work on this card.  We don't have a mockup for this feature.  Will the lack of a mockup add a lot of questions and time to developing this feature?

**Comment by cantsin** [comment]
Thanks! I think a mockup isn't necessary here. That being said, I'd like to demo this feature to get feedback before merging. That OK? I'll grab this card.

**Comment by blaughman** [comment]
@cantsin Absolutely.  Thanks for taking this on.

**Comment by cantsin** [comment]
Quick question -- do we want the full names or the abbreviations of the states in the selection list? Currently looks like:

![2020-08-18_14-04.png](https://images.zenhubusercontent.com/5eb05c8e896abe15ccf6dfa3/7fffce2b-20ff-40f9-8e78-fd50fd42d2e9)

**Comment by blaughman** [comment]
@cantsin This looks fantastic.  I, and others, may get confused on the A and M states if abbreviated.

**Comment by blaughman** [comment]
Function works as intended in Chrome and Edge.  Moving to UAT.

**Comment by blaughman** [comment]
Function is as intended on Chrome and Edge in Staging.

**Comment by blaughman** [comment]
Released to Production on 9/8/20.
