### ISSUE TITLE
Pop Up Message when redirecting to ABA and LSC.

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#663]
## Narrative

As a public user, when I click on the 'American Bar Association (ABA)' or 'Legal Services Corporation (LSC)', I would like to know that I am being redirected to a different site so that I am assured of my action

## Acceptance Criteria

1. Given that I'm on the landing page
When I click on the 'lsc.gov/find-legal-aid' link
Then I see a pop up screen that reminds me that I'm leaving the DOJ site with the following copy

**You are now leaving the Department of Justice website. 
The Department of Justice does not endorse the organizations or views represented by this site and takes no responsibility for, and exercises no control over, the accuracy, accessibility, copyright or trademark compliance or legality of the material contained on this site.**

- Spanish Translation

**Está saliendo del sitio web del Departamento de Justicia.
El Departamento de Justicia no respalda las organizaciones o los puntos de vista representados por este sitio y no se responsabiliza ni ejerce control sobre la precisión, la accesibilidad, el cumplimiento con los derechos de autor o marca registrada o la legalidad del material contenido en este sitio.**

2.  Given that I'm on the landing page
When I click on the 'www.findlegalhelp.org' link
Then I see a pop up screen that reminds me that I'm leaving the DOJ site with the following copy

**You are now leaving the Department of Justice website. 
The Department of Justice does not endorse the organizations or views represented by this site and takes no responsibility for, and exercises no control over, the accuracy, accessibility, copyright or trademark compliance or legality of the material contained on this site.**

- Spanish Translation

**Está saliendo del sitio web del Departamento de Justicia.
El Departamento de Justicia no respalda las organizaciones o los puntos de vista representados por este sitio y no se responsabiliza ni ejerce control sobre la precisión, la accesibilidad, el cumplimiento con los derechos de autor o marca registrada o la legalidad del material contenido en este sitio.**

##### Example Implementation
- https://www.justice.gov/crt/webinars#ier%20webinars

## Mockups
![Redirect Mockup.jpg](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/4655c86a-833a-4c97-8605-1ff8c5884970)
- Please insert each of the new links in place of the human trafficking link in the mockup
- 20 second autodirect time
- adding "continue" button if users are ready before hand
- a11y: make sure title/heading reads out when the modal opens.
- double check spanish translations are in place
- 50% desktop size breakpoint

**Comment by cantsin** [comment]
Adding a redirect modal for the landing page _and_ the confirmation page as well. 

Please let me know if the confirmation page should be excluded, but I believe this to be a simple oversight, as we also link to the ABA and LSC there as well.

**Comment by blaughman** [comment]
@cantsin You are correct - the confirmation page should be included as well.  Good catch.

**Comment by blaughman** [comment]
The landing page and confirmation page functions are both working as expected in Chrome and Edge.  Moving to UAT.

**Comment by blaughman** [comment]
Deployed to Prod on 8/18/20.
