### ISSUE TITLE
Add GF/AA Trending Topics Letters

### ISSUE THREAD

**Issue by danielhyi** [18F/crt-portal#664]
Add the GF/AA trending topics letters to the portal. 

Title should be:: 

Trending - [APPLICABLE NAME]
i.e., "Trending - John Doe"

Find the link to those letters [here](https://app.slack.com/client/T025AQGAN/CGWRRBB0E/thread/CGWRRBB0E-1596734928.476200)

**Comment by danielhyi** [comment]
Subject Line: Your Civil Rights Division Report - [REPORT ID]

**Comment by blaughman** [comment]
Deployed to Prod on 8/18/20.
