### ISSUE TITLE
Fix section names in the subject line of form letter responses

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#665]
ADM - from **the** Administrative Section.
CRM - from **the** Criminal Section.
DRS - from **the** Disability **Rights** Section.
ELS - from **the** Employment Litigation Section.      _Remove "Services" from the text_
EOS - from **the** Education**al** **Opportunities** Section.
FCS - from **the** Federal Coordination and Compliance Section.
HCE - from **the** Housing **and Civil Enforcement** Section.
IER - from **the** Immigrant and Employee Rights Section.
SPL - from **the** Special Litigation Section.
VOT - from **the** Voting Section.

**Comment by cantsin** [comment]
Noting that `Appellate (APP)` is not on the above list, anything we should do there?

**Comment by blaughman** [comment]
@cantsin No need to add Appellate.  They never are assigned anything from the public - I would have difficulty explaining their role myself.  Great work on a quick turnaround.

**Comment by blaughman** [comment]
I just tested this and it doesn't appear the changes merged.

![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/20e505b4-8ad5-4591-a15f-4f0e427c37c2)

![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/3775544f-765a-43e7-b5a2-6a3df018fe45)

**Comment by cantsin** [comment]
You're too quick for us :sweat_smile: still trying to get this to deploy to develop, we have pa11y CI failures.

**Comment by cantsin** [comment]
_Now_ its in dev, please give it a shot. :grinning:

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by blaughman** [comment]
Approved.  Thanks for the quick turnaround.

**Comment by blaughman** [comment]
Function works as intended in Chrome and Edge in Staging.

**Comment by blaughman** [comment]
Deployed to Production on 8/25/20
