### ISSUE TITLE
Adding navigation buttons to the complaint detail page

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#666]
## Problem
As a CRT user, I need to navigate to the next filtered complaint assigned to my section so that I can process complaints more efficiently.

## Solution
Adding forward and backward buttons will allow the CRT user to go to the next complaint detail page without having to return to the view all table first.

## Acceptance Criteria

1) Given I am on the view all table and I have filtered the data to view a subset of information
when I click on a record to view the complaint detail page
then I see the complaint details with a 'Back to All' button on the upper left portion of the page and a record counter with backward [<]and forward [>] buttons on the upper right portion of the page.

2) Given I am on the complaint detail page
when I click on the "forward" [>] button
then I am taken to the complaint detail page of the next record of the filtered results and the record counter updates accordingly.

3) Given I am on the complaint detail page
when I click on the "backward" [<] button
then I am taken to the complaint detail page of the previous record of the filtered results and the record counter updates accordingly.

4) Given I am on the complaint detail page
when I click on the 'Back to All' button
then I return to the view all table with the previously selected filters remaining persistent. 

## Assumptions
- The function will work in conjunction with whatever filters are utilized when a user is accessing a complaint detail page
- The backward button [<] can not be selected if I am on the first record of the filtered results.
- The forward button [>] can not be selected if I am on the last record of the filtered results.

**Comment by blaughman** [comment]
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/5642fd59-52a1-4e42-b57d-8522b943a2f8)

**Comment by cantsin** [comment]
Is this ready for dev? Happy to grab this one.

Quick question -- note that the current complaint can be modified and thus (possibly) would not show up when hitting "back to all".

For instance, if I filtered for all open complaints, opened up a complaint and subsequently closed it, and hit the "next" and then "back" buttons here, should I expect that the original now-closed complaint would "come back" even though it's not part of the filter ("all open complaints') anymore?

**Comment by blaughman** [comment]
@cantsin This is ready for dev.  To answer your question above, that's fine if the record is no longer available after a user takes action.  That's basically the expected outcome.  My use case for this function would be to filter all "New" complaints assigned to "ADM."  As I go into the complaint details page, I will take an action on the complaint and then it will no longer be "New."  It will either be "Open" or "Closed" if I take an action.  The total of the filtered results should decrease as I take more actions on more complaints.  Hope this helps, but I'm happy to have a quick chat if I you still have questions.

**Comment by cantsin** [comment]
Thanks! That works for me, because my solution (re-purpose the `next` query parameter) will keep the filtered report list "fresh".

**Comment by blaughman** [comment]
@cantsin Great.  I was curious on your thoughts on the size of this card.  Small?  Medium?  Large?

**Comment by cantsin** [comment]
Good question, I'd venture to say 4 hours (assuming we also add tests), so medium is my guess.

**Comment by blaughman** [comment]
Function works as intended  in Chrome and Edge.  Moving to UAT.

**Comment by blaughman** [comment]
Function is as intended on Chrome and Edge in Staging.
