### ISSUE TITLE
Hotfix - Delete landing page + examples text pending rewrite

### ISSUE THREAD

**Issue by danielhyi** [18F/crt-portal#668]
See here for text updates 
* One on landing page
* one on primary concern page

Content Updates located [here](https://docs.google.com/document/d/1V53xNms75yKD0vcFjQFo4vFo83x0sJSaC8ZSIvG2sN0/edit).

**Comment by danielhyi** [comment]
Also delete the same bullets on spanish translation side

**Comment by blaughman** [comment]
Function was deployed successfully.
