### ISSUE TITLE
Remove NewRelic HighSecurity setting from production config

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#671]
NewRelic offers a https://docs.newrelic.com/docs/agents/manage-apm-agents/configuration/high-security-mode configuration.

Do we need it for production?

---- 
 No, see discussion below.

**Comment by ilodidoj** [comment]
I was actually reading that yesterday. If the requirement is to block 100% of any sensitive data sent to New Relic then it's needed. The default setting also does not send any sensitive data but override is possible.

**Comment by Jkrzy** [comment]
Thanks @ilodidoj !

Here's an evaluation of what HighSecurity offers and what our current configuration provides.

Summary: given our current configuration enabling HighSecurity doesn't provide any benefits for this individual application as we're already preventing any potentially sensitive information from being passed to NewRelic. 

Enabling HighSecurity on the NewRelic/Organization side would help potential exposure due to future misconfiguration, but code review and release should also serve that purpose. 

HighSecurity enforced on NR side | Our current configuration
----|-----------------------
Prevents HTTP param capture | Capturing request parameters is off by default, and we're not overriding that
Prevents message queue param capture | We have no message queue
Prevents raw query statement capture | Not passing raw SQL, using `transaction_tracer.record_sql = obfuscated`
Prevents user attribute capture | Not setting any custom attributes
Prevents noticeError attribute capture | Not using the noticeError API
Prevents custom events | Not creating any custom events
Prevents deploying Custom Instrumentation via CIE | Not using CIE

**Comment by ilodidoj** [comment]
@Jkrzy Great evaluation summary!!  
Based on this we do not enable HighSecurity given that it is not adding any additional value in this context.

**Comment by Jkrzy** [comment]
Given that the production NewRelic agent is not currently collecting data due to this setting being True in our config, I suggest we remediate and release as a hotfix. cc: @randyabramson @blaughman

**Comment by ilodidoj** [comment]
> Given that the production NewRelic agent is not currently collecting data due to this setting being True in our config, I suggest we remediate and release as a hotfix. cc: @randyabramson @blaughman

Agreed.  CC: @randyabramson @blaughman

**Comment by blaughman** [comment]
This is fine with me.

**Comment by randyabramson** [comment]
Good by me
