### ISSUE TITLE
Maintenance Page Design - REFERENCE CARD

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#673]
### Problem
As a product owner, I want communicate with our users if we are doing maintenance to the Complaint Portal or if we are having other technical difficulties so that the user will know when the portal will be available again and how else they can contact us.

### Solution
Create a replacement page for the current landing page at https://civilrights.justice.gov/ that has alternate language and links

### Acceptance Criteria

Given that I am on the Complaint Portal landing page when the site is down for maintenance
When I look at the various language and links
Then I see messaging telling me that the site is currently down for maintenance AND I can still access other info about DOJ and the complaint process, but NOT be able to submit a report

Given that I am on the Complaint Portal landing page when the site is down for maintenance
When I look at the various language and links
Then I am able to read the maintenance and related DOJ info in both English and Spanish

### Assumptions
Assuming that we can contact a developer and edit the text below as needed and that the changes could be live relatively quickly.

Assuming that any page that is hit on the Portal site will render the maintenance page (example: /report) once we decide to put up the maintenance page

If a user is in the middle of the report and we decide to put up the maintenance page, the user can still finish their report (as long as our systems will allow)

Assuming that the process to publish this page will be documented

Assuming the https://civilrights.justice.gov/ page will stay the same except:

* Report a violation nav item at top will be removed.
* "We uphold the civil rights of all people in the United States" is present
* This text "The Civil Rights Division enforces federal laws that protect you from discrimination based on your race, color, national origin, disability status, sex, religion, familial status, or loss of other constitutional rights.

If you believe your civil rights, or someone else’s, have been violated, submit a report using our online form."

is replaced with:

"This page is currently down for maintenance. We expect to be back shortly. 

We recommend checking back to report a civil rights violation. However, if you need to contact us immediately, you can reach us at:

(202) 514-3847
1-855-856-1247 (toll-free)

Telephone Device for the Deaf
(TTY) (202) 514-0716"

* "Start a Report" button is removed
* "About the Civil Rights Division" section stays displayed
* "Understanding Your Rights" section stays displayed
* "Choose from this list to see example civil rights violations:" section stays displayed
* "How to report a civil rights violation" section is removed (along with the 'submit a report button)
* "Already submitted a report" section stays displayed
* Footer says displayed, but 'Report a violation' link is removed

**Comment by Jkrzy** [comment]
For this card, can we minimize the scope by assuming we'll serve this `Maintenance Page` via the existing application? 

The alternative is standing up a separate application on cloud.gov to which we'd re-direct traffic as the "switch on"

**Comment by cantsin** [comment]
Side note, I believe we already have existing 404 mockups which we can repurpose here, I believe, without much difficulty.

**Comment by Jkrzy** [comment]
For a conditionally rendered landing page approach, we could use an environment variable to toggle `maintenance mode` set in cloud.gov. This would allow a developer to toggle on/off by re-staging the application and not require pushing any new code. Serving that new landing page would also be blocked for a bit while it rolled out to Cloudfront.

We'd also need some design help, the requested text is _alot_ to drop as-is into the hero image
![Screen Shot 2020-08-26 at 11.15.07 AM.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/bb65d723-77b7-4dd3-9f53-9d340bc4fdd8)

Another option would be to leave the landing page unchanged, but provide this information when a visitor lands on the `/report/` page. Specifically in response to a `GET` request, thereby removing the interface for folks to submit a report. 

Overall it feels like we need some more planning before this one's `ready for dev`

**Comment by randyabramson** [comment]
@Jkrzy great point about the /report page. I believe this message should be present for the home page and the /report page.

You are right on the hero image having a lot of text. Let me run the image by Dan and see if he has other thoughts about removing the "The Civil Rights Division..." text.

**Comment by randyabramson** [comment]
Updating AC's at the top:
* Assuming that any page that is hit on the Portal site will render the maintenance page (example: /report) once we decide to put up the maintenance page
* If a user is in the middle of the report and we decide to put up the maintenance page, the user can still finish their report (as long as our systems will allow)

**Comment by Jkrzy** [comment]
Ahh, we already have _some_ copy for this that would be worthwhile to include in any of the messaging letting folks know of the other options available for submitting a report. 

![Screen Shot 2020-08-26 at 1.31.15 PM.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/762bbfe2-5281-4ab2-949b-dfd47ec9f652)

**Comment by randyabramson** [comment]
@Jkrzy I'm fine with using those inline jump links to clean up the text.

Text can read:

==

We recommend checking back to report a civil rights violation. However, if you need to contact us immediately, you can call (linked) to report a violation or report a violation by mail (linked)

==

**Comment by cantsin** [comment]
Just checking -- is this feature ready for dev? I know there was still some ongoing discussion around this, specifically re: how to not disrupt the public user experience.

**Comment by randyabramson** [comment]
@cantsin  --- yes, @Jkrzy said he had some thoughts. BTW, this will now be part of Sprint 27...there are too many unknowns for us to jump on this fro 26.

**Comment by Jkrzy** [comment]
How about we break this into two cards with these proposed implementations?

1. Turning off report submissions -- A toggle-able view of the `/report/` page which removes the form,  informs the visitor that we're currently unable to accept online submissions, and directs them to alternative submission paths. Toggleable via environment variables. 

2. Enhanced error pages --  A revised `server error (500)` page which, if generated on a non authenticated path, let's the visitor know we're having difficulty, asks them to try again later, and provides alternate submission paths.

With the goal of,

1. Maintaining the structure and information of the landing page. All of the information on submission and your rights is here and well designed, let's not interrupt that flow.
2. Minimizing changes within as few places as possible and as close as possible to the desired area, online reports in this case. We know visitors access /report/ directly.
3. Allowing CRT staff to remove access to the form for online submissions, in situations where we want to reduce the number of reports coming in via the web.
    a. Allow folks who are already submitting to continue
4. Providing a more detailed error page for unhandled situations where the application has failed to handle a Report submission.

**Comment by randyabramson** [comment]
@Jkrzy I like your thinking here.

Question: I'm assuming we'd also alter https://civilrights.justice.gov/, right? Not just /report?

Also, what other error types we should consider beyond 500 and 404?

Randy

**Comment by randyabramson** [comment]
@Jkrzy I am going to leave this card in 'analyzing' for now and create 2 new cards: one for the 404/500 page and one for the maintenance page.

Let me know if you have time to pair on this. If not, I'll try to tackle on my own based what is on this card.

**Comment by randyabramson** [comment]
Closing this ticket and will spin up separate tickets for Maintenance Page and Error Page
