### ISSUE TITLE
Add Google Search Console tracking code to Portal page headers

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#674]
### Request

(NOTE: Holding on this until we get the centralized Email account configured)

We want to be able to use Google Search Console in order to track Google queries that lead users to our Complaint Portal.

Per documentation at https://support.google.com/webmasters/answer/9274190?hl=en, we are instructed to add this code:

<meta name="google-site-verification" content="UA2qkRn7lIwEkydkzZG2yZEykhLDmEqn8hibqT8105A" />

inside the <head> </head> tag of the page at https://civilrights.justice.gov/

**Comment by randyabramson** [comment]
Updated code snipped:

Please place

<meta name="google-site-verification" content="UA2qkRn7lIwEkydkzZG2yZEykhLDmEqn8hibqT8105A" />

inside the <head> </head> tag of the page at https://civilrights.justice.gov/

**Comment by cantsin** [comment]
@randyabramson I cannot see the code snippet. Can you please enclose it in triple backslashes so the code renders correctly in Github? Like this:

```
```sample code```
```

**Comment by cantsin** [comment]
Nevermind, got it (by editing your comment). For reference:

```html
<meta name="google-site-verification" content="UA2qkRn7lIwEkydkzZG2yZEykhLDmEqn8hibqT8105A" />
```

**Comment by randyabramson** [comment]
Thanks @cantsin

**Comment by randyabramson** [comment]
@cantsin @Jkrzy @ilodidoj -- to verify this, I am searching for "UA2qkRn7lIwEkydkzZG2yZEykhLDmEqn8hibqT8105A"

on

view-source:https://crt-portal-django-dev.app.cloud.gov/form/view/?status=new&status=open&no_status=false

I don't see it. Not sure if the tag is being dynamically injected.

Please advise on how to verify this...thanks!

**Comment by randyabramson** [comment]
Hmmm @ilodidoj  not seeing it on view-source:https://crt-portal-django-dev.app.cloud.gov/ (not the internal admin tools) either. I guess I won't be able to see the code until it is in the live environment or when I use the Google tools to verify it is there on Live.

**Comment by randyabramson** [comment]
Moving this to UAT complete since I can't really test until this in the live environment

**Comment by randyabramson** [comment]
@cantsin - I believe that the previous HTML tag expired. Google says they give you a 'grace period' to verify, but they don't state how long that grace period is.

Wondering if we can add this new tag as a hotfix?

New tag supplied for Google Search Console: <meta name="google-site-verification" content="WVT4_Ja5oSh3rhswyl3OQsLbdxZgOVCgxG7hMoWzL0w" />

**Comment by cantsin** [comment]
Boooooo (regarding unknown grace period, though in fairness this is probably to deter spammers and squatters). Yes, we'll have to add this as a hotfix. I think @ilodidoj can do this, though!

**Comment by randyabramson** [comment]
@cantsin yes, frustrating, but understandable!  Thank you to you and @ilodidoj

**Comment by randyabramson** [comment]
Closing this since the fix for this card is in hotfix card 716
