### ISSUE TITLE
Add Google Analytics Tracking Code to Complaint Portal

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#675]
### Problem
DAP Google Analytics does not let up see demographic information, set up completion goals, etc.
DAP mentioned that other government orgs create spin off/individual GA accounts in order to see this type of data

### Status
We created a CRT organizational Google Analytics account. Now, per the Google instructions we just need to include the below tag on each page of the Portal site (assuming it is just the index page and /report):

"This is the Global Site Tag (gtag.js) tracking code for this property. Copy and paste this code as the first item into the <HEAD> of every webpage you want to track. If you already have a Global Site Tag on your page, simply add the config line from the snippet below to your existing Global Site Tag."

```html<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-176942176-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-176942176-1');
</script>```

**Comment by cantsin** [comment]
Do we want to maintain the previous DAP tracker as well or replace wholesale with GA?

**Comment by randyabramson** [comment]
@cantsin @Jkrzy @ilodidoj -- to verify this, I am searching for "UA-176942176-1"

on

view-source:https://crt-portal-django-dev.app.cloud.gov/form/view/?status=new&status=open&no_status=false

I don't see it. Not sure if the tag is being dynamically injected.

Please advise on how to verify this...thanks!
