### ISSUE TITLE
Replace Desktop and Mobile hero images

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#678]
In [Ticket 656 ](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/656) we replaced the current [homepage](https://civilrights.justice.gov/) hero image for tablet with an optimized image.

We would like to now also replace the mobile and desktop versions of the hero image.

Those images are attached below.

Here is the desktop image:

![desktop-optimized-aviva-082120.jfif](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/a3db4e91-f87a-4e73-9f7d-0825c200b4ef)

Here is the mobile image:

![mobile-optimized-aviva-082120.jfif](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/8d62d02a-31c3-4d29-8e28-7a5f9a6fa91e)

**Comment by randyabramson** [comment]
@cantsin and @Jkrzy - for testing on this ticket, I can eye-ball these images on DEV and they look fine.

However, to really test this, I would need the image url path on dev and make sure the sizes are correct (85kb for desktop and 65 kb for mobile). From there, I can download the images and make sure they are the optimized versions. 

Is it possible to provide the image URL paths? ... I didn't see it in the source code.

Thanks!

**Comment by Jkrzy** [comment]
Using chrome developer tools would be another good option to test this, happy to pair and walk through that if you'd like.

Here are the images in-use on the development instance:

https://cg-b2626a97-5c90-4d35-a39b-24f3b035d5c9.s3-us-gov-west-1.amazonaws.com/static/img/landing-page-hero.jpeg
https://cg-b2626a97-5c90-4d35-a39b-24f3b035d5c9.s3-us-gov-west-1.amazonaws.com/static/img/landing-page-hero-tablet.jpg
https://cg-b2626a97-5c90-4d35-a39b-24f3b035d5c9.s3-us-gov-west-1.amazonaws.com/static/img/landing-page-hero-mobile.jpeg

**Comment by randyabramson** [comment]
@Jkrzy thanks...yes, maybe in our next 1x1.

Downloaded these images and they are the correct optimized versions.  Good to go on these.
