### ISSUE TITLE
Tell DOJ CRT about the respondent

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#68]
## Narrative
As a \<type of user\>, I want \<a goal\> so that \<benefit\>. 

## Background
:add business context to help us better understand the story:

## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Mockups / Wireframes
![image]()

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by Jacklynn** [comment]
Someone during user testing brought up they'd like to list people separately it to CRT attention. 
DRS feedback: would like to see respondent information in the view all table.

**Comment by lalitha-jonnalagadda** [comment]
Duplicate to #228. Closing it
