### ISSUE TITLE
Remove extra semi-colon on Privacy page

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#680]
On https://civilrights.justice.gov/privacy-policy, please remove the ";" at the end of the first bullet in the 'you should also know section'

So, change: "Any information you provide to us through this form is voluntary; to

"Any information you provide to us through this form is voluntary"

**Comment by Jkrzy** [comment]
@randyabramson, the rest of the list items there have periods at the end of the sentences.

OK to include one here?

**Comment by randyabramson** [comment]
@Jkrzy - good pick up. Yes...for consistency, please add a 'period'

Thank you!

**Comment by blaughman** [comment]
Fixed.  Moving to UAT.

**Comment by blaughman** [comment]
Function is as intended on Chrome and Edge in Staging.
