### ISSUE TITLE
Add DOJ statement to bottom of Trending - GF response.

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#681]
The following text should be added to the bottom of the Trending - Floyd Inquiries.

**Comment by randyabramson** [comment]
@ilodidoj and @blaughman 

Per Dan, there is no need for the word 'basis' at the end of this trend letter.

So, the bottom of the letter should say:

==
DOJ statement on George Floyd
https://www.justice.gov/opa/pr/attorney-general-william-p-barrs-statement-death-mr-george-floyd

**Comment by blaughman** [comment]
I updated the card and removed “Basis.”

**Comment by blaughman** [comment]
Response has been updated and approved.

**Comment by blaughman** [comment]
Card cleaned of PII.

**Comment by blaughman** [comment]
Function is as intended on Chrome and Edge in Staging.
