### ISSUE TITLE
Remove word 'basis' at end of AA trending topic letter

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#682]
Please remove the word 'basis' at the end of the AA trending topic letter.

So, the bottom of the letter should read:
--

Sincerely,

U.S. Department of Justice
Civil Rights Division

**Comment by blaughman** [comment]
Basis has been removed.  Moving to UAT.

**Comment by blaughman** [comment]
Cleaned card of PII.

**Comment by blaughman** [comment]
Function is as intended on Chrome and Edge in Staging.
