### ISSUE TITLE
New Relic monitor error review

### ISSUE THREAD

**Issue by ilodidoj** [18F/crt-portal#683]
Over the last 7 days NewRelic has reported 4 unique errors occurring a total of 147 times as of this writing.

We should:

- [x] Assess each error with our bug triage process

**Comment by Jkrzy** [comment]
Thanks @cantsin!

Agree that `204 builtins:KeyError from cts_forms.views:CRTReportWizard.post` is the most interesting, the rest we can let lie.

I'll make a new card specifically to investigate the protected class related errors.

@ilodidoj, check out James' assessment above.

**Comment by Jkrzy** [comment]
Created https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/784 to investigate the first and most common error.
