### ISSUE TITLE
Submitting a comment in excess of the current character limit generates a server error

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#684]
As a user adding a New Comment to a report I want  a helpful error message if there's a problem after I hit the save button so that my work isn't lost and I understand what needs to be done to successfully create a comment.

There's currently a 7000 character limit for the Comment field and input. 

If a user attempts to save a new comment in excess of that limit, there's an unhandled exception and our 500 error page is displayed. We've seen ~9 occurrences of this over the past week.

**Comment by blaughman** [comment]
Going over the limit no longer triggers a 500 error.  Error displays on the detail page.  Moving to UAT.
