### ISSUE TITLE
Quick View On 'View All' Table

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#691]
### Problem statement: 
Intake users cannot get a quick view of personal descriptions without clicking into a ticket.
### Problem statement 2 (post-bulk actions roll out): 
Intake users can group common tickets and take bulk actions on them, but they need to click into each individual ticket to know the specifics of the personal description.

### User story: 
As an intake specialist, I want to be able to see an overview of the complainant name, contact information and a portion of the personal description from the 'View All' table so that I can efficiently take action on multiple similar tickets

### Acceptance Criteria: 
1) Given I am on the view all table
when I look next to each complaint row
then I see a collapsible carrot

2) Given I am on the view all table
when I click on any carrot in any row
then I layer below the selected row unfold to reveal a layer that contains the complainant name, contact info and the first 200 words of the personal description

3) Given I am on the view all table
when I see a complaint with more than 200 words
then I see a scroll bar that lets me view the rest of the selected complaint

4) Given I am on the view all table
when I click on any carrot in any row
then any previously expanded row would remain open

5) Given I am on the view all table
when I click a second time on any carrot in any expanded row
then that previously expanded row would collapses

### Mocks:

![quick-view-collapsed.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/9b8b70d6-f033-4070-8b5c-2599b8865339) 

### NOTE: Mock below should have a scroll bar in the text area

![quick-view-open.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/9edcc5e8-2d12-49b6-a622-4060e48291d0)

**Comment by Jkrzy** [comment]
@blaughman, @randyabramson  -- just double checking, is having both the `Reporter's Personal Description` in the expansion  and `division Staff's Summary` in the original table labeled as `Summary` here intentional? It looks a bit confusing to me.

**Comment by randyabramson** [comment]
@Jkrzy  did this get clarified for you? I only see on summary in the mock, so I'm not positive that I'm following you.

**Comment by Jkrzy** [comment]
Not quite @randyabramson, it's still a bit confusing to have two `Summary` headers on that page. One on the primary table, and then the additional one on the row expansion. This is on the development instance now, we can take a look there. 

If you or @blaughman think it's worth a closer look to help the division staff we can tackle in another card.

**Comment by randyabramson** [comment]
@Jkrzy I see what you mean now. Let's change the header on the open 'quick view' to say 'personal description,' since that is what it is anyway.

2 other things I see on dev for this one:

1. I think we need to test the scroll bar with users -- @blaughman should we maybe have Bob's team test?
2. The carrot disappears after you open. Should we leave it there and allow for the user to close the quick view by clicking the carrot again?

**Comment by Jkrzy** [comment]
@randyabramson,
1. For sure, here's what it looks like![Screen Shot 2020-09-09 at 9.30.39 AM.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/e346d832-d0d3-4a49-97d6-6c419c4698a7)

2. Can you try again after a hard refresh, the carot should persist and does for me on Chrome.

**Comment by Jkrzy** [comment]
Submitted https://github.com/usdoj-crt/crt-portal/pull/668 to update the text to `Personal Description`

**Comment by randyabramson** [comment]
@Jkrzy 'personal description' label looks good. Please update that. 

And, yes, I do see the carrot persist after the hard refresh. Thank you!

**Comment by randyabramson** [comment]
@blaughman @cantsin Two folks from VOT tested quick view and are happy with the functionality as is. I thought they might want a larger preview window (which could be tricky as you get to the bottom of the page), but they like it as is.

Maybe when Emily starts in October, we can revisit if needed.
