### ISSUE TITLE
Districts 65 and 90 need to be added to the Judicial District Table

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#692]
## Problem
District 65 represents Puerto Rico.  District 90 represents the United States Virgin Islands.  These district numbers are not an available selection in the database.  

![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/e5c72e11-da45-4acb-b84b-3623e81c5420)

**Comment by Jkrzy** [comment]
Noted in PR, copying here as well https://github.com/usdoj-crt/crt-portal/pull/661#issuecomment-687365041

**Comment by blaughman** [comment]
Values have been added.  Moving to UAT.
