### ISSUE TITLE
Filter duplication when clicking back to all button

### ISSUE THREAD

**Issue by hakhalid11** [18F/crt-portal#693]
Following steps can be used to create this bug.

Select any intake filter and hit apply filters button
Sort by incident location, contact first name, or incident date
Select any record from the data table
Once you have opened the record hit back to all button

Intake filters will now have duplicated (example screenshot below)
![image.png](https://images.zenhubusercontent.com/5efb8164bf9ea016ca6016f2/f5d21a07-c953-4886-ad6c-45f5262812b0)

**Comment by Jkrzy** [comment]
Is the impact of this limited to the UI with duplication of the applied filters boxes or are the search results unexpected as well?

**Comment by hakhalid11** [comment]
It is limited to the UI and the url params. The search results themselves are unaffected.

**Comment by blaughman** [comment]
Bug appears to have been fixed.  Moving to UAT.
