### ISSUE TITLE
Create a User Profile

### ISSUE THREAD

**Issue by hakhalid11** [18F/crt-portal#695]
Create a Django Model to create a new user profile for each user in the system. This user profile only contains an intake_filter field which will hold the default global section filters. For the new model we need to make it available in admin to create and modify. We will also need to create a new migration to apply the database changes. This will only include table and column creation and no data migration will be a part of this.

_This issue is building towards the resolution of [621](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/621)_

**Comment by blaughman** [comment]
Closing per Haseeb.
