### ISSUE TITLE
Create a class in Views.py to update or create a Profile

### ISSUE THREAD

**Issue by hakhalid11** [18F/crt-portal#697]
Create a Class that accepts post data containing a list of one or more assigned_sections and using the Profile form to create or update intake_filters. This submission will update the requester's (logged in user) profile. This function will also need to handle error validation, and will only update intake_filters if form is submitted with valid assigned sections.

The next iteration of this function will include the following, once the profile has been update the response will be to load the intake filters page again, making sure any applied report filters are kept while also using new assigned_section global filters.

_This issue is building towards the resolution of [621](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/621)_

**Comment by blaughman** [comment]
Closing per Haseeb.
