### ISSUE TITLE
SVI - Add new bullet to Employment section on Primary Concern page

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#699]
Per SVI's request, please add the following bullet:

* Denied reemployment or fired based on military service

to the Employment section of the Primary Concern page:

![image.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/67cbecb0-fcca-4d52-9f5d-788bdd6ce742)

**Comment by hakhalid11** [comment]
@blaughman We need Spanish translation for the new bullet. Thanks

**Comment by randyabramson** [comment]
@hakhalid11 translation here:
Se le negó el reempleo o fue despedido debido a estatus de servicio militar

cc: @blaughman

**Comment by Jkrzy** [comment]
@hakhalid11, this one is still in the `ready for dev` column but we just merged https://github.com/usdoj-crt/crt-portal/pull/691

Please remember to self-assign when you pull a card and move it into the `Developing` column

**Comment by blaughman** [comment]
Bullet is on Dev.  Moving to UAT.
