### ISSUE TITLE
Copy Edit for Disability Personal Characteristic

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#700]
DRS has requested the wording for the Disability selection on the Personal Characteristics page change 
from:
- [ ] Disability (including temporary or recovery)

to:
- [ ] Disability (including temporary, recovery, HIV, or drug addiction)

![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/8f0ba195-9675-48ba-97b7-845064f7e04b)

**Comment by blaughman** [comment]
@danielhyi Do you have any issues with this update?

**Comment by hakhalid11** [comment]
@randyabramson I wanted to confirm the new copy edit should be "Disability (including temporary, recovery, HIV, or drug addiction)" and not whats in the screenshot below.

**Comment by blaughman** [comment]
@hakhalid11 @randyabramson I'm checking with Naomi on this question.

**Comment by blaughman** [comment]
@hakhalid11 @randyabramson I just heard back from Naomi, this is the final copy:

“Disability (including temporary or recovered, and including HIV and drug addiction)”

**Comment by hakhalid11** [comment]
@blaughman We will need Spanish translation for the new copy edit

**Comment by randyabramson** [comment]
@hakhalid11  - the translation is "Discapacidad (incluyendo temporal o recuperada, e incluyendo VIH y adicción a las drogas)"

cc: @blaughman

**Comment by hakhalid11** [comment]
Spanish translation is now on dev/stage
