### ISSUE TITLE
Add Alert for Error rate in NewRelic

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#703]
As a developer or system owner, I want to be notified when errors are occurring on the production instance so that I can triage and escalate as needed.

We'll know we're done when:
- [x] We've established a NewRelic alerting policy for `Error Percentage` on the production instance
- [x] We've established a notification a policy so that developers and system owners are notified

cc: @ilodidoj, @randyabramson, @blaughman

**Comment by Jkrzy** [comment]
@ilodidoj configured this in NewRelic on September 25th.

**Comment by blaughman** [comment]
Closing per Imran.
