### ISSUE TITLE
SVI - add new bullet to housing section of Primary Concern page

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#704]
Per SVI's request, please add the following bullet:

•	Challenges with terminating a lease due to military status change  

to the housing section of the Primary Concern page (note: for consistency, no period on this bullet):

![image.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/424d090d-da50-4321-a13b-ef76286dfb0b)

**Comment by hakhalid11** [comment]
@randyabramson can we get a Spanish translation for this.

**Comment by randyabramson** [comment]
@hakhalid11 - I put in a request...big thanks for the reminder!

**Comment by randyabramson** [comment]
@hakhalid11  - Spanish bullet is:

Retos con la rescisión de un contrato de arrendamiento debido a un cambio de estatus militar

**Comment by blaughman** [comment]
Bullet appears on landing page and primary concern page.  Moving to UAT.
