### ISSUE TITLE
Customer Facing 404 Page

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#705]
**As a product owner, I want users of civilrights.justice.gov to see a welcoming and directional 404 page when they come to our site and hit a url that doesn't exist**

### Acceptance Criteria

Given that I am on the civilrights.justice.gov domain
When I hit a page that does not exist (either cause by human typo, broken link or other non-script related failure)
Then I see a 404 page

Given that I am on the civilrights.justice.gov domain
When I hit a page that does not exist (either cause by human typo, broken link or other non-script related failure)
AND I click the English/Spanish toggle at the bottom of the page
Then I see the 404 page in Spanish

### Background Research

See the attached for a group of government focused 404 pages. I included the features that I liked below most. Note that there are some very BAD 404s out there as well....namely: https://www.fbi.gov/r

[https://app.zenhub.com/files/183258764/23c5e9f9-b3d0-4358-b7b3-64eba05a5361/download](https://app.zenhub.com/files/183258764/23c5e9f9-b3d0-4358-b7b3-64eba05a5361/download)

### Page Elements

**Mandatory Text**
* 404 | Page Not Found
* We can't find the page you're looking for.
* Try one of these links:
- <a href = "https://civilrights.justice.gov/report/">File a complaint</a>
- Contact us by Email (mailto: Ask.CRT@crt.usdoj.gov ) | <a href = "https://civilrights.justice.gov/#contact-crt">phone or mail</a>
- <a href = "https://civilrights.justice.gov/#about-the-division">About the Civil Rights Division</a>
- If you or someone else is in immediate danger, <a href = "tel:911">please call 911 or local police.</a>

**Nice to haves**

1. Lead art: I would love a welcoming image, but I understand that it might be hard to get everyone to agree on what that is. I could see these as possibilities:
* A gavel and the text '404 | Page Not Found'
* A broken puzzle piece
* An unplugged plug
* A laptop with the words '404 | Page Not Found' on the screen
* A magnifying glass with a question mark
* Flashlight illuminating a '404 message' like https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRe3X5Y3Aq3vPAJTL9rN5VldyGhyhR_uW40xw&usqp=CAU

2. I'd consider image buttons for the following if we can come up with universally understood/approved images for:
- <a href = "https://civilrights.justice.gov/report/">File a complaint</a>
- Contact us by Email (mailto: Ask.CRT@crt.usdoj.gov ), <a href = "https://civilrights.justice.gov/#contact-crt">phone or mail</a>
- <a href = "https://civilrights.justice.gov/#about-the-division">About the Civil Rights Division</a>
- If you or someone else is in immediate danger, <a href = "tel:911">please call 911 or local police.</a>

### **Other Assumptions**

* This 404 page will have the same look and feel as the rest of the site.

**Comment by randyabramson** [comment]
**As a product owner, I want users of civilrights.justice.gov to see a welcoming and directional 404 page when they come to our site and hit a url that doesn't exist**

### Acceptance Criteria

Given that I am on the civilrights.justice.gov domain
When I hit a page that does not exist (either cause by human typo, broken link or other non-script related failure)
Then I see a 404 page

**Comment by randyabramson** [comment]
@hakhalid11 - in the interest of time, I am fine if this card has the same look and feel/contact info as card 706 and 707.

A nice to have would be to still have each page having unique messaging at the top ('This page is being maintained,' 'something went wrong' and 'we can't find what you're looking for' respectively.

Please note that the 500 error page encapsulates all other errors beyond 404 and Maintenance.

I'll try to get translations, but as discussed, you can move forward with just English for now and make sure that the translation button is greyed out if we don't have translations in time.

**Comment by randyabramson** [comment]
@hakhalid11 also, the text for the 404 page needs to be as follows:

404 | Page Not Found
We can't find the page you're looking for.

Try one of these links:

File a complaint
About the Civil Rights Division

If you need to contact us immediately, you can reach us by:
Email 
Phone 
(202) 514-3847
1-855-856-1247 (toll-free)
Telephone Device for the Deaf
(TTY) (202) 514-0716"
Mail 
U.S. Department of Justice
Civil Rights Division
950 Pennsylvania Avenue, NW
Washington, D.C. 20530-0001
Other information:
•	About the Civil Rights Division
•	If you or someone else is in immediate danger, please call 911 or local police.

**Comment by randyabramson** [comment]
@hakhalid11 -- Looks good! I see it on dev. A couple of tweaks before we move it to UAT complete, please:

1. Take out **"Try returning to the previous page**
2. Phone info should be:

(202) 514-3847
1-855-856-1247 (toll-free)
Telephone Device for the Deaf
(TTY) (202) 514-0716"

**Comment by randyabramson** [comment]
@hakhalid11 - friendly reminder about these fixes. Once you make these, I can move these to UAT complete.

* Take out "Try returning to the previous page

* Phone info should be:
(202) 514-3847
1-855-856-1247 (toll-free)
Telephone Device for the Deaf
(TTY) (202) 514-0716"

**Comment by randyabramson** [comment]
Translation here[https://app.zenhub.com/files/183258764/5945c057-d938-4b7b-b75f-e167047e38d5/download](https://app.zenhub.com/files/183258764/5945c057-d938-4b7b-b75f-e167047e38d5/download)

**Comment by Jkrzy** [comment]
@blaughman, @randyabramson, @hakhalid11  -- this card has been dancing all over the board :smile:

The work done so far has been limited to updating the 404 error page template. This is part of the acceptance criteria in the original issue but not all.  

We still need changes to render that page for a 404 response instead of re-directing to SSO. 

I'm going to create a new card for that work.

**Comment by Jkrzy** [comment]
Created: https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/752

**Comment by randyabramson** [comment]
Ah, thank you for pointing that out @Jkrzy  !!

**Comment by randyabramson** [comment]
Tested on Chrome and EDGE + mobile

**Comment by randyabramson** [comment]
@Jkrzy @cantsin @ilodidoj 

Formatting on 404 on CHROME PC looks off: 
https://civilrights.justice.gov/report/fewewf

![404-chrome.PNG](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/cd3165d7-0989-4657-a76a-f4bb1e144430)
