### ISSUE TITLE
Customer Facing Maintenance Page for /report page

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#706]
**As a user, when I try to submit a report while the Complaint Portal is being maintained, I will not be aware of the maintenance, when the site will be back up or how else I can submit a report.**

### Acceptance Criteria
Given that when I am https://civilrights.justice.gov/report/
When the site is being maintained
Then I see the maintenance page

Given that when I am https://civilrights.justice.gov/report/
When the site is being maintained
AND I click the English/Spanish toggle at the bottom of the page
Then I see the maintenance page in Spanish

### Assumptions
* We are assuming that the Complaint Portal is up and running on Cloud.gov
* If a user is in the middle of the report and we decide to put up the maintenance page, the user can still finish their report (as long as our systems will allow)
* Search engines will get 503 messaging telling them that the site is being maintained per https://moz.com/blog/how-to-handle-downtime-during-site-maintenance
* This page will have the same look and feel as the rest of the site
* As we get a clearer understanding of when the system will be back up OR the cause of the error, we can update the text of the page either though the help of a developer or an external text file that Bill, Randy or Dan can update 

### Mandatory Text

This page is currently down for maintenance. We expect to be back shortly.
We recommend checking back to report a civil rights violation. However, if you need to contact us immediately, you can reach us by:

**Email** (mailto: ask.crt@usdoj.gov ) (please use mail icon in footer)

**Phone (please use phone icon in footer):**

(202) 514-3847
1-855-856-1247 (toll-free)

Telephone Device for the Deaf
(TTY) (202) 514-0716"

**Mail (please use mail icon in footer):**

U.S. Department of Justice
Civil Rights Division
950 Pennsylvania Avenue, NW
Washington, D.C. 20530-0001

Other information: 
* <a href = "https://civilrights.justice.gov/#about-the-division">About the Civil Rights Division</a>
* If you or someone else is in immediate danger, <a href = "tel:911">please call 911 or local police.</a>

### Design guidance 
* Full design coming from Jacklynn
* I do recommend leaving the 'United States Department of Justice' logo at the top, but removing
![report-header.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/b2465f42-149f-4c3c-8129-bb507ada755a)

### Technical Guidance From Joe

For a conditionally rendered landing page approach, we could use an environment variable to toggle maintenance mode set in cloud.gov. This would allow a developer to toggle on/off by re-staging the application and not require pushing any new code. Serving that new landing page would also be blocked for a bit while it rolled out to Cloudfront.

For a conditionally rendered landing page approach, we could use an environment variable to toggle maintenance mode set in cloud.gov. This would allow a developer to toggle on/off by re-staging the application and not require pushing any new code. Serving that new landing page would also be blocked for a bit while it rolled out to Cloudfront.

**Comment by randyabramson** [comment]
Jacklynn mock attached

![404-mock-jacklynn.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/8d99ba9d-231d-411f-8e25-a5191829d970)

**Comment by Jkrzy** [comment]
On the landing page we're referring folks directly to the footer for contact information -- can we do that here instead of duplicating it on the page?

Links are beneath the `Submit a report` button
>If you cannot access the online form, you can call to report a violation or report a violation by mail.

**Comment by randyabramson** [comment]
Hey @Jkrzy -- I do recall us discussing this and I gave it some thought. 

I believe we should keep this contact info high on the page if possible.

In trying to empathize with the user, I'm assuming that they are already under duress and adding another click would just lead to further frustration. The footer is well designed, but still has a good amount of information to sift through in order to get the contact information they need.

Additionally, in my research, I didn't see any examples where users need to jump to a footer to get the correct information they need. Lastly, I'm thinking specifically of user behavior on a site like Amazon. On sites like Amazon, they have a ton of links in the footer to direct the user. Still, if I look at a 'contact customer service' page on mobile (attached), you will see that all of the important information/actions are right in front of the user...no clicking and sifting required.![amazong.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/38503620-d3c2-49d9-9056-9eeb36fd9f4a)

**Comment by randyabramson** [comment]
Translation here
[https://app.zenhub.com/files/183258764/3079d77f-f949-4944-a41f-44a68fc589fc/download](https://app.zenhub.com/files/183258764/3079d77f-f949-4944-a41f-44a68fc589fc/download)

**Comment by Jkrzy** [comment]
I got started on this and have the inner-workings and documentation for maintenance mode in place, still needs template work but noting here for whomever picks this up next.

https://github.com/usdoj-crt/crt-portal/pull/714

**Comment by randyabramson** [comment]
Thank you @Jkrzy

**Comment by randyabramson** [comment]
@Jkrzy if you have a url for me to test this, please let me know.

**Comment by Jkrzy** [comment]
We'll coordinate a test on the development environment by enabling maintenance mode there.

cc: @ilodidoj, @randyabramson
