### ISSUE TITLE
Actions not rendering on Print/Share functionality

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#709]
Using a report from development as a test case.

1. I select 'Actions' as a choice for print/share

![image.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/a2b649a6-6b9e-44b6-b49f-eb67e073243a)

2. Actions is not rendered in the 'print'share' function

**Comment by cantsin** [comment]
Looking at this real quick -- whoops. I think we accidentally reversed "Activity" and "Actions". It's a bit confusing here because "Actions" really means "Comments." Pushing up a quick fix for this.

**Comment by randyabramson** [comment]
@cantsin I see what you're saying now. When I select 'actions,' it actually prints 'activity' which is comments and other activities.

I think it should map exactly as it appears in the UI, so

1. Actions = Actions
2. Activity = Comments and other activity (opened, closed, etc.)

Make sense?

**Comment by cantsin** [comment]
Yep, makes sense!

One question, it's still a bit unclear to me what should be in `Activity`. Currently `Activity` only contains comments. From your above statement, I take we want `Activity` to be comments _and_ status changes (open, closed, ...) on the record? If so, should `Actions` also have status changes?

Also CC @blaughman

**Comment by blaughman** [comment]
Activity is the category we really need to be careful with.  That is where a lot of information resides that is typically redacted.  Any comments or summary added to a record should not be a part of what is shared with an external agency.

**Comment by randyabramson** [comment]
@cantsin @blaughman OK, I defer to Bill.

I think we just leave activity off as a check box option then, right??

**Comment by cantsin** [comment]
My fix is in develop now. Can y'all please make sure it works as expected? :sweat_smile: 

Yes, `Activity` is left off as a check box. 

Side note, I think I confused myself. `Activity` contains what happens to the record, `Actions` are comments. Argh!

**Comment by randyabramson** [comment]
@cantsin Looking on DEV and I still see 'Activity' as a check box option (I did a hard refresh and still see it). @blaughman had concerns about having that as a checkbox, so I think we should remove that.

**Comment by cantsin** [comment]
Oh, I mis-read, apologies. So we want to *remove* the `Activity` option entirely? @blaughman ?

**Comment by blaughman** [comment]
@cantsin Correct.  Selecting that option would never render a value since any action would be noted in the 'Activity' field.   Hope this helps.

**Comment by cantsin** [comment]
Got it! Removing comments, nee `Actions` and before that, `Activity`, due to the accidental swap. :sweat_smile: Not confusing at all!
