### ISSUE TITLE
Log out of admin portal as CRT User

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#71]
## Narrative
As a \<type of user\>, I want \<a goal\> so that \<benefit\>. 

## Background
:add business context to help us better understand the story:

## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Mockups / Wireframes
![image]()

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by lalitha-jonnalagadda** [comment]
Scope:
- Manual log out
System log out

**Comment by lalitha-jonnalagadda** [comment]
Closing this card as the log out is handled as a part of the logging card #14
