### ISSUE TITLE
COVID Form Letters

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#710]

**Comment by randyabramson** [comment]
I know we were talking about a couple of different letters here:

* One for people who were upset about they way they were treated for not wearing a mask due to disabilities
* General comments about the way the pandemic is being handled, etc.

Once we have the letters back from Dan, we should consult with:

* Marta
* Tarsha
* Naomi 
* Anne Raish
* Lorine (task force)
* Christie (task force)

Anyone else? cc: @blaughman  @danielhyi

**Comment by blaughman** [comment]
Perhaps we should add Greg Friel or Kathy Toomey from the Front Office for approval/sign off.

**Comment by randyabramson** [comment]
Good call @blaughman
