### ISSUE TITLE
Change FOIA link

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#711]
Please change FOIA link in footer to go to https://www.justice.gov/crt/freedom-information-act-0

![image.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/97f8e1e3-0075-454c-9816-1a9a9b3cea8c)

(It currently goes to https://www.justice.gov/oip)

Note: the footer exists on the landing page, report pages and privacy page. 

Note: Dan signed off on this change; the request came from Naomi.

**Comment by blaughman** [comment]
Link now directs user to CRT's FOIA unit.  Moving to UAT.
