### ISSUE TITLE
Replace library to address recent discovery of bugs

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#712]
Staff library is triggering bugs.

**Comment by cantsin** [comment]
Some suggestions from other 18F staff:

- https://github.com/trevoreyre/autocomplete
- https://github.com/mynamesleon/aria-autocomplete

**Comment by cantsin** [comment]
None of these are a drop in replacement, alas; we will have to do a bit of work to integrate any of these (maybe a custom widget would be best).

**Comment by cantsin** [comment]
We only use the autocomplete library for assignees; we have three different forms where we have an assignee field in the application: 

- Filter by "assignee" on the "view all" reports page
- Individual report assignment
- Bulk report assignment

Testing notes:

- Edge is a must. 
- Basic usage:
  - Test that changing an user (for any form above) does in fact change the user
  - Test that _clearing_ out an user works (note: may have to click outside the assignee box first)
  - Test that a blank assignee field can be populated by users, chosen, and submitted.
- Take note of any differences (if any) between the old behavior and new behavior: the number of users that show up, the speed, styling differences, how many letters to trigger auto completion, etc.

CC @blaughman @randyabramson

**Comment by randyabramson** [comment]
Thanks for your notes on this @cantsin We'll try to test this today.

Randy

**Comment by randyabramson** [comment]
@cantsin 

Testing this now.

I think this works fine. Some small comments below that make the experience a bit odd, but it is still very usable:

1. I enter the letter 'd' and it takes 8 names before I see an assignee with the letter 'd' in their name
2. For entry 'pernell.carter,' I have to enter 4 letters before I see his name appear



cc: @blaughman

**Comment by randyabramson** [comment]
@cantsin - do you have any thoughts on my notes above? Should we move forward with this and then just add another card with tweaks?

**Comment by randyabramson** [comment]
@cantsin 

I noticed that on 'single report changes', that if I clear out an assignee, then enter a new assignee and hit 'apply changes' that the top status says 'Successfully updated Assigned to.' without listing the name.

Not a show stopper...we can fix this in the next sprint.

Randy

**Comment by cantsin** [comment]
Thanks! Looking into these issues today. I'm not sure what's happening with the user search offhand ('d' not appearing in the first 7 names), will play around with that a bit,.
