### ISSUE TITLE
Write a unit test for `ComplaintActions.get_actions`

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#713]
@cantsin submitted a pull request https://github.com/usdoj-crt/crt-portal/pull/678/ to render user names in the activity log instead of ID. This PR and changed function lacks test coverage.

We'll add a unit test(s) to the above open pull request to assert the desired behavior of `ComplaintActions.get_actions`.

**Comment by Jkrzy** [comment]
@kmanubhai is going to tackle this one

**Comment by randyabramson** [comment]
Thanks @Jkrzy and @kmanubhai

**Comment by randyabramson** [comment]
@Jkrzy if there is a way for me to test this on staging, let me know.
