### ISSUE TITLE
Change intake type on proform to checkboxes instead of dropdown menu

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#720]
## Narrative
As a CRT intake specialist, I want a checkboxes in the 'intake format' on the proform so that I can create records more quickly.

## Acceptance Criteria

1)  Given I'm on the proform page
when I look in the 'Intake format' field
then I see four checkboxes with the following selections
- [ ] letter
- [ ] phone
- [ ] fax
- [ ] email

## Mockup (developer's choice - either 2 x 2 or 1 vertical column for checkboxes)
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/5ba563e3-6c01-4785-9ee2-4f6a608392c7)

**Comment by hakhalid11** [comment]
@blaughman question about multiple intake types selected. 
![image.png](https://images.zenhubusercontent.com/5efb8164bf9ea016ca6016f2/e8e30f21-01de-4e2c-92eb-089446b92ab7)
is the user allowed to select more than one checkbox or is it only restricted to one intake format per report?

**Comment by blaughman** [comment]
@hakhalid11 Only one box should be checked for this field.

**Comment by hakhalid11** [comment]
@blaughman thanks for the clarification, would the following screenshot work as an alternative. It seems limiting checkboxes to one input would take more work than just using a radio button.
![image.png](https://images.zenhubusercontent.com/5efb8164bf9ea016ca6016f2/f37cf393-b829-47e9-9677-ee288f9d7fdd)

**Comment by blaughman** [comment]
@hakhalid11 That works for me.  Thanks.

**Comment by blaughman** [comment]
Function works as intended on Chrome and Edge.  Moving to UAT.
