### ISSUE TITLE
[Bulk Actions] update multiple records with any selection in the 'Activity' menu

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#723]
## Narrative
As a CRT user, I want to take action on multiple records at once so that I can process my work more efficiently.

## Acceptance Criteria

1) Given I am on the view all table
when I look in the column heading
then I see a 'square' icon to the left of the text 'Status'

2) Given I am on the view all table
when I click on the 'square' icon
then the displayed records on the current page matching my selected filters are automatically selected
AND
when I click on the 'square' icon once all displayed records are selected
then all records will be unselected.

3) Given I am on the view all table
when I select a checkbox for any or all records
then I see an 'Actions' button appear in a sticky action bar on the bottom of the page

4) Given I have selected records in the view all table
when I click the 'Actions' button
then I am taken to a new page called 'Update Multiple Records"

5) Given I am on the Update Multiple Records page
when I look at the top of the page I see the complaint intake level chrome which includes 'Back to All' button and 'Add New Record' button
AND
I see a "Update Multiple Records" label under the 'Back to All' button
AND
I see the 'Activity' menu with the fields 'Section', 'Status', 'Primary Classification', 'Judicial District', 'Assigned to', 'Summary', and 'Comment'. 

6) Given I am on the bulk actions page
when I click the 'Section' dropdown menu  
then I see all the sections within CRT displayed 

7) Given I am on the bulk actions page
when I click the 'Status' dropdown menu  
then I see three selections (New, Open, Closed) available. 

8) Given I am on the bulk actions page
when I click the 'Primary Classification' dropdown menu  
then I see the classification number table displayed 

9) Given I am on the bulk actions page
when I click the 'Judicial District' dropdown menu  
then I see the judicial district table used by CRT displayed 

10) Given I am on the bulk actions page
when I click the 'Assigned to' field  
then I am able to enter a user's name with type ahead capability 

11) Given I am on the bulk actions page
when I click the 'Summary' field
then I am able to enter a personal summary which will apply to the selected records

12) Given I am on the bulk actions page
when I click the 'Comments' field  
then I am able to enter a comment which will apply to the selected records
AND
I see the text '*required' in red directly below the 'Comments' label

13) Given I am on the bulk actions page
when I look at the bottom of the 'Actions' menu
then I see a greyed out button stating 'Apply changes to x records' that is inactive until an action is selected.

14) Given I am on the bulk actions page
when I have selected an action to impact the selected records
then I see the 'Apply changes to x records'  is now blue and available for me to take the action.

15) Given I have chosen to take action on 15 or less records 
when click the 'Apply changes to x records'
then I am returned to the view all table with the previous filters remaining persistent
AND
I see a confirmation message indicating 'x records have been (selected action)'
AND
the activity log is updated for each impacted record.

16) Given I have chosen to take action on more than 15 records at once
when I click the 'Action' button 
then I see two buttons appear 'Apply changes to 15 records' and 'Apply changes to x (all queried records)'
AND
the activity log is updated for each impacted record.

17) Given I am on the bulk actions page
when I have executed a bulk action on selected records
AND
I click 'Back to All'
then I am returned to my previously filtered data.

## Assumptions
- A user will be able to select more than one action to impact the selected records (for instance, change status and add an assignee to the selected records)
- Any selection over 15 impacted records will trigger the warning labels
- Code will require a tweak for comments and summary

## Mockups
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/34b20e17-5942-480f-a1cf-5ecba6a9aa48)

![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/d6fbf908-98e8-4d06-9e8c-6316b23d4201)

**Comment by cantsin** [comment]
Would be nice to have @Jacklynn 's mockups here too if possible?

**Comment by cantsin** [comment]
Going to make a separate ticket for > 15 records as I believe we can do that immediately without much work and this can be done separately.

**Comment by cantsin** [comment]
@blaughman @randyabramson 

Currently if an user changes the assigned section, we also reset the assignee and status. This seems somewhat at odds with bulk update, but let me know if I should do something special if the user bulk updates the assigned section (with or without updating either the assignee or status).

**Comment by randyabramson** [comment]
Great catch @cantsin 

My take:

1. If user changes assigned section without assigning status or assignee, we give them a warning message as we did with the other bulk messaging:
"You are about to change the section for xyz records. The status will be set to New and there will not be an assignee."
Button for 'Apply changes to xyz records' is present.

2. If user changes assigned section with assigning status and/or assignee, we follow the request of the user and update status and/or assignee accordingly.

How does that sit with you @cantsin and @blaughman  ??

**Comment by cantsin** [comment]
Sure, I can do this. Related to the above, I think I'm going to split up the work a bit further: 

- Bulk update functionality (PR is ready for review) :tada:
- Prefill form field iff all reports have an identical field
- Follow up tweaks (such as above assigned section change)

That way we can get this work in sooner and test everything and play around with how bulk updates feel.

**Comment by randyabramson** [comment]
@Jkrzy When I checked this function on Dev, the 'apply changes' function is greyed out, even after I selected an Action.

Here is what I did:

* Start with [this view](https://crt-portal-django-dev.app.cloud.gov/form/view/?per_page=15&status=new&status=open&sort=-create_date&page=1
)

* Select two records and then 'Action'

* [Select section as "CRM"](https://crt-portal-django-dev.app.cloud.gov/form/actions/?next=%253Fper_page%253D15%2526status%253Dnew%2526status%253Dopen%2526sort%253D-create_date%2526page%253D1&id=444&id=443) 

* "Apply changes to two records" button is still greyed out

Is there something I missed here?

**Comment by Jkrzy** [comment]
Comment is a required field for bulk actions, it needs to be populated before submission is possible

**Comment by randyabramson** [comment]
thanks @Jkrzy 

@blaughman - why are comments mandatory for bulk actions? Also, I missed the _* required_ messaging because it was off screen. Should we leave the 'Apply changes' button active here and bring up a 'comments required' message if they user has not filled it out?

**Comment by randyabramson** [comment]
@blaughman said he'd get feedback from users on if we need additional messaging for the required comments field.

**Comment by randyabramson** [comment]
@cantsin I was testing Bulk Actions on Dev and saw that text is not wrapping on this record in EDGE. Not sure if this is just a DEV thing or somehow related to BULK ACTIONS: 

https://crt-portal-django-dev.app.cloud.gov/form/view/445/?next=%3Fper_page%3D15%26assigned_section%3DELS%26status%3Dnew%26status%3Dopen%26sort%3D-create_date%26page%3D1&index=0

Screen capture attached
![max.PNG](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/bca4e7af-9b1e-445c-afa8-f0c1af93b2cf)

**Comment by cantsin** [comment]
Thanks! 

I do not think this bug is not related to bulk actions -- did you edit the correspondent information individually? If so, yes, you can set the name to a very long string, since we have a limit of 225 characters for either first/last name. We can elide using some CSS :magic:, but I think this wouldn't be a problem during normal usage?

**Comment by randyabramson** [comment]
Decisions from 10/13/20 meeting with @blaughman and @cantsin 

* Decision - if you assign a section, you can't assign a specific user

* We would like a message telling user that if they change section, the ticket would be marked as 'new'. This would be for individual and bulk

* Grey out Jurisdiction

* Classification stays in 

* Bulk print/Save
- dynamic winZip is a lot of work
- bulk print is hard because of making sure page breaks work

** Recommendation - two new tickets: go for bulk save first and bulk print second

**Comment by blaughman** [comment]
@cantsin @Jkrzy @randyabramson Bug discovered - the 'Routed' column is blank if a user selects 'Multiple' as a section assignment.

**Comment by randyabramson** [comment]
[https://app.zenhub.com/files/183258764/995df15c-b786-4799-afbf-7c2db509e9d4/download](https://app.zenhub.com/files/183258764/995df15c-b786-4799-afbf-7c2db509e9d4/download)

Adding a word doc attachment that outlines the expected UX when users utilize the various Bulk Action options.

cc: @cantsin and @ilodidoj 

Let us know if we should create a new ticket for this or if you want to continue to work in this ticket.

cc: @blaughman @hakhalid11

**Comment by cantsin** [comment]
Thanks; made a new issue over at https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/758
