### ISSUE TITLE
[Bulk Actions] warn if > 15 records will be impacted

### ISSUE THREAD

**Issue by cantsin** [18F/crt-portal#726]
Any selection over 15 impacted records will trigger the warning labels

Part of prepatory work for [723](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/723)

**Comment by blaughman** [comment]
Function works as intended  in Chrome and Edge.  Moving to UAT.
