### ISSUE TITLE
Onboard Karan

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#727]

**Comment by randyabramson** [comment]
Tasks from previous cards: 

Invites to:
* core meetings
* documents/drive
* zenhub
* PA shareback doc (describing the thin slice)
* Charter
* Walkthrough vision, roadmap and thin slice @lalitha-jonnalagadda @UchMok
* Schedule meeting with design around end-to-end mockups @AvivaOskow
* Schedule meeting w/ design around User research, personas, etc @Jacklynn
* Schedule meeting w/ engineers around technical vision, history @LindsayYoung @alexsoble
* create accounts @LindsayYoung

Access and familiarity with:
*18F CRT GitHub team (circle and zenhub access are connected to GitHub)
* GoogleDrive
* CRT GitHub @dwechsle
* cloud.gov
* circle overview
* Kibana logs overview slides
* django tutorial (independent)
* backend view PR (one of the issues with a pairing tag)
* pa11y testing 3/10
* make production release schedule with assignments GitFlow- L 2/12
* Javascript - Codecademy into - A 2/11
* CSS - Codecademy into
* USWDS - Intro the docs - A 2/18
* filtering and url creation on crt views - A+L 3/17
* upgrades and patches
* git and github
* Disaster readness/recovery drill May 26 - Lindsay +
