### ISSUE TITLE
[Bulk assign] prefill form fields

### ISSUE THREAD

**Issue by cantsin** [18F/crt-portal#728]
When doing bulk updates, we want to prefill a form field if and only if all selected reports have the same value for that field. If the reports differ with respect to this field, then the field will show Multi instead (which will serve as a blank dropdown). 

"All reports" here meaning "all" (if selected) or the subset of records the user chose, whichever is greater.

See the original Bulk Update -- https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/723 issue for mockups.

**Comment by cantsin** [comment]
Edit: removed markdown

**Comment by randyabramson** [comment]
Working on CHROME and EDGE. Moving to UAT Complete
