### ISSUE TITLE
[design] Extra spacing on mobile

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#731]
I was looking at the form in mobile version and it looks like there is a lot of extra spacing on the the header making it harder for users to get to the content
Screenshots of build:
![avg phone.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/f2764c78-f3f1-4753-a470-b0fafd1144bf)![iphoneSE.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/27dd1892-f618-4d37-b602-da900122eab3)

It looks like there is more space than [Aviva's annotations](https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/84). Randy mentioned that a large number of users come in on mobile.

**Comment by randyabramson** [comment]
Gaps between modules are closed. @AvivaOskow should we also close the gap between the number bar and the first entry module?

![mobile grab.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/b202e560-8adf-49a4-b199-a5408df17933)
