### ISSUE TITLE
[Bulk Actions] Printing multiple records at once

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#734]
## Narrative
As a CRT user, I want to print multiple records at once so that I can refer multiple records to external agencies or respond to FOIA requests.

## Acceptance Criteria

1) Given I am on the view all table
when I look in the column heading
then I see a 'square' icon to the left of the text 'Status'

2) Given I am on the view all table
when I click on the 'square' icon
then the displayed records on the current page matching my selected filters are automatically selected
AND
when I click on the 'square' icon once all displayed records are selected
then all records will be unselected.

3) Given I am on the view all table
when I select a checkbox for any or all records
then I see an 'Actions' button appear in a sticky action bar on the bottom of the page

4) Given I have selected records in the view all table
when I click the 'Actions' button
then I am taken to a new page called 'Update Multiple Records"

5) Given I am on the Update Multiple Records page
when I look at the top of the page I see the complaint intake level chrome which includes 'Back to All' button and 'Add New Record' button
AND
I see a "Update Multiple Records" label under the 'Back to All' button
AND
I see the 'Activity' menu with the fields 'Section', 'Status', 'Primary Classification', 'Judicial District', 'Assigned to', 'Summary', and 'Comment'. 
AND
I see a 'Print' button to the right of the Activity menu.

6) Given I am on the Bulk Actions page
when I select the 'Print' button
then a modal opens with the following five checkboxes and a 'Print' button at the bottom: 
-   [x] Correspondent Information
  - [x] Reported Issue
  - [x] Personal Description
  - [ ] Activity
  - [ ] Summary 

7) Given that I am viewing the print modal 
when I see the five checkboxes
then I see [x] Correspondent Information [x] Reported Issue [x] Personal Description are checked by default

8) Given that I am in the print modal 
when I have selected 15 or less records 
then I see a 'Print x records' button.

9) Given that I am in the print modal
when I have selected 16-100 records
then I see the button 'Print 15 records'   
AND
I see a button  'Print x records' (with x representing a value between 16 and 100)

10) Given that I am in the print modal
when I have selected more than 100 records
then I see the button 'Print 15 records'   
AND
the 'Print x records' button is greyed out with a message indicating 'The maximum number of records for this function is 100'

11) Given that I have made my selections in the print modal
when I click the 'Print' button
then I am taken to the print screen to select my printing output options

12) Given that I have printed the record
when I check the activity log
then I see an entry that I printed the record
AND
I see the selections I made to print.

## Assumptions
- The leanest version of this function is basically a bulk save
- Size of file must be less than 100mb.

## Technical questions
- How can we ensure a clear break between records?
- Would the named batch be reflected in the activity field?
- For a large print job, would it be best practice to compress the data for easier transmission?
Max size test created a 70kb file
[https://app.zenhub.com/files/183258764/8887051c-0ede-4b0a-88ef-c3e64884cf15/download]
## Mockup
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/5d7cc0c0-0c2e-4f86-9307-99f02caf00e6)

**Comment by cantsin** [comment]
Update: we can force page breaks in the PDF using CSS. 

Example: ![2020-10-14_10-47.png](https://images.zenhubusercontent.com/5eb05c8e896abe15ccf6dfa3/014bb8c3-cd90-4d76-b0d5-b6da08cadf7a)

I know we're not focusing on this issue currently but its good to know this is a technical hurdle we can overcome.

**Comment by randyabramson** [comment]
@cantsin wow...thanks for exploring this! cc: @blaughman

**Comment by blaughman** [comment]
@cantsin @randyabramson I updated the AC's to reflect our earlier conversation.  Please let me know if there are any questions or concerns.

**Comment by cantsin** [comment]
For bulk printing 100 records, I've gotten the data transfer down to 1 mb on my machine (previously it was 8 to 12 mb). For reference, a single record currently takes ~100kb data transfer. We'll have to test again once this feature is in dev but I'm OK with this amount so far. There are ways to minimize this transfer amount but I think I've gotten most (all?) of the low hanging fruit.

The resulting PDF is 311 pages and 7mb in size.

**Comment by randyabramson** [comment]
Thank you for doing this leg work, @cantsin ! Much appreciated.

**Comment by Jkrzy** [comment]
In the development environment we're seeing a 400 response on navigation to the bulk actions page with 100 or more reports selected.

Initial clue is from cloud.gov logs where I believe Django is raising a `SuspiciousOperation` exception on attempting to render the template.
`   2020-11-06T12:49:35.66-0500 [APP/PROC/WEB/0] ERR Attempted access to '/img/alerts/warning.svg' denied.`
`   2020-11-06T12:49:35.68-0500 [APP/PROC/WEB/0] ERR Bad Request: /form/actions/`

**Comment by Jkrzy** [comment]
I believe it's a path issue in the template, submitted https://github.com/usdoj-crt/crt-portal/pull/738 to remedy.

**Comment by randyabramson** [comment]
@cantsin  -- awesome work on this!  Three questions, if you don't mind:

1. Here, can we change the wording to 'print/save'? 

![print-save.PNG](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/81efee21-169f-4666-89c3-f7a9c48edceb)

2. I noticed that if I select all 15 records from the 'view all table,' the 'print' button is greyed out until I select the 'activity' checkbox:

![greyed-out.PNG](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/bd970950-d0b5-4d29-9437-5996be222109)

- When I select the 'activity' check box, the print button becomes active

![blue.PNG](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/39526e39-852f-4de0-be1e-e3a584de179c)

Can we make both print buttons active regardless of if 'activity' is selected?

3. If all 15 records are selected from 'view all table' the second print button should say 'Print first 100 records'

Thank you!

cc @blaughman

**Comment by blaughman** [comment]
I'm not sure that this will ever happen, but I tested what would occur if I changed the number of records per page to 150 and tried to print them all.  This isn't really a concern for me - I don't think a CRT user would set up their display like this, but I wanted to put it out there.
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/7db52e37-e657-44b1-932e-634ba27828d1)

**Comment by cantsin** [comment]
Thanks y'all. We also have a bug when going to the second (or third ...) page and doing "print all". Not sure how often this may come up but I'll see if I can fix this as well as fixing the above suggestions.

**Comment by randyabramson** [comment]
Thank you @cantsin !!

**Comment by randyabramson** [comment]
@cantsin we see the below items outstanding. Let us know if we should open another ticket for these? Thanks and great work on this!

1. Change button to say print/save
2. Print all button isn't active until 'activity' is checked
3. 'Print all' total should be 100 or less than 100 (depending on number selected)
4. Your mention of changing the records to 150 per page

Anything else?

**Comment by Jkrzy** [comment]
Hi @randyabramson, the fixes for those are on the development instance and ready for UAT. 

I also created another card for a messaging fix related to bulk printing: https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/783

**Comment by blaughman** [comment]
Issues have been resolved.  Function tested on Chrome and Edge and approved.  Moving to UAT.

**Comment by randyabramson** [comment]
Working as expected., but note that it it taking over a minute to create the pdf for 100 reports on staging.

**Comment by cantsin** [comment]
Ooh yeah. It takes a while to render these 100+ pages into a PDF. Some optimization opportunities remain, so let me know if this wait takes longer or is blocking someone from doing what they need to do.

**Comment by randyabramson** [comment]
@cantsin - we don't have feedback yet that specialists would batch this many reports at this time, so I think we are OK.

Randy
