### ISSUE TITLE
Add location name and complaint number to quick view

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#736]
### Problem Statement
As an intake specialist, I need to click into individual reports in order to see complaint ID numbers and complaint location name

### Acceptance criteria
Given when I am on the 'view all table'
When I see all of the records that pertain to the selected filters
Then I am able to click the carrots to see the quick view of each record

Given when I click on the quick view of a particular record
When I see the quick view 
Then I see columns for CONTACT | PERSONAL INFO } LOCATION NAME | COMPLAINT ID

### Mock

![add-to-quick-view.PNG](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/daffe633-b216-45b4-a5dc-bb84af9f3a83)

**Comment by kmanubhai** [comment]
pull request submitted, let me know if need any changes on this ticket

**Comment by blaughman** [comment]
Quick view contains the requested items.
