### ISSUE TITLE
BUG:  Intake Specialist name cannot be removed from 5 tickets

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#737]
### Background

On 10/8, Intake Specialist name contacted Randy and Bill to report that she re-routed 5 tickets from HCE to other sections. In normal behavior, her name would be removed from these tickets, but in this instance, her name stayed with these tickets.

### Randy Triage

I tried to remove Intake Specialist name from these two tickets in both EDGE and CHROME:

I was not able to remove her. I also tried  to change the ticket from OPEN to NEW, but I still was not able to remove her name.

**Comment by Jkrzy** [comment]
This looks to be rooted in how we're using accessible-autocomplete, specifically we're providing no way for a user to select a `null` value or otherwise remove a current assignee.

https://github.com/alphagov/accessible-autocomplete#null-options

**Comment by Jkrzy** [comment]
Clarifying question for @randyabramson and @blaughman 

The issue we're investigating is:

1. The section for a given report was changed but the `assigned to` field was not automatically cleared.

AND/OR

2. User's cannot "un-assign" a report by modifying the `Assigned to` field to empty on the Report details page.

**Comment by randyabramson** [comment]
@Jkrzy  - it is AND. 

The reporter only had only reported number one.

I realized number two when I was trying to remove the reporter's name from the ticket.

It is up to you if you want to tackle number one and two on this ticket or if you just want to solve for number one first and we can create a second ticket for number two.

**Comment by Jkrzy** [comment]
Thanks!

Let's split these up since they're discrete issues. I'll create new cards for each.

**Comment by randyabramson** [comment]
Thank you @Jkrzy

**Comment by Jkrzy** [comment]
Replaced by:
 * https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/738
 * https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/739

cc: @randyabramson
