### ISSUE TITLE
Bug: Clear All filter not working on dev, stage or prod

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#750]
We got a report from intake specialists that the 'Clear All' filters were not working on Prod. 

Bill confirmed the issue.

**Triage**

**Scenario 1 on DEV in CHROME: Clear New/Open filters**
1. I open the admin console at: https://crt-portal-django-dev.app.cloud.gov/form/view/
2. I get redirected to https://crt-portal-django-dev.app.cloud.gov/form/view/?status=new&status=open&no_status=false
3. I press 'clear all filters' button
4. All filters are cleared (new and open)

**Scenario 2 on DEV in CHROME: Clear New/Open + Assignee filters**
1. I open the admin console at: https://crt-portal-django-dev.app.cloud.gov/form/view/
2. I get redirected to https://crt-portal-django-dev.app.cloud.gov/form/view/?status=new&status=open&no_status=false
3. I key in 'jamest' into the 'assignee field and hit 'apply filters'
4. I click 'clear all filters' but nothing happens

* I also tested this issue on DEV and not connected to the CRT network. Same issue.

Randy note: as a quick fix, can we remove logic from the 'clear all filters' button and just link to https://crt-portal-django-prod.app.cloud.gov/form/view/ ?

**Comment by Jkrzy** [comment]
Thanks for replication notes @randyabramson!

I see the origin, introduced [here](https://github.com/usdoj-crt/crt-portal/commit/8278fd0508b3c872e9dad52f2de246079bdcc98d) in https://github.com/usdoj-crt/crt-portal/pull/685. 

In practice this attempts to call `.map` on a String, resulting in 
```red
Uncaught TypeError: updates[key].map is not a function
```

**Comment by blaughman** [comment]
The bug seems to have been resolved.

**Comment by randyabramson** [comment]
@ilodidoj - can we move this to staging?

**Comment by ilodidoj** [comment]
@cantsin @Jkrzy Please add this card to current release 10-20-2020. CC: @randyabramson.

**Comment by ilodidoj** [comment]
@cantsin @Jkrzy I think the https://github.com/usdoj-crt/crt-portal/pull/705/commits/07b2f326e063bd8b0755f9d827523e5798be49fb already taking care of this, correct? In that case, please ignore my earlier request.
