### ISSUE TITLE
Don't re-direct on 404 page not found

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#752]
Follow-up to https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/705

We've updated the 404 error template but need to address redirects to SSO. 

# Acceptance Criteria
Given that I am on the civilrights.justice.gov domain
When I hit a page that does not exist (either cause by human typo, broken link or other non-script related failure)
Then I see a 404 page

Given that I am on the civilrights.justice.gov domain
When I hit a page that is access restricted
Then I'm re-directed to login

### Technical notes
We're currently using https://django-auth-adfs.readthedocs.io/en/latest/middleware.html.
Can we modify `LOGIN_EXEMPT_URLS` such that we serve 404 responses instead of redirecting?
Should we not use the middleware and instead enforce authentication on each associated view?

**Comment by randyabramson** [comment]
@Jkrzy  - I noticed that I get redirected with this URL https://civilrights.justice.gov/weffw

Maybe that page is considered 'restricted' but maybe it is part of your first AC above.

**Comment by randyabramson** [comment]
Works on EDGE, CHROME and mobile. Moving to UAT complete
