### ISSUE TITLE
502 Bad Gateway: Registered endpoint failed to handle the request Error on csv data extract

### ISSUE THREAD

**Issue by ilodidoj** [18F/crt-portal#756]
As and Portal Admin user I should be able to export data to csv using the portal admin function.  

Getting 502 Bad Gateway: Registered endpoint failed to handle the request error when exporting all current records about 30,300 records using the portal Admin console on chrome  or EDGE browser.

![image.png](https://images.zenhubusercontent.com/5d374c9d0efb727bd5a01afd/6f7183eb-4d60-4c23-ad72-7c4de61c2d15)

**Comment by ilodidoj** [comment]
Kibana log for reference on 502 error https://logs.fr.cloud.gov/app/kibana#/dashboard/5e33ed90-a428-11ea-83da-35cbb6cfbe36?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(description:'',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logs-app*',key:rtr.extra.x_cf_routererror,negate:!f,params:(query:endpoint_failure,type:phrase),type:phrase,value:endpoint_failure),query:(match:(rtr.extra.x_cf_routererror:(query:endpoint_failure,type:phrase))))),fullScreenMode:!f,options:(darkTheme:!t,hidePanelTitles:!f,useMargins:!t),panels:!((embeddableConfig:(),gridData:(h:13,i:'1',w:40,x:0,y:0),id:'915ba9f0-8e21-11ea-9f02-85d56bf05eb2',panelIndex:'1',type:visualization,version:'6.8.1'),(embeddableConfig:(),gridData:(h:16,i:'2',w:40,x:0,y:13),id:%5Bapp%5D-All-ERRORs,panelIndex:'2',type:search,version:'6.8.1'),(embeddableConfig:(),gridData:(h:15,i:'3',w:40,x:0,y:29),id:ebc1fc20-a427-11ea-b73b-3368ede4f96a,panelIndex:'3',type:search,version:'6.8.1')),query:(language:lucene,query:''),timeRestore:!t,title:'CRT-+All+erros+and+warnings',viewMode:view)

**Comment by randyabramson** [comment]
Just updating this card...per our standup today, we will limit exports for only one month.

Product owners don't need exports for greater than one month and Anthony is fine with one month as well.

I am taking this out of the current sprint.

cc: @blaughman @Jkrzy @ilodidoj

**Comment by randyabramson** [comment]
@ilodidoj  - can we add this to READY FOR DEV?

**Comment by randyabramson** [comment]
@ilodidoj  I don't have permissions to test this. Can you take a look and move to UAT complete if it passes?

**Comment by ilodidoj** [comment]
@randyabramson this part only can be verified in production, due to the amount of data is needed. I will check on production after release today.

**Comment by randyabramson** [comment]
thank you @ilodidoj
