### ISSUE TITLE
Error pages must be accessible

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#760]
We implemented a new foundational error template in https://github.com/usdoj-crt/crt-portal/pull/698 but missed a handful of issues surfaced via checking w/ [Accessibility Insights](https://accessibilityinsights.io/).

These accessibility concerns now persist across all errors rendered with this base template. 

We will:
- [ ] Identify all accessibility issues on custom error pages with [Accessibility Insights](https://accessibilityinsights.io/).
- [ ] Remediate all reported issues 

Initial results from running AI on the custom error page in https://github.com/usdoj-crt/crt-portal/pull/710

![Screen Shot 2020-10-23 at 11.08.29 AM.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/386c5eb2-4264-4b3f-8714-6c84e011ce4c)

**Comment by randyabramson** [comment]
@timoballard  I see the <alt> text in the source code for the images, so I think we are good there.  I tried to install Google Speak to listen to how the text plays for the semantic issue, but I don't think Google Speak can read pages on DEV. Can you please advise here?

**Comment by ilodidoj** [comment]
@randyabramson another alternative is windows narrator. You can turn on using Windows LOGO Button + CTL + Enter. Then hit tab on the page you are testing.  Blind or visually impaired user use tab to content location.  Once done, use the same buttons to turn it off.

**Comment by randyabramson** [comment]
thank you @ilodidoj

**Comment by randyabramson** [comment]
Question on this one:

1. When I mouse over the images, I don't see the alt text. Should I? I do see the alt tags in the code.
2. When I tab on these error pages using Windows Narrator, I hear the link text read, but not the static text. Is that expected behavior?

Randy

@Jkrzy  @cantsin @timoballard @ilodidoj

**Comment by Jkrzy** [comment]
1. Expected, beyond screenreaders -- the `alt` text is rendered if the image cannot be displayed. Some browsers, like IE may render the `alt` attribute on mouse hover but that is better implemented with a `title` attribute if it's functionality we want.

2. Expected, the tab key typically navigates between interactive elements on the page. Depending on your browser/screenreader other keys provide access to the static content on the page.

**Comment by randyabramson** [comment]
Alt text in place and interactive elements read semantically on DEV. Moving to UAT Complete

**Comment by randyabramson** [comment]
Verified on staging

**Comment by randyabramson** [comment]
Verified on prod
