### ISSUE TITLE
bulk action design tweaks

### ISSUE THREAD

**Issue by cantsin** [18F/crt-portal#761]
# Update:
## Change colors on the "actions" bar so it stands out more
- Background of bar should be blue-warm-80v #162E51
- text and check mark white
- "Actions" button can be blue-warm-10 #E1E7F1 with blue-warm-80v text and blue-warm-30v hover #81AEFC

# Mockup
_The table is not the most recent design, but just pay attention to the bar at the bottom_

![Screen Shot 2020-10-23 at 1.48.09 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/b925cbc2-407d-474c-8677-bfc4afa7bc00)

**On hover**
![Screen Shot 2020-10-23 at 1.48.19 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/619cc1fa-25d6-4863-b00f-6aef25dec367)

**Comment by AvivaOskow** [comment]
![Screen Shot 2020-10-23 at 11.24.30 AM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/27948e26-60cc-479a-89b2-811963e4c5ba)

**Comment by randyabramson** [comment]
Colors adjustment works on CHROM and EDGE
