### ISSUE TITLE
Email Roll Out Strategy and Risk Identification

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#764]
Roll Out Strategy and Risk Identification

**Comment by Jkrzy** [comment]
@randyabramson - Is this card fulfilled by the word doc we've collaborated on as a team?

**Comment by randyabramson** [comment]
@Jkrzy yes, I think you are right. I think some other cards will spill out of your technical analysis and some specific use cases will come out of the interviews. Beyond that, I think the attached doc clearly outlines risks and fleshed out pitfalls.

Closing this.

[https://app.zenhub.com/files/183258764/3c8780dd-98b6-4940-bcb1-c478fbba6d90/download](https://app.zenhub.com/files/183258764/3c8780dd-98b6-4940-bcb1-c478fbba6d90/download)
