### ISSUE TITLE
Onboard TimB

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#771]
Welcome Tim!

- [x] Invite to slack channels
- [x] Invite to 18F managed GitHub teams and zenhub
- [x] DOJ invite to collaborate on crt-portal repo
- [ ] Cloud.gov access if/when needed
- [x] Code walkthrough and local dev setup
- [x] Invite to standing meetings

**Comment by randyabramson** [comment]
@ilodidoj Do we need to think about equipment for Tim? I know there's also a clearance process with Albert's team.

**Comment by ilodidoj** [comment]
@randyabramson it depends on DOJ-CRT and GSA/18f engagement standpoint as well as his role on the project.  If this is similar to James and Joe's role, then we follow the same steps we did for James/Joe.  I am not sure we created a JCON account for either of them.  JCON device only applicable after a CRT JCON account is created.

**Comment by Jkrzy** [comment]
Imran's right, Tim does not need a JCON account or equipment.
