### ISSUE TITLE
Visual cue of sections selected on view all table

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#776]
**Problem statement:** As an intake specialist, I need to select the section drop down menu in order to see all of the sections I've previously selected. 

**Design reference** at https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/621

**Acceptance criteria:**

Given that I am on the 'view all table'
When I select one section from the section drop down and I click the 'update view' button
Then I see that section name in the top of the section drop down 

Given that I am on the 'view all table'
When I select two sections from the section drop down and I click the 'update view' button
Then I see two section names separated by a comma in the top of the section drop down 

Given that I am on the 'view all table'
When I select three or more sections from the section drop down and I click the 'update view' button
Then I see the word 'multi' in the top of the section drop down 

Given that I am on the 'view all table'
When I deselect all sections from the section drop down and I click the 'update view' button
Then I see the words 'view sections' in the top of the section drop down 

Assumptions: Rules for 'default section' for each user still applies

**Comment by emilycryan** [comment]
**Dropdown Options**

When the top nav drop down has...

No selection:
- As-is, View sections

One selection:
- “ADM” (or whatever the section is selected)

Two selections:
- “ADM, CRM” 
    - Listed alphabetically
    - Separated by comma and space

Three + selections:
- “Multi (x)”
    - “x” is the number selected as long as the number is 10 or less (aka, not all)

All selections:
- All selections are the same as no selections (shows all records)
    - Denote with “Multi (11)”

**Comment by randyabramson** [comment]
Works on Chrome and Edge. Nice work @timoballard  on the counter! Moving this to UAT
