### ISSUE TITLE
Identify technical tasks for Email integration 

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#777]

**Comment by Jkrzy** [comment]
On the technical front, we'll start simple:

* Credentials will be stored in environment variables
* We'll use Django templates to render subject and message content while supporting i8n
* We'll send mail within the request->response process
* We'll include `unsubscribe` links in all outbound messages to external parties
  - [ ] Decide if we'll Implement Django side or Mailgun side
* We'll use [AnyMail](https://github.com/anymail/django-anymail/) to provide a Django`Email backend` supporting Mandrill
* We'll write tests using [Django's provided email testing functionality](https://docs.djangoproject.com/en/2.2/topics/testing/tools/#email-services)

**Comment by cantsin** [comment]
>  Decide if we'll Implement Django side or Mailgun side

Shouldn't this be Mandrill? In any case, I'm inclined to use unsubscribe if it exists already on Mandrill (and cursory Googling indicates it does, at least for "Transactional Email") -- any particular concerns around this feature?

**Comment by Jkrzy** [comment]
Yes! Definitely not `mailgun`.

Leaning towards that as well, for the decision point I'd want to confirm
- [ ] Can we include Mailgun's [unsubscribe link ](https://mandrill.zendesk.com/hc/en-us/articles/360039335713-Can-I-add-an-automatic-unsubscribe-link-to-Transactional-Email-emails-)via the API while using django templates/send_mail (I _think_ yes) 
- [ ] Can the `Rejection Blacklist` be exported from Mailchimp (I _think_ yes)

**Comment by cantsin** [comment]
1. https://anymail.readthedocs.io/en/stable/esps/mandrill/#batch-sending-merge-and-esp-templates implies that we don't have to do anything special if we're using a built in merge tag, but we'll have to test to confirm. We might also want to document what we do here, so should we switch to another email provider, it will be easier to undo. 

2. I believe so as well. https://mailchimp.com/developer/api/transactional/rejects/ (may have a pretty severe limitation: limited to 1000 without any way to paginate, as far as I can see)

**Comment by Jkrzy** [comment]
Closing this one after these initial discussions with team, we'll refer back to it as we implement the first slice of email functionality.
