### ISSUE TITLE
Bulk printing success message must reflect number of selected reports

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#783]
Origin: https://github.com/usdoj-crt/crt-portal/pull/742#pullrequestreview-531771199

Upon printing reports the application renders a success message containing the number of selected reports. 

Currently, when you select Print first 100 reports the generated success message says

> Selected correspondent, issue, description for 15 reports

This message should reflect and confirm the user's actions on the previous page. 

"Printed `<fields>` for `<report count>` reports"

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.
