### ISSUE TITLE
Missing trailing comma  for empty  internal_summary  column

### ISSUE THREAD

**Issue by ilodidoj** [18F/crt-portal#785]
User experience missing column error using the data extract file generated from CP export. There are 47 headings in the current export, but in the first row (and many following it), there are only 46 columns. It appears the export does not include a trailing comma if the there is a protected_class listed without a internal_summary, i.e. if summary is blank or no summary.  Below are dev example exported of data showing missing trailing comma (,) for the record number 456 at the end. Example record 444 has correct trailing coma.

"456","","","","","","","","","","","voting","","","","new","APP","","","","","","","","","","","","","","","","","","","456-WLS","2020-11-13 14:12:02.644506+00:00","2020-11-13 16:13:33.984777+00:00","2020","20","1","letter","joe","","",""

"444","","","","","","","","","","","workplace","","","","new","APP","","","","","","","private_employer","","","","","","","","","","","","444-MJF","2020-10-02 16:49:04.481295+00:00","2020-11-13 16:13:33.984777+00:00","","","","","joe","","","","testing summary"

**Comment by randyabramson** [comment]
@ilodidoj could use your help confirming this on staging

**Comment by randyabramson** [comment]
Verified by @ilodidoj  - closing now
