### ISSUE TITLE
Email form letter response to a single complainant.

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#787]
## Narrative
As a CRT User, I want to email a form letter response to a complainant using the portal's interface so that I can respond to complainants more efficiently.

## Acceptance Criteria
1) Given I am on the 'Contact Complainant' modal
when I select a form letter from the drop down menu
then I see the greyed out 'Send' button become blue and available for selection

2) Given I am on the 'Contact Complainant' modal
when I have selected a form letter and click the blue 'Send' button
then an email is sent to the email address provided by the complainant

3) Given I am on the 'Contact Complainant' modal
when I have successfully sent a form letter response to a complainant
then I am returned to the complaint detail page 
AND I see the validation message 'emailed [form letter] form letter to [complainant's email address]' at the top of the complaint detail page
AND the same success validation message in the 'Activity' log.

## Assumptions
- The language 'Response: Your Civil Rights Division Report - [Complaint ID#] from the [Assigned] Section' will be the subject line of the email.
- The required unsubscribe text will automatically be added to the bottom of every email after the CRT User clicks the 'Send' button

Error state
Mail not sent error - CRT thought we sent it, but MailChimp did not.

**Comment by randyabramson** [comment]
Updated in ticket 803

**Comment by blaughman** [comment]
Superseded by card 803.
