### ISSUE TITLE
Parity between Staging and Live instances

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#788]
As a developer, I want the Staging environment to be functionally equivalent  to production so that manual and automated testing can be conducted with confidence that the results in Staging are consistent with a user's experience on production.

### We'll know we're done when:
- [x] We've inventoried and documented differences between `Staging` and `Production`
  * SSO
  * Cloudfront
  * What else? [Look at `IF ENV == 'PRODUCTION'` code branches]
- [x] For each difference, we've created a card to bring Staging into line with Production or documented an alternative approach

**Comment by cantsin** [comment]
After looking at the code, there are a couple of other slight differences but I think these are safe to ignore:

- [Prod] Google Tag manager (includes Google site verification tag) 
- [Non-prod] PII banner

**Comment by Jkrzy** [comment]
Three main components from audit results, **SSO**, **Cloudfront**, and **Analytics**. For each I recommend we implement them in the staging environment. 

The `Test site` banner, on all environments besides production, is excluded from consideration.

## Single sign-on
* Only in-use on production
* Handles all authentication checks
    * Currently cannot be tested in staging or development environments

### Recommendation
Implement SSO on staging environment giving us the ability to test authentication paths and workflows in a non-production environment.

## Cloudfront
* Only in-use on production
   * Caching behavior cannot be tested in development or staging environments
   * Requires a domain to establish e.g. `crt-portal-staging.justice.gov`

### Recommendation
Work with jmd for DNS assistance and implement [external domain service w/ CDN](https://cloud.gov/docs/services/external-domain-service/) on staging giving us the ability to test caching behavior in a non-production environment.

## Analytics
* Google Tag manager, Google Analytics, and Digital Analytics Program only being loaded in production
  * Implementation and analytics cannot be tested in development or staging
    
### Recommendation
Implement analytics in staging environment, giving us the ability to test implementation in a non-production environment

**Comment by Jkrzy** [comment]
cc: @ilodidoj, @cantsin, @timoballard, @randyabramson, @blaughman

Would love :eyes: on the initial report-out and recommendations above towards closing this card out. If finalized, each recommendation would be its own card for implementation.

**Comment by randyabramson** [comment]
@Jkrzy I think your approach is great here.

RE: Google tag manager on Staging, it is possible - https://support.google.com/tagmanager/answer/6311518?hl=en , but will require some heads down time.

**Comment by cantsin** [comment]
Since we are going through all of this trouble anyway, would it be worth it to add Cloudfront and/or Analytics to dev as well? (I'd love to do SSO on dev but that'd lock us out, unfortunately).

**Comment by randyabramson** [comment]
Good points, @cantsin 

For me, Google Analytics on dev or staging would be great...looks like you can do that with 'profiles' https://softwareengineering.stackexchange.com/questions/139603/google-analytics-with-multiple-environments

**Comment by ilodidoj** [comment]
Do we also need to do anything for TouchPoint https://touchpoints.digital.gov/ testing? I believe this only set for production now on the touch point side.

**Comment by randyabramson** [comment]
Good call, @ilodidoj 

I can define Staging URLs in Touchpoints for testing. For me this is a 'nice to have,' so it's up to you all based on complexity.

**Comment by Jkrzy** [comment]
Cards for next phase of this work created, closing this one out.
