### ISSUE TITLE
End-to-End test for Report submission spike

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#789]
As a developer, I need an automated test which progresses through, confirming the behavior of, the report submission process so that I can be confident my changes are not unexpectedly impacting it.

We're already running a development in the test pipeline as well as running tests against staging AND production upon deploy. We also previously approximated this with `pa11y-ci` [but greatly reduced the scope of our usage](https://github.com/usdoj-crt/crt-portal/pull/630) due to a high rate of intermittent test failures while attempting to navigate the submission form 

## We'll know we're done when
- [x] We've researched, discussed, and determined an approach for an automated test which progresses through the entire Report submission process
- [x] We've created a card to implement the E2E test

**Comment by randyabramson** [comment]
@Jkrzy -- Just out of curiosity, is this automated script part of the New Relic tools or something written by 18F developers?

**Comment by Jkrzy** [comment]
@randyabramson, that's an option we'll look at. Using  NewRelic's [scripted browser testing ]( https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/scripting-monitors/writing-scripted-browsers
). 

The focus of this card is making a decision on where and how to enhance our test suite and creating follow-up cards to implement and/or revise any prototypes developed in this card so they're ready for release.

**Comment by Jkrzy** [comment]
Going to work in [this doc](https://docs.google.com/document/d/1K0gv-Rk-G9PWAg9VMCYerTUqO9wH7xdRJ-lyXBm_1gs/edit?usp=sharing) so we can comment and collaborate!

**Comment by Jkrzy** [comment]
We'll 

1. Add an additional layer of E2E testing by implementing a foundation for Playwright testing
We'll run these against staging in CI as part of the release process

**Comment by Jkrzy** [comment]
Created #817 to tackle implementation of this

**Comment by randyabramson** [comment]
@Jkrzy  we can close this ticket, correct?

**Comment by Jkrzy** [comment]
:thumbs-up:
