### ISSUE TITLE
Output application logs in JSON when deployed

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#793]
As a developer, I want our application logs structured w/ JSON so that when they're ingested by cloud.gov they are super easily searchable in Kibana and so multi-line output doesn't get parsed as multiple log entries.

https://cloud.gov/docs/deployment/logs/#structured-logging

Right now we're outputting plaintext with a bit of custom formatting, this works in _most_ instances but is lacking when exceptions or other less-than-common events occur.

We'll look at using https://github.com/madzak/python-json-logger

We'll know we're done when
- [ ] Our log output is structured (JSON) and being successfully parsed by cloud.gov.

**Comment by Jkrzy** [comment]
@timoballard, @ilodidoj this looks to be working for logs that we're outputting from our views but exceptions are still being output as multiple lines on the dev instance.

**Comment by ilodidoj** [comment]
@Jkrzy @timoballard does this mean, we have to add "formatter": "json", before line 366 of settings.py? i.e. in the loggers section of the code?

**Comment by timoballard** [comment]
@ilodidoj - we can pair on this if you'd like

**Comment by ilodidoj** [comment]
@timoballard sure, we can pair on this one. Thank you.

**Comment by ilodidoj** [comment]
@Jkrzy is it possible to have a screen shot of the current log example that you are referring and some details on how this should format when JSON format applied.

**Comment by Jkrzy** [comment]
This one isn't quite resolved yet, exceptions are still being output as multiple lines on the dev instance.

@randyabramson, do you want to re-open this one or should we make a new card?

cc: @ilodidoj

**Comment by randyabramson** [comment]
I will re-open. Thanks @Jkrzy
