### ISSUE TITLE
Email Integration - soft tasks

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#798]

**Comment by randyabramson** [comment]
- [ ] Is email foiable question? (RANDY)
- [ ] Work with Devs on 'export' plan from MailChimp to 0365 (Randy)
- [ ] Establish OKRs (Randy)
- [ ] Explore uploading CRM R1 letter (90% is R1) as form letter – talk to Jim or Tyneeta in CRM RANDY Sprint 33 (need dev for ID number, subject line, etc.) (Randy)
- [ ] Work with Malika and Dan on reviewing form letters (Randy)
- [ ] Remember Make sure record has ‘Email sent via {service – MailChimp or 0365} is in the activity section 
 (Randy)
- [ ] Inventory of boxes (Darren?) + Explore with DEVs if we need new Email addresses for MailChimp vs. Outlook (Randy)
- [ ] Review design of language on site for ‘if we don’t have your contact info (read: EMAIL), we can’t communicate with you” (Emily)
- [ ] Work with Deep Dive - Assess risk vs. reward of bulk – example 15 at a time vs. 200 at a time  (Randy)

**Comment by Jkrzy** [comment]
We can't handle inbound email with Amazon SES.

[reference](https://docs.aws.amazon.com/general/latest/gr/ses.html):

> Email Receiving Endpoints
> 
> Amazon SES doesn't support email receiving in the following Regions: US East (Ohio), US West (N. California) Asia Pacific (Mumbai), Asia Pacific (Seoul), Asia Pacific (Singapore), Asia Pacific (Sydney), Asia Pacific (Tokyo), Canada (Central), Europe (Frankfurt), Europe (London), Europe (Paris), Europe (Stockholm), Middle East (Bahrain), South America (São Paulo), and **AWS GovCloud (US).**

**Comment by Jkrzy** [comment]
@randyabramson, not an immediate blocker but we'll need `FROM` and `REPLY-TO` addresses provided to us for implementation

**Comment by randyabramson** [comment]
Got it @Jkrzy thanks for the heads up.

**Comment by randyabramson** [comment]
@Jkrzy quick question - the addresses don't need to be configured at all on our side, correct? These will be configured on the AWS side, right?

**Comment by Jkrzy** [comment]
@randyabramson, the AWS portion is verification of those email addresses/domain once they've been selected. 

Deciding the from and reply-to email addresses is on our/crt's side.

**Comment by randyabramson** [comment]
Got it, @Jkrzy --- it'll definitely be a @usdoj.gov domain. I'll get back to you with the exact addresses soon.

**Comment by randyabramson** [comment]
Closing since we have a policy in place for no reply + boxes
