### ISSUE TITLE
'Assigned to' not listing name on single report assignee changes - 

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#799]
Referencing card 712:

I noticed that on 'single report changes', that if I clear out an assignee, then enter a new assignee and hit 'apply changes' that the top status says 'Successfully updated Assigned to.' without listing the name.

**Comment by randyabramson** [comment]
I see this happening in EDGE and Chrome

**Comment by cantsin** [comment]
I want to fold into some design changes into this one, if that's OK. Aviva says:

#### Assigned to
- Should the list of names appear if you don’t start typing? Currently nothing shows up unless you know who to start typing for
- Can we make them not bold except when you hover?

#### Currently
![Screen Shot 2020-11-09 at 4.49.34 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/069487b7-b735-4fc3-a763-6a9820af29c3)

**Comment by randyabramson** [comment]
@cantsin I am fine with both of your suggestions above. Thank you!

**Comment by randyabramson** [comment]
@cantsin - I just tested this on DEV in EDGE and Chrome. When I clear out an assignee and then click 'apply changes,' I still do not see the name populating in the status header in the top right (Successfully updated Assigned to.). See attached grab:

![assigned-to.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/ec6fd50a-3c92-421b-bff1-5d21c24d2d7b)
