### ISSUE TITLE
move apps in Acquia

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#81]
**Describe the defect**
The cloud subscription seems to be on the app level and not the org level. We need to move what we are working on in  DOJportal needs to be deployed in DOJ Civil Rights.

That will extend the sandbox while the account is upgraded. 

** DoD ** 

- [x] Deploy our usdoj-crt Drupal Acquia Codebase to the "DOJ Civil Rights App" under the Acquia Cloud org.
- [ ] Delete the "DOJ Portal app" under the Acquia Cloud org.
- [x] Update drush config to match "DOJ Civil Rights app".

**Comment by alexsoble** [comment]
Steps: 

1. Deploy our usdoj-crt Drupal Acquia Codebase to the "DOJ Civil Rights App" under the Acquia Cloud org.
2. Delete the "DOJ Portal app" under the Acquia Cloud org. 
3. Update drush config to match "DOJ Civil Rights app".

Talked this through with @LindsayYoung.

**Comment by alexsoble** [comment]
1a. Some type of database step and possibly a UUID change.

**Comment by alexsoble** [comment]
From Acquia Support:

```
Hi Alex,

It looks like the dojportal application is a free tier and not associated with this application.

If you are done with it, the owner who is Lindsay Young should be able to cancel the application. They should be able to follow these directions: https://docs.acquia.com/support/billing/#cancellation

Please let us know if you have other questions.

Regards,

Marran Linsky
Team Lead, US East | Acquia Global Support
```

@LindsayYoung — could you assign yourself to this issue since you are the application owner?

**Comment by alexsoble** [comment]
@LindsayYoung Sounds like we're just going to let the "old" app expire – shall we move this to Done?

**Comment by LindsayYoung** [comment]
I can't find the delete interface, I have just relabeled the old one, "don't use this" or something like that- it should be deleted next week anyway. Does anyone object to calling this done?

**Comment by alexsoble** [comment]
@LindsayYoung Yup, no problem with that! We closed this card during standup for that exact reason.
