### ISSUE TITLE
Print confirmation page (Design Audit)

### ISSUE THREAD

**Issue by cantsin** [18F/crt-portal#811]
#### Print?

- [ ] Can we add a print button or an option to email themselves the confirmation page? I know this was out of scope before but wondering if it could be added soon

James says: when doing bulk print I made sure the confirmation page still looked reasonably good to print. It could be easy to add a button that pops up a print dialog. But this is also a good opportunity to refine how the printed confirmation page looks, right now its a bit "vanilla" in terms of styling.

**Comment by cantsin** [comment]
This one needs a bit more discussion with the team, I think. It's going to be easy enough to add a print button for the confirmation page but we may also want to take a more holistic look at how we're doing print on this page -- anything we want to tweak? CC @blaughman @randyabramson

**Comment by randyabramson** [comment]
@cantsin did you have 'style' suggestions? TBH, I always thought this page was clean and straight forward, but if you have suggestions, I'm all ears!

**Comment by emilycryan** [comment]
My thoughts:

- The header area takes up half of the first page which is a waste of paper/print ink (see my image) I'd remove the 1-7 step thing and really shrink down the name and logo so it's much smaller. 
- The boxes around the sections are weird especially when the box breaks across two pages - a simple horizontal divider line between sections would work far better and look less odd on the breaks. Also, less ink wasted
- The footer def doesn't need to be there. Two pages of the printed report are footer. The only thing we may want to keep is the privacy policy which would be fine (perhaps at a very small font)

This is just some basic styling suggestions - I'd welcome @AvivaOskow's thoughts here. 

![Screen Shot 2021-01-06 at 8.19.48 AM.png](https://images.zenhubusercontent.com/5f970c483cdc923d98dfa265/2539f34c-4d60-4e18-8767-00f22429c57f)

CC @cantsin @randyabramson @blaughman

**Comment by randyabramson** [comment]
I like all of these suggestions, @emilycryan . I think @cantsin can fine tune what goes into the PDF (footer, etc.). Also, I assume we would just have a link on the word 'print' for print functionality as opposed to a print button?

**Comment by emilycryan** [comment]
@randyabramson where is the word "print"? I don't see it on the page. 

I would prefer a button only bc sometimes people can miss the inline text links, esp if they're not expecting or looking for them. But @AvivaOskow tell us what you think!

CC @cantsin

**Comment by cantsin** [comment]
We can absolutely tune whatever goes into this PDF. I agree that we should reduce (or eliminate) the current header/footer vertical size. 

Adding print is for the confirmation page, I believe (_after_ hitting submit). Here's what it looks like currently:

![localhost_8000_report_](https://user-images.githubusercontent.com/3013175/103801131-27092700-5002-11eb-8354-72fefff76e31.png)

We have not done any print modifications on this page (other than hiding the "this is a test site" banner) so it looks almost identical to the on-screen version. (If you uncheck "show background graphics" on your print dialog then you'll see more white).

Here's what the above revisions might look like (very rough mockup done in 5 minutes so it's missing a lot of polish). One thing in particular is that I've removed some left and right margins as that blank space is not too useful on paper (but of course I defer to design here).

![localhost_8000_report_ (1)](https://user-images.githubusercontent.com/3013175/103802099-7f8cf400-5003-11eb-8642-2549c82b35b2.png)

**Comment by emilycryan** [comment]
Ooo this is a nice upgrade @cantsin probably just a few tiny things left from @AvivaOskow to weigh in on but otherwise I think it's in far better shape. We also need a button somewhere to allow users to see the option to print this. I'd probably put it near the top. 

Finally, we can probably axe the "How can we improve this site" bar at the very bottom - again, it's not functional and is just adding noise and printing ink. 

CC @randyabramson @blaughman

**Comment by AvivaOskow** [comment]
I do think @emilycryan 's version is much better! I agree with the changes here. I do think either Jacklynn or I designed a printed version of this page already though...let me see if I can find it and attach. @cantsin do we have more control over how the printed version would look than this? I would maybe do even more to save space/make more print friendly.

**Comment by cantsin** [comment]
@AvivaOskow we can do almost anything here! (within reason ... :sweat_smile:) We can def eliminate more space and various bits that don't belong. Looking forward to seeing the designed version!

**Comment by randyabramson** [comment]
Thanks for the effort on this, gang! As I mentioned, the public has asked for this feature, so I'd love to deliver it.

**Comment by randyabramson** [comment]
@cantsin @blaughman - when testing this on DEV, I see the DEV url on the bottom of each page::
https://crt-portal-django-dev.app.cloud.gov/report/

Assuming that on PROD, we might see the civilrights.justice.gov url, but either way, I don't see the URL in the mocks above.

Also, maybe not a show stopper, but on the Confirmation page, we have text that says 
"If you want a copy of this report for your personal records, save or print a copy of this page."

We now supply a 'print' button, and the print function leads to a PDF save, but I wonder if any users might be searching for a 'SAVE' button?

Maybe we change the text and the button text to say 'print/save' PDF or the like?

cc @emilycryan for her input.

**Comment by randyabramson** [comment]
@cantsin  note that the URL display mentioned above only happens in the EDGE browser

**Comment by emilycryan** [comment]
@randyabramson what if the button says 'CREATE PDF' instead? That way we don't have to have a button label that might be confusing and it's then up to the user to decide if they want to print or save the PDF. And it's accurate - it's literally creating the PDF that the user may print or save, as stated in the instructions. 

CC @AvivaOskow @cantsin

**Comment by AvivaOskow** [comment]
@emilycryan I would maybe say "Print or save" instead of "Create PDF" because I think there are folks who won't know what a PDF is exactly, the language feels more general

**Comment by emilycryan** [comment]
@AvivaOskow Yeah sounds good - I think I just didn't like the PRINT/SAVE but I do like PRINT or SAVE in the button label. 

CC @randyabramson @cantsin

**Comment by randyabramson** [comment]
Sounds good @cantsin @cantsin @AvivaOskow 

I will make a reminder to myself to change this button text for the next sprint.
