### ISSUE TITLE
Add CRM form letters 

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#815]
These two form letters are the primary responses utilized by the Criminal Section.  These two responses should be added to the 'Contact Complainant' form letter menu.

CRM - R1 Form Letter
[https://app.zenhub.com/files/183258764/3e242ff5-70dd-4b9d-918c-807cb9e51795/download](https://app.zenhub.com/files/183258764/3e242ff5-70dd-4b9d-918c-807cb9e51795/download)

CRM - R2 Form Letter
[https://app.zenhub.com/files/183258764/17933906-4c0f-4a50-9a19-699cc4a4fe76/download](https://app.zenhub.com/files/183258764/17933906-4c0f-4a50-9a19-699cc4a4fe76/download)

CRM - R1 Form Letter (Spanish)
[https://app.zenhub.com/files/183258764/e0605dbb-820b-479b-bfed-592fcbc40335/download](https://app.zenhub.com/files/183258764/e0605dbb-820b-479b-bfed-592fcbc40335/download)

CRM - R2 Form Letter (Spanish)
[https://app.zenhub.com/files/183258764/856bc505-8e5a-46f6-9ffb-283e42920174/download](https://app.zenhub.com/files/183258764/856bc505-8e5a-46f6-9ffb-283e42920174/download)

**Comment by blaughman** [comment]
@randyabramson @emilycryan 
Please check the content of the attached responses.  My only concern is the phrase "medical reports if available" in the R2 letter.  A public user will not be able to attach any medical reports to the complaint.  When these letters are approved by you, I will send them to Marta for translation.

**Comment by randyabramson** [comment]
@blaughman - here are my comments:

R1 Letter

* In "The Federal Bureau of Investigation and other law enforcement agencies conduct investigations for the Division." - Assuming this should say "Civil Rights Division" instead of just 'the Division"

* I know internally we often capitalize 'Section' and 'Division' internally...should we be doing that here?

* On the bullet points, I don't think we should end those phrases with ';' - bullet points negate the need for a semi colon (also, on the 4th bullet point, we don't need the 'and' at the end

* Assuming the '/s/' is where the Specialist's name is filled in?

R2 Letter

* "You contact the Civil Rights Division on" - should be "You contacted the Civil Rights Division on"

**Comment by emilycryan** [comment]
After reviewing the docs, I agree with all @randyabramson points except the semi-colon/bullet point thing only bc the bullet points are sentence fragments and as such, the semi-colon is often still used, esp. in traditional communication stylings. Generally though, it should be consistent with other dept communications, which I assumed was on the more traditional side. 

My recommendation on letter R2 was to change the area to style like this:

"The information that you furnished is insufficient to permit us to determine the existence of a possible violation of federal criminal civil rights statutes.  Therefore, we are unable to authorize an investigation of your complaint at this time.  However, we will consider the allegation further if you provide specific information concerning the circumstances involved in your complaint. 

You should include:
- the name of the person injured; 
- medical reports if available; 
- a narrative involving the allegations leading up to and including the incident; 
- the name of any possible witness and
- the date of the incident and any other information you deem relevant to this incident. 

Please resubmit this information to our online complaint portal https://civilrights.justice.gov/ and reference your complaint number, listed in the subject line of this email. "

CC @blaughman

**Comment by blaughman** [comment]
@randyabramson @emilycryan I can make those changes, but I'm still concerned that we tell them they can submit medical reports when we don't have a mechanism to allow this transaction to occur.  I'm wondering if we should omit that language since the public's ability to add attachments may never happen.

**Comment by randyabramson** [comment]
@blaughman would it be ok to say 'include references to medical reports'?

**Comment by emilycryan** [comment]
I like @randyabramson suggestion - I do think it's important to include something around the medical records esp. for sexual offenses. CC @blaughman

**Comment by randyabramson** [comment]
@blaughman are these 'ready for dev' at this point?

**Comment by blaughman** [comment]
They are.  I'm waiting on the translations from Marta.

**Comment by blaughman** [comment]
@cantsin James - the Spanish versions of the form letters have been added.  Also, there was a minor edit in the R2 form letter.  The correct version is attached above.  Thanks

**Comment by cantsin** [comment]
Great, thanks! Do we have a better name for these templates than `CRM - R1 Form Letter` or `CRM - R2 Form Letter`?

**Comment by randyabramson** [comment]
@cantsin - believe it or not, that is what CRM calls them.

**Comment by cantsin** [comment]
Thanks! Sure thing, just wanted to double check.

**Comment by blaughman** [comment]
Function works as intended in both Chrome and Edge.  Moving to UAT.
