### ISSUE TITLE
Implement an E2E report submission test with playwright

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#817]
Building on #789

As a developer, I need an automated test which progresses through, confirming the behavior of, the report submission process so that I can be confident my changes are not unexpectedly impacting it.

We'll implement a test case encompassing the entire Report submission process using [playwright](https://github.com/microsoft/playwright-python).

Test case -- As a user I:
---
1. GET /reports/
2. Fill the required fields
3. Submit and Progress to Primary concern
4. Selecting `Voting`
5. Submit and Progress to Primary Concern cont.
6. Select No
7. Submit and Progress to Location details
8. Fill required fields
9. Submit and Progress to Personal characteristics
10. Select ‘Age’
11. Submit and Progress to Date
12. Fill required fields
13. Submit and progress to Personal description
14. Fill required fields
15. Submit and progress to Review your report
17. Submit and progress to Confirmation

At each step of the test case we'll assert on the page title which contains the form step.

Out of scope for this card
---
* Using the django test suite, we'll implement outside of the test suite for now to facilitate later testing in CI against deployed environments
* Integrating into CircleCI pipeline

We'll know we're done when
---
- [x] We've implemented the test case above and it can be executed locally with playwright
- [ ] We've updated our documentation with instructions on how to run the playwright test suite

**Comment by Jkrzy** [comment]
Building on #789

As a developer, I need an automated test which progresses through, confirming the behavior of, the report submission process so that I can be confident my changes are not unexpectedly impacting it.

We'll implement a test case encompassing the entire Report submission process using [playwright](https://github.com/microsoft/playwright-python).

Test case -- As a user I:
---
1. GET /reports/
2. Fill the required fields
3. Submit and Progress to Primary concern
4. Selecting `Voting`
5. Submit and Progress to Primary Concern cont.
6. Select No
7. Submit and Progress to Location details
8. Fill required fields
9. Submit and Progress to Personal characteristics
10. Select ‘Age’
11. Submit and Progress to Date
12. Fill required fields
13. Submit and progress to Personal description
14. Fill required fields
15. Submit and progress to Review your report
17. Submit and progress to Confirmation

At each step of the test case we'll assert on the page title which contains the form step.

Out of scope for this card
---
* Using the django test suite, we'll implement outside of the test suite for now to facilitate later testing in CI against deployed environments
* Integrating into CircleCI pipeline

We'll know we're done when
---
- [ ] We've implemented the test case above and it can be executed locally with playwright
- [ ] We've updated our documentation with instructions on how to run the playwright test suite

**Comment by randyabramson** [comment]
Changing this to Sprint 35 so that it stays on our radar.

**Comment by randyabramson** [comment]
Changing this to Sprint 35 so that it stays on our radar.
