### ISSUE TITLE
Email Filter

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#820]
## Narrative
As a CRT user, I want to filter records by a complainant's email address so that I can see all related records in the view all table.

## Acceptance Criteria
1) Given I am on the view all table
when I click the 'More' button in the Filters area
then I see a text box filter labeled 'Email' to the right of the 'Intake Type' filter

2) Given I am on the view all table
when I enter an email address in the 'Email' filter
AND
I click the 'Apply Filters' button or hit enter
then I see the results displayed in the view all table
AND
I see a label displayed for the email address at the bottom of the filters area

3) Given I am on the view all table
when I enter an email address in the email filter and click 'Apply Filters' or hit enter
then I see all records associated with that email based upon my current filters

4) Given I am on the view all table
when I am viewing the filtered results
AND 
I click the 'Clear All Filters' or the x on the 'email address' label
then the view all table displays the results of the remaining filters

## Technical Questions
- Should the filter have the same email address validation as the complaint form? **No (see below)**
- Should we be able to take action on multiple complaints assigned to different sections? (the Correspondence Policy should cover this question) **Yes (see below)**

**Comment by blaughman** [comment]
@emilycryan Could you attach a wireframe for the email filter?  Thanks in advance.

**Comment by emilycryan** [comment]
@blaughman Attached as a PNG file showing the output when it's used. 

![Repeat Writers-Table Email Filtered@2x](https://user-images.githubusercontent.com/73443807/101934236-4e0f3d00-3bab-11eb-8abd-4421312aa63b.png)

**Comment by timoballard** [comment]
Looks like there's a conflict between AUC #1 and the wireframe. Wireframe shows email filter up to and presumably displayed by default, wheres AUC.1 mentions it being hidden by default and adjacent to Intake Type when displayed. Thoughts @blaughman @emilycryan ? Thanks!

**Comment by blaughman** [comment]
@timoballard @emilycryan Good catch Tim.  We plan on reorganizing the filters at some point soon, but at this time, I think we should put this in the available area in the hidden portion of the filters.  Thoughts Emily?

**Comment by emilycryan** [comment]
@timoballard Yes, the email for now will go in the hidden drawer / area. I just it there so it would fit onto the screen but we should put it where we have space for it, within the "MORE" drawer. 

Ideally we will reorg these after ppl use email for a bit - I'd like to make sure we give the easiest access to the most common filters and hide the lesser used ones and I'm going to imagine email will be a popular one. 

CC @blaughman

**Comment by emilycryan** [comment]
Ok, updated designs. Attached are screens showing the email filter when it's used in various ways. 

![Repeat Writers-Table Email Filtered@2x.png](https://images.zenhubusercontent.com/5f970c483cdc923d98dfa265/78c58117-ff4b-4cb5-8c4a-22e5b2f0500d)
This shows what should show when someone has selected NEW and OPEN and there are 4 (of 6) records from that email in either OPEN or NEW state. 

![Repeat Writers-Table Email Return@2x.png](https://images.zenhubusercontent.com/5f970c483cdc923d98dfa265/d7fc7774-7405-4c96-8ae0-5443a62fdad6)

This shows that this user has 6 total records, and we have zero status filters set which is the same as having all 3 selected:

![Repeat Writers-Table Email Return Copy@2x.png](https://images.zenhubusercontent.com/5f970c483cdc923d98dfa265/19c0f475-bcab-4435-a38f-efda6964ca59)

**Comment by timoballard** [comment]
Thanks @emilycryan!

@blaughman - do you want to discuss the two technical questions? The first one (email validation) is straightforward to implement, so is really more of a UX question so I'd defer to @emilycryan on that.

The second one would involve either clearing or bypassing any active section filters whenever an email filter is specified, if I'm understanding correctly. Happy to discuss async here or jump on a call - let me know!

**Comment by Jkrzy** [comment]
I wouldn't recommend having validation on the filter input for email. Folks should be able to search that field with any text entered, like partial emails, names, domains, etc.

**Comment by blaughman** [comment]
@timoballard @emilycryan Randy, Emily and I discussed this yesterday.  The email filter should include any other active filters selected by a user.  This will allow the user the ability to really scope the work they need to address.  Also, I concur with Joe's assessment - no email validation on the back-end.  Hope this helps.

**Comment by timoballard** [comment]
It does - thanks @blaughman!

**Comment by Jkrzy** [comment]
Added https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/839 stemming from the code review here

**Comment by blaughman** [comment]
Tested function in both Chrome and Edge.  Approved - moving to UAT.

**Comment by randyabramson** [comment]
Tested function in both Chrome and Edge on Staging.

**Comment by blaughman** [comment]
Function confirmed on staging prior to production release.

**Comment by randyabramson** [comment]
Passed testing on Prod in CHROME and DEV. Closing.
