### ISSUE TITLE
CRM weekly rerouting reports

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#821]
With the logic that automatically sends Hate Crime to CRM being disabled, we want to measure the normal rerouting volume before the change with the new values (going live on 12/15/20).

Can we get the number of reports rerouted from CRM to other sections for the following 7 day periods:

11/15 - 11/21
11/8  - 11/15
10/25 - 10/31
10/18 - 10/24

**Comment by Jkrzy** [comment]
:thinking: Would you all be amenable for this be accomplished via an export and report generation outside of the system similar to how Reports are being looked at?

**Comment by randyabramson** [comment]
@Jkrzy Yes, I am flexible here.

**Comment by randyabramson** [comment]
@Jkrzy I know you showed me this on your local machine. Let me know if it has been merged and good for UAT complete.

**Comment by blaughman** [comment]
I can't test this due to admin rights.
