### ISSUE TITLE
'Sniffer' modal messaging for Samsung browsers 

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#823]
### Objective: 
Complainants are able to submit reports without errors

### Key Result: 
Complainants using the Samsung Internet browser download another mobile browser, return to our Portal and successfully submit their complaint

### Background to this ticket: 
[Ticket 791](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/791). Note that Samsung Internet versions are listed here: https://en.wikipedia.org/wiki/Samsung_Internet

### User Story:
As a product owner, I want to let complainants using the Samsung Internet Browser know that they need to use another browser in order to complete our form

### Acceptance criteria:
* Given that I am on https://civilrights.justice.gov/report/ AND I am using some version of [Samsung Internet](https://www.samsung.com/us/support/owners/app/samsung-internet)
When I look at the complaint form
Then I a modal with and 'X close box' and messaging that says: 

"Your mobile browser is not compatible with this form. Please download the latest version of Google Chrome, Mozilla Firefox, Safari or Microsoft Edge. You can also [contact us by phone or mail here.](https://civilrights.justice.gov/#contact-crt)"

* Given that I am on https://civilrights.justice.gov/report/ AND I am using some version of [Samsung Internet](https://www.samsung.com/us/support/owners/app/samsung-internet)
When I click the 'x close box' on the modal
Then the modal closes

### Assumptions:
1. That all users enter the form at https://civilrights.justice.gov/report/

**Comment by emilycryan** [comment]
This is based on the modal we use on the admin side. I also massaged the content a bit to let the user know we are not requiring them to update their browser. 

@AvivaOskow can you make sure the design works? Like I mentioned, this is the same design on the back end based on "Rerouting Guide" popup. 

CC @randyabramson @blaughman 

![Screen Shot 2020-12-08 at 3.34.56 PM.png](https://images.zenhubusercontent.com/5f970c483cdc923d98dfa265/8413e931-13fe-4883-a153-7660ca8fad23)

**Comment by randyabramson** [comment]
@emilycryan  thanks for the above.

One question: do we have to have the word 'error' here? At this point of the experience, no functional error has occurred yet. Would we better off with the word "Notice" or an icon like this? https://cdn3.vectorstock.com/i/1000x1000/84/57/orange-triangle-exclamation-mark-icon-warning-sign-vector-13228457.jpg

**Comment by emilycryan** [comment]
@randyabramson Good point- I'm open to calling it something else like:
- Notice
- Incompatible Browser
- Advisory

I don't think we need an icon in this but I'll defer to @AvivaOskow for that decision. 

-e

**Comment by randyabramson** [comment]
Let's go with 'Notice' -- I don't want people to think that the entire site is incompatible with the browser.

Thank you, @emilycryan

**Comment by emilycryan** [comment]
Sounds perfect, @randyabramson 
CC @AvivaOskow

**Comment by emilycryan** [comment]
Here's the updated popup with correct text. @randyabramson LMK if anything is missing. 

![Screen Shot 2020-12-10 at 12.32.14 PM.png](https://images.zenhubusercontent.com/5f970c483cdc923d98dfa265/1d6c6fcc-9fdd-419b-8e30-e669384aba2e)

**Comment by AvivaOskow** [comment]
@randyabramson @emilycryan this is how I would design this. It's taking the content from what Emily shared above, but putting it in our styles. Let me know what you think.

<img width="761" alt="Screen Shot 2020-12-10 at 2 19 28 PM" src="https://user-images.githubusercontent.com/21244661/101816047-ded81100-3af6-11eb-9130-ba3a02fe58ca.png">

**Comment by randyabramson** [comment]
@AvivaOskow and @emilycryan 

One quick change - change above - "Please consider download the latest version..." to "Please consider downloading the latest version..."

Beyond that, it looks great...thanks for your speedy work.

**Comment by Jkrzy** [comment]
Flagging that this will need ES translation

**Comment by AvivaOskow** [comment]
@timoballard @Jkrzy should I give you spacing and color annotations for this?

**Comment by randyabramson** [comment]
@timoballard we requested translation...will forward it when we get it back.

**Comment by timoballard** [comment]
@AvivaOskow yes please!

**Comment by AvivaOskow** [comment]
## USWDS mobile grid 
<img width="660" alt="Screen Shot 2020-12-11 at 3 39 54 PM" src="https://user-images.githubusercontent.com/21244661/101948101-e3b8c580-3bc7-11eb-9660-9ec41fc01d3c.png">

## Spacing Annotations
<img width="719" alt="Screen Shot 2020-12-11 at 3 45 01 PM" src="https://user-images.githubusercontent.com/21244661/101948202-034fee00-3bc8-11eb-939a-fdc5a333aae3.png">

## Styles

#### Font: CRT Body (Public Sans 16px, 26px line height
#### Colors: Bright yellow - bg-gold-20v #FFBE2E , backgorund light yellow - bg-gold-5 #F5F0E6

**Comment by randyabramson** [comment]
@timoballard - is there a way for @blaughman or I to test this?

**Comment by timoballard** [comment]
@randyabramson - If either of you have an android phone/tablet, you can install the [Samsung browser](https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser) and navigate to the report form. You should see the modal using that browser, but not with any others.

**Comment by Jkrzy** [comment]
I tested manually using android device and remote debugging, this could also be tested w/ playwright.

**Comment by timoballard** [comment]
@Jkrzy - that's true, I suppose we could override the user agent string. Good excuse for me to fiddle w/ playwright :)

**Comment by Jkrzy** [comment]
Django's test client may be a better option, lighterweight since all we're looking for is setting the user agent. https://docs.djangoproject.com/en/2.2/topics/testing/tools/#making-requests

**Comment by timoballard** [comment]
[Went with playwright](https://github.com/usdoj-crt/crt-portal/pull/767) due to the user agent inspection + modal display all happening on the client side. PR open!

**Comment by randyabramson** [comment]
@timoballard tested this on Android, so moving this over to UAT Complete.

**Comment by randyabramson** [comment]
@timoballard is there a way to test this on Playwright on Staging?

**Comment by timoballard** [comment]
Yes - Playwright tests ran (and passed) as part of the staging deploy, so all good there 👍

**Comment by randyabramson** [comment]
Passed deploy which contained Playwright test. Moving to Staging column.

**Comment by randyabramson** [comment]
Tim tested this on prod. Functioned as expected. Closing.
