### ISSUE TITLE
Protected_class missing Error page

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#824]
Needs approval and translation

### Objective: 
Complainants are able to successfully submit complaints

### Key result: 
Complainants using Samsung Internet, using multiple tabs/browsers, etc. that cause the 'Protected_class missing' error are informed of alternate browsers, advice on only using one tab/browser and other contact alternatives

### Ticket background:
[Ticket 791.](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/791) Note that Samsung Internet versions are listed here: https://en.wikipedia.org/wiki/Samsung_Internet

### User story: 
As a product owner, I want to alert complainants using a Samsung Internet browser or multiple tabs/browsers of alternative ways to successfully submit the form or contact us

### Acceptance criteria: 
Given that I am on any part of the [Complaint Form ](https://civilrights.justice.gov/report/)
When I trigger the Protected_class missing error
I see an [error page in this template](https://civilrights.justice.gov/report/wdq) that says:

We're sorry, something went wrong.

This error might be associated with an incompatible Internet browser. Please download the latest version of Google Chrome, Mozilla Firefox, Safari or Microsoft Edge. 

Additionally, please do not use multiple browsers and/or browser tabs when entering your report. 

{Developers - please [follow the style here](https://civilrights.justice.gov/report/wdq) for the contact portion of this page}

If you need to contact us immediately, you can reach us by:

Email : Ask.CRT@usdoj.gov

Phone: 
(202) 514-3847
1-855-856-1247 (toll-free)
Telephone Device for the Deaf
(TTY) (202) 514-0716

Mail
U.S. Department of Justice
Civil Rights Division
950 Pennsylvania Avenue, NW
Washington, D.C. 20530-0001

Other information

[About the Civil Rights Division](https://civilrights.justice.gov/#about-the-division)

If you or someone else is in immediate danger, [please call 911 or local police](tel:911).

**Comment by ilodidoj** [comment]
@randyabramson please check if this email ask.CRT@**crt.**usdoj.gov address is correct. **crt.usdo**j usually internal email probably can't resolve from public space.

**Comment by randyabramson** [comment]
Thank you @ilodidoj - yes the email should be Ask.CRT@usdoj.gov

I updated it above

**Comment by randyabramson** [comment]
@emilycryan if you approve this text, we can get rolling on coding this.

@blaughman can then get the translations rolling and we can always release the translation in a future sprint.

Thank you!

**Comment by emilycryan** [comment]
@randyabramson this looks good to me - the messaging matches what we have on the modal so I'm good with it. 

CC @blaughman

**Comment by randyabramson** [comment]
Great, @emilycryan - thank you. I will unblock this.  @blaughman  - feel free to send this to Marta for translation and you can give here this page as an error reference page: https://civilrights.justice.gov/report/dd

**Comment by randyabramson** [comment]
Translation added here[https://app.zenhub.com/files/183258764/c3140f50-5fce-4549-b59d-6b27295d363b/download](https://app.zenhub.com/files/183258764/c3140f50-5fce-4549-b59d-6b27295d363b/download)

**Comment by Jkrzy** [comment]
Flagging that we have two different translations for:

"We're sorry, something went wrong"

1. "Lo siento, se ha producido un error"
2. Received here: "Lo sentimos. Hay algún problema."

**Comment by Jkrzy** [comment]
Submitted https://github.com/usdoj-crt/crt-portal/pull/765

**Comment by randyabramson** [comment]
@Jkrzy in testing this, I started a report on DEV in EDGE. Half way through, I opened a second tab in the same browser and started a new report. I submitted that second report without seeing the error. I then went back to the first tab and completed that first report and submitted it without seeing an error.

Is there anything more specific I should be doing to show this error page?

Randy

**Comment by randyabramson** [comment]
Tested with Joe and works as expected. Moving to UAT complete.

**Comment by randyabramson** [comment]
I was able to create this error on Prod. Moving to closed.
