### ISSUE TITLE
Use optimized and smaller source for doj-logo-footer image

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#825]
The current [doj-logo-footer.svg](https://cg-b88f3063-f22b-4f72-b235-51832fdfffca.s3-us-gov-west-1.amazonaws.com/static/img/doj-logo-footer.svg) is the largest static file being served for civilrights.justice.gov. We're only using it for images that are ~64x64px, let's use a smaller image.

### We'll know we're done when
- [ ] We've replaced all occurrences of doj-logo-footer.svg with the smaller image attached here.
![doj-logo-footer.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/413ac91a-deaf-4a5d-8040-57f1fcc055b4)

**Comment by randyabramson** [comment]
Inspector shows that this image is 55 x 55. Moving to UAT complete.

**Comment by randyabramson** [comment]
Inspector shows that this image is 48x48 on Staging. Moving to Staging column.

**Comment by randyabramson** [comment]
Inspector shows that this image is 48x48 on Prod. Moving to close.
