### ISSUE TITLE
Frequent Flyer - Complaint Detail Page (Total Complaints Card)

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#834]
## Narrative
As a CRT User, I want a visual reference of other reports in the system associated with the email address of the complaint I am currently processing so I am more efficient in my work.

## Background
Knowing the previous history of a complainant in the portal will make intake specialists more efficient as they process incoming complaints.  A first time complainant can be processed quickly and confidently knowing there are no associated complaints.  A repeat complainant will require another level of analysis - confirmation of same/new issue presented, prior responses, and possible application of the correspondence policy.

## Acceptance Criteria
1) Given I am on the complaint detail page
when a complainant's email address has more than one associated report
then I see a card labeled 'Total Complaints' below the 'Actions' card
AND
I see the indication "There are (value of associated reports) complaints associated with this contact" below the 'Total Complaints' label

2) Given I am in the 'Total Complaints' card on the complaint detail page
when I see the associated reports in the portal
then I see their status, complaint ID#, assigned section, and date submitted

3) Given I am in the 'Total Complaints' card on the complaint detail page
if there is one total report with the email address (or the email address is blank)
then there should be no link to "View All" in the card.

4) Given I am in the 'Total Complaints' card on the complaint detail page
the height of the Total Complaints box should be a maximum of 450 pixels
but the height should be responsive and "fit" the content. 

5) Given I am in the 'Total Complaints' card on the complaint detail page
if there are enough matching complaint emails to push the box to a height of more than 450 pixels,
a scrollbar should be utilized so the user can scroll through the entries. 

## Mockup
![Individual Record View@2x.png](https://images.zenhubusercontent.com/5f970c483cdc923d98dfa265/6b4a1d0a-96e8-4661-ba75-55fb40ffeaee)

## Assumptions
- Any prior correspondence notifications in the 'Total Complaints' card is out of scope until email is integrated into the portal.

## Technical Questions
- How many records can/should be put on 'Total Complaints' card?
- Should we only show the previous year?

**Comment by emilycryan** [comment]
Notes on the design:

- Total Complaints box should be 450 pixels high. 

- The info within the box should scroll as indicated within the dotted blue area:

![Screen Shot 2020-12-21 at 3.28.04 PM.png](https://images.zenhubusercontent.com/5f970c483cdc923d98dfa265/f301d8ad-9232-42eb-8677-a422656aefb8)

- If there is only one record with a specific email address, there should be no link to "View All" as indicated:
![Screen Shot 2020-12-21 at 3.29.39 PM.png](https://images.zenhubusercontent.com/5f970c483cdc923d98dfa265/7779b68b-d096-4ae2-9bcb-17da81fef992)
* Note: This link should also be removed on the right hand side, next to the individual's email address.

**Comment by blaughman** [comment]
Icon source - "Copy"
https://feathericons.com/

**Comment by Jkrzy** [comment]
Should the current report we're viewing be included in the `Total Complaints` table?

**Comment by blaughman** [comment]
@Jkrzy Yes.  The total complaints card is essentially the view all table with an email filter.  Hope this makes sense - happy to jump on a call to discuss.

**Comment by Jkrzy** [comment]
@blaughman, should this be excluded from the page when printing a report?

**Comment by blaughman** [comment]
@Jkrzy Great question.  I think it should be added to the print option, but not checked by default.  At this point it's a nice to have.  I really wonder what the printout would look like for someone who has over a hundred complaints in the portal.  As this product ages, printing a report for a frequent flyer would trigger an error because it would exceed a certain file size.

**Comment by emilycryan** [comment]
@Jkrzy @blaughman The other option is to only include an abbreviated representation of the info. Instead of listing the duplicates out, just including something like "Complainant Submissions: 89" or something similar. I guess what I'd want to know is what are ppl doing with the printed reports that would merit including the other submissions' details?

**Comment by blaughman** [comment]
@Jkrzy @emilycryan We could opt to omit this from the print option.  At this point it is most likely the related complaints are all from the same person (although not confirmed - Randy brought up the possibility of more than one person having/entering the same email address).  It could potentially make a FOIA request much more difficult if the public requester sees some records associated with their email address that aren't their own.

**Comment by emilycryan** [comment]
@blaughman The email address+FOIA thing is sticky so def sounds like not including it would be the best bet. I'd say we just ignore it then and not even include a number of total complaints. CC @Jkrzy

**Comment by Jkrzy** [comment]
Ok, `Total Reports` will be excluded from print views! 

Thanks @emilycryan & @blaughman

**Comment by blaughman** [comment]
@Jkrzy @emilycryan Joe - I was testing this in Dev.  One thing I noticed on complaint 463-LJD, the view all link was removed from the correspondent information card (as expected), but it is still in the total complaints card (unexpected).  At this point, that is all I have found and I love, love, love the thought and implementation of this feature.  

This is the third bullet from Emily note on 12/21

If there are 0 or 1 email records for a particular submission, the "View All" should be removed from the box. Note This holds true for the "View All" next to the email address in the top right area (ticket 838)

**Comment by emilycryan** [comment]
Yeah, it just seems silly to have a "View All" link when the only record available is the one you're already on/looking at. We should remove it from both areas if there is only 1 record. 

CC @Jkrzy @blaughman

**Comment by Jkrzy** [comment]
Agh, I missed that on first pass. Thanks for pointing out! Fix is up for review: https://github.com/usdoj-crt/crt-portal/pull/791

**Comment by Jkrzy** [comment]
Fix up on https://crt-portal-django-dev.app.cloud.gov/ @blaughman!

**Comment by blaughman** [comment]
Excellent work @Jkrzy.  I love how clearing the email filter takes a user back to their previous global filter.  That will be a win for the CRT user experience.

**Comment by blaughman** [comment]
Function works as intended in Chrome and Edge.  Moving to UAT.

**Comment by emilycryan** [comment]
I LOVE THIS! Great work @Jkrzy!
