### ISSUE TITLE
Frequent Flyer - Complaint Detail Page (View all link)

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#838]
As a CRT intake specialist, I want to see all records associated with an email address in the view all table so that I can take action on those complaints.

## Acceptance Criteria
1) Given I am on the complaint detail page
when I look at the 'Email' line in the 'Correspondent information' card
then I see a link to the right labeled 'View all (value of associated records with that email - **when value =>2**)'

2) Given I am on the complaint detail page
when I look at the 'Email' line in the 'Correspondent information' card
then there is no link to the right labeled 'View all (value of associated records with that email - **when value =1** or **when value =0**)

3) Given I am on the complaint detail page
when I click the 'View all' link
then I am directed to the view all table and all records associated with that email address are displayed 

4) Given I am on the filtered list of the view all table
when I see the records displayed
then I see all records associated with the email address 
AND
only the email address label is displayed

5) Given I am on the view all table with the filtered records
when I click 'Clear All Filters' or the 'x' in the email filter label
then I am returned to the view all table with no active filters

## Mockup
![Individual Record View@2x.png](https://images.zenhubusercontent.com/5f970c483cdc923d98dfa265/50e08e1b-b4bf-4e88-a7f6-f48e4334f835)

## Assumption
- this represents the total volume of complaints associated with this email regardless of their status
- value must match the value in the 'Total Complaints' card
- the filtered view all table should only show email label and no filters
- only show view all link and total complaints card when the value is 2 or more

**Comment by emilycryan** [comment]
**Note** If there are 0 or 1 email records for a particular submission, the "View All" should be removed from the box. **Note** This holds true for the "View All" in the Total Complaints box in the left column (ticket 834)

CC @blaughman @randyabramson

**Comment by blaughman** [comment]
@emilycryan @randyabramson I updated the AC's to reflect Emily's instructions.  If you have a moment to review, please let me know your thoughts.

**Comment by Jkrzy** [comment]
Ahhh @blaughman I think I'm confused between the mock and the acceptance criteria --

This card is _**only**_ to implement this piece of the mock?
![Screen Shot 2020-12-22 at 1.32.34 PM.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/795c9d86-0bae-4d09-9050-a9aa1b86db71)

**Comment by blaughman** [comment]
@Jkrzy Correct.  This card is to only add the 'View All' link in the 'Contact information' card and the behavior one would expect when clicking the link.  Card 834 is the 'Total Complaints' card - this will also have a 'View All' link, but it will also visually display basic metadata on other complaints associated with that email address.  Hope this makes sense - please feel free to hit me up on zoom to discuss further.

**Comment by randyabramson** [comment]
@blaughman - just catching up to this...nice work

**Comment by Jkrzy** [comment]
Great question from @cantsin on code review!

How should we approach the intersection of user's `profiles` and this `view all` functionality?

More details from James: https://github.com/usdoj-crt/crt-portal/pull/779#pullrequestreview-559255064


cc: @randyabramson, @blaughman

**Comment by blaughman** [comment]
@Jkrzy @cantsin @randyabramson @emilycryan The thought on this function is that once the CRT user clicks the 'View All' link, the only filter will be for the email address.  All other filters are removed at this point.  A CRT user will have to go back and select their section once they have taken action on the filtered records.

**Comment by randyabramson** [comment]
+1 to @blaughman's point. To @cantsin's question -- yes, include section labels.

**Comment by blaughman** [comment]
Function works as intended on Chrome and Edge.  Moving to UAT.

**Comment by randyabramson** [comment]
Works as expected, but I see the DEV and STAGE versions have the scroll bar on the total complaints card. Closing for now...assuming the scroll function will be merged on the next release.
