### ISSUE TITLE
Frequent Flyer - Sorting on the view all table

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#843]
## Narrative
As a CRT user, I want to sort records based on the number of contacts by an email address so that I can prioritize my workload.

## Background
CRT intake staff need the ability to sort the records that are grouped by email so they can efficiently process the complaints.  Single complaints can be acted upon quickly, but multiple complaints need further analysis and could possibly be processed in bulk.

## Acceptance Criteria
1) Given I am on the view all table
when I look at the 'Tot. #' column
then I see an arrow which will allow me to sort the records in ascending or descending order

2) Given I am on the view all table
when I click the sort arrow in the 'Total #' column
the data is sorted so the email address with the most associated records is listed first
AND
the other records are sorted in a descending order

3) Given I am on the view all table
when I click the sort arrow in the 'Total #' column again
the data is sorted so the email address with the least associated records is listed first
AND
the other records are sorted in an ascending order

## Assumptions
- all records will have a value (single submissions will have a value of 1)
- records without an email address will have a value of '--'

**Comment by randyabramson** [comment]
@blaughman - just curious...how are records that don't have email  addresses ordered?

**Comment by blaughman** [comment]
Function works as intended in Chrome and Edge.  Moving to UAT.
