### ISSUE TITLE
Simplify test report data generation

### ISSUE THREAD

**Issue by timoballard** [18F/crt-portal#846]
There are dozens of places in our test suite where we install mock report data before test execution. The typical pattern is to create some number of reports using the `SAMPLE_REPORT` definition, and then iterate over the created reports making whatever data modifications are necessary to facilitate the upcoming test. 

We should introduce a single or small set of utility function(s) that allow test authors to quickly describe the shape and number of reports they need for each test.

**Comment by Jkrzy** [comment]
https://github.com/usdoj-crt/crt-portal/pull/782
