### ISSUE TITLE
Add USWDS date filter

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#849]
[Per ticket 772](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/772), please replace current date filter with USWDS date filter

**Comment by cantsin** [comment]
After looking at this, replacing will be tougher than it sounds. Currently we store the year, month, and day in separate database fields; to accommodate this change, we'll need to replace with a single date text field, re-do our validation code, forms, _and_ associated templates. Which inevitably brings up the question of why we are storing these date fields separately when the user-facing widget does not accurately reflect the underlying data schema. In other words, there's a cascading/ripple effect here that will reach other parts of the codebase. Not sure if the benefit is worth the trouble (but CCing other engineers in case they disagree or have a simpler solution in mind -- @Jkrzy @timoballard )

CC @blaughman @randyabramson

**Comment by randyabramson** [comment]
@cantsin - this is a nice to have, so no need to continue to focus on this. Maybe in standup today you can explain the issue with the interface not reflecting the data schema and the risks associated with that?
