### ISSUE TITLE
Tracking clicks for 'start a report' and 'submit a report' on homepage

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#850]
### Background
We know that about 25% of the sessions that occur on civilrights.justice.gov result in a completed report. However, we don't know why users that come to the site do not wind up completing the form. We are looking to do extensive user testing this quarter, but we also have Google Tag Manager configured, which can help us understand how many people are clicking which links within the Portal.

### Objective
To better understand the number of people that come to our home page, click 'start a report,' then 'submit a report'

This looks like a good primer: 
https://www.analyticsmania.com/post/google-tag-manager-click-tracking/

**Comment by randyabramson** [comment]
@timoballard - I think you mentioned that you might pick up this card. Let me know if you want to pair up at all. I can also reach out to the DAP team if we get stuck.

**Comment by timoballard** [comment]
Sounds good @randyabramson - I'll plan to pick this one up as I'll have analytics stuff relatively top of mind anyway 👍

**Comment by randyabramson** [comment]
Cool @timoballard ! Assuming that this project goes well, I'd like to track virtual page views within the form in the next sprint https://www.bounteous.com/insights/2020/06/11/tracking-virtual-pageviews-google-tag-manager/

**Comment by randyabramson** [comment]
Verified on dev. Moving to staging.
