### ISSUE TITLE
 JMD Ticket process for Mail subdomain for AWS SES

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#851]

**Comment by ilodidoj** [comment]
Three new tech tasks card needs to track each of the JMD request:
1. Card for mail domain reservation
2. Card for JSOC approval
3. Card for Setup email security/hygiene for the new domain
Once the above card tasks completed by JMD CP team can start testing sending email from sandbox

We will need another card to add the AWS production setup with JMD once we have procured the account.

**Comment by randyabramson** [comment]
@ilodidoj do you want to create 3 new cards or just a checklist on this card?

**Comment by ilodidoj** [comment]
@randyabramson I will create separate card for each because each has dependency on others in that order. Time line will vary based on the approval and completion of 1, then 2 and then finally 3.
