### ISSUE TITLE
View All and Total # has to be case agnostic

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#858]
When testing, the same email address with different letters capitalized will be treated as different results.  If the email address matches, despite some letters being capitalized, the Total # should equal both possibilities.

Update: Per @ilodidoj  testing, please make the logic that surfaces matched Email totals case agnostic on 2 sections of the Report Level page: 
1.  The Total Complaints card (matched reports and logic that drives the total in the View All link)
2.  The total next to the 'view all' link in the Correspondent Information card

![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/2d5ced1a-9a77-4a81-a4e8-26604077ab09)

**Comment by ilodidoj** [comment]
@randyabramson @blaughman @timoballard I think this card need more info on the detail page and view all link on the detail page as well.  More changes will be needed to the report detail page to display all the list where email is the same but other contact info are not.  Same adjustment needed on the view all link as well as to count as non-case items from the detail page. 
View all table:
![image.png](https://images.zenhubusercontent.com/5d374c9d0efb727bd5a01afd/4a5e96f9-3df4-433e-bd38-b18487a8dc5d)

detail report
![image.png](https://images.zenhubusercontent.com/5d374c9d0efb727bd5a01afd/dd42e5f8-7f76-4bcc-99e8-87203ea07b79)

**Comment by randyabramson** [comment]
@ilodidoj 's fixes now included in the main description of this ticket.

**Comment by randyabramson** [comment]
Working on staging as expected
