### ISSUE TITLE
HTML Trending Form Letter Mock

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#860]
@AvivaOskow - we would like to mock up this EEOC form letter as a HTML letter:

https://app.zenhub.com/files/183258764/8f652876-253a-4d2c-b1fd-9589f9fdc335/download

Please include the seal and any graphic header that makes sense.

We would also like to include the following contact info in the footer:

===

U.S. Department of Justice

Civil Rights Division

950 Pennsylvania Avenue, NW

Washington, D.C. 20530-0001

(202) 514-3847

**Comment by randyabramson** [comment]
@AvivaOskow - also including the CFPB response letter here in case it inspires

[https://app.zenhub.com/files/183258764/bb687f92-2efb-4b58-819e-74e3be9e1ecc/download](https://app.zenhub.com/files/183258764/bb687f92-2efb-4b58-819e-74e3be9e1ecc/download)

**Comment by AvivaOskow** [comment]
Hey all, I didn't see that EEOC letter before designing (sorry I should have checked the ticket!) but here are two mocks I worked on today based on one of the letter Emily had started to style already. I can go back and change the content to the EEOC letter tomorrow.

# Mockup 1
![Email Design 1.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/afec6c85-cbe2-45f8-a973-24b5daf4d7cc)

# Mockup 2
![Email Design 2.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/518c762e-737b-4b04-862e-fdf721c7fbc8)

**Comment by emilycryan** [comment]
@AvivaOskow The first one is really nice - I feel like the section contact info in the header is weighing it down in the second one and I like seeing the record number closer to the top. 

We probably need guidance on the mobile version of this as well - or at least the stacking order of the content areas. 

Love it! Great work... 
cc @randyabramson @blaughman

**Comment by randyabramson** [comment]
@AvivaOskow I agree with @emilycryan - I like #1.

Great work!

**Comment by randyabramson** [comment]
@AvivaOskow I am going to close this ticket and reference it in new tickets about this proejct.

Nice work!
