### ISSUE TITLE
Randy x Tim pair on Google Tag Manager

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#864]

**Comment by timoballard** [comment]
@randyabramson @blaughman - per our discussion, added an event to track when a user lands on step 1 of the report submission form (contact details). You'll see this as "Report Form - Start" and the final submission as "Report Form - Submit":

![image.png](https://images.zenhubusercontent.com/5f6b6d45a696d381a6f600f9/d55c9b74-87bb-4c16-aad1-dc2576ce82e7)

**Comment by timoballard** [comment]
@randyabramson @blaughman - Let's pair up and outline some next steps now that we have some real data to look at and react to!
