### ISSUE TITLE
Ming x Tim Orientation

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#867]

**Comment by timoballard** [comment]
@blaughman @randyabramson - do we know when Ming will be available to start onboarding?

**Comment by randyabramson** [comment]
@timoballard - Our CIO is chatting with Ming's manager to make sure the coast is clear. I hope to have more info for you soon.

cc @blaughman 

Randy

**Comment by randyabramson** [comment]
@timoballard - some bad news - Ming is resigning, so I am going to close this.

CC: @ilodidoj
