### ISSUE TITLE
'Secondary Review' filter

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#870]
## Narrative
As a CRT user, I want to filter records designated for secondary review so that I can see all related records in the view all table.

## Acceptance Criteria
1) Given I am on the view all table
when I click the 'More' button in the Filters area
then I see a drop down box filter labeled 'Secondary Review' 

2) Given I am on the view all table
when I click the down arrow in the Secondary Review filter
then I see a checkbox and the word 'Yes' next to it

3) Given I am on the view all table
when I check the 'Yes' box in the 'Secondary Review' filter and click 'Apply Filters' or hit enter
then I see all records displayed that were checked for secondary review based upon my current filters
AND
I see a label displayed 'Secondary Review: Yes' at the bottom of the filters area

4) Given I am on the view all table
when I am viewing the filtered results
AND 
I click the 'Clear All Filters' or the x on the 'Secondary Review' label
then the view all table displays the results of the remaining filters

## Mockups
This will appear similar to the Hate Crime filter
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/4ecb06ce-3322-475f-a52d-1536bb7995d3)

Example of the label
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/6ac57c41-76ae-46e3-9718-fc0b9065fd3a)

**Comment by randyabramson** [comment]
Looks good, @blaughman - thanks for tackling

**Comment by blaughman** [comment]
Function works as intended in Chrome and Edge.  Moving to UAT.

**Comment by randyabramson** [comment]
Functions as expected on Live. Closing ticket.
