### ISSUE TITLE
[Spike] attachment files

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#871]
Before developing the 'Add attachments via the proform' (Card 41), we should define the technical requirements for this feature.

1) List of reasonable file types for upload - examples: PDF, WAV, Word, Excel, CSV, Images, etc.
2) List of file types that CAN NOT be uploaded - .exe, movies, etc.
3) File size limit - when will the network prevent an upload from happening (Imran, John Watson can assist with info)
4) Alerting CRT User that file will exceed limit
5) File structure in the S3 buckets
6) Virus scanning of attachments

**Feel free to add other considerations as needed**

**Comment by timoballard** [comment]
Compiling notes and considerations here: https://docs.google.com/document/d/1_UKc1-KsNy1AKmuyuR8xteHuCmJ2tBXZwIZgvxktfF0/edit#

**Comment by blaughman** [comment]
Added document to Card 41.  Closing this card.
