### ISSUE TITLE
Fix issue with USWDS styles not applying to radio buttons / checkboxes

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#88]
## Narrative
As a person filling out the form, I want to see beautiful and usable USWDS 2 radio buttons and checkboxes so that I can have a pleasant and consistent experience filling out the form.

**Comment by alexsoble** [comment]
USWDS 2 code reference:

https://designsystem.digital.gov/components/form-controls/#checkbox

https://designsystem.digital.gov/components/form-controls/#radio-buttons

**Comment by alexsoble** [comment]
PR ready for review here: https://github.com/usdoj/crt-portal/pull/22.

**Comment by LindsayYoung** [comment]
this is merged
