### ISSUE TITLE
Move Voting module under 'mistreated by police, correctional staff, or inmates' on Primary concern page

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#880]

**Comment by blaughman** [comment]
Function appears as requested on both the public side and the proform.  Moving to UAT.

**Comment by blaughman** [comment]
@timoballard @ilodidoj @Jkrzy @randyabramson  Still showing errors on proform - errors to follow

**Comment by blaughman** [comment]
These branching questions should be associated with the Employment selection
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/1f637d83-756a-4ae2-8e45-3388297b2747)

**Comment by blaughman** [comment]
This question should be associated with the Education selection

![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/2754f020-398e-49c6-91c6-82890ffd959a)

**Comment by blaughman** [comment]
These branching questions should be associated with the Mistreated by Police... selection

![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/72933176-f9ad-4f43-bca8-c73b21d02354)

**Comment by timoballard** [comment]
Thanks @blaughman - looking into this

**Comment by timoballard** [comment]
Added [908](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/908) as a followup technical task based on our work here

**Comment by blaughman** [comment]
Proform is good to go.  Moving to UAT.

**Comment by randyabramson** [comment]
Working as expected on Staging. @blaughman would love your second set of eyes here.

**Comment by blaughman** [comment]
Function works as intended in staging.
