### ISSUE TITLE
Debug 'user account' issue w/ Acquia Deploy

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#89]
## Narrative
As a \<type of user\>, I want \<a goal\> so that \<benefit\>. 

## Background
:add business context to help us better understand the story:

## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Mockups / Wireframes
![image]()

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by alexsoble** [comment]
At an earlier stage in our Acquia BLT setup process, we noticed that deploys would at times overwrite Drupal user accounts.

As of today (8/5), we checked by deploying to the dev site, and found that a deploy did not overwrite my user account. 

Sent an email to Marvin asking what he knows about this phenomenon, what causes it, and if we need to be concerned about this going forward. Closing this issue for now but will add more info when we hear back from Marvin.
