### ISSUE TITLE
EMail field of form does not accept foreign language characters

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#891]
When we enter Chinese (simplified) characters in the email field of the form, we get this error:

![chinese.PNG](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/7bd08d26-a409-4ec9-927f-0d211390050d)

**Comment by Jkrzy** [comment]
This was resolved in https://github.com/usdoj-crt/crt-portal/pull/828 and we'll now allow international emails.

Important to note that while we're now accepting these email formats, support for sending and receiving email to them varies and they may be unreachable with the email systems available to us.

**Comment by randyabramson** [comment]
Thanks @Jkrzy. Note that I did ask GovDelivery about their international support. They said they are 99% sure that they do support it, but we will confirm before signing a contract

**Comment by blaughman** [comment]
@timoballard @ilodidoj @Jkrzy @randyabramson I just tested this and got the following error.  Thoughts?

**Comment by timoballard** [comment]
@blaughman - it looks to me like that entry contains two "@domain" segments:

@例子.广告
and
@aol.com

**Comment by blaughman** [comment]
@timoballard Spot on.  That character blended in with the other characters.  I tested five different languages and the system accepted all characters.  Moving to UAT.

**Comment by randyabramson** [comment]
Working as expected on Staging.
