### ISSUE TITLE
Design for new language drop down - top right

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#894]
Example mentioned by the Language Working Group
https://www.lep.gov/

## Notes
- Imran mentioned the scrolling language list may not be accessible on LEP (stressed this is a content page, not an application)
- Some language selections are not translated and point to English pages
- Emily is concerned this is not accessible - can reach out in Slack for feedback
- Also check with Terri Youngblood for accessibility

Language lineup is:

简体字 (Chinese Simplified)
簡體字 Chinese Traditional)
English
Español
한국어 (Korean)
Tagalog
Tiếng Việt (vietnamese)

**Comment by AvivaOskow** [comment]
![Screen Shot 2021-03-17 at 5.16.33 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/b299518f-fc3a-4c28-962a-31a9cc75ad0a)

![Screen Shot 2021-03-17 at 5.15.52 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/48f54c64-9a48-4e84-8702-ed4bd692a83d)

**Comment by randyabramson** [comment]
@AvivaOskow could I bug ya for a mock that shows the dropdown at the top AND bottom of the page?

Thank you!
