### ISSUE TITLE
Remediate performance degradation related to email count queries

### ISSUE THREAD

**Issue by timoballard** [18F/crt-portal#895]
New Relic has recently flagged some performance issues with queries that include JOINs to the email_report_count view. We'll explore some options for improving the performance of these queries, such as adding indexes or making email_report_count a materialized view.

[New Relic example](https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJzcGFQYXRoIjoiL292ZXJ2aWV3L0FsbC9kcmlsbGRvd24iLCJtZXRyaWMiOiJEYXRhc3RvcmUvc3RhdGVtZW50L1Bvc3RncmVzL2N0c19mb3Jtc19yZXBvcnQvc2VsZWN0Iiwic29ydCI6InRvdGFsX2NhbGxfdGltZV9wZXJfbWludXRlIiwibmVyZGxldElkIjoiYXBtLW5lcmRsZXRzLmRhdGFiYXNlcyIsImVudGl0eUlkIjoiTWpjek5EQXpOWHhCVUUxOFFWQlFURWxEUVZSSlQwNThNekU0TURBME5UQTQifQ&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQiOiJNamN6TkRBek5YeEJVRTE4UVZCUVRFbERRVlJKVDA1OE16RTRNREEwTlRBNCIsInNlbGVjdGVkTmVyZGxldCI6eyJuZXJkbGV0SWQiOiJhcG0tbmVyZGxldHMuZGF0YWJhc2VzIn19&platform[timeRange][duration]=604800000)

**Comment by Jkrzy** [comment]
The slow downs we're seeing are typically from queries of the `violation_summary` field. On each search we do a full text query of the that column. As implemented, we're calling `ts_vector` on the entire column for each call. Let's look at adding a [searchVectorField](https://docs.djangoproject.com/en/2.2/ref/contrib/postgres/search/#searchvectorfield) to do that parsing ahead of time and not for each search.

**Comment by blaughman** [comment]
Unable to test in dev.  Need real time interactions in the prod environment.  Ready for staging.

**Comment by randyabramson** [comment]
Unable to test in staging. Need real time interactions in the prod environment.
