### ISSUE TITLE
Set up CI/CD with Circle

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#9]
## Narrative
As a developer, I want set up CI/CD so that I can run tests automatically as part of the build pipeline. 

## Background
Hoping to connect DOJ Github to Circle CI pipelines

## Acceptance criteria
- [ ] code deploys to cloud in the applicable environment when code is pushed develop, staging or master branch, after tests pass
- [x] Set up Circle CI (automated deployments with tests) 🦃
- [x] Bandit (security) 🐭
- [x] Python flake 8 Linter (code style) 🐭
- [x] Pa11y  (accessability) 🐭
- [x] Automated deploys 🐭

**Comment by LindsayYoung** [comment]
Updated title to make this clear, we have several deployment tasks. This one is to set up automated deploys with Acquia pipelines once we have an upgraded account.

**Comment by alexsoble** [comment]
@LindsayYoung and I talked about me picking up the `flake8` piece of this work! I'm excited to do that because having a Python code style linter will help us write more consistent code as a team.

**Comment by LindsayYoung** [comment]
Last piece of the puzzle- Pa11y testing will come together here: https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/125
