### ISSUE TITLE
Check upload file name for special characters

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#903]
An upload triggered an error because it had a comma in the file name.
The URL doesn't support special characters.

Check files for: 
, @ ; "" '

**Comment by blaughman** [comment]
System would not allow file names to be added with special characters.  Attempted to add files with , ; "" ' ! and @.  The system did not allow any to be added with these characters.  Error message was clear to user.

**Comment by randyabramson** [comment]
Works as expected on staging.

**Comment by blaughman** [comment]
Function works as intended in staging.
