### ISSUE TITLE
Assign newly created record to ADM

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#91]
## Narrative
As a DOJ CRT user, I want newly created records assigned to ADM so that they can route complaints to the appropriate sections accordingly.   

(Bill's version 😂 )As a DOJ CRT ADM User, I want newly created records assigned anywhere other than ADM so that DOJ CRT ADM has more free time.

## Background

ADM will be the catch all section. All complaint records that don't have assigned sections via routing logic will be default assigned to ADM.
Section Abbreviations:

- ADM (Administrative) 
- IER (Immigrant and Employee Rights) 
- VOT (Voting) 
- DRS (Disability)
- CRM (Criminal)
- HCE (Housing)
- EOS (Education)
- SPL (Special Lit)
- ELS (Employment Litigation Section)
- FCS (Federal Coordination and Compliance) 
- APP ( Appellate) 

## Out of scope
- changing sections
- sorting and filtering by sections
- routing logic

## Acceptance criteria

1) Given a complaint has been submitted via
-- online intake form by a Public user
-- manual creation by CRT user
When I view the 'View All Complaints' table
Then I view a column called 'Routed' 

2) Given a  new complaint has been submitted via
-- online intake form by a Public user
-- manual creation by CRT user
When I view the 'View All Complaints' table
Then I see 
- [ ] the section abbreviation as ADM in the 'Routed' column 

3) given that I'm using a screen reader, when I get to a cell in this column it should announce "I-E-R, Routed" ([cell content, column name]).
- *I expect this to work as intended already based on the other tables. Preference for keeping it consistent with what sighted people would see vs having it read the section name*

## Mockups / Wireframes
![[LATEST] CRT view all - new.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/b6081e19-1a18-43db-97b7-e2d7ea0b78f1)

### Styles across the row
`font-family: PublicSans-Bold;` 
font-size: 14px; (same size)
color: #2E2E2A; (bg-gray-warm-80) - normal font color

### Status column
**TAG**
![tagstyles.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/c59b17b6-1547-48bd-a017-0cb6b1cbe5ac)
background color: primary blue
Height 22px
6px padding to the left and right

Other status colors:
Gold: #FFBE2E 'gold-20v'
Gray: #E6E6E2 'gray-warm-10'

**TEXT**
`text-transform: uppercase`
`font-family: PublicSans-Bold;`
`font-size: 14px;`
`color: #FFFFFF;`

### Story sign off
- [x] PO (Bill)
### UAT Sign off
- [ ] PO
- [ ] Sections

**Comment by LindsayYoung** [comment]
For this, we could also use the same template to also have pages pre-sorted for each section. It would be less than 5 lines of code and I think they would appreciate it. 

so something like: 
view/form/adm
view/form/idi
view/form/etc...

**Comment by blaughman** [comment]
@lalitha-jonnalagadda I updated Appellate's acronym.

**Comment by lalitha-jonnalagadda** [comment]
Completed independent UAT review.
