### ISSUE TITLE
Add 'secondary' review to regular export

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#914]
### Background

Currently, we can see the number of reports flagged for 'secondary review' through the ADMIN console and filtering on 'secondary review.' However, Anthony mentioned that he cannot see which reports are flagged for 'secondary review' in the export that we provide to him every two weeks.

### Our Ask
Please add 'secondary' review to regular export

**Comment by Jkrzy** [comment]
@randyabramson, @blaughman, this field is included in the exports with `referred` as the column header.

Can we consider this one resolved?

**Comment by blaughman** [comment]
@Jkrzy @randyabramson If this is already in the export, then we should consider this resolved.  Seems like a misunderstanding on the verbiage.

**Comment by Jkrzy** [comment]
Thanks @blaughman, I'll close this.

**Comment by randyabramson** [comment]
@Jkrzy @blaughman - just looking at this again. The 'referred' column has values of TRUE/FALSE, but no mention of 'secondary review.'

Am I missing something?

Thanks for your guidance.
