### ISSUE TITLE
Update translation on the Spanish version of the landing page

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#915]
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/7739ff57-0773-4822-9186-fa0d8b1efed1)

**Comment by blaughman** [comment]
If you believe your civil rights, or someone else’s, have been violated, submit a report using our online form.


Si cree que sus derechos civiles o los de otra persona han sido vulnerados, envíe un informe mediante nuestro formulario en línea.

**Comment by Jkrzy** [comment]
Fixed in https://github.com/usdoj-crt/crt-portal/pull/841

**Comment by blaughman** [comment]
The language should be updated to reflect the following:

Si cree que sus derechos civiles o los de otra persona han sido vulnerados, envíe un informe mediante nuestro formulario en línea.

**Comment by Jkrzy** [comment]
Thanks @blaughman, proposed that change here: https://github.com/usdoj-crt/crt-portal/pull/844

Noting that this is different than the original translation we received:
> Si cree que usted u otra persona ha sido discriminado/a ilegalmente, puede informar de una vulneración de los derechos civiles.

We'll likely encounter this moving forward, translations evolving over time.

**Comment by blaughman** [comment]
@timoballard @ilodidoj @Jkrzy It doesn't appear as though the language reflects the most recent translation provided by Marta
 "Si cree que sus derechos civiles o los de otra persona han sido vulnerados, envíe un informe mediante nuestro formulario en línea."

[Uploading... image.png]

**Comment by blaughman** [comment]
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/db98387f-058b-4634-a070-a796534c6c70)

**Comment by timoballard** [comment]
Thanks @blaughman - looking at it, I think we misinterpreted which block of text needed to be updated here - there are two similar statements on the landing page:

- If you believe your civil rights, or someone else’s, have been violated, submit a report using our online form.
- If you believe that you or someone else experienced unlawful discrimination, you can report a civil rights violation.

It sounds like we updated the second one when we should have updated the first one.

cc: @Jkrzy

**Comment by Jkrzy** [comment]
Thanks @blaughman and @timoballard! Fix for this incoming

**Comment by blaughman** [comment]
@timoballard @Jkrzy No worries - it took me a while to catch this as well.

**Comment by blaughman** [comment]
Translation is accurate.  Moving to UAT.

**Comment by randyabramson** [comment]
Works as expected on desktop and mobile. Moving to staging.

**Comment by blaughman** [comment]
Spanish text appears as intended in Production. Closing this card.
