### ISSUE TITLE
Add footer back to Part 2 of  Step 2 of form 

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#917]
### Background 
We noticed that the footer is missing from Part 2 of Step 2 (primary Issue, question: "Does your situation involve physical harm or threats of violence?")

### Request
Please add the footer back to this question/page. Assumption that this footer will be present in all language translation configurations

**Comment by ilodidoj** [comment]
![Screen Shot 2021-04-06 at 7.15.05 PM.png](https://images.zenhubusercontent.com/5d374c9d0efb727bd5a01afd/c2fd74ba-5fb9-4113-b63b-bdcb46b62f49)

Screenshot added

**Comment by randyabramson** [comment]
Thank you @ilodidoj

**Comment by blaughman** [comment]
Footer appears as requested in both Chrome and Edge.  Moving to UAT.

**Comment by randyabramson** [comment]
Works on desktop and mobile. Moving to staging.

**Comment by randyabramson** [comment]
Works as expected on desktop and mobile. Moving to closed.
