### ISSUE TITLE
Incorporate Translated Form Letters for Traditional Chinese.

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#919]
[https://app.zenhub.com/files/183258764/f1fb3c58-0dcd-4fbe-abeb-7c6a3a792eec/download](https://app.zenhub.com/files/183258764/f1fb3c58-0dcd-4fbe-abeb-7c6a3a792eec/download)

**Comment by blaughman** [comment]
Blocked by Card 911.

**Comment by timoballard** [comment]
@randyabramson @blaughman 

To properly construct the subject line of the form letters, we'll need translations for the section names:

Administrative
Appellate
Criminal
Disability Rights
Employment Litigation
Educational Opportunities
Federal Coordination and Compliance
Housing and Civil Enforcement
Immigrant and Employee Rights
Special Litigation
Voting

**Comment by timoballard** [comment]
@randyabramson @blaughman 

We also need the translation for the subject line static text:

Response: Your Civil Rights Division Report - _<Report ID>_ from _<Section Name>_ Section

**Comment by timoballard** [comment]
Marking as Blocked until we receive the above translations

cc: @randyabramson @blaughman

**Comment by blaughman** [comment]
[https://app.zenhub.com/files/183258764/4d528389-b38c-42a6-bd18-4e2e92735275/download](https://app.zenhub.com/files/183258764/4d528389-b38c-42a6-bd18-4e2e92735275/download)

**Comment by timoballard** [comment]
Thanks @blaughman - Realizing that my comment wasn't very clear or specific, my bad. We're blocked until we have translations for the form letter subject lines, so:

"Response: Your Civil Rights Division Report - {Report ID} from {Section Name} Section"

and we'll need translations for each of the section names, which get inserted into the subject lines:

Administrative
Appellate
Criminal
Disability Rights
Employment Litigation
Educational Opportunities
Federal Coordination and Compliance
Housing and Civil Enforcement
Immigrant and Employee Rights
Special Litigation
Voting

**Comment by blaughman** [comment]
Form letters appear to all be properly translated with no obvious errors.  Moving to UAT.
