### ISSUE TITLE
FBI Review of Translations - Landing Page, Form, Error Pages, Privacy Policy, headers, form letters, footers and nav links

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#928]
FBI Review of Translations - Landing Page, Form, Error Pages, Privacy Policy,  headers, footers, form letters and nav links

- [x] Chinese (Traditional)
- [x] Chinese (Simplified)
- [x] Korean
- [x] Vietnamese
- [x] Tagalog

**Comment by randyabramson** [comment]
@timoballard we can use the checklist above

**Comment by blaughman** [comment]
Deployed.  Moving to UAT complete.
