### ISSUE TITLE
Assign newly created record to FCS

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#93]
## Narrative
As a \<type of user\>, I want \<a goal\> so that \<benefit\>. 

## Background
:add business context to help us better understand the story:

## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Mockups / Wireframes
![image]()

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by lalitha-jonnalagadda** [comment]
Closing this per the release planning session on 7/22. Linda provided information the scenarios when a report can be routed to FCS
