### ISSUE TITLE
Implement routing logic example

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#94]
## Narrative
As an awesome person in the admin, I want example logic so that I can add the routing logic to the form. 

## Background
Add a default and multi-step logic example
  
## Acceptance criteria
- [ ] defaults to ADM
- [ ] handles voting and housing logic 
- [ ] deployed to stage and dev
- [ ] can deal with multiple assignments 

## Technical Notes

housing +
race and or national origin 

Housing (HCE)

**Comment by lalitha-jonnalagadda** [comment]
Closing this card - This seems to be a stale card and we handled routing to ADM in a different card already.
