### ISSUE TITLE
Unblock installation of CRT app on network

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#95]
## Narrative
As a DOJ CRT developer, I want to be able to install dependencies for the CRT Django App.

#### Network permissions:
  - [x] proxy set up
  - [x] docker registry
  - [x] python dependencies registry (pipenv)
  - [x] install CLI
  - [x] cloud.gov
  - [x] npm
  - [x] python dependencies registry (pipenv)

#### Machine permissions:
  - [x] proxy set up
  - [x] docker registry
  - [x] C drive access
  - [x] ~H drive access~ don't need
  - [x] install CLI
  - [x] cloud.gov
  - [x] npm
  - [x] python dependencies registry (pipenv)

- [x] When working from home, attempt to install dependencies offline
  - [ ] Darren: Use Wireshark to see which IPs are pinged during the process

**Comment by alexsoble** [comment]
@ilodidoj sent list of IP addresses to open up to network team this morning.

**Comment by alexsoble** [comment]
@ilodidoj blocked from downloading dependencies off-network because he is a PIV-mandatory group — you cannot log into any DOJ device without being on the network first.

**Comment by alexsoble** [comment]
Notes on @ilodidoj and @dwechsle progress here: https://docs.google.com/document/d/12x4xEs8BDjdOdeqJ79vVBmtuv2OUZvQqgmPACoGFjAc/edit

**Comment by alexsoble** [comment]
Darren was able to get Docker dependencies downloaded offline, now stuck on a non-networking issue related to folder permissions. Progress!!

**Comment by UchMok** [comment]
@ilodidoj needs cloud.gov account access

**Comment by UchMok** [comment]
Imran/Darren still stuck. We think the issue is related to their actual DOJ laptop. Imran will try setting up his local machine remotely from home this weekend, to test this hypothesis.

**Comment by dwechsle** [comment]
Set up a vanilla DOJ-imaged on network computer to test a local environment

**Comment by dwechsle** [comment]
If the vanilla DOJ-imaged on network computer does not work, set up a vanilla imaged computer off network to set up and work on a local environment

**Comment by UchMok** [comment]
Imran and Darren started this process over with fresh DOJ laptops

**Comment by Jacklynn** [comment]
CircleCI meeting tomorrow

**Comment by Jacklynn** [comment]
Got waiver from JMD testing to see if it works.

**Comment by Jacklynn** [comment]
cloud & docker still blockers

**Comment by Jacklynn** [comment]
More proxy waivers, JMD to reset overnight to try again tomorrow

**Comment by alexsoble** [comment]
*On-network* — Still in testing mode with Python dependencies. 

*Off-network* — Lots of progress! `docker-compose up` works! 

Ordering Macs!! For offline work. <3 <3 <3

**Comment by alexsoble** [comment]
Waiting for waiver implementation for on-network changes.
