### ISSUE TITLE
Add helptext to questions in Django webform 

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#97]
## Narrative
As a user, I want to see helptext so I can have additional context around form items.

**Comment by LindsayYoung** [comment]
found the docs while I was doing some model research https://docs.djangoproject.com/en/2.2/ref/forms/fields/#help-text

**Comment by UchMok** [comment]
@LindsayYoung this is going to get done in the first 'contact story'. DO we still need this tech task, or can we close it?
