### ISSUE TITLE
Writeup of challenges we faced with Drupal on Acquia

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#99]
### We've done bits and pieces of this before ...

+ We've already given writeups on Cloud.gov vs Django
+ Writeup on BLT
+ Slideshow on technical strategy — we outlined challenges

### Timebox

1 hour! 1 page. 4-5 sections. 

## Timeline

+ Reach: end of day.
+ For sure: end of week.

**Comment by LindsayYoung** [comment]
well done!
